[package]
name = "edgerun-qpack"
version.workspace = true
edition.workspace = true
description = "QPACK header compression for HTTP/3 (RFC 9204)"
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding", default-features = false }


[features]
default = []
std = ["edgerun-encoding/std"]
http-headers = []

[lints]
workspace = true
