[package]
name = "edgerun-dash-templates"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "HTML/CSS/JS templates for the Edgerun dashboard surfaces"

[dependencies]
edgerun-web-ui = { path = "../edgerun-web-ui", default-features = false }
edgerun-config = { path = "../edgerun-config", default-features = false, optional = true }

[features]
default = ["std"]
std = ["dep:edgerun-config"]

[lints]
workspace = true
