[package]
name = "edgerun-capability-policy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-crypto.workspace = true
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-proto = { path = "../edgerun-proto" }
prost-types.workspace = true
edgerun-core = { path = "../edgerun-core" }
