[package]
name = "bytes"
version = "1.11.1"
edition = "2021"
rust-version = "1.57"
license = "MIT"
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned upstream-compatible bytes crate"

[features]
default = ["std"]
serde = ["dep:serde"]
std = []

[dependencies]
serde = { path = "../edgerun-serde-upstream", optional = true, default-features = false, features = ["alloc"] }

[lints]
workspace = true
