[package]
name = "edgerun-solana"
version.workspace = true
edition.workspace = true

[dependencies]
bs58 = "0.5"
edgerun-error.workspace = true
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
edgerun-http = { path = "../edgerun-http" }
edgerun-json = { path = "../edgerun-json", features = ["serde"] }
edgerun-bare-rt = { path = "../edgerun-bare-rt" }
edgerun-crypto = { path = "../edgerun-crypto" }

[dev-dependencies]
mockall = "0.13"
