[package]
edition = "2021"
name = "edgerun-esp"
version = "0.1.0"
rust-version = "1.82"

resolver = "2"

[[bin]]
name = "edgerun-esp"
path = "src/main.rs"
harness = false

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
embassy-time = { version = "0.5", features = ["generic-queue-8"] }

[build-dependencies]
embuild = "0.33"