[package]
name = "edgerun-dhcpv6"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "DHCPv6 server and client (RFC 8415)"

[dependencies]
edgerun-rt = { path = "../edgerun-rt" }
edgerun-log = { path = "../edgerun-log" }
edgerun-crypto = { path = "../edgerun-crypto", default-features = false }
edgerun-encoding = { path = "../edgerun-encoding", default-features = false }
edgerun-error.workspace = true

[lints]
workspace = true
