[package]
name = "codex-app-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codex_app_server_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-protocol = { workspace = true }
codex-shell-command = { workspace = true }
edgerun-clap = { workspace = true, features = ["derive"] }
edgerun-error = { workspace = true }
edgerun-json = { workspace = true, features = ["serde-compat"] }
edgerun-similar = { workspace = true }
edgerun-uuid = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
edgerun-serde-with = { workspace = true }
edgerun-strum-macros = { workspace = true }
rmcp = { workspace = true, default-features = false, features = [
    "base64",
    "macros",
    "schemars",
    "server",
] }
ts-rs = { workspace = true }
edgerun-inventory = { workspace = true }
tracing = { workspace = true }
