[package]
name = "edgerun-dhcp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Async DHCPv4 server and client"

[lints]
workspace = true

[dependencies]
edgerun-rt = { path = "../edgerun-rt" }
edgerun-log = { path = "../edgerun-log" }
