[package]
name = "edgerun-dhcp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "DHCPv4 server and client"

[features]
default = ["std"]
std = ["edgerun-log", "edgerun-rt"]
bare = ["edgerun-bare-rt"]

[lints]
workspace = true

[dependencies]
edgerun-bare-rt = { version = "0.1", optional = true, path = "../edgerun-bare-rt" }
edgerun-encoding = { path = "../edgerun-encoding", default-features = false }
edgerun-log = { path = "../edgerun-log", optional = true }
edgerun-rt = { path = "../edgerun-rt", optional = true }
