[package]
name = "hashbrown"
version = "0.17.1"
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned SwissTable hash map"

[features]
default = []
default-hasher = []
inline-more = []
raw-entry = []
nightly = []
rustc-dep-of-std = ["nightly"]
rustc-internal-api = []

[lints]
workspace = true
