[package]
name = "lifegraph-node"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "lifegraphd"
path = "src/main.rs"

[dependencies]
lifegraph-core = { path = "../lifegraph-core" }
lifegraph-proto = { path = "../lifegraph-proto" }
lifegraph-capabilities = { path = "../lifegraph-capabilities" }
lifegraph-capability-policy = { path = "../lifegraph-capability-policy" }
lifegraph-stream = { path = "../lifegraph-stream" }
lifegraph-storage = { path = "../lifegraph-storage" }
lifegraph-hardware-signing = { path = "../lifegraph-hardware-signing" }
lifegraph-remote-capability = { path = "../lifegraph-remote-capability" }
lifegraph-evdev-input = { path = "../lifegraph-evdev-input" }
lifegraph-alsa-speaker = { path = "../lifegraph-alsa-speaker" }
lifegraph-alsa-microphone = { path = "../lifegraph-alsa-microphone" }
lifegraph-microphone = { path = "../lifegraph-microphone" }
lifegraph-v4l2-camera = { path = "../lifegraph-v4l2-camera" }
lifegraph-camera-biometrics = { path = "../lifegraph-camera-biometrics" }
lifegraph-speaker = { path = "../lifegraph-speaker" }
lifegraph-mesh = { path = "../lifegraph-mesh" }
lifegraph-mesh-link = { path = "../lifegraph-mesh-link" }
lifegraph-mesh-router = { path = "../lifegraph-mesh-router" }
lifegraph-linux-netif = { path = "../lifegraph-linux-netif" }
lifegraph-network-interface = { path = "../lifegraph-network-interface" }
sha2.workspace = true
p256.workspace = true
prost.workspace = true
prost-types.workspace = true
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
hex.workspace = true
getrandom.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
rustls-pemfile.workspace = true
rcgen.workspace = true
ring.workspace = true
x509-parser.workspace = true

[dev-dependencies]
rand.workspace = true
