[package]
name = "edgerun-icu-locale-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun shim for icu_locale_core"

[dependencies]
icu_locale_core = { path = "../../vendor/cargo/icu_locale_core" }

[lints]
workspace = true
