[package]
name = "edgerun-oauth"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-crypto = { path = "../edgerun-crypto" }
edgerun-http = { path = "../edgerun-http" }
edgerun-json = { path = "../edgerun-json" }
edgerun-bare-rt = { path = "../edgerun-bare-rt" }
edgerun-secret-service = { path = "../edgerun-secret-service" }
edgerun-encoding = { path = "../edgerun-encoding", default-features = false, features = ["alloc"] }
rsa = { version = "0.9", default-features = false, features = ["sha2", "pem"] }

[lints]
workspace = true
