[package]
name = "edgerun-amd-xdna"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "AMD XDNA Linux NPU adapter for Edgerun"
autobins = false

[dependencies]
edgerun-devices.workspace = true
edgerun-linux-npu = { version = "0.1", path = "../edgerun-linux-npu" }
edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }
edgerun-log = { version = "0.1", path = "../../utility/edgerun-log" }

[features]
std = []

[lints]
workspace = true
