[package]
name = "edgerun-term-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
embedded-emoji = ["dep:edgerun-emoji"]

[dependencies]
edgerun-encoding = { path = "../../utility/edgerun-encoding", features = ["std"] }
edgerun-emoji = { path = "../../utility/edgerun-emoji", optional = true }
edgerun-error = { path = "../../utility/edgerun-error" }
edgerun-log = { path = "../../utility/edgerun-log" }
edgerun-sixel = { path = "../../utility/edgerun-sixel" }
edgerun-terminal-parser = { path = "../../utility/edgerun-terminal-parser" }
edgerun-unicode = { path = "../../utility/edgerun-unicode" }
