// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDetail } from "./ImageDetail";

export type ContentItem = { "InputText": { text: string, } } | { "InputImage": { image_url: string, detail?: ImageDetail, } } | { "OutputText": { text: string, } };
