// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationGitInfo } from "./ConversationGitInfo";
import type { SessionSource } from "./SessionSource";
import type { ThreadId } from "./ThreadId";

export type ConversationSummary = { conversation_id: ThreadId, path: string, preview: string, timestamp: string | null, updated_at: string | null, model_provider: string, cwd: string, cli_version: string, source: SessionSource, git_info: ConversationGitInfo | null, };
