# SPDX-License-Identifier: Apache-2.0
services:
  whoami:
    image: traefik/whoami:v1.11.0
    ports:
      - target: 80
        published: 9081
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  registry:
    image: registry:2
    ports:
      - target: 5000
        published: 5001
        protocol: tcp
        mode: ingress
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - registry-data:/var/lib/registry
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  registry-data: {}
