// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedCommand } from "./ParsedCommand";
import type { ThreadId } from "./ThreadId";

export type ExecCommandApprovalParams = { conversation_id: ThreadId, 
/**
 * Use to correlate this with [codex_protocol::protocol::ExecCommandBeginEvent]
 * and [codex_protocol::protocol::ExecCommandEndEvent].
 */
call_id: string, 
/**
 * Identifier for this specific approval callback.
 */
approval_id: string | null, command: Array<string>, cwd: string, reason: string | null, parsed_cmd: Array<ParsedCommand>, };
