// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileChange = { "type": "Add", content: string, } | { "type": "Delete", content: string, } | { "type": "Update", unified_diff: string, move_path: string | null, };
