// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";

export type GetAuthStatusResponse = { auth_method: AuthMode | null, auth_token: string | null, requires_openai_auth: boolean | null, };
