// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAuthStatusParams = { include_token: boolean | null, refresh_token: boolean | null, };
