// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";

export type GetConversationSummaryParams = { "RolloutPath": { rollout_path: string, } } | { "ThreadId": { conversation_id: ThreadId, } };
