// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";

export type InitializeResponse = { user_agent: string, 
/**
 * Absolute path to the server's $CODEX_HOME directory.
 */
codex_home: AbsolutePathBuf, 
/**
 * Platform family for the running app-server target, for example
 * `"unix"` or `"windows"`.
 */
platform_family: string, 
/**
 * Operating system for the running app-server target, for example
 * `"macos"`, `"linux"`, or `"windows"`.
 */
platform_os: string, };
