// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInfo } from "./ClientInfo";
import type { InitializeCapabilities } from "./InitializeCapabilities";

export type InitializeParams = { client_info: ClientInfo, capabilities: InitializeCapabilities | null, };
