// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client-declared capabilities negotiated during initialize.
 */
export type InitializeCapabilities = { 
/**
 * Opt into receiving experimental API methods and fields.
 */
experimental_api: boolean, 
/**
 * Exact notification method names that should be suppressed for this
 * connection (for example `thread/started`).
 */
opt_out_notification_methods?: Array<string> | null, };
