// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A known resource that the server is capable of reading.
 */
export type Resource = { annotations?: JsonValue, description?: string, mime_type?: string, name: string, size?: number, title?: string, uri: string, icons?: Array<JsonValue>, meta?: JsonValue, };
