// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A template description for resources available on the server.
 */
export type ResourceTemplate = { annotations?: JsonValue, uri_template: string, name: string, title?: string, description?: string, mime_type?: string, };
