// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contents returned when reading a resource from an MCP server.
 */
export type ResourceContent = { "Text": { 
/**
 * The URI of this resource.
 */
uri: string, mimeType?: string, text: string, meta?: JsonValue, } } | { "Blob": { 
/**
 * The URI of this resource.
 */
uri: string, mimeType?: string, blob: string, meta?: JsonValue, } };
