// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItem } from "./ContentItem";
import type { FunctionCallOutputBody } from "./FunctionCallOutputBody";
import type { LocalShellAction } from "./LocalShellAction";
import type { LocalShellStatus } from "./LocalShellStatus";
import type { MessagePhase } from "./MessagePhase";
import type { ReasoningItemContent } from "./ReasoningItemContent";
import type { ReasoningItemReasoningSummary } from "./ReasoningItemReasoningSummary";
import type { WebSearchAction } from "./WebSearchAction";

export type ResponseItem = { "Message": { role: string, content: Array<ContentItem>, phase?: MessagePhase, } } | { "Reasoning": { summary: Array<ReasoningItemReasoningSummary>, content?: Array<ReasoningItemContent>, encrypted_content: string | null, } } | { "LocalShellCall": { 
/**
 * Set when using the Responses API.
 */
call_id: string | null, status: LocalShellStatus, action: LocalShellAction, } } | { "FunctionCall": { name: string, namespace?: string, arguments: string, call_id: string, } } | { "ToolSearchCall": { call_id: string | null, status?: string, execution: string, arguments: unknown, } } | { "FunctionCallOutput": { call_id: string, output: FunctionCallOutputBody, } } | { "CustomToolCall": { status?: string, call_id: string, name: string, input: string, } } | { "CustomToolCallOutput": { call_id: string, name?: string, output: FunctionCallOutputBody, } } | { "ToolSearchOutput": { call_id: string | null, status: string, execution: string, tools: unknown[], } } | { "WebSearchCall": { status?: string, action?: WebSearchAction, } } | { "ImageGenerationCall": { id: string, status: string, revised_prompt?: string, result: string, } } | { "Compaction": { encrypted_content: string, } } | { "ContextCompaction": { encrypted_content?: string, } } | "Other";
