// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecPolicyAmendment } from "./ExecPolicyAmendment";
import type { NetworkPolicyAmendment } from "./NetworkPolicyAmendment";

/**
 * User's decision in response to an ExecApprovalRequest.
 */
export type ReviewDecision = "Approved" | { "ApprovedExecpolicyAmendment": { proposed_execpolicy_amendment: ExecPolicyAmendment, } } | "ApprovedForSession" | { "NetworkPolicyAmendment": { network_policy_amendment: NetworkPolicyAmendment, } } | "Denied" | "TimedOut" | "Abort";
