// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyPatchApprovalParams } from "./ApplyPatchApprovalParams";
import type { ExecCommandApprovalParams } from "./ExecCommandApprovalParams";
import type { RequestId } from "./RequestId";
import type { ChatgptAuthTokensRefreshParams } from "./v2/ChatgptAuthTokensRefreshParams";
import type { CommandExecutionRequestApprovalParams } from "./v2/CommandExecutionRequestApprovalParams";
import type { DynamicToolCallParams } from "./v2/DynamicToolCallParams";
import type { FileChangeRequestApprovalParams } from "./v2/FileChangeRequestApprovalParams";
import type { McpServerElicitationRequestParams } from "./v2/McpServerElicitationRequestParams";
import type { PermissionsRequestApprovalParams } from "./v2/PermissionsRequestApprovalParams";
import type { ToolRequestUserInputParams } from "./v2/ToolRequestUserInputParams";

/**
 * Request initiated from the server and sent to the client.
 */
export type ServerRequest = { "item/commandExecution/requestApproval": { request_id: RequestId, params: CommandExecutionRequestApprovalParams, } } | { "item/fileChange/requestApproval": { request_id: RequestId, params: FileChangeRequestApprovalParams, } } | { "item/tool/requestUserInput": { request_id: RequestId, params: ToolRequestUserInputParams, } } | { "mcpServer/elicitation/request": { request_id: RequestId, params: McpServerElicitationRequestParams, } } | { "item/permissions/requestApproval": { request_id: RequestId, params: PermissionsRequestApprovalParams, } } | { "item/tool/call": { request_id: RequestId, params: DynamicToolCallParams, } } | { "account/chatgptAuthTokens/refresh": { request_id: RequestId, params: ChatgptAuthTokensRefreshParams, } } | { "ApplyPatchApproval": { request_id: RequestId, params: ApplyPatchApprovalParams, } } | { "ExecCommandApproval": { request_id: RequestId, params: ExecCommandApprovalParams, } };
