// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definition for a tool the client can call.
 */
export type Tool = { name: string, title?: string, description?: string, input_schema: JsonValue, output_schema?: JsonValue, annotations?: JsonValue, icons?: Array<JsonValue>, meta?: JsonValue, };
