// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebSearchAction = { "Search": { query?: string, queries?: Array<string>, } } | { "OpenPage": { url?: string, } } | { "FindInPage": { url?: string, pattern?: string, } } | "Other";
