[package]
name = "edgerun-mesh"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-hardware-signing = { path = "../edgerun-hardware-signing" }
edgerun-crypto.workspace = true

edgerun-core = { path = "../edgerun-core" }

[lints]
workspace = true
