[package]
name = "edgerun-virtual-disk"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Virtual block device and network block protocol support for Edgerun"

[dependencies]
edgerun-encoding = { workspace = true }
edgerun-protocols = { workspace = true, default-features = false, features = ["nbd", "websocket"] }

[lints]
workspace = true

[features]
std = []
