[package]
name = "edgerun-acme"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-rt.workspace = true
edgerun-log.workspace = true
edgerun-crypto.workspace = true
edgerun-http.workspace = true
edgerun-json.workspace = true
edgerun-dns.workspace = true
edgerun-encoding.workspace = true
edgerun-secret-service.workspace = true
edgerun-url.workspace = true
time = { version = "0.3", features = ["formatting", "parsing"] }
serde = { version = "1", features = ["derive"] }
edgerun-error.workspace = true

[dev-dependencies]

[features]
default = ["client"]
client = []
http_challenge = ["client"]
dns_challenge = ["client"]
