[package]
name = "edgerun-term-soft"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
portable-pty = "0.9.0"
softbuffer = { version = "0.4.6", default-features = false, features = ["x11", "x11-dlopen", "wayland", "wayland-dlopen"] }
edgerun-term-core = { path = "../edgerun-term-core", default-features = false }
vte = "0.13"
winit = { version = "0.30", default-features = false, features = ["rwh_06", "x11", "wayland", "wayland-dlopen"] }

[[bin]]
name = "edgerun-term-soft"
path = "src/main.rs"
