// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { PlanType } from "../PlanType";

export type AccountUpdatedNotification = { auth_mode: AuthMode | null, plan_type: PlanType | null, };
