// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { FileSystemSandboxEntry } from "./FileSystemSandboxEntry";

export type AdditionalFileSystemPermissions = { 
/**
 * This will be removed in favor of `entries`.
 */
read: Array<AbsolutePathBuf> | null, 
/**
 * This will be removed in favor of `entries`.
 */
write: Array<AbsolutePathBuf> | null, glob_scan_max_depth?: number, entries?: Array<FileSystemSandboxEntry>, };
