// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalyticsConfig = { enabled: boolean | null, additional: { [key in string]?: JsonValue }, };
