// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppBranding } from "./AppBranding";
import type { AppMetadata } from "./AppMetadata";

/**
 * EXPERIMENTAL - app metadata returned by app-list APIs.
 */
export type AppInfo = { id: string, name: string, description: string | null, logo_url: string | null, logo_url_dark: string | null, distribution_channel: string | null, branding: AppBranding | null, app_metadata: AppMetadata | null, labels: { [key in string]?: string } | null, install_url: string | null, is_accessible: boolean, 
/**
 * Whether this app is enabled in config.toml.
 * Example:
 * ```toml
 * [apps.bad_app]
 * enabled = false
 * ```
 */
is_enabled: boolean, plugin_display_names: Array<string>, };
