// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppReview } from "./AppReview";
import type { AppScreenshot } from "./AppScreenshot";

export type AppMetadata = { review: AppReview | null, categories: Array<string> | null, sub_categories: Array<string> | null, seo_description: string | null, screenshots: Array<AppScreenshot> | null, developer: string | null, version: string | null, version_id: string | null, version_notes: string | null, first_party_type: string | null, first_party_requires_install: boolean | null, show_in_composer_when_unlinked: boolean | null, };
