// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConfig } from "./AppConfig";
import type { AppsDefaultConfig } from "./AppsDefaultConfig";

export type AppsConfig = { default: AppsDefaultConfig | null, apps: { [key in string]?: AppConfig }, };
