// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - app metadata summary for plugin responses.
 */
export type AppSummary = { id: string, name: string, description: string | null, install_url: string | null, needs_auth: boolean, };
