// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppScreenshot = { url: string | null, file_id: string | null, user_prompt: string, };
