// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppToolConfig } from "./AppToolConfig";

export type AppToolsConfig = { tools: { [key in string]?: AppToolConfig }, };
