// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatgptAuthTokensRefreshResponse = { access_token: string, chatgpt_account_id: string, chatgpt_plan_type: string | null, };
