// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonSteerableTurnKind } from "./NonSteerableTurnKind";

/**
 * This translation layer make sure that we expose codex error code in camel case.
 *
 * When an upstream HTTP status is available (for example, from the Responses API or a provider),
 * it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.
 */
export type CodexErrorInfo = "ContextWindowExceeded" | "UsageLimitExceeded" | "ServerOverloaded" | "CyberPolicy" | { "HttpConnectionFailed": { httpStatusCode: number | null, } } | { "ResponseStreamConnectionFailed": { httpStatusCode: number | null, } } | "InternalServerError" | "Unauthorized" | "BadRequest" | "ThreadRollbackFailed" | "SandboxError" | { "ResponseStreamDisconnected": { httpStatusCode: number | null, } } | { "ResponseTooManyFailedAttempts": { httpStatusCode: number | null, } } | { "ActiveTurnNotSteerable": { turnKind: NonSteerableTurnKind, } } | "Other";
