// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Write stdin bytes to a running `command/exec` session, close stdin, or
 * both.
 */
export type CommandExecWriteParams = { 
/**
 * Client-supplied, connection-scoped `processId` from the original
 * `command/exec` request.
 */
process_id: string, 
/**
 * Optional base64-encoded stdin bytes to write.
 */
delta_base64?: string | null, 
/**
 * Close stdin after writing `deltaBase64`, if present.
 */
close_stdin: boolean, };
