// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecPolicyAmendment } from "./ExecPolicyAmendment";
import type { NetworkPolicyAmendment } from "./NetworkPolicyAmendment";

export type CommandExecutionApprovalDecision = "Accept" | "AcceptForSession" | { "AcceptWithExecpolicyAmendment": { execpolicy_amendment: ExecPolicyAmendment, } } | { "ApplyNetworkPolicyAmendment": { network_policy_amendment: NetworkPolicyAmendment, } } | "Decline" | "Cancel";
