// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecOutputStream } from "./CommandExecOutputStream";

/**
 * Base64-encoded output chunk emitted for a streaming `command/exec` request.
 *
 * These notifications are connection-scoped. If the originating connection
 * closes, the server terminates the process.
 */
export type CommandExecOutputDeltaNotification = { 
/**
 * Client-supplied, connection-scoped `processId` from the original
 * `command/exec` request.
 */
process_id: string, 
/**
 * Output stream for this chunk.
 */
stream: CommandExecOutputStream, 
/**
 * Base64-encoded output bytes.
 */
delta_base64: string, 
/**
 * `true` on the final streamed chunk for a stream when `outputBytesCap`
 * truncated later output on that stream.
 */
cap_reached: boolean, };
