// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type CommandAction = { "type": "Read", command: string, name: string, path: AbsolutePathBuf, } | { "type": "ListFiles", command: string, path: string | null, } | { "type": "Search", command: string, query: string | null, path: string | null, } | { "type": "Unknown", command: string, };
