// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { AdditionalPermissionProfile } from "./AdditionalPermissionProfile";
import type { CommandAction } from "./CommandAction";
import type { CommandExecutionApprovalDecision } from "./CommandExecutionApprovalDecision";
import type { ExecPolicyAmendment } from "./ExecPolicyAmendment";
import type { NetworkApprovalContext } from "./NetworkApprovalContext";
import type { NetworkPolicyAmendment } from "./NetworkPolicyAmendment";

export type CommandExecutionRequestApprovalParams = { thread_id: string, turn_id: string, item_id: string, 
/**
 * Unix timestamp (in milliseconds) when this approval request started.
 */
started_at_ms: number, 
/**
 * Unique identifier for this specific approval callback.
 *
 * For regular shell/unified_exec approvals, this is null.
 *
 * For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to
 * one parent `itemId`, so `approvalId` is a distinct opaque callback id
 * (a UUID) used to disambiguate routing.
 */
approval_id?: string | null, 
/**
 * Optional explanatory reason (e.g. request for network access).
 */
reason?: string | null, 
/**
 * Optional context for a managed-network approval prompt.
 */
network_approval_context?: NetworkApprovalContext | null, 
/**
 * The command to be executed.
 */
command?: string | null, 
/**
 * The command's working directory.
 */
cwd?: AbsolutePathBuf | null, 
/**
 * Best-effort parsed command actions for friendly display.
 */
command_actions?: Array<CommandAction> | null, 
/**
 * Optional additional permissions requested for this command.
 */
additional_permissions?: AdditionalPermissionProfile | null, 
/**
 * Optional proposed execpolicy amendment to allow similar commands without prompting.
 */
proposed_execpolicy_amendment?: ExecPolicyAmendment | null, 
/**
 * Optional proposed network policy amendments (allow/deny host) for future requests.
 */
proposed_network_policy_amendments?: Array<NetworkPolicyAmendment> | null, 
/**
 * Ordered list of decisions the client may present for this prompt.
 */
available_decisions?: Array<CommandExecutionApprovalDecision> | null, };
