// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type ConfigLayerSource = { "type": "Mdm", domain: string, key: string, } | { "type": "System", 
/**
 * This is the path to the system config.toml file, though it is not
 * guaranteed to exist.
 */
file: AbsolutePathBuf, } | { "type": "User", 
/**
 * This is the path to the user's config.toml file, though it is not
 * guaranteed to exist.
 */
file: AbsolutePathBuf, } | { "type": "Project", dotCodexFolder: AbsolutePathBuf, } | { "type": "SessionFlags" } | { "type": "LegacyManagedConfigTomlFromFile", file: AbsolutePathBuf, } | { "type": "LegacyManagedConfigTomlFromMdm" };
