// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeStrategy } from "./MergeStrategy";

export type ConfigValueWriteParams = { key_path: string, value: JsonValue, merge_strategy: MergeStrategy, 
/**
 * Path to the config file to write; defaults to the user's `config.toml` when omitted.
 */
file_path?: string | null, expected_version?: string | null, };
