// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchMode } from "../WebSearchMode";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { ManagedHooksRequirements } from "./ManagedHooksRequirements";
import type { NetworkRequirements } from "./NetworkRequirements";
import type { ResidencyRequirement } from "./ResidencyRequirement";
import type { SandboxMode } from "./SandboxMode";

export type ConfigRequirements = { allowed_approval_policies: Array<AskForApproval> | null, allowed_approvals_reviewers: Array<ApprovalsReviewer> | null, allowed_sandbox_modes: Array<SandboxMode> | null, allowed_web_search_modes: Array<WebSearchMode> | null, feature_requirements: { [key in string]?: boolean } | null, hooks: ManagedHooksRequirements | null, enforce_residency: ResidencyRequirement | null, network: NetworkRequirements | null, };
