// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deprecated: Use `ContextCompaction` item type instead.
 */
export type ContextCompactedNotification = { thread_id: string, turn_id: string, };
