// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicToolCallOutputContentItem } from "./DynamicToolCallOutputContentItem";

export type DynamicToolCallResponse = { content_items: Array<DynamicToolCallOutputContentItem>, success: boolean, };
