// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DynamicToolSpec = { namespace?: string, name: string, description: string, input_schema: JsonValue, defer_loading: boolean, };
