// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DynamicToolCallParams = { thread_id: string, turn_id: string, call_id: string, namespace: string | null, tool: string, arguments: JsonValue, };
