// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnError } from "./TurnError";

export type ErrorNotification = { error: TurnError, will_retry: boolean, thread_id: string, turn_id: string, };
