// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedbackUploadParams = { classification: string, reason?: string | null, thread_id?: string | null, include_logs: boolean, extra_log_files?: Array<string> | null, tags?: { [key in string]?: string } | null, };
