// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deprecated legacy notification for `apply_patch` textual output.
 *
 * The server no longer emits this notification.
 */
export type FileChangeOutputDeltaNotification = { thread_id: string, turn_id: string, item_id: string, delta: string, };
