// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { FileSystemSpecialPath } from "./FileSystemSpecialPath";

export type FileSystemPath = { "type": "Path", path: AbsolutePathBuf, } | { "type": "GlobPattern", pattern: string, } | { "type": "Special", value: FileSystemSpecialPath, };
