// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileSystemSpecialPath = { "kind": "Root" } | { "kind": "Minimal" } | { "kind": "ProjectRoots", subpath: string | null, } | { "kind": "Tmpdir" } | { "kind": "SlashTmp" } | { "kind": "Unknown", path: string, subpath: string | null, };
