// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileChangeRequestApprovalParams = { thread_id: string, turn_id: string, item_id: string, 
/**
 * Unix timestamp (in milliseconds) when this approval request started.
 */
started_at_ms: number, 
/**
 * Optional explanatory reason (e.g. request for extra write access).
 */
reason?: string | null, 
/**
 * [UNSTABLE] When set, the agent is asking the user to allow writes under this root
 * for the remainder of the session (unclear if this is honored today).
 */
grant_root?: string | null, };
