// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileUpdateChange } from "./FileUpdateChange";

export type FileChangePatchUpdatedNotification = { thread_id: string, turn_id: string, item_id: string, changes: Array<FileUpdateChange>, };
