// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Filesystem watch notification emitted for `fs/watch` subscribers.
 */
export type FsChangedNotification = { 
/**
 * Watch identifier previously provided to `fs/watch`.
 */
watch_id: string, 
/**
 * File or directory paths associated with this event.
 */
changed_paths: Array<AbsolutePathBuf>, };
