// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata returned by `fs/getMetadata`.
 */
export type FsGetMetadataResponse = { 
/**
 * Whether the path resolves to a directory.
 */
is_directory: boolean, 
/**
 * Whether the path resolves to a regular file.
 */
is_file: boolean, 
/**
 * Whether the path itself is a symbolic link.
 */
is_symlink: boolean, 
/**
 * File creation time in Unix milliseconds when available, otherwise `0`.
 */
created_at_ms: number, 
/**
 * File modification time in Unix milliseconds when available, otherwise `0`.
 */
modified_at_ms: number, };
