// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A directory entry returned by `fs/readDirectory`.
 */
export type FsReadDirectoryEntry = { 
/**
 * Direct child entry name only, not an absolute or relative path.
 */
file_name: string, 
/**
 * Whether this entry resolves to a directory.
 */
is_directory: boolean, 
/**
 * Whether this entry resolves to a regular file.
 */
is_file: boolean, };
