// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type GetAccountRateLimitsResponse = { 
/**
 * Backward-compatible single-bucket view; mirrors the historical payload.
 */
rate_limits: RateLimitSnapshot, 
/**
 * Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
 */
rate_limits_by_limit_id: { [key in string]?: RateLimitSnapshot } | null, };
