// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookSource = "System" | "User" | "Project" | "Mdm" | "SessionFlags" | "Plugin" | "CloudRequirements" | "LegacyManagedConfigFile" | "LegacyManagedConfigMdm" | "Unknown";
