// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookRunSummary } from "./HookRunSummary";

export type HookCompletedNotification = { thread_id: string, turn_id: string | null, run: HookRunSummary, };
