// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { HookEventName } from "./HookEventName";
import type { HookHandlerType } from "./HookHandlerType";
import type { HookSource } from "./HookSource";
import type { HookTrustStatus } from "./HookTrustStatus";

export type HookMetadata = { key: string, event_name: HookEventName, handler_type: HookHandlerType, matcher: string | null, command: string | null, timeout_sec: bigint, status_message: string | null, source_path: AbsolutePathBuf, source: HookSource, plugin_id: string | null, display_order: bigint, enabled: boolean, is_managed: boolean, current_hash: string, trust_status: HookTrustStatus, };
