// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianApprovalReview } from "./GuardianApprovalReview";
import type { GuardianApprovalReviewAction } from "./GuardianApprovalReviewAction";

/**
 * [UNSTABLE] Temporary notification payload for approval auto-review. This
 * shape is expected to change soon.
 */
export type ItemGuardianApprovalReviewStartedNotification = { thread_id: string, turn_id: string, 
/**
 * Unix timestamp (in milliseconds) when this review started.
 */
started_at_ms: number, 
/**
 * Stable identifier for this review.
 */
review_id: string, 
/**
 * Identifier for the reviewed item or tool call when one exists.
 *
 * In most cases, one review maps to one target item. The exceptions are
 * - execve reviews, where a single command may contain multiple execve
 *   calls to review (only possible when using the shell_zsh_fork feature)
 * - network policy reviews, where there is no target item
 *
 * A network call is triggered by a CommandExecution item, so having a
 * target_item_id set to the CommandExecution item would be misleading
 * because the review is about the network call, not the command execution.
 * Therefore, target_item_id is set to None for network policy reviews.
 */
target_item_id: string | null, review: GuardianApprovalReview, action: GuardianApprovalReviewAction, };
