// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";

export type ItemCompletedNotification = { item: ThreadItem, thread_id: string, turn_id: string, 
/**
 * Unix timestamp (in milliseconds) when this item lifecycle completed.
 */
completed_at_ms: number, };
