// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketplaceAddParams = { source: string, ref_name?: string | null, sparse_paths?: Array<string> | null, };
