// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { MarketplaceUpgradeErrorInfo } from "./MarketplaceUpgradeErrorInfo";

export type MarketplaceUpgradeResponse = { selected_marketplaces: Array<string>, upgraded_roots: Array<AbsolutePathBuf>, errors: Array<MarketplaceUpgradeErrorInfo>, };
