// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpElicitationSchema } from "./McpElicitationSchema";

export type McpServerElicitationRequest = { "mode": "Form", _meta: JsonValue | null, message: string, requestedSchema: McpElicitationSchema, } | { "mode": "Url", _meta: JsonValue | null, message: string, url: string, elicitationId: string, };
