// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerToolCallParams = { thread_id: string, server: string, tool: string, arguments?: JsonValue, meta?: JsonValue, };
