// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerElicitationRequest } from "./McpServerElicitationRequest";

export type McpServerElicitationRequestParams = { thread_id: string, 
/**
 * Active Codex turn when this elicitation was observed, if app-server could correlate one.
 *
 * This is nullable because MCP models elicitation as a standalone server-to-client request
 * identified by the MCP server request id. It may be triggered during a turn, but turn
 * context is app-server correlation rather than part of the protocol identity of the
 * elicitation itself.
 */
turn_id: string | null, server_name: string, request: McpServerElicitationRequest, };
