// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerToolCallResponse = { content: Array<JsonValue>, structured_content?: JsonValue, is_error?: boolean, meta?: JsonValue, };
