// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpToolCallResult = { content: Array<JsonValue>, structured_content: JsonValue | null, _meta: JsonValue | null, };
