// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelVerification } from "./ModelVerification";

export type ModelVerificationNotification = { thread_id: string, turn_id: string, verifications: Array<ModelVerification>, };
