// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputModality } from "../InputModality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ModelAvailabilityNux } from "./ModelAvailabilityNux";
import type { ModelServiceTier } from "./ModelServiceTier";
import type { ModelUpgradeInfo } from "./ModelUpgradeInfo";
import type { ReasoningEffortOption } from "./ReasoningEffortOption";

export type Model = { id: string, model: string, upgrade: string | null, upgrade_info: ModelUpgradeInfo | null, availability_nux: ModelAvailabilityNux | null, display_name: string, description: string, hidden: boolean, supported_reasoning_efforts: Array<ReasoningEffortOption>, default_reasoning_effort: ReasoningEffort, input_modalities: Array<InputModality>, supports_personality: boolean, 
/**
 * Deprecated: use `serviceTiers` instead.
 */
additional_speed_tiers: Array<string>, service_tiers: Array<ModelServiceTier>, is_default: boolean, };
