// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProviderCapabilitiesReadResponse = { namespace_tools: boolean, image_generation: boolean, web_search: boolean, };
