// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRerouteReason } from "./ModelRerouteReason";

export type ModelReroutedNotification = { thread_id: string, turn_id: string, from_model: string, to_model: string, reason: ModelRerouteReason, };
