// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkDomainPermission } from "./NetworkDomainPermission";
import type { NetworkUnixSocketPermission } from "./NetworkUnixSocketPermission";

export type NetworkRequirements = { enabled: boolean | null, http_port: number | null, socks_port: number | null, allow_upstream_proxy: boolean | null, dangerously_allow_non_loopback_proxy: boolean | null, dangerously_allow_all_unix_sockets: boolean | null, 
/**
 * Canonical network permission map for `experimental_network`.
 */
domains: { [key in string]?: NetworkDomainPermission } | null, 
/**
 * When true, only managed allowlist entries are respected while managed
 * network enforcement is active.
 */
managed_allowed_domains_only: boolean | null, 
/**
 * Legacy compatibility view derived from `domains`.
 */
allowed_domains: Array<string> | null, 
/**
 * Legacy compatibility view derived from `domains`.
 */
denied_domains: Array<string> | null, 
/**
 * Canonical unix socket permission map for `experimental_network`.
 */
unix_sockets: { [key in string]?: NetworkUnixSocketPermission } | null, 
/**
 * Legacy compatibility view derived from `unix_sockets`.
 */
allow_unix_sockets: Array<string> | null, allow_local_binding: boolean | null, };
