// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigLayerMetadata } from "./ConfigLayerMetadata";

export type OverriddenMetadata = { message: string, overriding_layer: ConfigLayerMetadata, effective_value: JsonValue, };
