// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PatchChangeKind = { "type": "Add" } | { "type": "Delete" } | { "type": "Update", move_path: string | null, };
