// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSystemSandboxEntry } from "./FileSystemSandboxEntry";

export type PermissionProfileFileSystemPermissions = { "type": "Restricted", entries: Array<FileSystemSandboxEntry>, globScanMaxDepth?: number, } | { "type": "Unrestricted" };
