// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionProfileModificationParams } from "./PermissionProfileModificationParams";

export type PermissionProfileSelectionParams = { "type": "Profile", id: string, modifications?: Array<PermissionProfileModificationParams> | null, };
