// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { RequestPermissionProfile } from "./RequestPermissionProfile";

export type PermissionsRequestApprovalParams = { thread_id: string, turn_id: string, item_id: string, 
/**
 * Unix timestamp (in milliseconds) when this approval request started.
 */
started_at_ms: number, cwd: AbsolutePathBuf, reason: string | null, permissions: RequestPermissionProfile, };
