// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginSource = { "type": "Local", path: AbsolutePathBuf, } | { "type": "Git", url: string, path: string | null, refName: string | null, sha: string | null, } | { "type": "Remote" };
