// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginShareTarget } from "./PluginShareTarget";

export type PluginShareUpdateTargetsParams = { remote_plugin_id: string, share_targets: Array<PluginShareTarget>, };
