// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginInterface = { display_name: string | null, short_description: string | null, long_description: string | null, developer_name: string | null, category: string | null, capabilities: Array<string>, website_url: string | null, privacy_policy_url: string | null, terms_of_service_url: string | null, 
/**
 * Starter prompts for the plugin. Capped at 3 entries with a maximum of
 * 128 characters per entry.
 */
default_prompt: Array<string> | null, brand_color: string | null, 
/**
 * Local composer icon path, resolved from the installed plugin package.
 */
composer_icon: AbsolutePathBuf | null, 
/**
 * Remote composer icon URL from the plugin catalog.
 */
composer_icon_url: string | null, 
/**
 * Local logo path, resolved from the installed plugin package.
 */
logo: AbsolutePathBuf | null, 
/**
 * Remote logo URL from the plugin catalog.
 */
logo_url: string | null, 
/**
 * Local screenshot paths, resolved from the installed plugin package.
 */
screenshots: Array<AbsolutePathBuf>, 
/**
 * Remote screenshot URLs from the plugin catalog.
 */
screenshot_urls: Array<string>, };
