// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { PluginShareDiscoverability } from "./PluginShareDiscoverability";
import type { PluginShareTarget } from "./PluginShareTarget";

export type PluginShareSaveParams = { plugin_path: AbsolutePathBuf, remote_plugin_id?: string | null, discoverability?: PluginShareDiscoverability | null, share_targets?: Array<PluginShareTarget> | null, };
