// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSharePrincipalType } from "./PluginSharePrincipalType";

export type PluginShareTarget = { principal_type: PluginSharePrincipalType, principal_id: string, };
