// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSharePrincipal } from "./PluginSharePrincipal";

export type PluginShareContext = { remote_plugin_id: string, share_url: string | null, creator_account_user_id: string | null, creator_name: string | null, share_targets: Array<PluginSharePrincipal> | null, };
