// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSummary } from "./AppSummary";
import type { PluginAuthPolicy } from "./PluginAuthPolicy";

export type PluginInstallResponse = { auth_policy: PluginAuthPolicy, apps_needing_auth: Array<AppSummary>, };
