// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketplaceLoadErrorInfo } from "./MarketplaceLoadErrorInfo";
import type { PluginMarketplaceEntry } from "./PluginMarketplaceEntry";

export type PluginListResponse = { marketplaces: Array<PluginMarketplaceEntry>, marketplace_load_errors: Array<MarketplaceLoadErrorInfo>, featured_plugin_ids: Array<string>, };
