// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginSkillReadParams = { remote_marketplace_name: string, remote_plugin_id: string, skill_name: string, };
