// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginReadParams = { marketplace_path?: AbsolutePathBuf | null, remote_marketplace_name?: string | null, plugin_name: string, };
