// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteControlConnectionStatus } from "./RemoteControlConnectionStatus";

/**
 * Current remote-control connection status and environment id exposed to clients.
 */
export type RemoteControlStatusChangedNotification = { status: RemoteControlConnectionStatus, environment_id: string | null, };
