// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewTarget = { "type": "UncommittedChanges" } | { "type": "BaseBranch", branch: string, } | { "type": "Commit", sha: string, 
/**
 * Optional human-readable label (e.g., commit subject) for UIs.
 */
title: string | null, } | { "type": "Custom", instructions: string, };
