// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { NetworkAccess } from "./NetworkAccess";

export type SandboxPolicy = { "type": "DangerFullAccess" } | { "type": "ReadOnly", networkAccess: boolean, } | { "type": "ExternalSandbox", networkAccess: NetworkAccess, } | { "type": "WorkspaceWrite", writableRoots: Array<AbsolutePathBuf>, networkAccess: boolean, excludeTmpdirEnvVar: boolean, excludeSlashTmp: boolean, };
