// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoal = { thread_id: string, objective: string, status: ThreadGoalStatus, token_budget: number | null, tokens_used: number, time_used_seconds: number, created_at: number, updated_at: number, };
