// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - emitted with the remote SDP for a WebRTC realtime session.
 */
export type ThreadRealtimeSdpNotification = { thread_id: string, sdp: string, };
