// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";
import type { ThreadSortKey } from "./ThreadSortKey";
import type { ThreadSourceKind } from "./ThreadSourceKind";

export type ThreadListParams = { 
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null, 
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null, 
/**
 * Optional sort key; defaults to created_at.
 */
sort_key?: ThreadSortKey | null, 
/**
 * Optional sort direction; defaults to descending (newest first).
 */
sort_direction?: SortDirection | null, 
/**
 * Optional provider filter; when set, only sessions recorded under these
 * providers are returned. When present but empty, includes all providers.
 */
model_providers?: Array<string> | null, 
/**
 * Optional source filter; when set, only sessions from these source kinds
 * are returned. When omitted or empty, defaults to interactive sources.
 */
source_kinds?: Array<ThreadSourceKind> | null, 
/**
 * Optional archived filter; when set to true, only archived threads are returned.
 * If false or null, only non-archived threads are returned.
 */
archived?: boolean | null, 
/**
 * Optional cwd filter or filters; when set, only threads whose session cwd
 * exactly matches one of these paths are returned.
 */
cwd?: string | Array<string> | null, 
/**
 * If true, return from the state DB without scanning JSONL rollouts to
 * repair thread metadata. Omitted or false preserves scan-and-repair
 * behavior.
 */
use_state_db_only: boolean, 
/**
 * Optional substring filter for the extracted thread title.
 */
search_term?: string | null, };
