// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { DynamicToolSpec } from "./DynamicToolSpec";
import type { PermissionProfileSelectionParams } from "./PermissionProfileSelectionParams";
import type { SandboxMode } from "./SandboxMode";
import type { ThreadSource } from "./ThreadSource";
import type { ThreadStartSource } from "./ThreadStartSource";
import type { TurnEnvironmentParams } from "./TurnEnvironmentParams";

export type ThreadStartParams = { model?: string | null, model_provider?: string | null, service_tier?: string | null | null, cwd?: string | null, approval_policy?: AskForApproval | null, 
/**
 * Override where approval requests are routed for review on this thread
 * and subsequent turns.
 */
approvals_reviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null, 
/**
 * Named profile selection for this thread. Cannot be combined with
 * `sandbox`. Use bounded `modifications` for supported turn/thread
 * adjustments instead of replacing the full permissions profile.
 */
permissions?: PermissionProfileSelectionParams | null, config?: { [key in string]?: JsonValue } | null, service_name?: string | null, base_instructions?: string | null, developer_instructions?: string | null, personality?: Personality | null, ephemeral?: boolean | null, session_start_source?: ThreadStartSource | null, 
/**
 * Optional client-supplied analytics source classification for this thread.
 */
thread_source?: ThreadSource | null, 
/**
 * Optional sticky environments for this thread.
 *
 * Omitted selects the default environment when environment access is
 * enabled. Empty disables environment access for turns that do not
 * provide a turn override. Non-empty selects the first environment as the
 * current turn environment.
 */
environments?: Array<TurnEnvironmentParams> | null, dynamic_tools?: Array<DynamicToolSpec> | null, 
/**
 * Test-only experimental field used to validate experimental gating and
 * schema filtering behavior in a stable way.
 */
mock_experimental_field?: string | null, 
/**
 * If true, opt into emitting raw Responses API items on the event stream.
 * This is for internal use only (e.g. Codex Cloud).
 */
experimental_raw_events: boolean, 
/**
 * Deprecated and ignored by app-server. Kept only so older clients can
 * continue sending the field while rollout persistence always uses the
 * limited history policy.
 */
persist_extended_history: boolean, };
