// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, model_context_window: number | null, };
