// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoal } from "./ThreadGoal";

export type ThreadGoalUpdatedNotification = { thread_id: string, turn_id: string | null, goal: ThreadGoal, };
