// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadReadParams = { thread_id: string, 
/**
 * When true, include turns and their items from rollout history.
 */
include_turns: boolean, };
