// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadActiveFlag } from "./ThreadActiveFlag";

export type ThreadStatus = { "type": "NotLoaded" } | { "type": "Idle" } | { "type": "SystemError" } | { "type": "Active", activeFlags: Array<ThreadActiveFlag>, };
