// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeOutputModality } from "../RealtimeOutputModality";
import type { RealtimeVoice } from "../RealtimeVoice";
import type { ThreadRealtimeStartTransport } from "./ThreadRealtimeStartTransport";

/**
 * EXPERIMENTAL - start a thread-scoped realtime session.
 */
export type ThreadRealtimeStartParams = { thread_id: string, 
/**
 * Selects text or audio output for the realtime session. Transport and voice stay
 * independent so clients can choose how they connect separately from what the model emits.
 */
output_modality: RealtimeOutputModality, prompt?: string | null | null, realtime_session_id?: string | null, transport?: ThreadRealtimeStartTransport | null, voice?: RealtimeVoice | null, };
