// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRollbackParams = { thread_id: string, 
/**
 * The number of turns to drop from the end of the thread. Must be >= 1.
 *
 * This only modifies the thread's history and does not revert local file changes
 * that have been made by the agent. Clients are responsible for reverting these changes.
 */
num_turns: number, };
