// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ActivePermissionProfile } from "./ActivePermissionProfile";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { PermissionProfile } from "./PermissionProfile";
import type { SandboxPolicy } from "./SandboxPolicy";
import type { Thread } from "./Thread";

export type ThreadResumeResponse = { thread: Thread, model: string, model_provider: string, service_tier: string | null, cwd: AbsolutePathBuf, 
/**
 * Instruction source files currently loaded for this thread.
 */
instruction_sources: Array<AbsolutePathBuf>, approval_policy: AskForApproval, 
/**
 * Reviewer currently used for approval requests on this thread.
 */
approvals_reviewer: ApprovalsReviewer, 
/**
 * Legacy sandbox policy retained for compatibility. Experimental clients
 * should prefer `permissionProfile` when they need exact runtime
 * permissions.
 */
sandbox: SandboxPolicy, 
/**
 * Full active permissions for this thread. `activePermissionProfile`
 * carries display/provenance metadata for this runtime profile.
 */
permission_profile: PermissionProfile | null, 
/**
 * Named or implicit built-in profile that produced the active
 * permissions, when known.
 */
active_permission_profile: ActivePermissionProfile | null, reasoning_effort: ReasoningEffort | null, };
