// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadInjectItemsParams = { thread_id: string, 
/**
 * Raw Responses API items to append to the thread's model-visible history.
 */
items: Array<JsonValue>, };
