// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { GitInfo } from "./GitInfo";
import type { SessionSource } from "./SessionSource";
import type { ThreadSource } from "./ThreadSource";
import type { ThreadStatus } from "./ThreadStatus";
import type { Turn } from "./Turn";

export type Thread = { id: string, 
/**
 * Session id shared by threads that belong to the same session tree.
 */
session_id: string, 
/**
 * Source thread id when this thread was created by forking another thread.
 */
forked_from_id: string | null, 
/**
 * Usually the first user message in the thread, if available.
 */
preview: string, 
/**
 * Whether the thread is ephemeral and should not be materialized on disk.
 */
ephemeral: boolean, 
/**
 * Model provider used for this thread (for example, 'openai').
 */
model_provider: string, 
/**
 * Unix timestamp (in seconds) when the thread was created.
 */
created_at: number, 
/**
 * Unix timestamp (in seconds) when the thread was last updated.
 */
updated_at: number, 
/**
 * Current runtime status for the thread.
 */
status: ThreadStatus, 
/**
 * [UNSTABLE] Path to the thread on disk.
 */
path: string | null, 
/**
 * Working directory captured for the thread.
 */
cwd: AbsolutePathBuf, 
/**
 * Version of the CLI that created the thread.
 */
cli_version: string, 
/**
 * Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).
 */
source: SessionSource, 
/**
 * Optional analytics source classification for this thread.
 */
thread_source: ThreadSource | null, 
/**
 * Optional random unique nickname assigned to an AgentControl-spawned sub-agent.
 */
agent_nickname: string | null, 
/**
 * Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
 */
agent_role: string | null, 
/**
 * Optional Git metadata captured when the thread was created.
 */
git_info: GitInfo | null, 
/**
 * Optional user-facing thread title.
 */
name: string | null, 
/**
 * Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read`
 * (when `includeTurns` is true) responses.
 * For all other responses and notifications returning a Thread,
 * the turns field will be an empty list.
 */
turns: Array<Turn>, };
