// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ResponseItem } from "../ResponseItem";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { PermissionProfileSelectionParams } from "./PermissionProfileSelectionParams";
import type { SandboxMode } from "./SandboxMode";

/**
 * There are three ways to resume a thread:
 * 1. By thread_id: load the thread from disk by thread_id and resume it.
 * 2. By history: instantiate the thread from memory and resume it.
 * 3. By path: load the thread from disk by path and resume it.
 *
 * The precedence is: history > path > thread_id.
 * If using history or path, the thread_id param will be ignored.
 *
 * Prefer using thread_id whenever possible.
 */
export type ThreadResumeParams = { thread_id: string, 
/**
 * [UNSTABLE] FOR CODEX CLOUD - DO NOT USE.
 * If specified, the thread will be resumed with the provided history
 * instead of loaded from disk.
 */
history?: Array<ResponseItem> | null, 
/**
 * [UNSTABLE] Specify the rollout path to resume from.
 * If specified, the thread_id param will be ignored.
 */
path?: string | null, 
/**
 * Configuration overrides for the resumed thread, if any.
 */
model?: string | null, model_provider?: string | null, service_tier?: string | null | null, cwd?: string | null, approval_policy?: AskForApproval | null, 
/**
 * Override where approval requests are routed for review on this thread
 * and subsequent turns.
 */
approvals_reviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null, 
/**
 * Named profile selection for the resumed thread. Cannot be combined
 * with `sandbox`. Use bounded `modifications` for supported thread
 * adjustments instead of replacing the full permissions profile.
 */
permissions?: PermissionProfileSelectionParams | null, config?: { [key in string]?: JsonValue } | null, base_instructions?: string | null, developer_instructions?: string | null, personality?: Personality | null, 
/**
 * When true, return only thread metadata and live-resume state without
 * populating `thread.turns`. This is useful when the client plans to call
 * `thread/turns/list` immediately after resuming.
 */
exclude_turns: boolean, 
/**
 * Deprecated and ignored by app-server. Kept only so older clients can
 * continue sending the field while rollout persistence always uses the
 * limited history policy.
 */
persist_extended_history: boolean, };
