// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";

export type ThreadTurnsItemsListParams = { thread_id: string, turn_id: string, 
/**
 * Opaque cursor to pass to the next call to continue after the last item.
 */
cursor?: string | null, 
/**
 * Optional item page size.
 */
limit?: number | null, 
/**
 * Optional item pagination direction; defaults to ascending.
 */
sort_direction?: SortDirection | null, };
