// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTokenUsage } from "./ThreadTokenUsage";

export type ThreadTokenUsageUpdatedNotification = { thread_id: string, turn_id: string, token_usage: ThreadTokenUsage, };
