// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolRequestUserInputQuestion } from "./ToolRequestUserInputQuestion";

/**
 * EXPERIMENTAL. Params sent with a request_user_input event.
 */
export type ToolRequestUserInputParams = { thread_id: string, turn_id: string, item_id: string, questions: Array<ToolRequestUserInputQuestion>, };
