// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInput } from "./UserInput";

export type TurnSteerParams = { thread_id: string, input: Array<UserInput>, 
/**
 * Optional turn-scoped Responses API client metadata.
 */
responsesapi_client_metadata?: { [key in string]?: string } | null, 
/**
 * Required active turn id precondition. The request fails when it does not
 * match the currently active turn.
 */
expected_turn_id: string, };
