// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";
import type { TurnError } from "./TurnError";
import type { TurnItemsView } from "./TurnItemsView";
import type { TurnStatus } from "./TurnStatus";

export type Turn = { id: string, 
/**
 * Thread items currently included in this turn payload.
 */
items: Array<ThreadItem>, 
/**
 * Describes how much of `items` has been loaded for this turn.
 */
items_view: TurnItemsView, status: TurnStatus, 
/**
 * Only populated when the Turn's status is failed.
 */
error: TurnError | null, 
/**
 * Unix timestamp (in seconds) when the turn started.
 */
started_at: number | null, 
/**
 * Unix timestamp (in seconds) when the turn completed.
 */
completed_at: number | null, 
/**
 * Duration between turn start and completion in milliseconds, if known.
 */
duration_ms: number | null, };
