// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnPlanStep } from "./TurnPlanStep";

export type TurnPlanUpdatedNotification = { thread_id: string, turn_id: string, explanation: string | null, plan: Array<TurnPlanStep>, };
