// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexErrorInfo } from "./CodexErrorInfo";

export type TurnError = { message: string, codex_error_info: CodexErrorInfo | null, additional_details: string | null, };
