// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextElement } from "./TextElement";

export type UserInput = { "type": "Text", text: string, 
/**
 * UI-defined spans within `text` used to render or persist special elements.
 */
text_elements: Array<TextElement>, } | { "type": "Image", url: string, } | { "type": "LocalImage", path: string, } | { "type": "Skill", name: string, path: string, } | { "type": "Mention", name: string, path: string, };
