// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowsWorldWritableWarningNotification = { sample_paths: Array<string>, extra_count: number, failed_scan: boolean, };
