//! Built-in fallback seccomp allow-list.

use crate::prelude::*;

use super::syscall_nr;

pub(crate) fn allowed_syscalls() -> Vec<u32> {
    ALLOWED_SYSCALL_NAMES
        .iter()
        .filter_map(|name| syscall_nr(name))
        .collect()
}

const ALLOWED_SYSCALL_NAMES: &[&str] = &[
    // I/O fundamentals
    "read",
    "write",
    "close",
    "pread64",
    "pwrite64",
    "readv",
    "writev",
    "getdents64",
    "fcntl",
    "flock",
    // File operations
    "openat",
    "mkdirat",
    "mknodat",
    "fchownat",
    "newfstatat",
    "unlinkat",
    "renameat",
    "linkat",
    "symlinkat",
    "readlinkat",
    "fchmodat",
    "faccessat",
    "faccessat2",
    "fsync",
    "rename",
    "mkdir",
    "rmdir",
    "unlink",
    "symlink",
    "readlink",
    "chmod",
    "fchmod",
    "chown",
    "fchown",
    "mknod",
    "getcwd",
    // Memory management
    "mmap",
    "mprotect",
    "munmap",
    "brk",
    "mremap",
    "mincore",
    "madvise",
    "fallocate",
    // Signal handling
    "rt_sigaction",
    "rt_sigprocmask",
    "rt_sigreturn",
    "kill",
    "rt_sigpending",
    "rt_sigtimedwait",
    "rt_sigqueueinfo",
    "rt_sigsuspend",
    "sigaltstack",
    "tgkill",
    "tkill",
    // Process management
    "getpid",
    "clone",
    "clone3",
    "fork",
    "vfork",
    "execve",
    "exit",
    "exit_group",
    "wait4",
    "setpgid",
    "getppid",
    "getpgrp",
    "setsid",
    "getpgid",
    "getsid",
    // Thread / TLS setup
    "set_tid_address",
    "set_robust_list",
    "get_robust_list",
    "gettimeofday",
    "clock_gettime",
    "clock_getres",
    "clock_nanosleep",
    "nanosleep",
    "futex",
    "arch_prctl",
    "rseq",
    "sysinfo",
    "times",
    // Random / entropy
    "getrandom",
    // User/identity
    "getuid",
    "getgid",
    "setuid",
    "setgid",
    "geteuid",
    "getegid",
    "getgroups",
    "setgroups",
    "setresuid",
    "getresuid",
    "setresgid",
    "getresgid",
    "setfsuid",
    "setfsgid",
    // Capabilities / security
    "capget",
    "capset",
    "prctl",
    "seccomp",
    // Resource limits
    "getrlimit",
    "setrlimit",
    "prlimit64",
    "getrusage",
    "syslog",
    // Network
    "socket",
    "connect",
    "accept",
    "accept4",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "recvmmsg",
    "shutdown",
    "bind",
    "listen",
    "getsockname",
    "getpeername",
    "socketpair",
    "setsockopt",
    "getsockopt",
    // Event / epoll / io multiplexing
    "poll",
    "select",
    "pselect6",
    "ppoll",
    "epoll_wait",
    "epoll_ctl",
    "epoll_pwait",
    "epoll_create1",
    "signalfd",
    "signalfd4",
    "timerfd_create",
    "timerfd_settime",
    "timerfd_gettime",
    "eventfd",
    // Scheduling
    "sched_yield",
    "sched_setparam",
    "sched_getparam",
    "sched_setscheduler",
    "sched_getscheduler",
    "sched_get_priority_max",
    "sched_get_priority_min",
    "sched_rr_get_interval",
    "sched_setaffinity",
    "sched_getaffinity",
    // Misc
    "uname",
    "ioctl",
    "access",
    "dup",
    "dup2",
    "dup3",
    "chdir",
    "fchdir",
    "getcpu",
    "pidfd_send_signal",
    "pidfd_open",
    "close_range",
];
