[package]
name = "edgerun-mail-web"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Webmail frontend for edgerun email server"

[dependencies]
edgerun-http = { path = "../edgerun-http", default-features = false, features = ["server", "static-files"] }
edgerun-log = { path = "../edgerun-log" }

[lints]
workspace = true
