[package]
name = "edgerun-clap"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Zero-dependency drop-in replacement for clap crate"

[features]
default = []
std = ["edgerun-json/std"]

[dependencies]
edgerun-json = { path = "../edgerun-json", default-features = false }
edgerun-clap-derive = { path = "../edgerun-clap-derive" }

[lints]
workspace = true
