// Edgerun Conformance Tests
// AUTO-GENERATED by scripts/generate_conformance_tests.py
// DO NOT EDIT. Re-run the generator after proto or rasterizer changes.
//
#![allow(clippy::identity_op)]

// ─── Framebuffer ───
// ─── Framebuffer Conformance ───

#[test]
fn framebuffer_clear() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    let mut pixels = vec![0u8; 8 * 4 * 4]; // 8x4
    let mut fb = Framebuffer::new(&mut pixels, 8, 4);
    fb.clear();
    // Every pixel should be 0x1a, 0x1a, 0x2e, 0xFF
    for i in (0..pixels.len()).step_by(4) {
        assert_eq!(pixels[i], 0x1a);
        assert_eq!(pixels[i + 1], 0x1a);
        assert_eq!(pixels[i + 2], 0x2e);
        assert_eq!(pixels[i + 3], 0xFF);
    }
}

#[test]
fn framebuffer_fill_solid() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    let mut pixels = vec![0u8; 8 * 8 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 8, 8);
    fb.clear();
    fb.fill_solid(1, 1, 3, 3, 0xFF, 0x00, 0x80);
    // Center pixel should be filled
    let i = (2 * 8 * 4 + 2 * 4) as usize;
    assert_eq!(pixels[i], 0x80);   // B
    assert_eq!(pixels[i + 1], 0x00); // G
    assert_eq!(pixels[i + 2], 0xFF); // R
}

#[test]
fn framebuffer_fill_alpha_opaque() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    let mut pixels = vec![0u8; 4 * 4 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 4, 4);
    fb.clear();
    fb.fill_alpha(0, 0, 4, 4, 0xFF, 0xFF, 0xFF, 255);
    // Alpha=255 should be same as fill_solid
    for i in (0..pixels.len()).step_by(4) {
        assert_eq!(pixels[i], 0xFF);   // B
        assert_eq!(pixels[i + 1], 0xFF); // G
        assert_eq!(pixels[i + 2], 0xFF); // R
    }
}

#[test]
fn framebuffer_fill_alpha_zero() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    let mut pixels = vec![0u8; 4 * 4 * 4];
    {
        let mut fb = Framebuffer::new(&mut pixels, 4, 4);
        fb.clear();
    }
    let bg = pixels.clone();
    {
        let mut fb = Framebuffer::new(&mut pixels, 4, 4);
        fb.fill_alpha(0, 0, 4, 4, 0xFF, 0xFF, 0xFF, 0);
    }
    // Alpha=0 should not change anything
    assert_eq!(pixels, bg);
}

#[test]
fn framebuffer_clips_bounds() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    let mut pixels = vec![0u8; 4 * 4 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 4, 4);
    fb.clear();
    // Fill beyond bounds — should not panic
    fb.fill_solid(2, 2, 10, 10, 0xFF, 0x00, 0x00);
    fb.fill_alpha(0, 0, 100, 100, 0x00, 0xFF, 0x00, 128);
    // Just verifying it doesn't panic — values are clamped
}

// ─── Color LUT ───
// ─── Color LUT Conformance (148 named colors) ───

#[test]
fn color_lut_known_values() {
    use edgerun_rasterizer::color_lut::{named_color, COLOR_LUT, NAMED_COLOR_COUNT};
    assert_eq!(NAMED_COLOR_COUNT, 148);
    // black
    // white
    // red
    // green
    // blue
    // yellow
    // cyan
    // magenta
    // orange
    // purple
    let (r, g, b, a) = named_color(0);
    assert_eq!((r, g, b, a), (0x00, 0x00, 0x00, 0xFF), "black");
    let (r, g, b, a) = named_color(1);
    assert_eq!((r, g, b, a), (0xFF, 0xFF, 0xFF, 0xFF), "white");
    let (r, g, b, a) = named_color(2);
    assert_eq!((r, g, b, a), (0xFF, 0x00, 0x00, 0xFF), "red");
    let (r, g, b, a) = named_color(3);
    assert_eq!((r, g, b, a), (0x00, 0x80, 0x00, 0xFF), "green");
    let (r, g, b, a) = named_color(4);
    assert_eq!((r, g, b, a), (0x00, 0x00, 0xFF, 0xFF), "blue");
}

#[test]
fn color_lut_all_entries_valid() {
    use edgerun_rasterizer::color_lut::COLOR_LUT;
    // All 148 entries are non-zero-length colors (at least one channel is non-zero,
    // or alpha is 0 for transparent). The LUT is statically defined so values are
    // guaranteed valid u8 — this test documents the invariant.
    assert_eq!(COLOR_LUT[0], [0x00, 0x00, 0x00, 0xFF]); // black is entry 0
    assert_eq!(COLOR_LUT.len(), 148);
}

#[test]
fn color_lut_transparent_is_transparent() {
    use edgerun_rasterizer::color_lut::named_color;
    let (_, _, _, a) = named_color(12); // transparent
    assert_eq!(a, 0x00, "transparent color should have alpha=0");
}

// ─── Border Patterns ───
// ─── Border Pattern Conformance ───

#[test]
fn border_patterns_all_valid() {
    use edgerun_rasterizer::border_lut::*;
    assert_eq!(DASHED_PATTERN, [1, 1, 1, 1, 0, 0, 0, 0]);
    assert_eq!(DOTTED_PATTERN, [1, 0, 0, 0, 1, 0, 0, 0]);
    assert_eq!(DOUBLE_PATTERN, [1, 1, 0, 1, 1, 0, 0, 0]);
    assert_eq!(SOLID_PATTERN, [1, 1, 1, 1, 1, 1, 1, 1]);
    assert_eq!(GROOVE_PATTERN, [1, 0, 1, 0, 1, 0, 1, 0]);
    assert_eq!(RIDGE_PATTERN, [1, 0, 1, 0, 1, 0, 1, 0]);
    assert_eq!(INSET_PATTERN, [1, 1, 1, 1, 1, 1, 1, 1]);
    assert_eq!(OUTSET_PATTERN, [1, 1, 1, 1, 1, 1, 1, 1]);
    assert_eq!(NONE_PATTERN, [0, 0, 0, 0, 0, 0, 0, 0]);
}

#[test]
fn border_pattern_dispatch() {
    use edgerun_rasterizer::border_lut::{border_pattern, *};
    // 0=none, 1=solid, 2=dashed, 3=dotted, 4=double,
    // 5=groove, 6=ridge, 7=inset, 8=outset
    let p0 = border_pattern(0);
    assert_eq!(*p0, NONE_PATTERN);
    let p1 = border_pattern(1);
    assert_eq!(*p1, SOLID_PATTERN);
    let p2 = border_pattern(2);
    assert_eq!(*p2, DASHED_PATTERN);
    let p3 = border_pattern(3);
    assert_eq!(*p3, DOTTED_PATTERN);
    let p4 = border_pattern(4);
    assert_eq!(*p4, DOUBLE_PATTERN);
    let p5 = border_pattern(5);
    assert_eq!(*p5, GROOVE_PATTERN);
    let p6 = border_pattern(6);
    assert_eq!(*p6, RIDGE_PATTERN);
    let p7 = border_pattern(7);
    assert_eq!(*p7, INSET_PATTERN);
    let p8 = border_pattern(8);
    assert_eq!(*p8, OUTSET_PATTERN);
}

#[test]
fn border_pattern_clamps_out_of_range() {
    use edgerun_rasterizer::border_lut::{border_pattern, *};
    // Out-of-range should clamp to last (outset)
    let p = border_pattern(255);
    assert_eq!(*p, OUTSET_PATTERN);
}

#[test]
fn border_solid_is_all_draw() {
    use edgerun_rasterizer::border_lut::SOLID_PATTERN;
    assert!(SOLID_PATTERN.iter().all(|&b| b == 1));
}

#[test]
fn border_none_is_all_skip() {
    use edgerun_rasterizer::border_lut::NONE_PATTERN;
    assert!(NONE_PATTERN.iter().all(|&b| b == 0));
}

// ─── Blend Modes ───
// ─── Blend Mode Conformance ───

#[test]
fn blend_normal_is_identity() {
    use edgerun_rasterizer::blend_lut::blend_normal;
    // Normal blend: source replaces destination
    assert_eq!(blend_normal(0x00, 0xFF), 0x00);
    assert_eq!(blend_normal(0x80, 0x40), 0x80);
    assert_eq!(blend_normal(0xFF, 0x00), 0xFF);
}

#[test]
fn blend_multiply() {
    use edgerun_rasterizer::blend_lut::blend_multiply;
    assert_eq!(blend_multiply(0, 255), 0);    // 0 * anything = 0
    assert_eq!(blend_multiply(255, 255), 255); // 1 * 1 = 1
    assert_eq!(blend_multiply(128, 128), 64);  // 0.5 * 0.5 = 0.25
}

#[test]
fn blend_screen() {
    use edgerun_rasterizer::blend_lut::blend_screen;
    assert_eq!(blend_screen(0, 0), 0);       // 0 + 0 - 0 = 0
    assert_eq!(blend_screen(255, 0), 255);   // 1 + 0 - 0 = 1
    assert_eq!(blend_screen(0, 255), 255);   // 0 + 1 - 0 = 1
}

#[test]
fn blend_darken_lighten() {
    use edgerun_rasterizer::blend_lut::{blend_darken, blend_lighten};
    assert_eq!(blend_darken(100, 200), 100);
    assert_eq!(blend_darken(200, 100), 100);
    assert_eq!(blend_lighten(100, 200), 200);
    assert_eq!(blend_lighten(200, 100), 200);
}

#[test]
fn blend_difference() {
    use edgerun_rasterizer::blend_lut::blend_difference;
    assert_eq!(blend_difference(100, 100), 0);
    assert_eq!(blend_difference(255, 0), 255);
    assert_eq!(blend_difference(0, 255), 255);
}

#[test]
fn blend_exclusion() {
    use edgerun_rasterizer::blend_lut::blend_exclusion;
    assert_eq!(blend_exclusion(0, 0), 0);
    assert_eq!(blend_exclusion(255, 255), 0);
    // 128 + 128 - 2*128*128/255 = 256 - 128 = 128
    assert_eq!(blend_exclusion(128, 128), 128);
}

#[test]
fn blend_alpha_blending() {
    use edgerun_rasterizer::blend_lut::alpha_blend;
    assert_eq!(alpha_blend(0xFF, 0x00, 255), 0xFF);  // fully opaque src
    assert_eq!(alpha_blend(0x00, 0xFF, 0), 0xFF);    // fully transparent src
    assert_eq!(alpha_blend(0xFF, 0x00, 128), 0x80);  // 50% blend
}

#[test]
fn blend_mode_count() {
    // 16 blend functions exist
    use edgerun_rasterizer::blend_lut::blend_normal;
    use edgerun_rasterizer::blend_lut::blend_multiply;
    use edgerun_rasterizer::blend_lut::blend_screen;
    use edgerun_rasterizer::blend_lut::blend_overlay;
    use edgerun_rasterizer::blend_lut::blend_darken;
    use edgerun_rasterizer::blend_lut::blend_lighten;
    use edgerun_rasterizer::blend_lut::blend_colordodge;
    use edgerun_rasterizer::blend_lut::blend_colorburn;
    use edgerun_rasterizer::blend_lut::blend_hardlight;
    use edgerun_rasterizer::blend_lut::blend_softlight;
    use edgerun_rasterizer::blend_lut::blend_difference;
    use edgerun_rasterizer::blend_lut::blend_exclusion;
    use edgerun_rasterizer::blend_lut::blend_hue;
    use edgerun_rasterizer::blend_lut::blend_saturation;
    use edgerun_rasterizer::blend_lut::blend_color;
    use edgerun_rasterizer::blend_lut::blend_luminosity;
}

// ─── Bitmap Font ───
// ─── Bitmap Font Conformance ───

#[test]
fn font_table_size() {
    use edgerun_rasterizer::text_bitmap::FONT_8X8;
    assert_eq!(FONT_8X8.len(), 128); // 7-bit ASCII
    for glyph in &FONT_8X8 {
        assert_eq!(glyph.len(), 8); // 8 rows per glyph
    }
}

#[test]
fn font_known_glyphs() {
    use edgerun_rasterizer::text_bitmap::FONT_8X8;
    // '0' (ASCII 48)
    assert_eq!(FONT_8X8[48], [0x3C, 0x66, 0x6E, 0x76, 0x66, 0x66, 0x3C, 0x00]);
    // 'A' (ASCII 65)
    assert_eq!(FONT_8X8[65], [0x18, 0x3C, 0x66, 0x66, 0x7E, 0x66, 0x66, 0x00]);
    // 'a' (ASCII 97)
    assert_eq!(FONT_8X8[97], [0x00, 0x00, 0x3C, 0x06, 0x3E, 0x66, 0x3E, 0x00]);
    // '!' (ASCII 33)
    assert_eq!(FONT_8X8[33], [0x18, 0x18, 0x18, 0x18, 0x18, 0x00, 0x18, 0x00]);
}

#[test]
fn all_glyphs_valid_size() {
    use edgerun_rasterizer::text_bitmap::FONT_8X8;
    for (i, glyph) in FONT_8X8.iter().enumerate() {
        assert_eq!(glyph.len(), 8, "glyph {i} has wrong size");
    }
}

// ─── Gradients ───
// ─── Gradient Conformance ───

#[test]
fn gradient_stop_count_min() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    use edgerun_rasterizer::gradient::GradientStop;
    let mut pixels = vec![0u8; 8 * 8 * 4];
    {
        let mut fb = Framebuffer::new(&mut pixels, 8, 8);
        fb.clear();
    }
    // Capture bg state
    let bg_b = pixels[0];
    let bg_g = pixels[1];
    let bg_r = pixels[2];
    {
        let mut fb = Framebuffer::new(&mut pixels, 8, 8);
        // Gradient with < 2 stops should be a no-op
        let cmds = [RasterCommand::LinearGradient {
            x: 0, y: 0, w: 8, h: 8, angle: 0.0,
            stops: vec![GradientStop { r: 0xFF, g: 0, b: 0, a: 255, position: 0.0 }],
        }];
        rasterize(&mut fb, &cmds);
    }
    // Should remain background
    assert_eq!(pixels[0], bg_b, "B channel unchanged");
    assert_eq!(pixels[1], bg_g, "G channel unchanged");
    assert_eq!(pixels[2], bg_r, "R channel unchanged");
}

#[test]
fn linear_gradient_endpoints() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    use edgerun_rasterizer::gradient::GradientStop;
    let mut pixels = vec![0u8; 8 * 2 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 8, 2);
    fb.clear();
    let cmds = [RasterCommand::LinearGradient {
        x: 0, y: 0, w: 8, h: 2, angle: 0.0,
        stops: vec![
            GradientStop { r: 0xFF, g: 0, b: 0, a: 255, position: 0.0 },
            GradientStop { r: 0, g: 0, b: 0xFF, a: 255, position: 1.0 },
        ],
    }];
    rasterize(&mut fb, &cmds);
    // Left pixel should be closer to red
    let left_r = pixels[2]; // pixel 0, R channel
    // Right pixel should be closer to blue
    let right_b = pixels[7 * 4]; // pixel 7, B channel
    assert!(left_r > 0, "left pixel should have some red");
    assert!(right_b > 0, "right pixel should have some blue");
}

// ─── Scanline Rasterizer ───
// ─── Scanline Rasterizer Conformance ───

#[test]
fn fill_rect_solid() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    let mut pixels = vec![0u8; 8 * 8 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 8, 8);
    fb.clear();
    let cmds = [RasterCommand::FillRect {
        x: 2, y: 2, w: 4, h: 4,
        r: 0xFF, g: 0x00, b: 0x80, a: 255,
    }];
    rasterize(&mut fb, &cmds);
    // Inside rect
    let i = (3 * 8 * 4 + 3 * 4) as usize;
    assert_eq!(pixels[i], 0x80);   // B
    assert_eq!(pixels[i + 1], 0x00); // G
    assert_eq!(pixels[i + 2], 0xFF); // R
    // Outside rect (should remain background)
    let j = 0; // pixel (0,0), outside the rect
    assert_eq!(pixels[j], 0x1a);   // B = bg
}

#[test]
fn fill_rect_zero_size_is_noop() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    let mut pixels = vec![0u8; 4 * 4 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 4, 4);
    fb.clear();
    let bg: [u8; 64] = {
        let mut tmp = [0u8; 64];
        for i in (0..64).step_by(4) { tmp[i] = 0x1a; tmp[i+1] = 0x1a; tmp[i+2] = 0x2e; tmp[i+3] = 0xFF; }
        tmp
    };
    let cmds = [RasterCommand::FillRect {
        x: 0, y: 0, w: 0, h: 0,
        r: 0xFF, g: 0, b: 0, a: 255,
    }];
    rasterize(&mut fb, &cmds);
    assert_eq!(&pixels[..], &bg[..], "zero-size rect should not modify framebuffer");
}

#[test]
fn fill_rect_alpha_blend() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    let mut pixels = vec![0u8; 4 * 4 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 4, 4);
    fb.clear();
    let cmds = [RasterCommand::FillRect {
        x: 0, y: 0, w: 4, h: 4,
        r: 0xFF, g: 0xFF, b: 0xFF, a: 128,
    }];
    rasterize(&mut fb, &cmds);
    // Alpha=128 should blend towards white
    let i = 0usize;
    // Background was 0x1a, 0x1a, 0x2e
    // With 50% white: should be between bg and white
    assert!(pixels[i] > 0x1a, "B channel should increase");
    assert!(pixels[i + 2] > 0x2e, "R channel should increase");
}

#[test]
fn empty_command_list_is_noop() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{rasterize, RasterCommand};
    let mut pixels = vec![0u8; 4 * 4 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 4, 4);
    fb.clear();
    let cmds: &[RasterCommand] = &[];
    // Just verify it doesn't panic — clear() sets bg color
    rasterize(&mut fb, &cmds);
    assert_eq!(pixels[0], 0x1a);
}

#[test]
fn stroke_rect_solid_border() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    let mut pixels = vec![0u8; 8 * 8 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 8, 8);
    fb.clear();
    let cmds = [RasterCommand::StrokeRect {
        x: 1, y: 1, w: 6, h: 6,
        r: 0xFF, g: 0, b: 0,
        style: 1, // solid
        thickness: 1,
    }];
    rasterize(&mut fb, &cmds);
    // Top-left border pixel
    let i = (1 * 8 * 4 + 1 * 4) as usize;
    assert_eq!(pixels[i], 0x00);   // B
    assert_eq!(pixels[i + 1], 0x00); // G
    assert_eq!(pixels[i + 2], 0xFF); // R
    // Inside (not stroked) — should be background
    let j = (2 * 8 * 4 + 2 * 4) as usize;
    assert_eq!(pixels[j], 0x1a);   // B = bg
}

#[test]
fn text_renders_non_whitespace() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    let mut pixels = vec![0u8; 32 * 8 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 32, 8);
    fb.clear();
    let cmds = [RasterCommand::Text {
        x: 0, y: 0,
        text: "Hi".to_string(),
        r: 0xFF, g: 0xFF, b: 0xFF,
    }];
    rasterize(&mut fb, &cmds);
    // At least some pixels should have changed from background
    let changed = pixels.iter().enumerate().filter(|(i, &v)| {
        match i % 4 { 0 => v != 0x1a, 1 => v != 0x1a, 2 => v != 0x2e, _ => false }
    }).count();
    assert!(changed > 0, "text should modify at least some pixels (modified {})", changed);
}

#[test]
fn whitespace_text_is_skipped() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::scanline::{RasterCommand, rasterize};
    let mut pixels = vec![0u8; 16 * 8 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 16, 8);
    fb.clear();
    let cmds = [RasterCommand::Text {
        x: 0, y: 0,
        text: "   ".to_string(),
        r: 0xFF, g: 0xFF, b: 0xFF,
    }];
    // Note: the text_bitmap module draws all chars including space.
    // The demo-level code skips whitespace-only nodes before creating commands.
    // At the rasterizer level, space IS drawn (as a blank glyph box).
    rasterize(&mut fb, &cmds);
    // Space glyph has 0xFF mask which means all pixels are 'drawn' but the
    // font bitmap for space is 0xFF,0x81,... which IS a box shape.
    // This test documents the behavior.
}

// ─── Rectangle Rendering ───
// ─── Rectangle Rendering Conformance ───

#[test]
fn fill_rect_alpha_zero_no_change() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::rect::fill_rect;
    let mut pixels = vec![0u8; 4 * 4 * 4];
    {
        let mut fb = Framebuffer::new(&mut pixels, 4, 4);
        fb.clear();
    }
    let bg: [u8; 64] = {
        let mut tmp = [0u8; 64];
        for i in (0..64).step_by(4) { tmp[i] = 0x1a; tmp[i+1] = 0x1a; tmp[i+2] = 0x2e; tmp[i+3] = 0xFF; }
        tmp
    };
    {
        let mut fb = Framebuffer::new(&mut pixels, 4, 4);
        fill_rect(&mut fb, 0, 0, 4, 4, 0xFF, 0x00, 0x00, 0);
    }
    assert_eq!(&pixels[..], &bg[..]);
}

#[test]
fn stroke_rect_thickness() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::rect::stroke_rect;
    let mut pixels = vec![0u8; 10 * 10 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 10, 10);
    fb.clear();
    stroke_rect(&mut fb, 2, 2, 6, 6, 0xFF, 0, 0, 1, 3);
    // Top border at y=2, spanning x=2..8, thickness=3
    // Check center of top border (row 2, col 5)
    // Pixel index: row*stride + col*4, R is at +2
    let i = (2u32 * 40 + 5u32 * 4) as usize;
    let is_red = pixels[i + 2] == 0xFF;
    assert!(is_red, "center of top border should be red (got r={})", pixels[i + 2]);
}

#[test]
fn stroke_rect_dashed_pattern() {
    use edgerun_rasterizer::framebuffer::Framebuffer;
    use edgerun_rasterizer::rect::stroke_rect;
    let mut pixels = vec![0u8; 16 * 2 * 4];
    let mut fb = Framebuffer::new(&mut pixels, 16, 2);
    fb.clear();
    stroke_rect(&mut fb, 0, 0, 16, 1, 0xFF, 0, 0, 2, 1); // style=2 (dashed)
    // Dashed: 4 on, 4 off → first 4 pixels should be red
    // Top border row is y=0, stride=64
    for x in 0..4u32 {
        let i = (x * 4 + 2) as usize; // R channel of pixel x
        assert_eq!(pixels[i], 0xFF, "R at x={x} should be drawn");
    }
    // Next 4 should be off (background)
    for x in 4..8u32 {
        let i = (x * 4 + 2) as usize;
        assert_eq!(pixels[i], 0x2e, "R at x={x} should be bg");
    }
}

// ─── Proto Enums ───
// ─── Proto Enum Conformance ───
// AUTO-GENERATED from proto/*.proto files.
// Re-run scripts/generate_conformance_tests.py after proto changes.

#[test]
fn css_value_type_enum_discriminants() {
    // Total: 65 value types
    // Generated from css_value_types.proto
    // CSS_VALUE_TYPE_UNSPECIFIED = 0
    // EM = 1
    // REM = 2
    // EX = 3
    // REX = 4
    // CAP = 5
    // RCAP = 6
    // CH = 7
    // RCH = 8
    // IC = 9
    // RIC = 10
    // LH = 11
    // RLH = 12
    // VW = 13
    // SVW = 14
    // LVW = 15
    // DVW = 16
    // VH = 17
    // SVH = 18
    // LVH = 19
    // DVH = 20
    // VI = 21
    // SVI = 22
    // LVI = 23
    // DVI = 24
    // VB = 25
    // SVB = 26
    // LVB = 27
    // DVB = 28
    // VMIN = 29
    // SVMIN = 30
    // LVMIN = 31
    // DVMIN = 32
    // VMAX = 33
    // SVMAX = 34
    // LVMAX = 35
    // DVMAX = 36
    // CM = 37
    // MM = 38
    // Q = 39
    // IN = 40
    // PC = 41
    // PT = 42
    // PX = 43
    // DEG = 44
    // GRAD = 45
    // RAD = 46
    // TURN = 47
    // S = 48
    // MS = 49
    // HZ = 50
    // KHZ = 51
    // DPI = 52
    // DPCM = 53
    // DPPX = 54
    // X = 55
    // NONE = 56
    // NEAREST = 57
    // UP = 58
    // DOWN = 59
    // TO_ZERO = 60
    // LINE_WIDTH = 61
    // E = 62
    // PI = 63
    // INFINITY = 64
    // NAN = 66
}

#[test]
fn css_property_enum_discriminants() {
    // Total: 19 CSS properties
    // Generated from css_properties.proto
    // CSS_PROPERTY_UNSPECIFIED = 0
    // ANIMATION_NAME = 1
    // ANIMATION_DURATION = 2
    // ANIMATION_TIMING_FUNCTION = 3
    // ANIMATION_ITERATION_COUNT = 4
    // ... and 14 more
}

#[test]
fn css_display_outer_enum() {
    // Total: 8 display outer types
    // DISPLAY_OUTER_UNSPECIFIED = 0
    // FLOW = 1
    // FLOW_ROOT = 2
    // TABLE = 3
    // FLEX = 4
    // GRID = 5
    // RUBY = 6
    // NONE = 7
    // CONTENTS = 8
}

#[test]
fn css_display_inner_enum() {
    // Total: 18 display inner types
    // DISPLAY_INNER_UNSPECIFIED = 0
    // BLOCK = 1
    // INLINE = 2
    // TABLE_ROW_GROUP = 3
    // TABLE_HEADER_GROUP = 4
    // TABLE_FOOTER_GROUP = 5
    // TABLE_ROW = 6
    // TABLE_CELL = 7
    // TABLE_COLUMN_GROUP = 8
    // TABLE_COLUMN = 9
    // TABLE_CAPTION = 10
    // INNER_FLEX = 11
    // INNER_GRID = 12
    // RUBY_BASE = 13
    // RUBY_TEXT = 14
    // RUBY_BASE_CONTAINER = 15
    // RUBY_TEXT_CONTAINER = 16
    // LIST_ITEM = 17
    // MATH = 18
}

#[test]
fn css_shadow_type_enum() {
    // SHADOW_TYPE_UNSPECIFIED = 0
    // DROP = 1
    // INSET = 2
}

#[test]
fn html_element_enum_count() {
    // Total: 108 HTML elements
    // Generated from html_elements.proto
}


// ─── Summary ───
// Total proto files scanned: 40
// Total color LUT entries: 148
// Total border patterns: 9
// Total blend modes: 16
// Total font glyphs: 128