[package]
name = "edgerun-ts-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Owned EdgeRun TypeScript type export support"

[dependencies]
edgerun-error = { path = "../edgerun-error", default-features = false, features = ["std"] }
edgerun-ts-rs-derive = { path = "../edgerun-ts-rs-derive" }

[features]
default = []
uuid-impl = []
serde-json-impl = []
no-serde-warnings = []

[lints]
workspace = true
