[package]
name = "edgerun-ts-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun shim for ts-rs"

[dependencies]
ts-rs = { path = "../../../vendor/cargo/ts-rs", default-features = false }

[features]
default = []
uuid-impl = ["ts-rs/uuid-impl"]
serde-json-impl = ["ts-rs/serde-json-impl"]
no-serde-warnings = ["ts-rs/no-serde-warnings"]

[lints]
workspace = true
