[package]
name = "edgerun-crypto-wasm-bench"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "native-bench"
path = "src/main.rs"

[dependencies]
edgerun-crypto = { path = "../../../crates/utility/edgerun-crypto", default-features = false, features = [
  "full",
  "sha1",
] }

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "fat"
strip = true
