[package]
name = "edgerun-linux-cec"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Linux HDMI-CEC adapter for Edgerun"

[dependencies]
edgerun-capabilities = { version = "0.1", path = "../edgerun-capabilities" }
edgerun-cec = { version = "0.1", path = "../edgerun-cec" }
edgerun-linux-gpu = { version = "0.1", path = "../edgerun-linux-gpu" }
edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding" }

[features]
std = []

[[bin]]
name = "linux_cec_tool"
path = "src/bin/linux-cec-tool.rs"
required-features = ["std"]

[lints]
workspace = true
