[package]
name = "edgerun-linux-cec"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-cec = { path = "../edgerun-cec" }
edgerun-linux-gpu = { path = "../edgerun-linux-gpu" }
edgerun-linux-sysfs = { path = "../edgerun-linux-sysfs" }
edgerun-encoding = { path = "../edgerun-encoding" }

[features]
std = []

[[bin]]
name = "linux_cec_tool"
path = "src/bin/linux-cec-tool.rs"
required-features = ["std"]

[lints]
workspace = true
