(import "edgerun" "string_eq" (func $m30eq (param i32 i32 i32 i32) (result i32)))
  (func (export "acme_account_status_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 16) (i32.const 5)) (then (return (i32.const 1))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 21) (i32.const 11)) (then (return (i32.const 2))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 32) (i32.const 7)) (then (return (i32.const 3))))
    i32.const 0)

  (func (export "acme_order_status_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 48) (i32.const 7)) (then (return (i32.const 1))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 55) (i32.const 5)) (then (return (i32.const 2))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 60) (i32.const 10)) (then (return (i32.const 3))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 16) (i32.const 5)) (then (return (i32.const 4))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 70) (i32.const 7)) (then (return (i32.const 5))))
    i32.const 0)

  (func (export "acme_authorization_status_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 48) (i32.const 7)) (then (return (i32.const 1))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 16) (i32.const 5)) (then (return (i32.const 2))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 70) (i32.const 7)) (then (return (i32.const 3))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 21) (i32.const 11)) (then (return (i32.const 4))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 77) (i32.const 7)) (then (return (i32.const 5))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 32) (i32.const 7)) (then (return (i32.const 6))))
    i32.const 0)

  (func (export "acme_challenge_status_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 48) (i32.const 7)) (then (return (i32.const 1))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 60) (i32.const 10)) (then (return (i32.const 2))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 16) (i32.const 5)) (then (return (i32.const 3))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 70) (i32.const 7)) (then (return (i32.const 4))))
    i32.const 0)

  (func (export "acme_challenge_type_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 96) (i32.const 7)) (then (return (i32.const 1))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 103) (i32.const 6)) (then (return (i32.const 2))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 109) (i32.const 11)) (then (return (i32.const 3))))
    i32.const 4)

  (func (export "acme_challenge_material_kind") (param $type_code i32) (result i32)
    (if (i32.eq (local.get $type_code) (i32.const 1)) (then (return (i32.const 1))))
    (if (i32.eq (local.get $type_code) (i32.const 2)) (then (return (i32.const 2))))
    (if (i32.eq (local.get $type_code) (i32.const 3)) (then (return (i32.const 3))))
    i32.const 0)

  (func (export "acme_key_authorization_parts_valid") (param $token_len i32) (param $thumbprint_len i32) (result i32)
    (i32.and (i32.gt_u (local.get $token_len) (i32.const 0)) (i32.gt_u (local.get $thumbprint_len) (i32.const 0))))

  (func (export "acme_directory_builtin_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 128) (i32.const 11)) (then (return (i32.const 1))))
    (if (call $m30eq (local.get $ptr) (local.get $len) (i32.const 139) (i32.const 18)) (then (return (i32.const 2))))
    i32.const 0)

  (func (export "acme_jwk_kind") (param $has_n i32) (param $has_e i32) (param $has_crv i32) (param $has_x i32) (param $has_y i32) (result i32)
    (if (i32.and (local.get $has_n) (local.get $has_e)) (then (return (i32.const 1))))
    (if (i32.and (local.get $has_crv) (i32.and (local.get $has_x) (local.get $has_y))) (then (return (i32.const 2))))
    i32.const 0)

  (data (i32.const 16) "validdeactivatedrevoked")
  (data (i32.const 48) "pendingreadyprocessinginvalidexpired")
  (data (i32.const 96) "http-01dns-01tls-alpn-01")
  (data (i32.const 128) "letsencryptletsencryptstaging")
