
  (global $q0 (mut i64) (i64.const 0))
  (global $q1 (mut i64) (i64.const 0))
  (global $q2 (mut i64) (i64.const 0))
  (global $q3 (mut i64) (i64.const 0))

  (func (export "marketplace_listing_status_valid") (param $id i32) (result i32)
    (i32.le_u (local.get $id) (i32.const 3)))

  (func (export "marketplace_checkout_status_valid") (param $id i32) (result i32)
    (i32.le_u (local.get $id) (i32.const 3)))

  (func $marketplace_listing_live (export "marketplace_listing_live") (param $id i32) (result i32)
    (i32.and
      (i32.ge_u (local.get $id) (i32.const 1))
      (i32.le_u (local.get $id) (i32.const 2))))

  (func $marketplace_checkout_live (export "marketplace_checkout_live") (param $id i32) (result i32)
    (i32.and
      (i32.ge_u (local.get $id) (i32.const 1))
      (i32.le_u (local.get $id) (i32.const 2))))

  (func $marketplace_create_listing_offer (export "marketplace_create_listing_offer") (param $merchant_id i64) (param $price_lo i64) (param $price_hi i64) (param $min_ship_days i32) (param $max_ship_days i32) (param $expires_s i64) (param $out i32) (result i32)
    (local $ts i64)
    (local $head_len i32)
    (local $varint_len i32)
    (local $boff i32)
    (local.set $head_len (i32.const 24))
    (local.set $boff (i32.add (local.get $out) (local.get $head_len)))
    (local.set $ts (i64.load (i32.const 3000)))
    (i64.store (local.get $out) (local.get $merchant_id))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $price_lo))
    (i64.store (i32.add (local.get $out) (i32.const 16)) (local.get $price_hi))
    (i32.store8 (i32.add (local.get $out) (i32.const 24)) (i32.const 0))
    (local.set $varint_len (call $write_varint64 (local.get $boff) (i32.add (local.get $out) (i32.const 3048)) (local.get $ts)))
    (i32.store8 (i32.add (local.get $boff) (local.get $varint_len)) (i32.const 44))
    (local.set $varint_len (i32.add (local.get $varint_len) (i32.const 1)))
    (local.set $boff (i32.add (local.get $boff) (local.get $varint_len)))
    (i32.store8 (local.get $boff) (i32.const 0))
    (i32.store16 (i32.add (local.get $out) (i32.const 26)) (local.get $min_ship_days))
    (i32.store16 (i32.add (local.get $out) (i32.const 28)) (local.get $max_ship_days))
    (i64.store (i32.add (local.get $out) (i32.const 30)) (local.get $expires_s))
    (i32.store (i32.add (local.get $out) (i32.const 38)) (i32.const 46))
    (i32.store (i32.add (local.get $out) (i32.const 42)) (local.get $head_len))
    (i32.store (i32.add (local.get $out) (i32.const 46)) (local.get $varint_len))
    (i32.const 0))

  (func $marketplace_accept_offer (export "marketplace_accept_offer") (param $listing_id i64) (param $offer_id i64) (param $offer_expires_s i64) (param $shipping_name_len i32) (param $shipping_address_len i32) (param $shipping_note_len i32) (param $out i32) (result i32)
    (local $head_len i32)
    (local.set $head_len (i32.const 38))
    (i64.store (local.get $out) (local.get $listing_id))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $offer_id))
    (i64.store (i32.add (local.get $out) (i32.const 16)) (local.get $offer_expires_s))
    (i32.store16 (i32.add (local.get $out) (i32.const 24)) (local.get $shipping_name_len))
    (i32.store16 (i32.add (local.get $out) (i32.const 26)) (local.get $shipping_address_len))
    (i32.store16 (i32.add (local.get $out) (i32.const 28)) (local.get $shipping_note_len))
    (i32.store (i32.add (local.get $out) (i32.const 30)) (i32.const 0))
    (i32.store (i32.add (local.get $out) (i32.const 34)) (local.get $head_len))
    (i32.const 0))

  (func $marketplace_dispute (export "marketplace_dispute") (param $listing_id i64) (param $offer_id i64) (param $arbiter_key_id i32) (param $out i32) (result i32)
    (i64.store (local.get $out) (local.get $listing_id))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $offer_id))
    (i32.store (i32.add (local.get $out) (i32.const 16)) (local.get $arbiter_key_id))
    (i32.store (i32.add (local.get $out) (i32.const 20)) (i32.const 20))
    (i32.const 0))

  (func $marketplace_resolve_dispute (export "marketplace_resolve_dispute") (param $listing_id i64) (param $offer_id i64) (param $resolution i32) (param $out i32) (result i32)
    (i64.store (local.get $out) (local.get $listing_id))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $offer_id))
    (i32.store8 (local.get $out) (local.get $resolution))
    (i32.store (i32.add (local.get $out) (i32.const 12)) (i32.const 13))
    (i32.const 0))

  (func $marketplace_checkout (export "marketplace_checkout") (param $listing_id i64) (param $offer_id i64) (param $shipping_addr_len i32) (param $shipping_addr_ptr i32) (param $shipping_note_len i32) (param $shipping_note_ptr i32) (param $out i32) (result i32)
    (local $off i32)
    (local $head_len i32)
    (local.set $head_len (i32.const 28))
    (local.set $off (i32.add (local.get $out) (local.get $head_len)))
    (i64.store (local.get $out) (local.get $listing_id))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $offer_id))
    (i32.store16 (i32.add (local.get $out) (i32.const 16)) (local.get $shipping_addr_len))
    (i32.store16 (i32.add (local.get $out) (i32.const 18)) (local.get $shipping_note_len))
    (i32.store (i32.add (local.get $out) (i32.const 20)) (i32.const 0))
    (i32.store (i32.add (local.get $out) (i32.const 24)) (local.get $head_len))
    (if (i32.eqz (local.get $shipping_addr_len)) (then (i32.store8 (local.get $off) (i32.const 0))))
    (if (i32.eqz (local.get $shipping_addr_len)) (then (i32.store16 (i32.add (local.get $out) (i32.const 28)) (i32.const 0))))
    (if (i32.eqz (local.get $shipping_note_len)) (then (i32.store8 (local.get $off) (i32.const 0))))
    (if (i32.eqz (local.get $shipping_note_len)) (then (i32.store16 (i32.add (local.get $out) (i32.const 30)) (i32.const 0))))
    (i32.const 0))

  (func $marketplace_rate_seller (export "marketplace_rate_seller") (param $listing_id i64) (param $offer_id i64) (param $rating i32) (param $out i32) (result i32)
    (i64.store (local.get $out) (local.get $listing_id))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $offer_id))
    (i32.store8 (i32.add (local.get $out) (i32.const 16)) (local.get $rating))
    (i32.store (i32.add (local.get $out) (i32.const 17)) (i32.const 17))
    (i32.const 0))

  (func $write_varint64 (param $buf i32) (param $end i32) (param $v i64) (result i32)
    (local $b i32)
    (loop $loop
      (local.set $b (i32.wrap_i64 (i64.and (local.get $v) (i64.const 127))))
      (local.set $v (i64.shr_u (local.get $v) (i64.const 7)))
      (if (i64.ne (local.get $v) (i64.const 0))
        (then
          (i32.store8 (local.get $buf) (i32.or (local.get $b) (i32.const 128)))
          (local.set $buf (i32.add (local.get $buf) (i32.const 1)))
          (br $loop))
        (else
          (i32.store8 (local.get $buf) (local.get $b))
          (local.set $buf (i32.add (local.get $buf) (i32.const 1))))))
    (if (i32.gt_u (local.get $buf) (local.get $end))
      (then (return (i32.const -1))))
    (local.get $buf))

  (func $marketplace_listings_fee (export "marketplace_listings_fee") (param $price_lo i64) (param $price_hi i64) (param $out i32) (result i32)
    (local $fee_lo i64)
    (local $fee_hi i64)
    (local $rem_lo i64)
    (local $rem_hi i64)
    (local $hundred i64)
    (local.set $hundred (i64.const 100))
    (local.set $fee_lo (i64.div_u (i64.mul (local.get $price_lo) (i64.const 3)) (local.get $hundred)))
    (local.set $rem_lo (i64.rem_u (i64.mul (local.get $price_lo) (i64.const 3)) (local.get $hundred)))
    (local.set $fee_hi (i64.div_u (i64.mul (local.get $price_hi) (i64.const 3)) (local.get $hundred)))
    (local.set $fee_hi (i64.add (local.get $fee_hi) (i64.div_u (local.get $rem_lo) (local.get $hundred))))
    (local.set $rem_hi (i64.rem_u (local.get $rem_lo) (local.get $hundred)))
    (if (i64.ge_u (local.get $rem_hi) (i64.const 50))
      (then (local.set $fee_lo (i64.add (local.get $fee_lo) (i64.const 1)))))
    (i64.store (local.get $out) (local.get $fee_lo))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $fee_hi))
    (i32.store (i32.add (local.get $out) (i32.const 16)) (i32.const 16))
    (i32.const 0))

  (func $marketplace_affiliate_reward (export "marketplace_affiliate_reward") (param $price_lo i64) (param $price_hi i64) (param $out i32) (result i32)
    (local $reward_lo i64)
    (local $reward_hi i64)
    (local.set $reward_lo (i64.div_u (local.get $price_lo) (i64.const 10)))
    (local.set $reward_hi (i64.div_u (local.get $price_hi) (i64.const 10)))
    (i64.store (local.get $out) (local.get $reward_lo))
    (i64.store (i32.add (local.get $out) (i32.const 8)) (local.get $reward_hi))
    (i64.store (i32.add (local.get $out) (i32.const 16)) (i64.const 0))
    (i64.store (i32.add (local.get $out) (i32.const 24)) (i64.const 0))
    (i64.store (i32.add (local.get $out) (i32.const 32)) (i64.const 0))
    (i64.store (i32.add (local.get $out) (i32.const 40)) (i64.const 0))
    (global.set $q0 (i64.add (global.get $q0) (i64.const 1)))
    (i64.store (i32.add (local.get $out) (i32.const 48)) (local.get $reward_lo))
    (i64.store (i32.add (local.get $out) (i32.const 56)) (local.get $reward_hi))
    (i32.const 0))
