[package]
name = "edgerun-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-bare-rt = { path = "../edgerun-bare-rt", optional = true }
edgerun-core = { path = "../edgerun-core" }
edgerun-proto = { path = "../edgerun-proto" }
edgerun-rt = { path = "../edgerun-rt" }
edgerun-hardware-signing = { path = "../edgerun-hardware-signing", default-features = false }
edgerun-crypto.workspace = true
prost.workspace = true
prost-types.workspace = true
libc.workspace = true
edgerun-log = { path = "../edgerun-log" }

[features]
bare-rt = ["dep:edgerun-bare-rt"]

[lints]
workspace = true
