[package]
name = "edgerun-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-rt = { path = "../edgerun-rt" }
edgerun-core = { path = "../edgerun-core" }
edgerun-proto = { path = "../edgerun-proto" }
edgerun-stream = { path = "../edgerun-stream" }
edgerun-hardware-signing = { path = "../edgerun-hardware-signing", default-features = false }
edgerun-crypto = { workspace = true, default-features = false, features = ["aead", "p256", "pbkdf2"] }
edgerun-encoding = { path = "../edgerun-encoding", default-features = false, features = ["alloc"] }
prost.workspace = true
prost-types.workspace = true
edgerun-log = { path = "../edgerun-log" }

[target.'cfg(not(target_os = "none"))'.dependencies]
libc.workspace = true

[features]
bare-rt = []

[lints]
workspace = true
