[package]
name = "edgerun-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-core = { path = "../edgerun-core" }
edgerun-proto = { path = "../edgerun-proto" }
edgerun-hardware-signing = { path = "../edgerun-hardware-signing" }
aes-gcm.workspace = true
prost.workspace = true
prost-types.workspace = true
libc.workspace = true
edgerun-log = { path = "../edgerun-log" }
