   ;; EdgeRun shared runtime helpers — fragment for inclusion in single module.
  ;; (memory), LUT data, and all address globals are in out/gen/config.wat — from package.json edgerun
   ;; This file provides char helpers, pack/unpack, memcpy, status codes, syscalls.

  ;; ── Character classification helpers ──

  (func $char_class (export "char_class") (param $b i32) (result i32)
    (i32.load8_u offset=0x1000 (local.get $b)))

  (func $is_digit (export "is_digit") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 1)))

  (func $is_upper (export "is_upper") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 2)))

  (func $is_lower (export "is_lower") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 4)))

  (func $is_alpha (export "is_alpha") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 6)))

  (func $is_hex (export "is_hex") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 16)))

  (func $is_ws (export "is_ws") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 32)))

  (func $is_scheme_byte (export "is_scheme_byte") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 64)))

  (func $is_label_byte (export "is_label_byte") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 128)))

  (func $to_lower (export "to_lower") (param $b i32) (result i32)
    (local $cl i32)
    (local.set $cl (call $char_class (local.get $b)))
    (if (i32.and (local.get $cl) (i32.const 2))
      (then (return (i32.or (local.get $b) (i32.const 32)))))
    (if (i32.and (local.get $cl) (i32.const 4))
      (then (return (local.get $b))))
    (i32.const 0))

  (func $to_upper (export "to_upper") (param $b i32) (result i32)
    (if (i32.and (call $char_class (local.get $b)) (i32.const 4))
      (then (return (i32.sub (local.get $b) (i32.const 32)))))
    (local.get $b))

  (func $is_alnum (export "is_alnum") (param $b i32) (result i32)
    (i32.and (call $char_class (local.get $b)) (i32.const 7)))

  (func $is_print (export "is_print") (param $b i32) (result i32)
    (i32.and
      (i32.ge_u (local.get $b) (i32.const 32))
      (i32.le_u (local.get $b) (i32.const 126))))

  (func $is_cont (export "is_cont") (param $b i32) (result i32)
    (i32.eq (i32.and (local.get $b) (i32.const 0xC0)) (i32.const 0x80)))

  ;; ── Pack/unpack helpers ──

  (func $pack (export "pack") (param $status i32) (param $value i32) (result i64)
    (i64.or
      (i64.extend_i32_u (local.get $value))
      (i64.shl (i64.extend_i32_u (local.get $status)) (i64.const 32))))

  (func $pack_u16 (export "pack_u16") (param $a i32) (param $b i32) (result i32)
    (i32.or
      (local.get $b)
      (i32.shl (local.get $a) (i32.const 8))))

  (func $byte (export "byte") (param $v i32) (param $i i32) (result i32)
    (i32.and
      (i32.shr_u (local.get $v) (i32.shl (local.get $i) (i32.const 3)))
      (i32.const 0xFF)))

  (func $has (export "has") (param $v i32) (param $mask i32) (result i32)
    (i32.ne (i32.and (local.get $v) (local.get $mask)) (i32.const 0)))

  ;; ── Shared memcpy ──
  (func $memcpy (export "memcpy") (param $dst i32) (param $src i32) (param $len i32)
    (local $i i32)
    (block $done
      (loop $loop
        (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
        (i32.store8
          (i32.add (local.get $dst) (local.get $i))
          (i32.load8_u (i32.add (local.get $src) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop))))

  (func $memcpy_off (export "memcpy_off") (param $dst i32) (param $doff i32) (param $src i32) (param $soff i32) (param $len i32)
    (local $i i32)
    (block $done
      (loop $loop
        (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
        (i32.store8
          (i32.add (i32.add (local.get $dst) (local.get $doff)) (local.get $i))
          (i32.load8_u
            (i32.add (i32.add (local.get $src) (local.get $soff)) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop))))

  ;; ── SIMD stubs ──

  (func $simd_memchr (export "simd_memchr") (param $ptr i32) (param $len i32) (param $byte i32) (result i32)
    (local $i i32) (local $vec v128) (local $cmp v128) (local $mask i32)
    (local.set $i (local.get $ptr))
    (block $done
      (loop $loop
        (br_if $done (i32.lt_u (local.get $len) (i32.const 16)))
        (local.set $vec (v128.load (local.get $i)))
        (local.set $cmp (i8x16.eq (local.get $vec) (i8x16.splat (local.get $byte))))
        (local.set $mask (i8x16.bitmask (local.get $cmp)))
        (if (local.get $mask)
          (then (return (i32.add (local.get $i) (i32.ctz (local.get $mask))))))
        (local.set $i (i32.add (local.get $i) (i32.const 16)))
        (local.set $len (i32.sub (local.get $len) (i32.const 16)))
        (br $loop)))
    (block $r_done
      (loop $r_loop
        (br_if $r_done (i32.eqz (local.get $len)))
        (if (i32.eq (i32.load8_u (local.get $i)) (local.get $byte))
          (then (return (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $len (i32.sub (local.get $len) (i32.const 1)))
        (br $r_loop)))
    (i32.const -1))

  (func $simd_memrchr (export "simd_memrchr") (param $ptr i32) (param $len i32) (param $byte i32) (result i32)
    (local $i i32) (local $end i32) (local $vec v128) (local $cmp v128) (local $mask i32)
    (local.set $end (i32.add (local.get $ptr) (local.get $len)))
    (local.set $i (i32.sub (local.get $end) (i32.const 16)))
    (block $done
      (loop $loop
        (br_if $done (i32.lt_u (local.get $i) (local.get $ptr)))
        (local.set $vec (v128.load (local.get $i)))
        (local.set $cmp (i8x16.eq (local.get $vec) (i8x16.splat (local.get $byte))))
        (local.set $mask (i8x16.bitmask (local.get $cmp)))
        (if (local.get $mask)
          (then (return (i32.add (local.get $i) (i32.sub (i32.const 31) (i32.clz (local.get $mask)))))))
        (local.set $i (i32.sub (local.get $i) (i32.const 16)))
        (br $loop)))
    (local.set $i (i32.sub (local.get $end) (i32.const 1)))
    (block $r_done
      (loop $r_loop
        (br_if $r_done (i32.lt_u (local.get $i) (local.get $ptr)))
        (if (i32.eq (i32.load8_u (local.get $i)) (local.get $byte))
          (then (return (local.get $i))))
        (local.set $i (i32.sub (local.get $i) (i32.const 1)))
        (br $r_loop)))
    (i32.const -1))

  (func $memcpy_simd (export "memcpy_simd") (param $dst i32) (param $src i32) (param $len i32)
    (local $i i32)
    (block $done
      (loop $loop
        (br_if $done (i32.lt_u (local.get $len) (i32.const 16)))
        (v128.store (i32.add (local.get $dst) (local.get $i))
          (v128.load (i32.add (local.get $src) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 16)))
        (local.set $len (i32.sub (local.get $len) (i32.const 16)))
        (br $loop)))
    (block $r_done
      (loop $r_loop
        (br_if $r_done (i32.eqz (local.get $len)))
        (i32.store8
          (i32.add (local.get $dst) (local.get $i))
          (i32.load8_u (i32.add (local.get $src) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $len (i32.sub (local.get $len) (i32.const 1)))
        (br $r_loop))))

  (func $memset_simd (export "memset_simd") (param $ptr i32) (param $val i32) (param $len i32)
    (local $i i32) (local $vec v128)
    (local.set $vec (i8x16.splat (local.get $val)))
    (block $done
      (loop $loop
        (br_if $done (i32.lt_u (local.get $len) (i32.const 16)))
        (v128.store (i32.add (local.get $ptr) (local.get $i)) (local.get $vec))
        (local.set $i (i32.add (local.get $i) (i32.const 16)))
        (local.set $len (i32.sub (local.get $len) (i32.const 16)))
        (br $loop)))
    (block $r_done
      (loop $r_loop
        (br_if $r_done (i32.eqz (local.get $len)))
        (i32.store8 (i32.add (local.get $ptr) (local.get $i)) (local.get $val))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (local.set $len (i32.sub (local.get $len) (i32.const 1)))
        (br $r_loop))))

  (func $string_eq_simd (export "string_eq_simd") (param $ptr i32) (param $len i32) (param $lit i32) (param $lit_len i32) (result i32)
    (local $i i32) (local $v1 v128) (local $v2 v128)
    (if (result i32) (i32.ne (local.get $len) (local.get $lit_len))
      (then (i32.const 0))
      (else
        (block $simd_done
          (loop $loop
            (br_if $simd_done (i32.lt_u (local.get $len) (i32.const 16)))
            (local.set $v1 (v128.load (i32.add (local.get $ptr) (local.get $i))))
            (local.set $v2 (v128.load (i32.add (local.get $lit) (local.get $i))))
            (if (i32.eqz (i8x16.all_true (i8x16.eq (local.get $v1) (local.get $v2))))
              (then (return (i32.const 0))))
            (local.set $i (i32.add (local.get $i) (i32.const 16)))
            (local.set $len (i32.sub (local.get $len) (i32.const 16)))
            (br $loop)))
        (block $r_done
          (loop $r_loop
            (br_if $r_done (i32.eqz (local.get $len)))
            (if (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $i)))
                        (i32.load8_u (i32.add (local.get $lit) (local.get $i))))
              (then (return (i32.const 0))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (local.set $len (i32.sub (local.get $len) (i32.const 1)))
            (br $r_loop)))
        (i32.const 1))))

  ;; ── Shared status codes (all modules should use these) ──
  (global $STATUS_OK           (export "STATUS_OK")           i32 (i32.const 0))
  (global $STATUS_INPUT_SHORT  (export "STATUS_INPUT_SHORT")  i32 (i32.const 1))
  (global $STATUS_OUTPUT_SHORT (export "STATUS_OUTPUT_SHORT") i32 (i32.const 2))
  (global $STATUS_INVALID      (export "STATUS_INVALID")      i32 (i32.const 3))
  (global $STATUS_OVERFLOW     (export "STATUS_OVERFLOW")     i32 (i32.const 4))
  (global $STATUS_TRUNCATED    (export "STATUS_TRUNCATED")    i32 (i32.const 5))
  (global $STATUS_TOO_LONG     (export "STATUS_TOO_LONG")     i32 (i32.const 6))
   (global $STATUS_MORE         (export "STATUS_MORE")         i32 (i32.const 7))
   (global $STATUS_TIMEOUT      (export "STATUS_TIMEOUT")      i32 (i32.const 8))

    ;; $OK, $ERR_UNSUP defined in out/gen/config.wat

   ;; ── Global epoch — shared tick counter across all modules ──
  ;; Schedulers increment this before driving pipelines. Stages read it
  ;; for cross-pipeline synchronization and tick-based timeouts.
  (global $epoch (export "epoch") (mut i32) (i32.const 0))
  (global $LINUX_SYS_X64_READ                    (export "LINUX_SYS_X64_READ") i32 (i32.const 0))
  (global $LINUX_SYS_X64_WRITE                   (export "LINUX_SYS_X64_WRITE") i32 (i32.const 1))
  (global $LINUX_SYS_X64_OPEN                    (export "LINUX_SYS_X64_OPEN") i32 (i32.const 2))
  (global $LINUX_SYS_X64_CLOSE                   (export "LINUX_SYS_X64_CLOSE") i32 (i32.const 3))
  (global $LINUX_SYS_X64_STAT                    (export "LINUX_SYS_X64_STAT") i32 (i32.const 4))
  (global $LINUX_SYS_X64_FSTAT                   (export "LINUX_SYS_X64_FSTAT") i32 (i32.const 5))
  (global $LINUX_SYS_X64_LSTAT                   (export "LINUX_SYS_X64_LSTAT") i32 (i32.const 6))
  (global $LINUX_SYS_X64_POLL                    (export "LINUX_SYS_X64_POLL") i32 (i32.const 7))
  (global $LINUX_SYS_X64_LSEEK                   (export "LINUX_SYS_X64_LSEEK") i32 (i32.const 8))
  (global $LINUX_SYS_X64_MMAP                    (export "LINUX_SYS_X64_MMAP") i32 (i32.const 9))
  (global $LINUX_SYS_X64_MPROTECT                (export "LINUX_SYS_X64_MPROTECT") i32 (i32.const 10))
  (global $LINUX_SYS_X64_MUNMAP                  (export "LINUX_SYS_X64_MUNMAP") i32 (i32.const 11))
  (global $LINUX_SYS_X64_BRK                     (export "LINUX_SYS_X64_BRK") i32 (i32.const 12))
  (global $LINUX_SYS_X64_RT_SIGACTION            (export "LINUX_SYS_X64_RT_SIGACTION") i32 (i32.const 13))
  (global $LINUX_SYS_X64_RT_SIGPROCMASK          (export "LINUX_SYS_X64_RT_SIGPROCMASK") i32 (i32.const 14))
  (global $LINUX_SYS_X64_RT_SIGRETURN            (export "LINUX_SYS_X64_RT_SIGRETURN") i32 (i32.const 15))
  (global $LINUX_SYS_X64_IOCTL                   (export "LINUX_SYS_X64_IOCTL") i32 (i32.const 16))
  (global $LINUX_SYS_X64_PREAD64                 (export "LINUX_SYS_X64_PREAD64") i32 (i32.const 17))
  (global $LINUX_SYS_X64_PWRITE64                (export "LINUX_SYS_X64_PWRITE64") i32 (i32.const 18))
  (global $LINUX_SYS_X64_READV                   (export "LINUX_SYS_X64_READV") i32 (i32.const 19))
  (global $LINUX_SYS_X64_WRITEV                  (export "LINUX_SYS_X64_WRITEV") i32 (i32.const 20))
  (global $LINUX_SYS_X64_ACCESS                  (export "LINUX_SYS_X64_ACCESS") i32 (i32.const 21))
  (global $LINUX_SYS_X64_PIPE                    (export "LINUX_SYS_X64_PIPE") i32 (i32.const 22))
  (global $LINUX_SYS_X64_SELECT                  (export "LINUX_SYS_X64_SELECT") i32 (i32.const 23))
  (global $LINUX_SYS_X64_SCHED_YIELD             (export "LINUX_SYS_X64_SCHED_YIELD") i32 (i32.const 24))
  (global $LINUX_SYS_X64_MREMAP                  (export "LINUX_SYS_X64_MREMAP") i32 (i32.const 25))
  (global $LINUX_SYS_X64_MSYNC                   (export "LINUX_SYS_X64_MSYNC") i32 (i32.const 26))
  (global $LINUX_SYS_X64_MINCORE                 (export "LINUX_SYS_X64_MINCORE") i32 (i32.const 27))
  (global $LINUX_SYS_X64_MADVISE                 (export "LINUX_SYS_X64_MADVISE") i32 (i32.const 28))
  (global $LINUX_SYS_X64_SHMGET                  (export "LINUX_SYS_X64_SHMGET") i32 (i32.const 29))
  (global $LINUX_SYS_X64_SHMAT                   (export "LINUX_SYS_X64_SHMAT") i32 (i32.const 30))
  (global $LINUX_SYS_X64_SHMCTL                  (export "LINUX_SYS_X64_SHMCTL") i32 (i32.const 31))
  (global $LINUX_SYS_X64_DUP                     (export "LINUX_SYS_X64_DUP") i32 (i32.const 32))
  (global $LINUX_SYS_X64_DUP2                    (export "LINUX_SYS_X64_DUP2") i32 (i32.const 33))
  (global $LINUX_SYS_X64_PAUSE                   (export "LINUX_SYS_X64_PAUSE") i32 (i32.const 34))
  (global $LINUX_SYS_X64_NANOSLEEP               (export "LINUX_SYS_X64_NANOSLEEP") i32 (i32.const 35))
  (global $LINUX_SYS_X64_GETITIMER               (export "LINUX_SYS_X64_GETITIMER") i32 (i32.const 36))
  (global $LINUX_SYS_X64_ALARM                   (export "LINUX_SYS_X64_ALARM") i32 (i32.const 37))
  (global $LINUX_SYS_X64_SETITIMER               (export "LINUX_SYS_X64_SETITIMER") i32 (i32.const 38))
  (global $LINUX_SYS_X64_GETPID                  (export "LINUX_SYS_X64_GETPID") i32 (i32.const 39))
  (global $LINUX_SYS_X64_SENDFILE                (export "LINUX_SYS_X64_SENDFILE") i32 (i32.const 40))
  (global $LINUX_SYS_X64_SOCKET                  (export "LINUX_SYS_X64_SOCKET") i32 (i32.const 41))
  (global $LINUX_SYS_X64_CONNECT                 (export "LINUX_SYS_X64_CONNECT") i32 (i32.const 42))
  (global $LINUX_SYS_X64_ACCEPT                  (export "LINUX_SYS_X64_ACCEPT") i32 (i32.const 43))
  (global $LINUX_SYS_X64_SENDTO                  (export "LINUX_SYS_X64_SENDTO") i32 (i32.const 44))
  (global $LINUX_SYS_X64_RECVFROM                (export "LINUX_SYS_X64_RECVFROM") i32 (i32.const 45))
  (global $LINUX_SYS_X64_SENDMSG                 (export "LINUX_SYS_X64_SENDMSG") i32 (i32.const 46))
  (global $LINUX_SYS_X64_RECVMSG                 (export "LINUX_SYS_X64_RECVMSG") i32 (i32.const 47))
  (global $LINUX_SYS_X64_SHUTDOWN                (export "LINUX_SYS_X64_SHUTDOWN") i32 (i32.const 48))
  (global $LINUX_SYS_X64_BIND                    (export "LINUX_SYS_X64_BIND") i32 (i32.const 49))
  (global $LINUX_SYS_X64_LISTEN                  (export "LINUX_SYS_X64_LISTEN") i32 (i32.const 50))
  (global $LINUX_SYS_X64_GETSOCKNAME             (export "LINUX_SYS_X64_GETSOCKNAME") i32 (i32.const 51))
  (global $LINUX_SYS_X64_GETPEERNAME             (export "LINUX_SYS_X64_GETPEERNAME") i32 (i32.const 52))
  (global $LINUX_SYS_X64_SOCKETPAIR              (export "LINUX_SYS_X64_SOCKETPAIR") i32 (i32.const 53))
  (global $LINUX_SYS_X64_SETSOCKOPT              (export "LINUX_SYS_X64_SETSOCKOPT") i32 (i32.const 54))
  (global $LINUX_SYS_X64_GETSOCKOPT              (export "LINUX_SYS_X64_GETSOCKOPT") i32 (i32.const 55))
  (global $LINUX_SYS_X64_CLONE                   (export "LINUX_SYS_X64_CLONE") i32 (i32.const 56))
  (global $LINUX_SYS_X64_FORK                    (export "LINUX_SYS_X64_FORK") i32 (i32.const 57))
  (global $LINUX_SYS_X64_VFORK                   (export "LINUX_SYS_X64_VFORK") i32 (i32.const 58))
  (global $LINUX_SYS_X64_EXECVE                  (export "LINUX_SYS_X64_EXECVE") i32 (i32.const 59))
  (global $LINUX_SYS_X64_EXIT                    (export "LINUX_SYS_X64_EXIT") i32 (i32.const 60))
  (global $LINUX_SYS_X64_WAIT4                   (export "LINUX_SYS_X64_WAIT4") i32 (i32.const 61))
  (global $LINUX_SYS_X64_KILL                    (export "LINUX_SYS_X64_KILL") i32 (i32.const 62))
  (global $LINUX_SYS_X64_UNAME                   (export "LINUX_SYS_X64_UNAME") i32 (i32.const 63))
  (global $LINUX_SYS_X64_SEMGET                  (export "LINUX_SYS_X64_SEMGET") i32 (i32.const 64))
  (global $LINUX_SYS_X64_SEMOP                   (export "LINUX_SYS_X64_SEMOP") i32 (i32.const 65))
  (global $LINUX_SYS_X64_SEMCTL                  (export "LINUX_SYS_X64_SEMCTL") i32 (i32.const 66))
  (global $LINUX_SYS_X64_SHMDT                   (export "LINUX_SYS_X64_SHMDT") i32 (i32.const 67))
  (global $LINUX_SYS_X64_MSGGET                  (export "LINUX_SYS_X64_MSGGET") i32 (i32.const 68))
  (global $LINUX_SYS_X64_MSGSND                  (export "LINUX_SYS_X64_MSGSND") i32 (i32.const 69))
  (global $LINUX_SYS_X64_MSGRCV                  (export "LINUX_SYS_X64_MSGRCV") i32 (i32.const 70))
  (global $LINUX_SYS_X64_MSGCTL                  (export "LINUX_SYS_X64_MSGCTL") i32 (i32.const 71))
  (global $LINUX_SYS_X64_FCNTL                   (export "LINUX_SYS_X64_FCNTL") i32 (i32.const 72))
  (global $LINUX_SYS_X64_FLOCK                   (export "LINUX_SYS_X64_FLOCK") i32 (i32.const 73))
  (global $LINUX_SYS_X64_FSYNC                   (export "LINUX_SYS_X64_FSYNC") i32 (i32.const 74))
  (global $LINUX_SYS_X64_FDATASYNC               (export "LINUX_SYS_X64_FDATASYNC") i32 (i32.const 75))
  (global $LINUX_SYS_X64_TRUNCATE                (export "LINUX_SYS_X64_TRUNCATE") i32 (i32.const 76))
  (global $LINUX_SYS_X64_FTRUNCATE               (export "LINUX_SYS_X64_FTRUNCATE") i32 (i32.const 77))
  (global $LINUX_SYS_X64_GETDENTS                (export "LINUX_SYS_X64_GETDENTS") i32 (i32.const 78))
  (global $LINUX_SYS_X64_GETCWD                  (export "LINUX_SYS_X64_GETCWD") i32 (i32.const 79))
  (global $LINUX_SYS_X64_CHDIR                   (export "LINUX_SYS_X64_CHDIR") i32 (i32.const 80))
  (global $LINUX_SYS_X64_FCHDIR                  (export "LINUX_SYS_X64_FCHDIR") i32 (i32.const 81))
  (global $LINUX_SYS_X64_RENAME                  (export "LINUX_SYS_X64_RENAME") i32 (i32.const 82))
  (global $LINUX_SYS_X64_MKDIR                   (export "LINUX_SYS_X64_MKDIR") i32 (i32.const 83))
  (global $LINUX_SYS_X64_RMDIR                   (export "LINUX_SYS_X64_RMDIR") i32 (i32.const 84))
  (global $LINUX_SYS_X64_CREAT                   (export "LINUX_SYS_X64_CREAT") i32 (i32.const 85))
  (global $LINUX_SYS_X64_LINK                    (export "LINUX_SYS_X64_LINK") i32 (i32.const 86))
  (global $LINUX_SYS_X64_UNLINK                  (export "LINUX_SYS_X64_UNLINK") i32 (i32.const 87))
  (global $LINUX_SYS_X64_SYMLINK                 (export "LINUX_SYS_X64_SYMLINK") i32 (i32.const 88))
  (global $LINUX_SYS_X64_READLINK                (export "LINUX_SYS_X64_READLINK") i32 (i32.const 89))
  (global $LINUX_SYS_X64_CHMOD                   (export "LINUX_SYS_X64_CHMOD") i32 (i32.const 90))
  (global $LINUX_SYS_X64_FCHMOD                  (export "LINUX_SYS_X64_FCHMOD") i32 (i32.const 91))
  (global $LINUX_SYS_X64_CHOWN                   (export "LINUX_SYS_X64_CHOWN") i32 (i32.const 92))
  (global $LINUX_SYS_X64_FCHOWN                  (export "LINUX_SYS_X64_FCHOWN") i32 (i32.const 93))
  (global $LINUX_SYS_X64_LCHOWN                  (export "LINUX_SYS_X64_LCHOWN") i32 (i32.const 94))
  (global $LINUX_SYS_X64_UMASK                   (export "LINUX_SYS_X64_UMASK") i32 (i32.const 95))
  (global $LINUX_SYS_X64_GETTIMEOFDAY            (export "LINUX_SYS_X64_GETTIMEOFDAY") i32 (i32.const 96))
  (global $LINUX_SYS_X64_GETRLIMIT               (export "LINUX_SYS_X64_GETRLIMIT") i32 (i32.const 97))
  (global $LINUX_SYS_X64_GETRUSAGE               (export "LINUX_SYS_X64_GETRUSAGE") i32 (i32.const 98))
  (global $LINUX_SYS_X64_SYSINFO                 (export "LINUX_SYS_X64_SYSINFO") i32 (i32.const 99))
  (global $LINUX_SYS_X64_TIMES                   (export "LINUX_SYS_X64_TIMES") i32 (i32.const 100))
  (global $LINUX_SYS_X64_PTRACE                  (export "LINUX_SYS_X64_PTRACE") i32 (i32.const 101))
  (global $LINUX_SYS_X64_GETUID                  (export "LINUX_SYS_X64_GETUID") i32 (i32.const 102))
  (global $LINUX_SYS_X64_SYSLOG                  (export "LINUX_SYS_X64_SYSLOG") i32 (i32.const 103))
  (global $LINUX_SYS_X64_GETGID                  (export "LINUX_SYS_X64_GETGID") i32 (i32.const 104))
  (global $LINUX_SYS_X64_SETUID                  (export "LINUX_SYS_X64_SETUID") i32 (i32.const 105))
  (global $LINUX_SYS_X64_SETGID                  (export "LINUX_SYS_X64_SETGID") i32 (i32.const 106))
  (global $LINUX_SYS_X64_GETEUID                 (export "LINUX_SYS_X64_GETEUID") i32 (i32.const 107))
  (global $LINUX_SYS_X64_GETEGID                 (export "LINUX_SYS_X64_GETEGID") i32 (i32.const 108))
  (global $LINUX_SYS_X64_SETPGID                 (export "LINUX_SYS_X64_SETPGID") i32 (i32.const 109))
  (global $LINUX_SYS_X64_GETPPID                 (export "LINUX_SYS_X64_GETPPID") i32 (i32.const 110))
  (global $LINUX_SYS_X64_GETPGRP                 (export "LINUX_SYS_X64_GETPGRP") i32 (i32.const 111))
  (global $LINUX_SYS_X64_SETSID                  (export "LINUX_SYS_X64_SETSID") i32 (i32.const 112))
  (global $LINUX_SYS_X64_SETREUID                (export "LINUX_SYS_X64_SETREUID") i32 (i32.const 113))
  (global $LINUX_SYS_X64_SETREGID                (export "LINUX_SYS_X64_SETREGID") i32 (i32.const 114))
  (global $LINUX_SYS_X64_GETGROUPS               (export "LINUX_SYS_X64_GETGROUPS") i32 (i32.const 115))
  (global $LINUX_SYS_X64_SETGROUPS               (export "LINUX_SYS_X64_SETGROUPS") i32 (i32.const 116))
  (global $LINUX_SYS_X64_SETRESUID               (export "LINUX_SYS_X64_SETRESUID") i32 (i32.const 117))
  (global $LINUX_SYS_X64_GETRESUID               (export "LINUX_SYS_X64_GETRESUID") i32 (i32.const 118))
  (global $LINUX_SYS_X64_SETRESGID               (export "LINUX_SYS_X64_SETRESGID") i32 (i32.const 119))
  (global $LINUX_SYS_X64_GETRESGID               (export "LINUX_SYS_X64_GETRESGID") i32 (i32.const 120))
  (global $LINUX_SYS_X64_GETPGID                 (export "LINUX_SYS_X64_GETPGID") i32 (i32.const 121))
  (global $LINUX_SYS_X64_SETFSUID                (export "LINUX_SYS_X64_SETFSUID") i32 (i32.const 122))
  (global $LINUX_SYS_X64_SETFSGID                (export "LINUX_SYS_X64_SETFSGID") i32 (i32.const 123))
  (global $LINUX_SYS_X64_GETSID                  (export "LINUX_SYS_X64_GETSID") i32 (i32.const 124))
  (global $LINUX_SYS_X64_CAPGET                  (export "LINUX_SYS_X64_CAPGET") i32 (i32.const 125))
  (global $LINUX_SYS_X64_CAPSET                  (export "LINUX_SYS_X64_CAPSET") i32 (i32.const 126))
  (global $LINUX_SYS_X64_RT_SIGPENDING           (export "LINUX_SYS_X64_RT_SIGPENDING") i32 (i32.const 127))
  (global $LINUX_SYS_X64_RT_SIGTIMEDWAIT         (export "LINUX_SYS_X64_RT_SIGTIMEDWAIT") i32 (i32.const 128))
  (global $LINUX_SYS_X64_RT_SIGQUEUEINFO         (export "LINUX_SYS_X64_RT_SIGQUEUEINFO") i32 (i32.const 129))
  (global $LINUX_SYS_X64_RT_SIGSUSPEND           (export "LINUX_SYS_X64_RT_SIGSUSPEND") i32 (i32.const 130))
  (global $LINUX_SYS_X64_SIGALTSTACK             (export "LINUX_SYS_X64_SIGALTSTACK") i32 (i32.const 131))
  (global $LINUX_SYS_X64_UTIME                   (export "LINUX_SYS_X64_UTIME") i32 (i32.const 132))
  (global $LINUX_SYS_X64_MKNOD                   (export "LINUX_SYS_X64_MKNOD") i32 (i32.const 133))
  (global $LINUX_SYS_X64_USELIB                  (export "LINUX_SYS_X64_USELIB") i32 (i32.const 134))
  (global $LINUX_SYS_X64_PERSONALITY             (export "LINUX_SYS_X64_PERSONALITY") i32 (i32.const 135))
  (global $LINUX_SYS_X64_USTAT                   (export "LINUX_SYS_X64_USTAT") i32 (i32.const 136))
  (global $LINUX_SYS_X64_STATFS                  (export "LINUX_SYS_X64_STATFS") i32 (i32.const 137))
  (global $LINUX_SYS_X64_FSTATFS                 (export "LINUX_SYS_X64_FSTATFS") i32 (i32.const 138))
  (global $LINUX_SYS_X64_SYSFS                   (export "LINUX_SYS_X64_SYSFS") i32 (i32.const 139))
  (global $LINUX_SYS_X64_GETPRIORITY             (export "LINUX_SYS_X64_GETPRIORITY") i32 (i32.const 140))
  (global $LINUX_SYS_X64_SETPRIORITY             (export "LINUX_SYS_X64_SETPRIORITY") i32 (i32.const 141))
  (global $LINUX_SYS_X64_SCHED_SETPARAM          (export "LINUX_SYS_X64_SCHED_SETPARAM") i32 (i32.const 142))
  (global $LINUX_SYS_X64_SCHED_GETPARAM          (export "LINUX_SYS_X64_SCHED_GETPARAM") i32 (i32.const 143))
  (global $LINUX_SYS_X64_SCHED_SETSCHEDULER      (export "LINUX_SYS_X64_SCHED_SETSCHEDULER") i32 (i32.const 144))
  (global $LINUX_SYS_X64_SCHED_GETSCHEDULER      (export "LINUX_SYS_X64_SCHED_GETSCHEDULER") i32 (i32.const 145))
  (global $LINUX_SYS_X64_SCHED_GET_PRIORITY_MAX  (export "LINUX_SYS_X64_SCHED_GET_PRIORITY_MAX") i32 (i32.const 146))
  (global $LINUX_SYS_X64_SCHED_GET_PRIORITY_MIN  (export "LINUX_SYS_X64_SCHED_GET_PRIORITY_MIN") i32 (i32.const 147))
  (global $LINUX_SYS_X64_SCHED_RR_GET_INTERVAL   (export "LINUX_SYS_X64_SCHED_RR_GET_INTERVAL") i32 (i32.const 148))
  (global $LINUX_SYS_X64_MLOCK                   (export "LINUX_SYS_X64_MLOCK") i32 (i32.const 149))
  (global $LINUX_SYS_X64_MUNLOCK                 (export "LINUX_SYS_X64_MUNLOCK") i32 (i32.const 150))
  (global $LINUX_SYS_X64_MLOCKALL                (export "LINUX_SYS_X64_MLOCKALL") i32 (i32.const 151))
  (global $LINUX_SYS_X64_MUNLOCKALL              (export "LINUX_SYS_X64_MUNLOCKALL") i32 (i32.const 152))
  (global $LINUX_SYS_X64_VHANGUP                 (export "LINUX_SYS_X64_VHANGUP") i32 (i32.const 153))
  (global $LINUX_SYS_X64_MODIFY_LDT              (export "LINUX_SYS_X64_MODIFY_LDT") i32 (i32.const 154))
  (global $LINUX_SYS_X64_PIVOT_ROOT              (export "LINUX_SYS_X64_PIVOT_ROOT") i32 (i32.const 155))
  (global $LINUX_SYS_X64_SYSCTL                  (export "LINUX_SYS_X64_SYSCTL") i32 (i32.const 156))
  (global $LINUX_SYS_X64_PRCTL                   (export "LINUX_SYS_X64_PRCTL") i32 (i32.const 157))
  (global $LINUX_SYS_X64_ARCH_PRCTL              (export "LINUX_SYS_X64_ARCH_PRCTL") i32 (i32.const 158))
  (global $LINUX_SYS_X64_ADJTIMEX                (export "LINUX_SYS_X64_ADJTIMEX") i32 (i32.const 159))
  (global $LINUX_SYS_X64_SETRLIMIT               (export "LINUX_SYS_X64_SETRLIMIT") i32 (i32.const 160))
  (global $LINUX_SYS_X64_CHROOT                  (export "LINUX_SYS_X64_CHROOT") i32 (i32.const 161))
  (global $LINUX_SYS_X64_SYNC                    (export "LINUX_SYS_X64_SYNC") i32 (i32.const 162))
  (global $LINUX_SYS_X64_ACCT                    (export "LINUX_SYS_X64_ACCT") i32 (i32.const 163))
  (global $LINUX_SYS_X64_SETTIMEOFDAY            (export "LINUX_SYS_X64_SETTIMEOFDAY") i32 (i32.const 164))
  (global $LINUX_SYS_X64_MOUNT                   (export "LINUX_SYS_X64_MOUNT") i32 (i32.const 165))
  (global $LINUX_SYS_X64_UMOUNT2                 (export "LINUX_SYS_X64_UMOUNT2") i32 (i32.const 166))
  (global $LINUX_SYS_X64_SWAPON                  (export "LINUX_SYS_X64_SWAPON") i32 (i32.const 167))
  (global $LINUX_SYS_X64_SWAPOFF                 (export "LINUX_SYS_X64_SWAPOFF") i32 (i32.const 168))
  (global $LINUX_SYS_X64_REBOOT                  (export "LINUX_SYS_X64_REBOOT") i32 (i32.const 169))
  (global $LINUX_SYS_X64_SETHOSTNAME             (export "LINUX_SYS_X64_SETHOSTNAME") i32 (i32.const 170))
  (global $LINUX_SYS_X64_SETDOMAINNAME           (export "LINUX_SYS_X64_SETDOMAINNAME") i32 (i32.const 171))
  (global $LINUX_SYS_X64_IOPL                    (export "LINUX_SYS_X64_IOPL") i32 (i32.const 172))
  (global $LINUX_SYS_X64_IOPERM                  (export "LINUX_SYS_X64_IOPERM") i32 (i32.const 173))
  (global $LINUX_SYS_X64_CREATE_MODULE           (export "LINUX_SYS_X64_CREATE_MODULE") i32 (i32.const 174))
  (global $LINUX_SYS_X64_INIT_MODULE             (export "LINUX_SYS_X64_INIT_MODULE") i32 (i32.const 175))
  (global $LINUX_SYS_X64_DELETE_MODULE           (export "LINUX_SYS_X64_DELETE_MODULE") i32 (i32.const 176))
  (global $LINUX_SYS_X64_GET_KERNEL_SYMS         (export "LINUX_SYS_X64_GET_KERNEL_SYMS") i32 (i32.const 177))
  (global $LINUX_SYS_X64_QUERY_MODULE            (export "LINUX_SYS_X64_QUERY_MODULE") i32 (i32.const 178))
  (global $LINUX_SYS_X64_QUOTACTL                (export "LINUX_SYS_X64_QUOTACTL") i32 (i32.const 179))
  (global $LINUX_SYS_X64_NFSSERVCTL              (export "LINUX_SYS_X64_NFSSERVCTL") i32 (i32.const 180))
  (global $LINUX_SYS_X64_GETPMSG                 (export "LINUX_SYS_X64_GETPMSG") i32 (i32.const 181))
  (global $LINUX_SYS_X64_PUTPMSG                 (export "LINUX_SYS_X64_PUTPMSG") i32 (i32.const 182))
  (global $LINUX_SYS_X64_AFS_SYSCALL             (export "LINUX_SYS_X64_AFS_SYSCALL") i32 (i32.const 183))
  (global $LINUX_SYS_X64_TUXCALL                 (export "LINUX_SYS_X64_TUXCALL") i32 (i32.const 184))
  (global $LINUX_SYS_X64_SECURITY                (export "LINUX_SYS_X64_SECURITY") i32 (i32.const 185))
  (global $LINUX_SYS_X64_GETTID                  (export "LINUX_SYS_X64_GETTID") i32 (i32.const 186))
  (global $LINUX_SYS_X64_READAHEAD               (export "LINUX_SYS_X64_READAHEAD") i32 (i32.const 187))
  (global $LINUX_SYS_X64_SETXATTR                (export "LINUX_SYS_X64_SETXATTR") i32 (i32.const 188))
  (global $LINUX_SYS_X64_LSETXATTR               (export "LINUX_SYS_X64_LSETXATTR") i32 (i32.const 189))
  (global $LINUX_SYS_X64_FSETXATTR               (export "LINUX_SYS_X64_FSETXATTR") i32 (i32.const 190))
  (global $LINUX_SYS_X64_GETXATTR                (export "LINUX_SYS_X64_GETXATTR") i32 (i32.const 191))
  (global $LINUX_SYS_X64_LGETXATTR               (export "LINUX_SYS_X64_LGETXATTR") i32 (i32.const 192))
  (global $LINUX_SYS_X64_FGETXATTR               (export "LINUX_SYS_X64_FGETXATTR") i32 (i32.const 193))
  (global $LINUX_SYS_X64_LISTXATTR               (export "LINUX_SYS_X64_LISTXATTR") i32 (i32.const 194))
  (global $LINUX_SYS_X64_LLISTXATTR              (export "LINUX_SYS_X64_LLISTXATTR") i32 (i32.const 195))
  (global $LINUX_SYS_X64_FLISTXATTR              (export "LINUX_SYS_X64_FLISTXATTR") i32 (i32.const 196))
  (global $LINUX_SYS_X64_REMOVEXATTR             (export "LINUX_SYS_X64_REMOVEXATTR") i32 (i32.const 197))
  (global $LINUX_SYS_X64_LREMOVEXATTR            (export "LINUX_SYS_X64_LREMOVEXATTR") i32 (i32.const 198))
  (global $LINUX_SYS_X64_FREMOVEXATTR            (export "LINUX_SYS_X64_FREMOVEXATTR") i32 (i32.const 199))
  (global $LINUX_SYS_X64_TKILL                   (export "LINUX_SYS_X64_TKILL") i32 (i32.const 200))
  (global $LINUX_SYS_X64_TIME                    (export "LINUX_SYS_X64_TIME") i32 (i32.const 201))
  (global $LINUX_SYS_X64_FUTEX                   (export "LINUX_SYS_X64_FUTEX") i32 (i32.const 202))
  (global $LINUX_SYS_X64_SCHED_SETAFFINITY       (export "LINUX_SYS_X64_SCHED_SETAFFINITY") i32 (i32.const 203))
  (global $LINUX_SYS_X64_SCHED_GETAFFINITY       (export "LINUX_SYS_X64_SCHED_GETAFFINITY") i32 (i32.const 204))
  (global $LINUX_SYS_X64_SET_THREAD_AREA         (export "LINUX_SYS_X64_SET_THREAD_AREA") i32 (i32.const 205))
  (global $LINUX_SYS_X64_IO_SETUP                (export "LINUX_SYS_X64_IO_SETUP") i32 (i32.const 206))
  (global $LINUX_SYS_X64_IO_DESTROY              (export "LINUX_SYS_X64_IO_DESTROY") i32 (i32.const 207))
  (global $LINUX_SYS_X64_IO_GETEVENTS            (export "LINUX_SYS_X64_IO_GETEVENTS") i32 (i32.const 208))
  (global $LINUX_SYS_X64_IO_SUBMIT               (export "LINUX_SYS_X64_IO_SUBMIT") i32 (i32.const 209))
  (global $LINUX_SYS_X64_IO_CANCEL               (export "LINUX_SYS_X64_IO_CANCEL") i32 (i32.const 210))
  (global $LINUX_SYS_X64_GET_THREAD_AREA         (export "LINUX_SYS_X64_GET_THREAD_AREA") i32 (i32.const 211))
  (global $LINUX_SYS_X64_LOOKUP_DCOOKIE          (export "LINUX_SYS_X64_LOOKUP_DCOOKIE") i32 (i32.const 212))
  (global $LINUX_SYS_X64_EPOLL_CREATE            (export "LINUX_SYS_X64_EPOLL_CREATE") i32 (i32.const 213))
  (global $LINUX_SYS_X64_EPOLL_CTL_OLD           (export "LINUX_SYS_X64_EPOLL_CTL_OLD") i32 (i32.const 214))
  (global $LINUX_SYS_X64_EPOLL_WAIT_OLD          (export "LINUX_SYS_X64_EPOLL_WAIT_OLD") i32 (i32.const 215))
  (global $LINUX_SYS_X64_REMAP_FILE_PAGES        (export "LINUX_SYS_X64_REMAP_FILE_PAGES") i32 (i32.const 216))
  (global $LINUX_SYS_X64_GETDENTS64              (export "LINUX_SYS_X64_GETDENTS64") i32 (i32.const 217))
  (global $LINUX_SYS_X64_SET_TID_ADDRESS         (export "LINUX_SYS_X64_SET_TID_ADDRESS") i32 (i32.const 218))
  (global $LINUX_SYS_X64_RESTART_SYSCALL         (export "LINUX_SYS_X64_RESTART_SYSCALL") i32 (i32.const 219))
  (global $LINUX_SYS_X64_SEMTIMEDOP              (export "LINUX_SYS_X64_SEMTIMEDOP") i32 (i32.const 220))
  (global $LINUX_SYS_X64_FADVISE64               (export "LINUX_SYS_X64_FADVISE64") i32 (i32.const 221))
  (global $LINUX_SYS_X64_TIMER_CREATE            (export "LINUX_SYS_X64_TIMER_CREATE") i32 (i32.const 222))
  (global $LINUX_SYS_X64_TIMER_SETTIME           (export "LINUX_SYS_X64_TIMER_SETTIME") i32 (i32.const 223))
  (global $LINUX_SYS_X64_TIMER_GETTIME           (export "LINUX_SYS_X64_TIMER_GETTIME") i32 (i32.const 224))
  (global $LINUX_SYS_X64_TIMER_GETOVERRUN        (export "LINUX_SYS_X64_TIMER_GETOVERRUN") i32 (i32.const 225))
  (global $LINUX_SYS_X64_TIMER_DELETE            (export "LINUX_SYS_X64_TIMER_DELETE") i32 (i32.const 226))
  (global $LINUX_SYS_X64_CLOCK_SETTIME           (export "LINUX_SYS_X64_CLOCK_SETTIME") i32 (i32.const 227))
  (global $LINUX_SYS_X64_CLOCK_GETTIME           (export "LINUX_SYS_X64_CLOCK_GETTIME") i32 (i32.const 228))
  (global $LINUX_SYS_X64_CLOCK_GETRES            (export "LINUX_SYS_X64_CLOCK_GETRES") i32 (i32.const 229))
  (global $LINUX_SYS_X64_CLOCK_NANOSLEEP         (export "LINUX_SYS_X64_CLOCK_NANOSLEEP") i32 (i32.const 230))
  (global $LINUX_SYS_X64_EXIT_GROUP              (export "LINUX_SYS_X64_EXIT_GROUP") i32 (i32.const 231))
  (global $LINUX_SYS_X64_EPOLL_WAIT              (export "LINUX_SYS_X64_EPOLL_WAIT") i32 (i32.const 232))
  (global $LINUX_SYS_X64_EPOLL_CTL               (export "LINUX_SYS_X64_EPOLL_CTL") i32 (i32.const 233))
  (global $LINUX_SYS_X64_TGKILL                  (export "LINUX_SYS_X64_TGKILL") i32 (i32.const 234))
  (global $LINUX_SYS_X64_UTIMES                  (export "LINUX_SYS_X64_UTIMES") i32 (i32.const 235))
  (global $LINUX_SYS_X64_VSERVER                 (export "LINUX_SYS_X64_VSERVER") i32 (i32.const 236))
  (global $LINUX_SYS_X64_MBIND                   (export "LINUX_SYS_X64_MBIND") i32 (i32.const 237))
  (global $LINUX_SYS_X64_SET_MEMPOLICY           (export "LINUX_SYS_X64_SET_MEMPOLICY") i32 (i32.const 238))
  (global $LINUX_SYS_X64_GET_MEMPOLICY           (export "LINUX_SYS_X64_GET_MEMPOLICY") i32 (i32.const 239))
  (global $LINUX_SYS_X64_MQ_OPEN                 (export "LINUX_SYS_X64_MQ_OPEN") i32 (i32.const 240))
  (global $LINUX_SYS_X64_MQ_UNLINK               (export "LINUX_SYS_X64_MQ_UNLINK") i32 (i32.const 241))
  (global $LINUX_SYS_X64_MQ_TIMEDSEND            (export "LINUX_SYS_X64_MQ_TIMEDSEND") i32 (i32.const 242))
  (global $LINUX_SYS_X64_MQ_TIMEDRECEIVE         (export "LINUX_SYS_X64_MQ_TIMEDRECEIVE") i32 (i32.const 243))
  (global $LINUX_SYS_X64_MQ_NOTIFY               (export "LINUX_SYS_X64_MQ_NOTIFY") i32 (i32.const 244))
  (global $LINUX_SYS_X64_MQ_GETSETATTR           (export "LINUX_SYS_X64_MQ_GETSETATTR") i32 (i32.const 245))
  (global $LINUX_SYS_X64_KEXEC_LOAD              (export "LINUX_SYS_X64_KEXEC_LOAD") i32 (i32.const 246))
  (global $LINUX_SYS_X64_WAITID                  (export "LINUX_SYS_X64_WAITID") i32 (i32.const 247))
  (global $LINUX_SYS_X64_ADD_KEY                 (export "LINUX_SYS_X64_ADD_KEY") i32 (i32.const 248))
  (global $LINUX_SYS_X64_REQUEST_KEY             (export "LINUX_SYS_X64_REQUEST_KEY") i32 (i32.const 249))
  (global $LINUX_SYS_X64_KEYCTL                  (export "LINUX_SYS_X64_KEYCTL") i32 (i32.const 250))
  (global $LINUX_SYS_X64_IOPRIO_SET              (export "LINUX_SYS_X64_IOPRIO_SET") i32 (i32.const 251))
  (global $LINUX_SYS_X64_IOPRIO_GET              (export "LINUX_SYS_X64_IOPRIO_GET") i32 (i32.const 252))
  (global $LINUX_SYS_X64_INOTIFY_INIT            (export "LINUX_SYS_X64_INOTIFY_INIT") i32 (i32.const 253))
  (global $LINUX_SYS_X64_INOTIFY_ADD_WATCH       (export "LINUX_SYS_X64_INOTIFY_ADD_WATCH") i32 (i32.const 254))
  (global $LINUX_SYS_X64_INOTIFY_RM_WATCH        (export "LINUX_SYS_X64_INOTIFY_RM_WATCH") i32 (i32.const 255))
  (global $LINUX_SYS_X64_MIGRATE_PAGES           (export "LINUX_SYS_X64_MIGRATE_PAGES") i32 (i32.const 256))
  (global $LINUX_SYS_X64_OPENAT                  (export "LINUX_SYS_X64_OPENAT") i32 (i32.const 257))
  (global $LINUX_SYS_X64_MKDIRAT                 (export "LINUX_SYS_X64_MKDIRAT") i32 (i32.const 258))
  (global $LINUX_SYS_X64_MKNODAT                 (export "LINUX_SYS_X64_MKNODAT") i32 (i32.const 259))
  (global $LINUX_SYS_X64_FCHOWNAT                (export "LINUX_SYS_X64_FCHOWNAT") i32 (i32.const 260))
  (global $LINUX_SYS_X64_FUTIMESAT               (export "LINUX_SYS_X64_FUTIMESAT") i32 (i32.const 261))
  (global $LINUX_SYS_X64_NEWFSTATAT              (export "LINUX_SYS_X64_NEWFSTATAT") i32 (i32.const 262))
  (global $LINUX_SYS_X64_UNLINKAT                (export "LINUX_SYS_X64_UNLINKAT") i32 (i32.const 263))
  (global $LINUX_SYS_X64_RENAMEAT                (export "LINUX_SYS_X64_RENAMEAT") i32 (i32.const 264))
  (global $LINUX_SYS_X64_LINKAT                  (export "LINUX_SYS_X64_LINKAT") i32 (i32.const 265))
  (global $LINUX_SYS_X64_SYMLINKAT               (export "LINUX_SYS_X64_SYMLINKAT") i32 (i32.const 266))
  (global $LINUX_SYS_X64_READLINKAT              (export "LINUX_SYS_X64_READLINKAT") i32 (i32.const 267))
  (global $LINUX_SYS_X64_FCHMODAT                (export "LINUX_SYS_X64_FCHMODAT") i32 (i32.const 268))
  (global $LINUX_SYS_X64_FACCESSAT               (export "LINUX_SYS_X64_FACCESSAT") i32 (i32.const 269))
  (global $LINUX_SYS_X64_PSELECT6                (export "LINUX_SYS_X64_PSELECT6") i32 (i32.const 270))
  (global $LINUX_SYS_X64_PPOLL                   (export "LINUX_SYS_X64_PPOLL") i32 (i32.const 271))
  (global $LINUX_SYS_X64_UNSHARE                 (export "LINUX_SYS_X64_UNSHARE") i32 (i32.const 272))
  (global $LINUX_SYS_X64_SET_ROBUST_LIST         (export "LINUX_SYS_X64_SET_ROBUST_LIST") i32 (i32.const 273))
  (global $LINUX_SYS_X64_GET_ROBUST_LIST         (export "LINUX_SYS_X64_GET_ROBUST_LIST") i32 (i32.const 274))
  (global $LINUX_SYS_X64_SPLICE                  (export "LINUX_SYS_X64_SPLICE") i32 (i32.const 275))
  (global $LINUX_SYS_X64_TEE                     (export "LINUX_SYS_X64_TEE") i32 (i32.const 276))
  (global $LINUX_SYS_X64_SYNC_FILE_RANGE         (export "LINUX_SYS_X64_SYNC_FILE_RANGE") i32 (i32.const 277))
  (global $LINUX_SYS_X64_VMSPLICE                (export "LINUX_SYS_X64_VMSPLICE") i32 (i32.const 278))
  (global $LINUX_SYS_X64_MOVE_PAGES              (export "LINUX_SYS_X64_MOVE_PAGES") i32 (i32.const 279))
  (global $LINUX_SYS_X64_UTIMENSAT               (export "LINUX_SYS_X64_UTIMENSAT") i32 (i32.const 280))
  (global $LINUX_SYS_X64_EPOLL_PWAIT             (export "LINUX_SYS_X64_EPOLL_PWAIT") i32 (i32.const 281))
  (global $LINUX_SYS_X64_SIGNALFD                (export "LINUX_SYS_X64_SIGNALFD") i32 (i32.const 282))
  (global $LINUX_SYS_X64_TIMERFD_CREATE          (export "LINUX_SYS_X64_TIMERFD_CREATE") i32 (i32.const 283))
  (global $LINUX_SYS_X64_EVENTFD                 (export "LINUX_SYS_X64_EVENTFD") i32 (i32.const 284))
  (global $LINUX_SYS_X64_FALLOCATE               (export "LINUX_SYS_X64_FALLOCATE") i32 (i32.const 285))
  (global $LINUX_SYS_X64_TIMERFD_SETTIME         (export "LINUX_SYS_X64_TIMERFD_SETTIME") i32 (i32.const 286))
  (global $LINUX_SYS_X64_TIMERFD_GETTIME         (export "LINUX_SYS_X64_TIMERFD_GETTIME") i32 (i32.const 287))
  (global $LINUX_SYS_X64_ACCEPT4                 (export "LINUX_SYS_X64_ACCEPT4") i32 (i32.const 288))
  (global $LINUX_SYS_X64_SIGNALFD4               (export "LINUX_SYS_X64_SIGNALFD4") i32 (i32.const 289))
  (global $LINUX_SYS_X64_EVENTFD2                (export "LINUX_SYS_X64_EVENTFD2") i32 (i32.const 290))
  (global $LINUX_SYS_X64_EPOLL_CREATE1           (export "LINUX_SYS_X64_EPOLL_CREATE1") i32 (i32.const 291))
  (global $LINUX_SYS_X64_DUP3                    (export "LINUX_SYS_X64_DUP3") i32 (i32.const 292))
  (global $LINUX_SYS_X64_PIPE2                   (export "LINUX_SYS_X64_PIPE2") i32 (i32.const 293))
  (global $LINUX_SYS_X64_INOTIFY_INIT1           (export "LINUX_SYS_X64_INOTIFY_INIT1") i32 (i32.const 294))
  (global $LINUX_SYS_X64_PREADV                  (export "LINUX_SYS_X64_PREADV") i32 (i32.const 295))
  (global $LINUX_SYS_X64_PWRITEV                 (export "LINUX_SYS_X64_PWRITEV") i32 (i32.const 296))
  (global $LINUX_SYS_X64_RT_TGSIGQUEUEINFO       (export "LINUX_SYS_X64_RT_TGSIGQUEUEINFO") i32 (i32.const 297))
  (global $LINUX_SYS_X64_PERF_EVENT_OPEN         (export "LINUX_SYS_X64_PERF_EVENT_OPEN") i32 (i32.const 298))
  (global $LINUX_SYS_X64_RECVMMSG                (export "LINUX_SYS_X64_RECVMMSG") i32 (i32.const 299))
  (global $LINUX_SYS_X64_FANOTIFY_INIT           (export "LINUX_SYS_X64_FANOTIFY_INIT") i32 (i32.const 300))
  (global $LINUX_SYS_X64_FANOTIFY_MARK           (export "LINUX_SYS_X64_FANOTIFY_MARK") i32 (i32.const 301))
  (global $LINUX_SYS_X64_PRLIMIT64               (export "LINUX_SYS_X64_PRLIMIT64") i32 (i32.const 302))
  (global $LINUX_SYS_X64_NAME_TO_HANDLE_AT       (export "LINUX_SYS_X64_NAME_TO_HANDLE_AT") i32 (i32.const 303))
  (global $LINUX_SYS_X64_OPEN_BY_HANDLE_AT       (export "LINUX_SYS_X64_OPEN_BY_HANDLE_AT") i32 (i32.const 304))
  (global $LINUX_SYS_X64_CLOCK_ADJTIME           (export "LINUX_SYS_X64_CLOCK_ADJTIME") i32 (i32.const 305))
  (global $LINUX_SYS_X64_SYNCFS                  (export "LINUX_SYS_X64_SYNCFS") i32 (i32.const 306))
  (global $LINUX_SYS_X64_SENDMMSG                (export "LINUX_SYS_X64_SENDMMSG") i32 (i32.const 307))
  (global $LINUX_SYS_X64_SETNS                   (export "LINUX_SYS_X64_SETNS") i32 (i32.const 308))
  (global $LINUX_SYS_X64_GETCPU                  (export "LINUX_SYS_X64_GETCPU") i32 (i32.const 309))
  (global $LINUX_SYS_X64_PROCESS_VM_READV        (export "LINUX_SYS_X64_PROCESS_VM_READV") i32 (i32.const 310))
  (global $LINUX_SYS_X64_PROCESS_VM_WRITEV       (export "LINUX_SYS_X64_PROCESS_VM_WRITEV") i32 (i32.const 311))
  (global $LINUX_SYS_X64_KCMP                    (export "LINUX_SYS_X64_KCMP") i32 (i32.const 312))
  (global $LINUX_SYS_X64_FINIT_MODULE            (export "LINUX_SYS_X64_FINIT_MODULE") i32 (i32.const 313))
  (global $LINUX_SYS_X64_SCHED_SETATTR           (export "LINUX_SYS_X64_SCHED_SETATTR") i32 (i32.const 314))
  (global $LINUX_SYS_X64_SCHED_GETATTR           (export "LINUX_SYS_X64_SCHED_GETATTR") i32 (i32.const 315))
  (global $LINUX_SYS_X64_RENAMEAT2               (export "LINUX_SYS_X64_RENAMEAT2") i32 (i32.const 316))
  (global $LINUX_SYS_X64_SECCOMP                 (export "LINUX_SYS_X64_SECCOMP") i32 (i32.const 317))
  (global $LINUX_SYS_X64_GETRANDOM               (export "LINUX_SYS_X64_GETRANDOM") i32 (i32.const 318))
  (global $LINUX_SYS_X64_MEMFD_CREATE            (export "LINUX_SYS_X64_MEMFD_CREATE") i32 (i32.const 319))
  (global $LINUX_SYS_X64_KEXEC_FILE_LOAD         (export "LINUX_SYS_X64_KEXEC_FILE_LOAD") i32 (i32.const 320))
  (global $LINUX_SYS_X64_BPF                     (export "LINUX_SYS_X64_BPF") i32 (i32.const 321))
  (global $LINUX_SYS_X64_EXECVEAT                (export "LINUX_SYS_X64_EXECVEAT") i32 (i32.const 322))
  (global $LINUX_SYS_X64_USERFAULTFD             (export "LINUX_SYS_X64_USERFAULTFD") i32 (i32.const 323))
  (global $LINUX_SYS_X64_MEMBARRIER              (export "LINUX_SYS_X64_MEMBARRIER") i32 (i32.const 324))
  (global $LINUX_SYS_X64_MLOCK2                  (export "LINUX_SYS_X64_MLOCK2") i32 (i32.const 325))
  (global $LINUX_SYS_X64_COPY_FILE_RANGE         (export "LINUX_SYS_X64_COPY_FILE_RANGE") i32 (i32.const 326))
  (global $LINUX_SYS_X64_PREADV2                 (export "LINUX_SYS_X64_PREADV2") i32 (i32.const 327))
  (global $LINUX_SYS_X64_PWRITEV2                (export "LINUX_SYS_X64_PWRITEV2") i32 (i32.const 328))
  (global $LINUX_SYS_X64_PKEY_MPROTECT           (export "LINUX_SYS_X64_PKEY_MPROTECT") i32 (i32.const 329))
  (global $LINUX_SYS_X64_PKEY_ALLOC              (export "LINUX_SYS_X64_PKEY_ALLOC") i32 (i32.const 330))
  (global $LINUX_SYS_X64_PKEY_FREE               (export "LINUX_SYS_X64_PKEY_FREE") i32 (i32.const 331))
  (global $LINUX_SYS_X64_STATX                   (export "LINUX_SYS_X64_STATX") i32 (i32.const 332))
  (global $LINUX_SYS_X64_IO_PGETEVENTS           (export "LINUX_SYS_X64_IO_PGETEVENTS") i32 (i32.const 333))
  (global $LINUX_SYS_X64_RSEQ                    (export "LINUX_SYS_X64_RSEQ") i32 (i32.const 334))
  (global $LINUX_SYS_X64_URETPROBE               (export "LINUX_SYS_X64_URETPROBE") i32 (i32.const 335))
  (global $LINUX_SYS_X64_UPROBE                  (export "LINUX_SYS_X64_UPROBE") i32 (i32.const 336))
  (global $LINUX_SYS_X64_PIDFD_SEND_SIGNAL       (export "LINUX_SYS_X64_PIDFD_SEND_SIGNAL") i32 (i32.const 424))
  (global $LINUX_SYS_X64_IO_URING_SETUP          (export "LINUX_SYS_X64_IO_URING_SETUP") i32 (i32.const 425))
  (global $LINUX_SYS_X64_IO_URING_ENTER          (export "LINUX_SYS_X64_IO_URING_ENTER") i32 (i32.const 426))
  (global $LINUX_SYS_X64_IO_URING_REGISTER       (export "LINUX_SYS_X64_IO_URING_REGISTER") i32 (i32.const 427))
  (global $LINUX_SYS_X64_OPEN_TREE               (export "LINUX_SYS_X64_OPEN_TREE") i32 (i32.const 428))
  (global $LINUX_SYS_X64_MOVE_MOUNT              (export "LINUX_SYS_X64_MOVE_MOUNT") i32 (i32.const 429))
  (global $LINUX_SYS_X64_FSOPEN                  (export "LINUX_SYS_X64_FSOPEN") i32 (i32.const 430))
  (global $LINUX_SYS_X64_FSCONFIG                (export "LINUX_SYS_X64_FSCONFIG") i32 (i32.const 431))
  (global $LINUX_SYS_X64_FSMOUNT                 (export "LINUX_SYS_X64_FSMOUNT") i32 (i32.const 432))
  (global $LINUX_SYS_X64_FSPICK                  (export "LINUX_SYS_X64_FSPICK") i32 (i32.const 433))
  (global $LINUX_SYS_X64_PIDFD_OPEN              (export "LINUX_SYS_X64_PIDFD_OPEN") i32 (i32.const 434))
  (global $LINUX_SYS_X64_CLONE3                  (export "LINUX_SYS_X64_CLONE3") i32 (i32.const 435))
  (global $LINUX_SYS_X64_CLOSE_RANGE             (export "LINUX_SYS_X64_CLOSE_RANGE") i32 (i32.const 436))
  (global $LINUX_SYS_X64_OPENAT2                 (export "LINUX_SYS_X64_OPENAT2") i32 (i32.const 437))
  (global $LINUX_SYS_X64_PIDFD_GETFD             (export "LINUX_SYS_X64_PIDFD_GETFD") i32 (i32.const 438))
  (global $LINUX_SYS_X64_FACCESSAT2              (export "LINUX_SYS_X64_FACCESSAT2") i32 (i32.const 439))
  (global $LINUX_SYS_X64_PROCESS_MADVISE         (export "LINUX_SYS_X64_PROCESS_MADVISE") i32 (i32.const 440))
  (global $LINUX_SYS_X64_EPOLL_PWAIT2            (export "LINUX_SYS_X64_EPOLL_PWAIT2") i32 (i32.const 441))
  (global $LINUX_SYS_X64_MOUNT_SETATTR           (export "LINUX_SYS_X64_MOUNT_SETATTR") i32 (i32.const 442))
  (global $LINUX_SYS_X64_QUOTACTL_FD             (export "LINUX_SYS_X64_QUOTACTL_FD") i32 (i32.const 443))
  (global $LINUX_SYS_X64_LANDLOCK_CREATE_RULESET (export "LINUX_SYS_X64_LANDLOCK_CREATE_RULESET") i32 (i32.const 444))
  (global $LINUX_SYS_X64_LANDLOCK_ADD_RULE       (export "LINUX_SYS_X64_LANDLOCK_ADD_RULE") i32 (i32.const 445))
  (global $LINUX_SYS_X64_LANDLOCK_RESTRICT_SELF  (export "LINUX_SYS_X64_LANDLOCK_RESTRICT_SELF") i32 (i32.const 446))
  (global $LINUX_SYS_X64_MEMFD_SECRET            (export "LINUX_SYS_X64_MEMFD_SECRET") i32 (i32.const 447))
  (global $LINUX_SYS_X64_PROCESS_MRELEASE        (export "LINUX_SYS_X64_PROCESS_MRELEASE") i32 (i32.const 448))
  (global $LINUX_SYS_X64_FUTEX_WAITV             (export "LINUX_SYS_X64_FUTEX_WAITV") i32 (i32.const 449))
  (global $LINUX_SYS_X64_SET_MEMPOLICY_HOME_NODE (export "LINUX_SYS_X64_SET_MEMPOLICY_HOME_NODE") i32 (i32.const 450))
  (global $LINUX_SYS_X64_CACHESTAT               (export "LINUX_SYS_X64_CACHESTAT") i32 (i32.const 451))
  (global $LINUX_SYS_X64_FCHMODAT2               (export "LINUX_SYS_X64_FCHMODAT2") i32 (i32.const 452))
  (global $LINUX_SYS_X64_MAP_SHADOW_STACK        (export "LINUX_SYS_X64_MAP_SHADOW_STACK") i32 (i32.const 453))
  (global $LINUX_SYS_X64_FUTEX_WAKE              (export "LINUX_SYS_X64_FUTEX_WAKE") i32 (i32.const 454))
  (global $LINUX_SYS_X64_FUTEX_WAIT              (export "LINUX_SYS_X64_FUTEX_WAIT") i32 (i32.const 455))
  (global $LINUX_SYS_X64_FUTEX_REQUEUE           (export "LINUX_SYS_X64_FUTEX_REQUEUE") i32 (i32.const 456))
  (global $LINUX_SYS_X64_STATMOUNT               (export "LINUX_SYS_X64_STATMOUNT") i32 (i32.const 457))
  (global $LINUX_SYS_X64_LISTMOUNT               (export "LINUX_SYS_X64_LISTMOUNT") i32 (i32.const 458))
  (global $LINUX_SYS_X64_LSM_GET_SELF_ATTR       (export "LINUX_SYS_X64_LSM_GET_SELF_ATTR") i32 (i32.const 459))
  (global $LINUX_SYS_X64_LSM_SET_SELF_ATTR       (export "LINUX_SYS_X64_LSM_SET_SELF_ATTR") i32 (i32.const 460))
  (global $LINUX_SYS_X64_LSM_LIST_MODULES        (export "LINUX_SYS_X64_LSM_LIST_MODULES") i32 (i32.const 461))
  (global $LINUX_SYS_X64_MSEAL                   (export "LINUX_SYS_X64_MSEAL") i32 (i32.const 462))
  (global $LINUX_SYS_X64_SETXATTRAT              (export "LINUX_SYS_X64_SETXATTRAT") i32 (i32.const 463))
  (global $LINUX_SYS_X64_GETXATTRAT              (export "LINUX_SYS_X64_GETXATTRAT") i32 (i32.const 464))
  (global $LINUX_SYS_X64_LISTXATTRAT             (export "LINUX_SYS_X64_LISTXATTRAT") i32 (i32.const 465))
  (global $LINUX_SYS_X64_REMOVEXATTRAT           (export "LINUX_SYS_X64_REMOVEXATTRAT") i32 (i32.const 466))
  (global $LINUX_SYS_X64_OPEN_TREE_ATTR          (export "LINUX_SYS_X64_OPEN_TREE_ATTR") i32 (i32.const 467))
  (global $LINUX_SYS_X64_FILE_GETATTR            (export "LINUX_SYS_X64_FILE_GETATTR") i32 (i32.const 468))
  (global $LINUX_SYS_X64_FILE_SETATTR            (export "LINUX_SYS_X64_FILE_SETATTR") i32 (i32.const 469))
  (global $LINUX_SYS_X64_LISTNS                  (export "LINUX_SYS_X64_LISTNS") i32 (i32.const 470))
  (global $LINUX_SYS_X64_RSEQ_SLICE_YIELD        (export "LINUX_SYS_X64_RSEQ_SLICE_YIELD") i32 (i32.const 471))

  ;; ── Linux aarch64 syscall numbers (only where they differ from x86_64) ──
  (global $LINUX_SYS_AARCH64_EXIT       (export "LINUX_SYS_AARCH64_EXIT")       i32 (i32.const 93))
  (global $LINUX_SYS_AARCH64_CLONE      (export "LINUX_SYS_AARCH64_CLONE")      i32 (i32.const 220))
  (global $LINUX_SYS_AARCH64_EXECVE     (export "LINUX_SYS_AARCH64_EXECVE")     i32 (i32.const 221))
  (global $LINUX_SYS_AARCH64_MMAP       (export "LINUX_SYS_AARCH64_MMAP")       i32 (i32.const 222))
  (global $LINUX_SYS_AARCH64_MOUNT      (export "LINUX_SYS_AARCH64_MOUNT")      i32 (i32.const 40))
  (global $LINUX_SYS_AARCH64_UMOUNT2    (export "LINUX_SYS_AARCH64_UMOUNT2")    i32 (i32.const 39))
  (global $LINUX_SYS_AARCH64_PIVOT_ROOT (export "LINUX_SYS_AARCH64_PIVOT_ROOT") i32 (i32.const 41))
  (global $LINUX_SYS_AARCH64_UNSHARE    (export "LINUX_SYS_AARCH64_UNSHARE")    i32 (i32.const 97))
  (global $LINUX_SYS_AARCH64_SETNS      (export "LINUX_SYS_AARCH64_SETNS")      i32 (i32.const 268))
  (global $LINUX_SYS_AARCH64_SETHOSTNAME    (export "LINUX_SYS_AARCH64_SETHOSTNAME")    i32 (i32.const 161))
  (global $LINUX_SYS_AARCH64_SETDOMAINNAME  (export "LINUX_SYS_AARCH64_SETDOMAINNAME")  i32 (i32.const 162))
  (global $LINUX_SYS_AARCH64_SECCOMP    (export "LINUX_SYS_AARCH64_SECCOMP")    i32 (i32.const 277))
  (global $LINUX_SYS_AARCH64_CAPSET     (export "LINUX_SYS_AARCH64_CAPSET")     i32 (i32.const 91))
  (global $LINUX_SYS_AARCH64_PRCTL      (export "LINUX_SYS_AARCH64_PRCTL")      i32 (i32.const 167))
  (global $LINUX_SYS_AARCH64_SETUID     (export "LINUX_SYS_AARCH64_SETUID")     i32 (i32.const 146))
  (global $LINUX_SYS_AARCH64_SETGID     (export "LINUX_SYS_AARCH64_SETGID")     i32 (i32.const 144))
  (global $LINUX_SYS_AARCH64_SETGROUPS  (export "LINUX_SYS_AARCH64_SETGROUPS")  i32 (i32.const 159))
  (global $LINUX_SYS_AARCH64_PRLIMIT64  (export "LINUX_SYS_AARCH64_PRLIMIT64")  i32 (i32.const 261))
  (global $LINUX_SYS_AARCH64_SCHED_SETATTR (export "LINUX_SYS_AARCH64_SCHED_SETATTR") i32 (i32.const 274))
  (global $LINUX_SYS_AARCH64_IOPRIO_SET (export "LINUX_SYS_AARCH64_IOPRIO_SET") i32 (i32.const 30))
  (global $LINUX_SYS_AARCH64_UMASK      (export "LINUX_SYS_AARCH64_UMASK")      i32 (i32.const 166))
  (global $LINUX_SYS_AARCH64_KILL       (export "LINUX_SYS_AARCH64_KILL")       i32 (i32.const 129))
  (global $LINUX_SYS_AARCH64_WAIT4      (export "LINUX_SYS_AARCH64_WAIT4")      i32 (i32.const 260))
  (global $LINUX_SYS_AARCH64_BPF        (export "LINUX_SYS_AARCH64_BPF")        i32 (i32.const 280))
  (global $LINUX_SYS_AARCH64_OPEN_TREE  (export "LINUX_SYS_AARCH64_OPEN_TREE")  i32 (i32.const 428))
  (global $LINUX_SYS_AARCH64_MOVE_MOUNT (export "LINUX_SYS_AARCH64_MOVE_MOUNT") i32 (i32.const 429))
  (global $LINUX_SYS_AARCH64_MOUNT_SETATTR (export "LINUX_SYS_AARCH64_MOUNT_SETATTR") i32 (i32.const 442))

  ;; ── Linux ARM32 (EABI) syscall numbers (only where they differ) ──
  (global $LINUX_SYS_ARM32_EXIT         (export "LINUX_SYS_ARM32_EXIT")         i32 (i32.const 1))

  ;; ── Bounds check ──
  ;; Returns 1 if offset + need <= len, 0 otherwise.
  (func $bounds_check (export "bounds_check")
    (param $len i32) (param $offset i32) (param $need i32) (result i32)
    (if (result i32)
      (i32.lt_u (local.get $len) (local.get $need))
      (then (i32.const 0))
      (else
        (i32.le_u
          (local.get $offset)
          (i32.sub (local.get $len) (local.get $need))))))

  ;; ── LEB128 decoders ──

  (func $read_leb128_u (export "read_leb128_u")
    (param $ptr i32) (param $len i32) (param $offset i32) (result i64)
    (local $pos i32) (local $val i64) (local $b i32) (local $shift i32)
    (local.set $pos (local.get $offset))
    (local.set $val (i64.const 0))
    (local.set $shift (i32.const 0))
    (block $done
      (loop $loop
        (if (i32.ge_u (local.get $pos) (local.get $len))
          (then
            (return (call $pack (i32.const 1) (i32.wrap_i64 (local.get $val))))))
        (local.set $b (i32.load8_u (i32.add (local.get $ptr) (local.get $pos))))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1)))
        (local.set $val
          (i64.or (local.get $val)
            (i64.shl (i64.extend_i32_u (i32.and (local.get $b) (i32.const 0x7f))) (i64.extend_i32_u (local.get $shift)))))
        (local.set $shift (i32.add (local.get $shift) (i32.const 7)))
        (if (i32.eqz (i32.and (local.get $b) (i32.const 0x80)))
          (then
            (return (call $pack (i32.const 0)
              (i32.or (local.get $pos) (i32.shl (i32.wrap_i64 (local.get $val)) (i32.const 8)))))))
        (br $loop)))
    (call $pack (i32.const 5) (i32.const 0)))

  (func $read_leb128_s (export "read_leb128_s")
    (param $ptr i32) (param $len i32) (param $offset i32) (result i64)
    (local $pos i32) (local $val i64) (local $b i32) (local $shift i32)
    (local.set $pos (local.get $offset))
    (local.set $val (i64.const 0))
    (local.set $shift (i32.const 0))
    (block $done
      (loop $loop
        (if (i32.ge_u (local.get $pos) (local.get $len))
          (then
            (return (call $pack (i32.const 1) (i32.wrap_i64 (local.get $val))))))
        (local.set $b (i32.load8_u (i32.add (local.get $ptr) (local.get $pos))))
        (local.set $pos (i32.add (local.get $pos) (i32.const 1)))
        (local.set $val
          (i64.or (local.get $val)
            (i64.shl (i64.extend_i32_u (i32.and (local.get $b) (i32.const 0x7f))) (i64.extend_i32_u (local.get $shift)))))
        (local.set $shift (i32.add (local.get $shift) (i32.const 7)))
        (if (i32.eqz (i32.and (local.get $b) (i32.const 0x80)))
          (then
            (if (i32.and (local.get $b) (i32.const 0x40))
              (then
                (local.set $val
                  (i64.or (local.get $val)
                    (i64.shl (i64.const -1) (i64.extend_i32_u (local.get $shift)))))))
            (return (call $pack (i32.const 0)
              (i32.or (local.get $pos) (i32.shl (i32.wrap_i64 (local.get $val)) (i32.const 8)))))))
        (br $loop)))
    (call $pack (i32.const 5) (i32.const 0)))

  ;; ── Additional shared utilities ──

  (func $load8_u (export "load8_u") (param $ptr i32) (param $offset i32) (result i32)
    (i32.load8_u (i32.add (local.get $ptr) (local.get $offset))))

  (func $store8 (export "store8") (param $ptr i32) (param $offset i32) (param $val i32)
    (i32.store8 (i32.add (local.get $ptr) (local.get $offset)) (local.get $val)))

  (func $memset (export "memset") (param $ptr i32) (param $val i32) (param $len i32)
    (local $i i32)
    (block $done
      (loop $loop
        (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
        (i32.store8 (i32.add (local.get $ptr) (local.get $i)) (local.get $val))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop))))

  (func $string_eq (export "string_eq") (param $ptr i32) (param $len i32) (param $lit i32) (param $lit_len i32) (result i32)
    (local $i i32)
    (if (result i32) (i32.ne (local.get $len) (local.get $lit_len))
      (then (i32.const 0))
      (else
        (block $done
          (loop $loop
            (if (i32.ge_u (local.get $i) (local.get $len))
              (then (br $done)))
            (if (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $i)))
                        (i32.load8_u (i32.add (local.get $lit) (local.get $i))))
              (then (return (i32.const 0))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $loop))
          )
        (i32.const 1))))

  (func $starts_with (export "starts_with") (param $ptr i32) (param $len i32) (param $prefix i32) (param $prefix_len i32) (result i32)
    (local $i i32)
    (if (result i32) (i32.lt_u (local.get $len) (local.get $prefix_len))
      (then (i32.const 0))
      (else
        (block $done
          (loop $loop
            (if (i32.ge_u (local.get $i) (local.get $prefix_len))
              (then (br $done)))
            (if (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $i)))
                        (i32.load8_u (i32.add (local.get $prefix) (local.get $i))))
              (then (return (i32.const 0))))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $loop))
          )
        (i32.const 1))))

  (func $strlen (export "strlen") (param $ptr i32) (result i32)
    (local $i i32)
    (block $done
      (loop $loop
        (if (i32.eqz (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))
          (then (return (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop)))
    (i32.const -1))

  (func $fnv1a_lower (export "fnv1a_lower") (param $ptr i32) (param $len i32) (result i32)
    (local $h i32) (local $i i32)
    (local.set $h (i32.const 2166136261))
    (block $done
      (loop $loop
        (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
        (local.set $h (i32.xor (local.get $h) (call $to_lower (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))))
        (local.set $h (i32.mul (local.get $h) (i32.const 16777619)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $loop)))
    (local.get $h))

  ;; ── Protocol exports ──

  (func $proto_abi_version (export "proto_abi_version") (result i32)
    (i32.const 2))

  (func $proto_standard_id (export "proto_standard_id") (result i32)
    (i32.const 0))

  (func $simd_capabilities (export "simd_capabilities") (result i32)
    (i32.const 1))
