;; AES-128-GCM Encrypt/Decrypt Pipeline Stage — slots 21, 22
  ;; Config layout:
  ;;   +0: key_len (i32) — expected 16
  ;;   +4: key (key_len bytes)
  ;;   +4+key_len: iv_len (i32) — expected 12
  ;;   +4+key_len+4: iv (iv_len bytes)
  ;;   +4+key_len+4+iv_len: aad_len (i32)
  ;;   +4+key_len+4+iv_len+4: aad (aad_len bytes)

  (func $process_aes128_gcm_encrypt (export "process_aes128_gcm_encrypt")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32)
    (local $key_len i32) (local $iv_len i32) (local $aad_len i32) (local $read i32)
    (local $key_ptr i32) (local $iv_ptr i32) (local $aad_ptr i32)
    (local $result i32) (local $tag_ptr i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.eqz (local.get $read)) (then (return (i32.const 0))))
    (local.set $key_len (i32.load (local.get $cfg)))
    (local.set $key_ptr (i32.add (local.get $cfg) (i32.const 4)))
    (local.set $iv_len (i32.load (i32.add (local.get $key_ptr) (local.get $key_len))))
    (local.set $iv_ptr (i32.add (i32.add (local.get $key_ptr) (local.get $key_len)) (i32.const 4)))
    (local.set $aad_len (i32.load (i32.add (local.get $iv_ptr) (local.get $iv_len))))
    (local.set $aad_ptr (i32.add (i32.add (local.get $iv_ptr) (local.get $iv_len)) (i32.const 4)))
    (local.set $tag_ptr (i32.add (global.get $SHA256_OUT_BUF) (local.get $read)))
    (drop (call $pipe_read (local.get $input) (global.get $CRYPTO_INPUT_BUF) (local.get $read)))
    (local.set $result
      (call $aes128_gcm_encrypt
        (global.get $SHA256_OUT_BUF) (global.get $CRYPTO_INPUT_BUF)
        (local.get $read) (local.get $aad_ptr) (local.get $aad_len)
        (local.get $key_ptr) (local.get $iv_ptr) (local.get $tag_ptr)))
    (if (local.get $result) (then (return (i32.sub (i32.const 0) (local.get $result)))))
    (drop (call $pipe_write (local.get $output) (global.get $SHA256_OUT_BUF) (local.get $read)))
    (drop (call $pipe_write (local.get $output) (local.get $tag_ptr) (i32.const 16)))
    (i32.add (local.get $read) (i32.const 16)))

  (func $process_aes128_gcm_decrypt (export "process_aes128_gcm_decrypt")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32)
    (local $key_len i32) (local $iv_len i32) (local $aad_len i32)
    (local $key_ptr i32) (local $iv_ptr i32) (local $aad_ptr i32)
    (local $data_len i32) (local $tag_ptr i32)
    (local $result i32) (local $read i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.lt_u (local.get $read) (i32.const 16)) (then (return (i32.const 0))))
    (local.set $key_len (i32.load (local.get $cfg)))
    (local.set $key_ptr (i32.add (local.get $cfg) (i32.const 4)))
    (local.set $iv_len (i32.load (i32.add (local.get $key_ptr) (local.get $key_len))))
    (local.set $iv_ptr (i32.add (i32.add (local.get $key_ptr) (local.get $key_len)) (i32.const 4)))
    (local.set $aad_len (i32.load (i32.add (local.get $iv_ptr) (local.get $iv_len))))
    (local.set $aad_ptr (i32.add (i32.add (local.get $iv_ptr) (local.get $iv_len)) (i32.const 4)))
    (local.set $data_len (i32.sub (local.get $read) (i32.const 16)))
    (local.set $tag_ptr (i32.add (global.get $CRYPTO_INPUT_BUF) (local.get $data_len)))
    (drop (call $pipe_read (local.get $input) (global.get $CRYPTO_INPUT_BUF) (local.get $read)))
    (local.set $result
      (call $aes128_gcm_decrypt
        (global.get $SHA256_OUT_BUF) (global.get $CRYPTO_INPUT_BUF)
        (local.get $data_len) (local.get $aad_ptr) (local.get $aad_len)
        (local.get $key_ptr) (local.get $iv_ptr) (local.get $tag_ptr)))
    (if (local.get $result) (then (return (i32.sub (i32.const 0) (local.get $result)))))
    (drop (call $pipe_write (local.get $output) (global.get $SHA256_OUT_BUF) (local.get $data_len)))
    local.get $data_len)
