;; Varint Encode Pipeline Stage — slot 124
  (func $process_varint_encode (export "process_varint_encode")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32) (local $result i64) (local $status i32) (local $written i32)
    (local $val_lo i32) (local $val_hi i32) (local $read i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.lt_u (local.get $read) (i32.const 8)) (then (return (i32.const 0))))
    (drop (call $pipe_read (local.get $input) (global.get $SCRATCH_BUF) (i32.const 8)))
    (local.set $val_lo (i32.load (global.get $SCRATCH_BUF)))
    (local.set $val_hi (i32.load (i32.add (global.get $SCRATCH_BUF) (i32.const 4))))
    (local.set $result (call $varint_encode_u64 (local.get $val_lo) (local.get $val_hi) (global.get $WORK_BUF) (global.get $BUF_SIZE_8K)))
    (local.set $status (i32.wrap_i64 (i64.and (local.get $result) (i64.const 0xffffffff))))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (drop (call $pipe_write (local.get $output) (global.get $WORK_BUF) (local.get $written)))
    local.get $written)
