[package]
name = "edgerun-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-rt = { path = "../edgerun-rt" }
edgerun-core = { path = "../edgerun-core" }
edgerun-proto = { path = "../edgerun-proto" }
edgerun-hardware-signing = { path = "../edgerun-hardware-signing" }
prost.workspace = true
prost-types.workspace = true
p256.workspace = true
