[package]
name = "edgerun-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-core = { path = "../edgerun-core" }
edgerun-proto = { path = "../edgerun-proto" }
edgerun-hardware-signing = { path = "../edgerun-hardware-signing" }
edgerun-storage = { path = "../edgerun-storage" }
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-remote-capability = { path = "../edgerun-remote-capability" }
edgerun-mesh = { path = "../edgerun-mesh" }
edgerun-mesh-link = { path = "../edgerun-mesh-link" }
edgerun-mesh-session = { path = "../edgerun-mesh-session" }
prost.workspace = true
edgerun-crypto = { workspace = true, default-features = false, features = ["p256"] }

[features]
default = []
std = ["dep:edgerun-oci", "edgerun-oci/std"]

[target.'cfg(not(target_os = "none"))'.dependencies]
edgerun-oci = { path = "../edgerun-oci", optional = true }

[dev-dependencies]

[lints]
workspace = true
