[package]
name = "edgerun-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-rt = { path = "../edgerun-rt" }
edgerun-core = { path = "../edgerun-core" }
edgerun-proto = { path = "../edgerun-proto" }
edgerun-hardware-signing = { path = "../edgerun-hardware-signing" }
edgerun-storage = { path = "../edgerun-storage" }
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-remote-capability = { path = "../edgerun-remote-capability" }
edgerun-mesh = { path = "../edgerun-mesh" }
edgerun-mesh-link = { path = "../edgerun-mesh-link" }
edgerun-mesh-session = { path = "../edgerun-mesh-session" }
edgerun-oci = { path = "../edgerun-oci" }
prost.workspace = true
prost-types.workspace = true
edgerun-crypto.workspace = true

[dev-dependencies]

[lints]
workspace = true
