[package]
name = "edgerun-oauth"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "OAuth helpers for Edgerun service authentication"

[dependencies]
edgerun-crypto = { version = "0.1", path = "../../utility/edgerun-crypto", default-features = false, features = ["hmac", "p256", "rsa"] }
edgerun-node = { version = "0.1", path = "../../node/edgerun-node", default-features = false, features = ["client", "tls"] }
edgerun-log = { version = "0.1", path = "../../utility/edgerun-log" }
edgerun-json = { version = "0.1", path = "../../utility/edgerun-json" }
edgerun-secret-service = { version = "0.1", path = "../edgerun-secret-service" }
edgerun-encoding = { version = "0.1", path = "../../utility/edgerun-encoding", default-features = false }
edgerun-protocols = { version = "0.1", path = "../../protocol/edgerun-protocols", default-features = false, features = ["oauth"] }

[lints]
workspace = true
