[package]
name = "edgerun-tungstenite"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun compatibility surface for tungstenite-style WebSocket APIs"

[features]
default = ["deflate", "proxy"]
deflate = []
handshake = []
proxy = ["handshake"]

[dependencies]
bytes = { package = "edgerun-bytes", version = "0.1", path = "../edgerun-bytes" }
edgerun-crypto = { workspace = true, default-features = false, features = ["sha1"] }
edgerun-encoding = { workspace = true, default-features = false }
edgerun-http = { version = "0.1", path = "../edgerun-http" }
edgerun-random = { workspace = true }

[lints]
workspace = true
