[package]
name = "edgerun-linux-pci"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Linux PCI device adapter for Edgerun"

[dependencies]
edgerun-capabilities = { version = "0.1", path = "../../capability/edgerun-capabilities" }
edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }
edgerun-pci = { version = "0.1", path = "../../device-types/edgerun-pci" }

[features]
std = []

[[bin]]
name = "linux_pci_tool"
path = "src/bin/linux-pci-tool.rs"
required-features = ["std"]

[lints]
workspace = true
