[package]
name = "simdutf8"
version = "0.1.5"
edition = "2018"
license = "MIT OR Apache-2.0"
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned SIMD UTF-8 validation compatibility crate"

[features]
aarch64_neon = []
aarch64_neon_prefetch = []
default = ["std"]
hints = []
public_imp = []
std = []

[lints]
workspace = true
