[package]
name = "edgerun-seccompiler"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun seccomp error surface"

[features]
default = ["std"]
std = []

[lints]
workspace = true
