[package]
name = "edgerun-sdk-unit-ipv4-rfc791"
version = "0.1.1"
edition = "2021"
publish = false

[package.metadata.edgerun.unit]
id = "ipv4-rfc791"
standard = "RFC791"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
edgerun-unit = { path = "../../../../edgerun-unit" }

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true
