[package]
edition.workspace = true
license.workspace = true
name = "codex-code-mode"
version.workspace = true

[lib]
doctest = false
name = "codex_code_mode"
path = "src/lib.rs"

[features]
default = []

[lints]
workspace = true

[dependencies]
edgerun-async-channel = { workspace = true }
edgerun-async-trait = { workspace = true }
codex-protocol = { workspace = true }
edgerun-json = { workspace = true, features = ["serde-compat"] }
serde = { workspace = true, features = ["derive"] }
edgerun-tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
edgerun-tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true }
