[package]
name = "edgerun-qpack"
version.workspace = true
edition.workspace = true
description = "QPACK header compression for HTTP/3 (RFC 9204)"
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-encoding = { path = "../edgerun-encoding", default-features = false, features = ["alloc"] }


[dev-dependencies]
assert_matches = "1"
proptest = "1"

[features]
default = []
std = ["edgerun-encoding/std"]
http-headers = []
