[package]
name = "edgerun-audio-calibration"
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
version.workspace = true
description = "Audio loopback calibration tools and primitives for Edgerun devices"
autobins = false

[dependencies]
edgerun-devices.workspace = true
edgerun-alsa-microphone = { version = "0.1", path = "../edgerun-alsa-microphone" }
edgerun-alsa-speaker = { version = "0.1", path = "../edgerun-alsa-speaker" }
edgerun-capabilities = { version = "0.1", path = "../../capability/edgerun-capabilities" }

[lints]
workspace = true

[features]
std = []
