[package]
name = "edgerun-tuya"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Tuya device discovery and control support for Edgerun"
autobins = false

[dependencies]
edgerun-capabilities = { version = "0.1", path = "../../capability/edgerun-capabilities" }
edgerun-crypto = { version = "0.1", path = "../../utility/edgerun-crypto", default-features = false, features = ["aead", "hmac"] }
edgerun-node = { version = "0.1", path = "../../node/edgerun-node", default-features = false }
edgerun-json = { version = "0.1", path = "../../utility/edgerun-json", default-features = false }
edgerun-protocols = { workspace = true, default-features = false, features = ["tuya"] }

[features]
std = []

[lints]
workspace = true
