[package]
name = "edgerun-config"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Kubernetes-compatible DNS/DHCP configuration with event-sourced state"

[dependencies]
edgerun-dhcpv6 = { version = "0.1", path = "../edgerun-dhcpv6" }
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding", default-features = false }
edgerun-json = { version = "0.1", path = "../edgerun-json", default-features = false, features = ["yaml"] }
edgerun-error.workspace = true

[lints]
workspace = true
