[package]
name = "edgerun-exchange-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun Exchange HTTP API service"

[dependencies]
edgerun-protocols = { version = "0.1", path = "../../protocol/edgerun-protocols", default-features = false, features = ["core"] }
edgerun-exchange = { version = "0.1", path = "../../edgerun-exchange" }
edgerun-wallet = { version = "0.1", path = "../../edgerun-wallet" }
edgerun-node = { version = "0.1", path = "../../node/edgerun-node", default-features = false, features = ["server"] }
edgerun-json = { version = "0.1", path = "../../utility/edgerun-json" }
edgerun-log = { version = "0.1", path = "../../utility/edgerun-log" }
edgerun-sdk = { version = "0.1", path = "../../edgerun-sdk", default-features = false, features = ["runtime-api"] }
edgerun-url = { version = "0.1", path = "../../utility/edgerun-url" }

[lints]
workspace = true
