//! `resolv.conf` content parser.
//!
//! This module parses resolver configuration text handed to it by a caller. It
//! does not read `/etc/resolv.conf` or decide where resolver configuration
//! should come from.

use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};
use core::net::IpAddr;

const MAXNS: usize = 3;
const DEFAULT_DNS_PORT: u16 = 53;

/// A nameserver entry from resolv.conf content.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Nameserver {
    pub addr: IpAddr,
    pub port: u16,
}

/// Parsed resolv.conf configuration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvConf {
    pub nameservers: Vec<Nameserver>,
    pub search: Vec<String>,
    pub domain: Option<String>,
    pub options: Vec<String>,
}

impl ResolvConf {
    /// Parse resolv.conf content from a string.
    ///
    /// Empty or nameserver-less content returns an empty resolver list.
    pub fn parse(content: &str) -> Self {
        let mut nameservers = Vec::new();
        let mut search = Vec::new();
        let mut domain = None;
        let mut options = Vec::new();
        let mut global_port = DEFAULT_DNS_PORT;

        for line in content.lines() {
            let line = line.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                continue;
            }

            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.is_empty() {
                continue;
            }

            match parts[0] {
                "nameserver" => {
                    if nameservers.len() >= MAXNS {
                        continue;
                    }
                    if let Some(addr) = parts.get(1).and_then(|s| s.parse::<IpAddr>().ok()) {
                        nameservers.push(Nameserver {
                            addr,
                            port: global_port,
                        });
                    }
                }
                "port" => {
                    if let Some(p) = parts.get(1).and_then(|s| s.parse::<u16>().ok()) {
                        global_port = p;
                        for ns in &mut nameservers {
                            ns.port = p;
                        }
                    }
                }
                "domain" => {
                    if let Some(d) = parts.get(1) {
                        domain = Some(d.to_string());
                    }
                }
                "search" => {
                    search = parts[1..].iter().map(|s| s.to_string()).collect();
                }
                "options" => {
                    options = parts[1..].iter().map(|s| s.to_string()).collect();
                }
                _ => {}
            }
        }

        let conf = Self {
            nameservers,
            search,
            domain,
            options,
        };

        conf
    }

    /// Return nameservers as `host:port` strings suitable for resolver clients.
    pub fn server_addrs(&self) -> Vec<String> {
        self.nameservers
            .iter()
            .map(|ns| format!("{}:{}", ns.addr, ns.port))
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    #[test]
    fn parse_typical_resolv_conf() {
        let content = r#"# Generated by NetworkManager
search example.com local
nameserver 192.168.1.1
nameserver 10.0.0.1
nameserver 8.8.4.4
"#;
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.nameservers.len(), 3);
        assert_eq!(conf.nameservers[0].addr.to_string(), "192.168.1.1");
        assert_eq!(conf.nameservers[0].port, 53);
        assert_eq!(conf.search, vec!["example.com", "local"]);
        assert!(conf.domain.is_none());
    }

    #[test]
    fn parse_with_port_directive() {
        let content = r#"port 5353
nameserver 127.0.0.53
"#;
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.nameservers.len(), 1);
        assert_eq!(conf.nameservers[0].addr.to_string(), "127.0.0.53");
        assert_eq!(conf.nameservers[0].port, 5353);
    }

    #[test]
    fn parse_ipv6_nameserver() {
        let conf = ResolvConf::parse("nameserver ::1\n");
        assert_eq!(conf.nameservers.len(), 1);
        assert_eq!(conf.nameservers[0].addr.to_string(), "::1");
    }

    #[test]
    fn parse_ignores_extra_nameservers() {
        let content =
            "nameserver 1.1.1.1\nnameserver 2.2.2.2\nnameserver 3.3.3.3\nnameserver 4.4.4.4\n";
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.nameservers.len(), 3);
    }

    #[test]
    fn empty_content_has_no_nameservers() {
        let conf = ResolvConf::parse("");
        assert!(conf.nameservers.is_empty());
    }

    #[test]
    fn server_addrs_format() {
        let content = "nameserver 192.168.1.1\nnameserver 10.0.0.1\n";
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.server_addrs(), vec!["192.168.1.1:53", "10.0.0.1:53"]);
    }
}
