[package]
name = "edgerun-evdev-input"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-encoding = { path = "../edgerun-encoding" }
edgerun-input = { path = "../edgerun-input" }
edgerun-linux-sysfs = { path = "../edgerun-linux-sysfs" }

[target.'cfg(not(target_os = "none"))'.dependencies]
libc.workspace = true

[features]
std = []

[[bin]]
name = "evdev_input_tool"
path = "src/bin/evdev-input-tool.rs"
required-features = ["std"]

[lints]
workspace = true
