//! Fuzz target for ResizeType (from css_ui.proto)
//!
//! Generated by scripts/generate_fuzz_corpus.py
//! DO NOT EDIT.

#![no_main]

use libfuzzer_sys::fuzz_target;

/// Valid discriminants for ResizeType
const VALID_VALUES: &[i32] = &[0, 1, 2, 3, 4, 5, 6];
const MIN_VALUE: i32 = 0;
const MAX_VALUE: i32 = 6;

fuzz_target!(|data: &[u8]| {
    if data.len() < 4 { return; }
    
    // Interpret first 4 bytes as i32 (little-endian)
    let val = i32::from_le_bytes([data[0], data[1], data[2], data[3]]);
    
    // Test 1: is it a valid discriminant?
    let is_valid = VALID_VALUES.contains(&val);
    
    // Test 2: boundary checks
    let in_range = val >= MIN_VALUE && val <= MAX_VALUE;
    
    // Test 3: edge cases that should always be valid
    let zero_is_valid = VALID_VALUES.contains(&0);
    
    // Report findings (fuzzer uses these for coverage)
    if is_valid {
        let _ = in_range; // always true if is_valid
    }
    
    // Test 4: out-of-range values should NOT be valid
    if !in_range {
        assert!(!is_valid, "value {} is out of range but claimed valid", val);
    }
    
    // Test 5: known valid values should always be recognized
    for &v in VALID_VALUES {
        assert!(VALID_VALUES.contains(&v));
    }
});
