//! Fuzz target for CssValueType (from css_value_types.proto)
//!
//! Generated by scripts/generate_fuzz_corpus.py
//! DO NOT EDIT.

#![no_main]

use libfuzzer_sys::fuzz_target;

/// Valid discriminants for CssValueType
const VALID_VALUES: &[i32] = &[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66];
const MIN_VALUE: i32 = 0;
const MAX_VALUE: i32 = 66;

fuzz_target!(|data: &[u8]| {
    if data.len() < 4 { return; }
    
    // Interpret first 4 bytes as i32 (little-endian)
    let val = i32::from_le_bytes([data[0], data[1], data[2], data[3]]);
    
    // Test 1: is it a valid discriminant?
    let is_valid = VALID_VALUES.contains(&val);
    
    // Test 2: boundary checks
    let in_range = val >= MIN_VALUE && val <= MAX_VALUE;
    
    // Test 3: edge cases that should always be valid
    let zero_is_valid = VALID_VALUES.contains(&0);
    
    // Report findings (fuzzer uses these for coverage)
    if is_valid {
        let _ = in_range; // always true if is_valid
    }
    
    // Test 4: out-of-range values should NOT be valid
    if !in_range {
        assert!(!is_valid, "value {} is out of range but claimed valid", val);
    }
    
    // Test 5: known valid values should always be recognized
    for &v in VALID_VALUES {
        assert!(VALID_VALUES.contains(&v));
    }
});
