[package]
name = "edgerun-tcl-ac"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "TCL air conditioner integration support for Edgerun"

[dependencies]
edgerun-capabilities = { version = "0.1", path = "../capability/edgerun-capabilities" }
edgerun-bluetooth-gatt = { version = "0.1", path = "../linux-adapters/edgerun-bluetooth-gatt" }
edgerun-matter = { version = "0.1", path = "../edgerun-matter" }
edgerun-crypto = { version = "0.1", path = "../utility/edgerun-crypto", default-features = false, features = ["hmac"] }
aes = "0.8"

[lints]
workspace = true
