[package]
name = "edgerun-schemars"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun shim for schemars"

[dependencies]
edgerun-schemars-derive = { path = "../edgerun-schemars-derive" }
serde = { package = "edgerun-serde", path = "../edgerun-serde", features = ["derive", "std"] }

[features]
chrono04 = []

[lints]
workspace = true
