[package]
name = "edgerun-codelyzer"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
autobins = false

[lib]
crate-type = ["rlib"]

[[bin]]
name = "edgerun-apk-api-calls"
path = "src/bin/apk_api_calls.rs"

[features]
default = ["std", "lang-rust"]
std = ["edgerun-vfs?/std"]
lang-rust = []
lang-typescript = []
lang-c = []
lang-python = []
lang-go = []
lang-java = []
lang-javascript = []
mount = ["vfs"]
vfs = ["dep:edgerun-vfs"]
wire-rkyv = ["dep:rkyv"]

[dependencies]
edgerun-json = { workspace = true, features = ["toml"] }
edgerun-encoding = { workspace = true, features = ["compression"] }
edgerun-vfs = { workspace = true, optional = true }
rkyv = { workspace = true, features = ["std", "bytecheck"], optional = true }
