  (import "edgerun" "STATUS_OK" (global $OK i32))
  (memory (export "memory") 33)
  (global (export "cache_index_data_ptr") i32 (i32.const 0))
  (global (export "cache_index_data_len") i32 (i32.const 8))
  (global (export "cache_index_cursor") i32 (i32.const 16))
  (global (export "cache_index_end") i32 (i32.const 24))
  (global (export "cache_index_rows") i32 (i32.const 32))
  (global (export "cache_index_id") i32 (i32.const 2097184))
  (global (export "cache_index_protocol") i32 (i32.const 2097188))
  (global (export "cache_index_flags") i32 (i32.const 2097192))
  (global (export "cache_index_revision") i32 (i32.const 2097196))
  (global (export "cache_index_archive_count") i32 (i32.const 2097200))
  (global (export "cache_index_total_files") i32 (i32.const 2097204))
  (global (export "cache_index_max_files") i32 (i32.const 2097208))
  (global (export "cache_index_error") i32 (i32.const 2097212))
  (global $ERR_BOUNDS i32 (i32.const -1))
  (global $ERR_PROTOCOL i32 (i32.const -2))
  (global $ERR_CAPACITY i32 (i32.const -3))
  (global $ERR_FLAGS i32 (i32.const -4))
  (global $MAX_ROWS i32 (i32.const 65536))
  (global $ROW_SIZE i32 (i32.const 32))
  (global $RA i32 (i32.const 0))
  (global $RNH i32 (i32.const 4))
  (global $RCRC i32 (i32.const 8))
  (global $RCS i32 (i32.const 12))
  (global $RDS i32 (i32.const 16))
  (global $RREV i32 (i32.const 20))
  (global $RFC i32 (i32.const 24))
  (global $RFO i32 (i32.const 28))

  (func $read_u8 (result i32)
    (local $ptr i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (if (i32.ge_u (local.get $ptr) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS))
        (return (global.get $ERR_BOUNDS))
      )
    )
    (i32.store (i32.const 16) (i32.add (local.get $ptr) (i32.const 1)))
    (i32.load8_u (local.get $ptr))
  )

  (func $read_u16 (result i32)
    (local $ptr i32) (local $next i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (local.set $next (i32.add (local.get $ptr) (i32.const 2)))
    (if (i32.gt_u (local.get $next) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS))
        (return (global.get $ERR_BOUNDS))
      )
    )
    (i32.store (i32.const 16) (local.get $next))
    (i32.or
      (i32.shl (i32.load8_u (local.get $ptr)) (i32.const 8))
      (i32.load8_u (i32.add (local.get $ptr) (i32.const 1)))
    )
  )

  (func $read_u32 (result i32)
    (local $ptr i32) (local $next i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (local.set $next (i32.add (local.get $ptr) (i32.const 4)))
    (if (i32.gt_u (local.get $next) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS))
        (return (global.get $ERR_BOUNDS))
      )
    )
    (i32.store (i32.const 16) (local.get $next))
    (i32.or
      (i32.or
        (i32.or
          (i32.shl (i32.load8_u (local.get $ptr)) (i32.const 24))
          (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 1))) (i32.const 16))
        )
        (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 2))) (i32.const 8))
      )
      (i32.load8_u (i32.add (local.get $ptr) (i32.const 3)))
    )
  )

  (func $read_big_smart (result i32)
    (local $ptr i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (if (i32.ge_u (local.get $ptr) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS))
        (return (global.get $ERR_BOUNDS))
      )
    )
    (if (i32.lt_u (i32.load8_u (local.get $ptr)) (i32.const 128))
      (then (return (call $read_u16)))
    )
    (i32.and (call $read_u32) (i32.const 0x7fffffff))
  )

  (func (export "cache_index_get_summary") (result i32)
    (i32.const 2097184)
  )

  (func (export "cache_index_get_row_table") (result i32 i32)
    (i32.const 32)
    (i32.load (i32.const 2097200))
  )

  (func (export "cache_index_region_archive_id") (param $x i32) (param $y i32) (result i32)
    (i32.or (i32.shl (local.get $x) (i32.const 8)) (i32.and (local.get $y) (i32.const 255)))
  )

  (func (export "cache_index_parse_protocol7") (param $data i32) (param $len i32) (param $index_id i32) (result i32)
    (local $v i32) (local $row_count i32) (local $row_idx i32) (local $cumulative i32) (local $row_ptr i32) (local $file_count i32) (local $file_idx i32)
    (if (i32.eqz (local.get $data))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS))
        (return (global.get $ERR_BOUNDS))
      )
    )
    (if (i32.lt_u (local.get $len) (i32.const 4))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS))
        (return (global.get $ERR_BOUNDS))
      )
    )
    (i32.store (i32.const 0) (local.get $data))
    (i32.store (i32.const 8) (local.get $len))
    (i32.store (i32.const 16) (local.get $data))
    (i32.store (i32.const 24) (i32.add (local.get $data) (local.get $len)))
    (i32.store (i32.const 2097184) (local.get $index_id))
    (i32.store (i32.const 2097200) (i32.const 0))
    (i32.store (i32.const 2097204) (i32.const 0))
    (i32.store (i32.const 2097208) (i32.const 0))
    (i32.store (i32.const 2097212) (global.get $OK))
    (local.set $v (call $read_u8))
    (if (i32.lt_s (local.get $v) (i32.const 0))
      (then (return (local.get $v)))
    )
    (i32.store (i32.const 2097188) (local.get $v))
    (if (i32.ne (local.get $v) (i32.const 7))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_PROTOCOL))
        (return (global.get $ERR_PROTOCOL))
      )
    )
    (local.set $v (call $read_u32))
    (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
      (then (return (i32.load (i32.const 2097212))))
    )
    (i32.store (i32.const 2097196) (local.get $v))
    (local.set $v (call $read_u8))
    (if (i32.lt_s (local.get $v) (i32.const 0))
      (then (return (local.get $v)))
    )
    (i32.store (i32.const 2097192) (local.get $v))
    (if (i32.and (local.get $v) (i32.const 250))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_FLAGS))
        (return (global.get $ERR_FLAGS))
      )
    )
    (local.set $v (call $read_big_smart))
    (if (i32.lt_s (local.get $v) (i32.const 0))
      (then (return (local.get $v)))
    )
    (if (i32.gt_u (local.get $v) (global.get $MAX_ROWS))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_CAPACITY))
        (return (global.get $ERR_CAPACITY))
      )
    )
    (i32.store (i32.const 2097200) (local.get $v))
    (local.set $row_count (local.get $v))

    (local.set $row_idx (i32.const 0))
    (local.set $cumulative (i32.const 0))
    (block $b_ids
      (loop $l_ids
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_ids))
        )
        (local.set $v (call $read_big_smart))
        (if (i32.lt_s (local.get $v) (i32.const 0))
          (then (return (local.get $v)))
        )
        (local.set $cumulative (i32.add (local.get $cumulative) (local.get $v)))
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (local.get $row_ptr) (local.get $cumulative))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RNH)) (i32.const 0))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RCS)) (i32.const 0))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RDS)) (i32.const 0))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RFO)) (i32.const 0))
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_ids)
      )
    )

    (if (i32.and (i32.load (i32.const 2097192)) (i32.const 1))
      (then
        (local.set $row_idx (i32.const 0))
        (block $b_nm
          (loop $l_nm
            (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
              (then (br $b_nm))
            )
            (local.set $v (call $read_u32))
            (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
              (then (return (i32.load (i32.const 2097212))))
            )
            (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
            (i32.store (i32.add (local.get $row_ptr) (global.get $RNH)) (local.get $v))
            (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
            (br $l_nm)
          )
        )
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_crc
      (loop $l_crc
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_crc))
        )
        (local.set $v (call $read_u32))
        (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
          (then (return (i32.load (i32.const 2097212))))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RCRC)) (local.get $v))
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_crc)
      )
    )

    (if (i32.and (i32.load (i32.const 2097192)) (i32.const 4))
      (then
        (local.set $row_idx (i32.const 0))
        (block $b_sz
          (loop $l_sz
            (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
              (then (br $b_sz))
            )
            (local.set $v (call $read_u32))
            (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
              (then (return (i32.load (i32.const 2097212))))
            )
            (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
            (i32.store (i32.add (local.get $row_ptr) (global.get $RCS)) (local.get $v))
            (local.set $v (call $read_u32))
            (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
              (then (return (i32.load (i32.const 2097212))))
            )
            (i32.store (i32.add (local.get $row_ptr) (global.get $RDS)) (local.get $v))
            (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
            (br $l_sz)
          )
        )
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_rev
      (loop $l_rev
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_rev))
        )
        (local.set $v (call $read_u32))
        (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
          (then (return (i32.load (i32.const 2097212))))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RREV)) (local.get $v))
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_rev)
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_fc
      (loop $l_fc
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_fc))
        )
        (local.set $v (call $read_big_smart))
        (if (i32.lt_s (local.get $v) (i32.const 0))
          (then (return (local.get $v)))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RFC)) (local.get $v))
        (i32.store (i32.const 2097204) (i32.add (i32.load (i32.const 2097204)) (local.get $v)))
        (if (i32.gt_u (local.get $v) (i32.load (i32.const 2097208)))
          (then (i32.store (i32.const 2097208) (local.get $v)))
        )
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_fc)
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_fid
      (loop $l_fid
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_fid))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store
          (i32.add (local.get $row_ptr) (global.get $RFO))
          (i32.sub (i32.load (i32.const 16)) (i32.load (i32.const 0)))
        )
        (local.set $file_count (i32.load (i32.add (local.get $row_ptr) (global.get $RFC))))
        (local.set $file_idx (i32.const 0))
        (block $b_fid_in
          (loop $l_fid_in
            (if (i32.ge_u (local.get $file_idx) (local.get $file_count))
              (then (br $b_fid_in))
            )
            (local.set $v (call $read_big_smart))
            (if (i32.lt_s (local.get $v) (i32.const 0))
              (then (return (local.get $v)))
            )
            (local.set $file_idx (i32.add (local.get $file_idx) (i32.const 1)))
            (br $l_fid_in)
          )
        )
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_fid)
      )
    )

    (if (i32.and (i32.load (i32.const 2097192)) (i32.const 1))
      (then
        (local.set $row_idx (i32.const 0))
        (block $b_fnh
          (loop $l_fnh
            (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
              (then (br $b_fnh))
            )
            (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
            (local.set $file_count (i32.load (i32.add (local.get $row_ptr) (global.get $RFC))))
            (local.set $file_idx (i32.const 0))
            (block $b_fnh_in
              (loop $l_fnh_in
                (if (i32.ge_u (local.get $file_idx) (local.get $file_count))
                  (then (br $b_fnh_in))
                )
                (local.set $v (call $read_u32))
                (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
                  (then (return (i32.load (i32.const 2097212))))
                )
                (local.set $file_idx (i32.add (local.get $file_idx) (i32.const 1)))
                (br $l_fnh_in)
              )
            )
            (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
            (br $l_fnh)
          )
        )
      )
    )

    (i32.const 0)
  )

  (func (export "cache_index_find_archive") (param $archive_id i32) (result i32 i32)
    (local $count i32) (local $idx i32) (local $ptr i32)
    (local.set $count (i32.load (i32.const 2097200)))
    (local.set $idx (i32.const 0))
    (local.set $ptr (i32.const 32))
    (loop $l_fa
      (if (i32.ge_u (local.get $idx) (local.get $count))
        (then (return (i32.const 0) (i32.const 0)))
      )
      (if (i32.eq (i32.load (local.get $ptr)) (local.get $archive_id))
        (then (return (local.get $ptr) (local.get $idx)))
      )
      (local.set $ptr (i32.add (local.get $ptr) (global.get $ROW_SIZE)))
      (local.set $idx (i32.add (local.get $idx) (i32.const 1)))
      (br $l_fa)
    )
    (unreachable)
  )

  (func (export "cache_index_find_name_hash") (param $name_hash i32) (result i32 i32)
    (local $count i32) (local $idx i32) (local $ptr i32)
    (local.set $count (i32.load (i32.const 2097200)))
    (local.set $idx (i32.const 0))
    (local.set $ptr (i32.const 32))
    (loop $l_fh
      (if (i32.ge_u (local.get $idx) (local.get $count))
        (then (return (i32.const 0) (i32.const 0)))
      )
      (if (i32.eq (i32.load (i32.add (local.get $ptr) (global.get $RNH))) (local.get $name_hash))
        (then (return (local.get $ptr) (local.get $idx)))
      )
      (local.set $ptr (i32.add (local.get $ptr) (global.get $ROW_SIZE)))
      (local.set $idx (i32.add (local.get $idx) (i32.const 1)))
      (br $l_fh)
    )
    (unreachable)
  )
