(module
  (import "edgerun-core" "memory" (memory 1))
(func (export "proto_standard_id") (result i32)
    i32.const 300034)

  (func $m83read_u16_be (param $ptr i32) (result i32)
    (i32.or
      (i32.shl (i32.load8_u (local.get $ptr)) (i32.const 8))
      (i32.load8_u (i32.add (local.get $ptr) (i32.const 1)))))

  (func $m83read_u32_be (param $ptr i32) (result i32)
    (i32.or
      (i32.or
        (i32.shl (i32.load8_u (local.get $ptr)) (i32.const 24))
        (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 1))) (i32.const 16)))
      (i32.or
        (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 2))) (i32.const 8))
        (i32.load8_u (i32.add (local.get $ptr) (i32.const 3))))))

  ;; Status values: 0 ok, 1 input_short, 3 invalid, 6 too_long.
  (func $name_len (param $ptr i32) (param $msg_len i32) (param $start i32) (result i64)
    (local $pos i32)
    (local $len i32)
    (local $target i32)
    (local $consumed i32)
    (local $jumped i32)
    (local $hops i32)
    (local $name_len i32)
    (if (i32.ge_u (local.get $start) (local.get $msg_len))
      (then (return (i64.const 1))))
    (local.set $pos (local.get $start))
    (loop $scan
      (if (i32.ge_u (local.get $pos) (local.get $msg_len))
        (then (return (i64.const 1))))
      (local.set $len (i32.load8_u (i32.add (local.get $ptr) (local.get $pos))))
      (if (i32.eqz (local.get $len))
        (then
          (if (i32.eqz (local.get $jumped))
            (then (local.set $consumed (i32.add (local.get $consumed) (i32.const 1)))))
          (return
            (i64.or
              (i64.extend_i32_u (i32.const 0))
              (i64.shl (i64.extend_i32_u (local.get $consumed)) (i64.const 32))))))
      (if (i32.eq (i32.and (local.get $len) (i32.const 0xc0)) (i32.const 0xc0))
        (then
          (if (i32.ge_u (i32.add (local.get $pos) (i32.const 1)) (local.get $msg_len))
            (then (return (i64.const 1))))
          (local.set $target
            (i32.or
              (i32.shl (i32.and (local.get $len) (i32.const 0x3f)) (i32.const 8))
              (i32.load8_u (i32.add (i32.add (local.get $ptr) (local.get $pos)) (i32.const 1)))))
          (if (i32.ge_u (local.get $target) (local.get $msg_len))
            (then (return (i64.const 3))))
          (if (i32.eq (local.get $target) (local.get $pos))
            (then (return (i64.const 3))))
          (if (i32.eqz (local.get $jumped))
            (then
              (local.set $consumed (i32.add (local.get $consumed) (i32.const 2)))
              (local.set $jumped (i32.const 1))))
          (local.set $hops (i32.add (local.get $hops) (i32.const 1)))
          (if (i32.gt_u (local.get $hops) (i32.const 16))
            (then (return (i64.const 3))))
          (local.set $pos (local.get $target))
          (br $scan)))
      (if (i32.ne (i32.and (local.get $len) (i32.const 0xc0)) (i32.const 0))
        (then (return (i64.const 3))))
      (if (i32.gt_u (local.get $len) (i32.const 63))
        (then (return (i64.const 3))))
      (if (i32.gt_u (i32.add (i32.add (local.get $pos) (i32.const 1)) (local.get $len)) (local.get $msg_len))
        (then (return (i64.const 1))))
      (local.set $name_len
        (i32.add
          (local.get $name_len)
          (i32.add (local.get $len) (i32.const 1))))
      (if (i32.gt_u (local.get $name_len) (i32.const 255))
        (then (return (i64.const 6))))
      (if (i32.eqz (local.get $jumped))
        (then
          (local.set $consumed
            (i32.add (local.get $consumed) (i32.add (local.get $len) (i32.const 1))))))
      (local.set $pos (i32.add (i32.add (local.get $pos) (i32.const 1)) (local.get $len)))
      (br $scan))
    (i64.const 3))

  ;; Question record: name_start, name_wire_len, qtype, qclass, next_offset.
  (func $dns_question_next (export "dns_question_next")
    (param $ptr i32) (param $msg_len i32) (param $start i32) (param $out_ptr i32)
    (result i32)
    (local $packed i64)
    (local $status i32)
    (local $name_wire_len i32)
    (local $pos i32)
    (local.set $packed (call $name_len (local.get $ptr) (local.get $msg_len) (local.get $start)))
    (local.set $status (i32.wrap_i64 (local.get $packed)))
    (if (i32.ne (local.get $status) (i32.const 0))
      (then (return (local.get $status))))
    (local.set $name_wire_len (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (local.set $pos (i32.add (local.get $start) (local.get $name_wire_len)))
    (if (i32.gt_u (i32.add (local.get $pos) (i32.const 4)) (local.get $msg_len))
      (then (return (i32.const 1))))
    (i32.store (local.get $out_ptr) (local.get $start))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 4)) (local.get $name_wire_len))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 8)) (call $m83read_u16_be (i32.add (local.get $ptr) (local.get $pos))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 12)) (call $m83read_u16_be (i32.add (i32.add (local.get $ptr) (local.get $pos)) (i32.const 2))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 16)) (i32.add (local.get $pos) (i32.const 4)))
    (i32.const 0))

  ;; RR record: name_start, name_wire_len, type, class, ttl, rdlen, rdata_start, next_offset, is_opt.
  (func $dns_rr_next (export "dns_rr_next")
    (param $ptr i32) (param $msg_len i32) (param $start i32) (param $out_ptr i32)
    (result i32)
    (local $packed i64)
    (local $status i32)
    (local $name_wire_len i32)
    (local $pos i32)
    (local $typ i32)
    (local $rdlen i32)
    (local $rdata i32)
    (local $next i32)
    (local.set $packed (call $name_len (local.get $ptr) (local.get $msg_len) (local.get $start)))
    (local.set $status (i32.wrap_i64 (local.get $packed)))
    (if (i32.ne (local.get $status) (i32.const 0))
      (then (return (local.get $status))))
    (local.set $name_wire_len (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (local.set $pos (i32.add (local.get $start) (local.get $name_wire_len)))
    (if (i32.gt_u (i32.add (local.get $pos) (i32.const 10)) (local.get $msg_len))
      (then (return (i32.const 1))))
    (local.set $typ (call $m83read_u16_be (i32.add (local.get $ptr) (local.get $pos))))
    (local.set $rdlen (call $m83read_u16_be (i32.add (i32.add (local.get $ptr) (local.get $pos)) (i32.const 8))))
    (local.set $rdata (i32.add (local.get $pos) (i32.const 10)))
    (local.set $next (i32.add (local.get $rdata) (local.get $rdlen)))
    (if (i32.gt_u (local.get $next) (local.get $msg_len))
      (then (return (i32.const 1))))
    (i32.store (local.get $out_ptr) (local.get $start))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 4)) (local.get $name_wire_len))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 8)) (local.get $typ))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 12)) (call $m83read_u16_be (i32.add (i32.add (local.get $ptr) (local.get $pos)) (i32.const 2))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 16)) (call $m83read_u32_be (i32.add (i32.add (local.get $ptr) (local.get $pos)) (i32.const 4))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 20)) (local.get $rdlen))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 24)) (local.get $rdata))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 28)) (local.get $next))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 32)) (i32.eq (local.get $typ) (i32.const 41)))
    (i32.const 0))

  ;; Summary record: q_start, q_end, an_start, an_end, ns_start, ns_end,
  ;; ar_start, ar_end, q_count, rr_count, opt_count, error_offset.
  (func (export "dns_section_walk")
    (param $ptr i32) (param $msg_len i32) (param $out_ptr i32) (param $out_cap i32)
    (result i32)
    (local $qd i32) (local $an i32) (local $ns i32) (local $ar i32)
    (local $pos i32) (local $i i32) (local $status i32) (local $tmp i32)
    (local $an_start i32) (local $ns_start i32) (local $ar_start i32)
    (local $opt_count i32)
    (if (i32.lt_u (local.get $out_cap) (i32.const 48))
      (then (return (i32.const 2))))
    (if (i32.lt_u (local.get $msg_len) (i32.const 12))
      (then
        (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (local.get $msg_len))
        (return (i32.const 1))))
    (local.set $qd (call $m83read_u16_be (i32.add (local.get $ptr) (i32.const 4))))
    (local.set $an (call $m83read_u16_be (i32.add (local.get $ptr) (i32.const 6))))
    (local.set $ns (call $m83read_u16_be (i32.add (local.get $ptr) (i32.const 8))))
    (local.set $ar (call $m83read_u16_be (i32.add (local.get $ptr) (i32.const 10))))
    (if (i32.or
          (i32.gt_u (local.get $qd) (i32.const 16))
          (i32.or
            (i32.gt_u (local.get $an) (i32.const 256))
            (i32.or (i32.gt_u (local.get $ns) (i32.const 256)) (i32.gt_u (local.get $ar) (i32.const 256)))))
      (then
        (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (i32.const 12))
        (return (i32.const 3))))
    (local.set $pos (i32.const 12))
    (i32.store (local.get $out_ptr) (local.get $pos))
    (local.set $tmp (i32.const 8192))
    (local.set $i (i32.const 0))
    (loop $questions
      (if (i32.lt_u (local.get $i) (local.get $qd))
        (then
          (local.set $status (call $dns_question_next (local.get $ptr) (local.get $msg_len) (local.get $pos) (local.get $tmp)))
          (if (i32.ne (local.get $status) (i32.const 0))
            (then
              (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (local.get $pos))
              (return (local.get $status))))
          (local.set $pos (i32.load (i32.add (local.get $tmp) (i32.const 16))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $questions))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 4)) (local.get $pos))
    (local.set $an_start (local.get $pos))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 8)) (local.get $an_start))
    (local.set $i (i32.const 0))
    (loop $answers
      (if (i32.lt_u (local.get $i) (local.get $an))
        (then
          (local.set $status (call $dns_rr_next (local.get $ptr) (local.get $msg_len) (local.get $pos) (local.get $tmp)))
          (if (i32.ne (local.get $status) (i32.const 0))
            (then
              (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (local.get $pos))
              (return (local.get $status))))
          (local.set $pos (i32.load (i32.add (local.get $tmp) (i32.const 28))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $answers))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 12)) (local.get $pos))
    (local.set $ns_start (local.get $pos))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 16)) (local.get $ns_start))
    (local.set $i (i32.const 0))
    (loop $authority
      (if (i32.lt_u (local.get $i) (local.get $ns))
        (then
          (local.set $status (call $dns_rr_next (local.get $ptr) (local.get $msg_len) (local.get $pos) (local.get $tmp)))
          (if (i32.ne (local.get $status) (i32.const 0))
            (then
              (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (local.get $pos))
              (return (local.get $status))))
          (local.set $pos (i32.load (i32.add (local.get $tmp) (i32.const 28))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $authority))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 20)) (local.get $pos))
    (local.set $ar_start (local.get $pos))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 24)) (local.get $ar_start))
    (local.set $i (i32.const 0))
    (loop $additional
      (if (i32.lt_u (local.get $i) (local.get $ar))
        (then
          (local.set $status (call $dns_rr_next (local.get $ptr) (local.get $msg_len) (local.get $pos) (local.get $tmp)))
          (if (i32.ne (local.get $status) (i32.const 0))
            (then
              (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (local.get $pos))
              (return (local.get $status))))
          (local.set $opt_count (i32.add (local.get $opt_count) (i32.load (i32.add (local.get $tmp) (i32.const 32)))))
          (local.set $pos (i32.load (i32.add (local.get $tmp) (i32.const 28))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $additional))))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 28)) (local.get $pos))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 32)) (local.get $qd))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 36)) (i32.add (i32.add (local.get $an) (local.get $ns)) (local.get $ar)))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 40)) (local.get $opt_count))
    (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (i32.const 0))
    (if (i32.ne (local.get $pos) (local.get $msg_len))
      (then
        (i32.store (i32.add (local.get $out_ptr) (i32.const 44)) (local.get $pos))
        (return (i32.const 3))))
    (i32.const 0))
)
