    (import "hpack-qpack" "huff_lookup" (func $huff_lookup (param $code i32) (param $bits i32) (result i32)))
  (import "hpack-qpack" "huffman_decode_internal" (func $huffman_decode_internal (param $in_ptr i32) (param $in_len i32) (param $out_ptr i32) (param $out_cap i32) (param $write i32) (result i64)))

;; Meta record: 0:u32 flags, 4:u32 huffman, 8:u32 consumed, 12:u32 payload_offset, 16:u32 payload_len.
  (func $m154qpack_prefix_decode
    (param $size i32) (param $in_ptr i32) (param $in_len i32) (param $meta_ptr i32)
    (result i32)
    (local $prefix_bits i32)
    (local $mask i32)
    (local $first i32)
    (local $flags i32)
    (local $value i64)
    (local $consumed i32)
    (local $shift i32)
    (local $byte i32)
    (if (i32.or (i32.lt_u (local.get $size) (i32.const 2)) (i32.gt_u (local.get $size) (i32.const 8)))
      (then (return (i32.const 3))))
    (if (i32.eqz (local.get $in_len)) (then (return (i32.const 1))))
    (local.set $prefix_bits (i32.sub (local.get $size) (i32.const 1)))
    (local.set $mask (i32.sub (i32.shl (i32.const 1) (local.get $prefix_bits)) (i32.const 1)))
    (local.set $first (i32.load8_u (local.get $in_ptr)))
    (local.set $flags (i32.shr_u (local.get $first) (local.get $prefix_bits)))
    (local.set $value (i64.extend_i32_u (i32.and (local.get $first) (local.get $mask))))
    (local.set $consumed (i32.const 1))
    (if (i64.eq (local.get $value) (i64.extend_i32_u (local.get $mask)))
      (then
        (loop $again
          (if (i32.ge_u (local.get $consumed) (local.get $in_len)) (then (return (i32.const 1))))
          (if (i32.ge_u (local.get $shift) (i32.const 63)) (then (return (i32.const 4))))
          (local.set $byte (i32.load8_u (i32.add (local.get $in_ptr) (local.get $consumed))))
          (local.set $value
            (i64.add
              (local.get $value)
              (i64.shl
                (i64.extend_i32_u (i32.and (local.get $byte) (i32.const 127)))
                (i64.extend_i32_u (local.get $shift)))))
          (local.set $consumed (i32.add (local.get $consumed) (i32.const 1)))
          (if (i32.eqz (i32.and (local.get $byte) (i32.const 128)))
            (then)
            (else
              (local.set $shift (i32.add (local.get $shift) (i32.const 7)))
              (if (i32.ge_u (local.get $shift) (i32.const 63)) (then (return (i32.const 4))))
              (br $again))))))
    (if (i64.gt_u (local.get $value) (i64.extend_i32_u (i32.sub (local.get $in_len) (local.get $consumed))))
      (then (return (i32.const 1))))
    (i32.store (local.get $meta_ptr) (local.get $flags))
    (i32.store (i32.add (local.get $meta_ptr) (i32.const 4)) (i32.and (local.get $flags) (i32.const 1)))
    (i32.store (i32.add (local.get $meta_ptr) (i32.const 8)) (local.get $consumed))
    (i32.store (i32.add (local.get $meta_ptr) (i32.const 12)) (local.get $consumed))
    (i32.store (i32.add (local.get $meta_ptr) (i32.const 16)) (i32.wrap_i64 (local.get $value)))
    (i32.const 0))

  (func (export "qpack_string_scan")
    (param $size i32) (param $in_ptr i32) (param $in_len i32) (param $meta_ptr i32)
    (result i32)
    (call $m154qpack_prefix_decode (local.get $size) (local.get $in_ptr) (local.get $in_len) (local.get $meta_ptr)))

  (func (export "qpack_string_decode")
    (param $size i32) (param $in_ptr i32) (param $in_len i32) (param $out_ptr i32) (param $out_cap i32) (param $meta_ptr i32)
    (result i64)
    (local $status i32)
    (local $payload_off i32)
    (local $payload_len i32)
    (local $i i32)
    (local $packed i64)
    (local.set $status (call $m154qpack_prefix_decode (local.get $size) (local.get $in_ptr) (local.get $in_len) (local.get $meta_ptr)))
    (if (local.get $status) (then (return (call $pack (local.get $status) (i32.const 0)))))
    (local.set $payload_off (i32.load (i32.add (local.get $meta_ptr) (i32.const 12))))
    (local.set $payload_len (i32.load (i32.add (local.get $meta_ptr) (i32.const 16))))
    (if (i32.load (i32.add (local.get $meta_ptr) (i32.const 4)))
      (then
        (local.set $packed
          (call huffman_decode_internal
            (i32.add (local.get $in_ptr) (local.get $payload_off))
            (local.get $payload_len)
            (local.get $out_ptr)
            (local.get $out_cap)
            (i32.const 1)))
        (return (local.get $packed))))
    (if (i32.gt_u (local.get $payload_len) (local.get $out_cap))
      (then (return (call $pack (i32.const 2) (i32.const 0)))))
    (loop $copy
      (if (i32.ge_u (local.get $i) (local.get $payload_len))
        (then (return (call $pack (i32.const 0) (local.get $payload_len)))))
      (i32.store8
        (i32.add (local.get $out_ptr) (local.get $i))
        (i32.load8_u (i32.add (i32.add (local.get $in_ptr) (local.get $payload_off)) (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $copy))
    (call $pack (i32.const 0) (local.get $payload_len)))
