[package]
name = "edgerun-alsa-speaker"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-speaker = { path = "../edgerun-speaker" }

[dev-dependencies]
edgerun-linux-sysfs = { path = "../edgerun-linux-sysfs" }

[[bin]]
name = "alsa_speaker_tool"
path = "src/bin/alsa-speaker-tool.rs"
required-features = ["std"]

[features]
std = []

[lints]
workspace = true
