;; Base32hex Encode Pipeline Stage — slot 121
  (func $process_base32hex_encode (export "process_base32hex_encode")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $result i64) (local $status i32) (local $written i32)
    (local $read i32)
    (local.set $read (call $stage_read_input (local.get $input) (local.get $scratch) (local.get $scap)))
    (if (i32.eqz (local.get $read)) (then (return (i32.const 0))))
    (local.set $result (call $base32hex_encode (i32.const 0x3000) (local.get $read) (i32.const 0x4000) (i32.const 8192)))
    (local.set $status (i32.wrap_i64 (i64.and (local.get $result) (i64.const 0xffffffff))))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (drop (call $pipe_write (local.get $output) (i32.const 0x4000) (local.get $written)))
    local.get $written)
