
;; Process bracket_list_next Stage — slot 137
  (func $process_bracket_list_next (export "process_bracket_list_next")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $read i32) (local $result i64) (local $status i32) (local $written i32)
    (local $offset i32)
    (local.set $read (call $stage_read_input (local.get $input) (local.get $scratch) (local.get $scap)))
    (if (i32.eqz (local.get $read)) (then (return (i32.const 0))))
        (local.set $offset (i32.load (global.get $SCRATCH_BUF)))
    (local.set $result (call $bracket_list_next (i32.add (global.get $SCRATCH_BUF) (i32.const 4)) (i32.sub (local.get $read) (i32.const 4)) (local.get $offset) (local.get $scratch) ((i32.sub (local.get $scap) (i32.const 8)))))
    (local.set $status (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (local.set $written (i32.wrap_i64 (local.get $result)))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (local.get $written)))
    local.get $written)
