;; Bracket List Next Stage — slot 137
  (func $process_bracket_list_next (export "process_bracket_list_next")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32) (local $read i32) (local $result i64) (local $offset i32)
    (local $status i32) (local $next_offset i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.lt_u (local.get $read) (i32.const 5)) (then (return (i32.const 0))))
    (drop (call $pipe_read (local.get $input) (i32.const 0x3000) (local.get $read)))
    (local.set $offset (i32.load (i32.const 0x3000)))
    (local.set $result (call $bracket_list_next (i32.add (i32.const 0x3000) (i32.const 4)) (i32.sub (local.get $read) (i32.const 4)) (local.get $offset) (local.get $scratch)))
    (local.set $status (i32.wrap_i64 (i64.and (local.get $result) (i64.const 0xffffffff))))
    (local.set $next_offset (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (i32.store (i32.add (local.get $scratch) (i32.const 8)) (local.get $next_offset))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (i32.const 12)))
    i32.const 12)
