
;; Process dns_header_encode Stage — slot 60
  (func $process_dns_header_encode (export "process_dns_header_encode")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $read i32) (local $result i64) (local $status i32) (local $written i32)
    (local $id i32)
    (local $flags i32)
    (local $qd i32)
    (local $an i32)
    (local $ns i32)
    (local $ar i32)
    (local.set $read (call $stage_read_input (local.get $input) (local.get $scratch) (local.get $scap)))
    (if (i32.eqz (local.get $read)) (then (return (i32.const 0))))
        (local.set $id (i32.load (global.get $SCRATCH_BUF)))
    (local.set $flags (i32.load offset=4 (global.get $SCRATCH_BUF)))
    (local.set $qd (i32.load offset=8 (global.get $SCRATCH_BUF)))
    (local.set $an (i32.load offset=12 (global.get $SCRATCH_BUF)))
    (local.set $ns (i32.load offset=16 (global.get $SCRATCH_BUF)))
    (local.set $ar (i32.load offset=20 (global.get $SCRATCH_BUF)))
    (local.set $result (call $dns_header_encode (local.get $id) (local.get $flags) (local.get $qd) (local.get $an) (local.get $ns) (local.get $ar) (local.get $scratch) (local.get $scap)))
    (local.set $status (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (local.set $written (i32.wrap_i64 (local.get $result)))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (local.get $written)))
    local.get $written)
