
;; Process dns_question_next Stage — slot 71
  (func $process_dns_question_next (export "process_dns_question_next")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $status i32)
    (local $start i32)
    (local $read i32)
    (local.set $read (call $stage_read_input (local.get $input) (local.get $scratch) (local.get $scap)))
    (if (i32.lt_u (local.get $read) (i32.const 8)) (then (return (i32.const 0))))
        (local.set $start (i32.load (global.get $SCRATCH_BUF)))
    (local.set $status (call $dns_question_next (i32.add (global.get $SCRATCH_BUF) (i32.const 4)) (i32.sub (local.get $read) (i32.const 4)) (local.get $start) (local.get $scratch)))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (i32.const 20)))
    i32.const 20)
