
;; Process endian_read Stage — slot 73
  (func $process_endian_read (export "process_endian_read")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $status i32)
    (local $offset i32)
    (local $width i32)
    (local $endian i32)
    (local $signed i32)
    (local $read i32)
    (local.set $read (call $stage_read_input (local.get $input) (local.get $scratch) (local.get $scap)))
    (if (i32.lt_u (local.get $read) (i32.const 20)) (then (return (i32.const 0))))
        (local.set $offset (i32.load (global.get $SCRATCH_BUF)))
    (local.set $width (i32.load (i32.add (global.get $SCRATCH_BUF) (i32.const 4))))
    (local.set $endian (i32.load (i32.add (global.get $SCRATCH_BUF) (i32.const 8))))
    (local.set $signed (i32.load (i32.add (global.get $SCRATCH_BUF) (i32.const 12))))
    (local.set $status (call $endian_read (i32.add (global.get $SCRATCH_BUF) (i32.const 16)) (i32.sub (local.get $read) (i32.const 16)) (local.get $offset) (local.get $width) (local.get $endian) (local.get $signed) (local.get $scratch)))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (i32.const 8)))
    i32.const 8)
