
;; Process endian_write Stage — slot 74
  (func $process_endian_write (export "process_endian_write")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $read i32) (local $result i64) (local $status i32) (local $written i32)    (local $val_lo i32)
    (local $val_hi i32)
    (local $width i32)
    (local $endian i32)
    (local $out_len i32)
    (local.set $read (call $stage_read_input (local.get $input) (local.get $scratch) (local.get $scap)))
    (if (i32.eqz (local.get $read)) (then (return (i32.const 0))))
        (if (i32.ge_u (local.get $clen) (i32.const 4)) (then (local.set $val_lo (i32.load (local.get $cfg)))))
    (if (i32.ge_u (local.get $clen) (i32.const 8)) (then (local.set $val_hi (i32.load offset=4 (local.get $cfg)))))
    (if (i32.ge_u (local.get $clen) (i32.const 12)) (then (local.set $width (i32.load offset=8 (local.get $cfg)))))
    (if (i32.ge_u (local.get $clen) (i32.const 16)) (then (local.set $endian (i32.load offset=12 (local.get $cfg)))))
    (local.set $val_lo (i32.load (global.get $SCRATCH_BUF)))
    (local.set $val_hi (i32.load (i32.add (global.get $SCRATCH_BUF) (i32.const 4))))
    (local.set $width (i32.load (i32.add (global.get $SCRATCH_BUF) (i32.const 8))))
    (local.set $endian (i32.load (i32.add (global.get $SCRATCH_BUF) (i32.const 12))))
    (local.set $result (call $endian_write (local.get $val_lo) (local.get $val_hi) (local.get $width) (local.get $endian) (local.get $scratch) (local.get $scap)))
    (local.set $status (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (local.set $written (i32.wrap_i64 (local.get $result)))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (local.get $written)))
    local.get $written)
