;; HTTP Find CRLF Boundary Stage — slot 127
  (func $process_http_find_crlf (export "process_http_find_crlf")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32) (local $read i32) (local $result i64)
    (local $start i32) (local $offset i32) (local $flags i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.lt_u (local.get $read) (i32.const 5)) (then (return (i32.const 0))))
    (drop (call $pipe_read (local.get $input) (i32.const 0x3000) (local.get $read)))
    (local.set $start (i32.load (i32.const 0x3000)))
    (local.set $result (call $http_find_crlf (i32.add (i32.const 0x3000) (i32.const 4)) (i32.sub (local.get $read) (i32.const 4)) (local.get $start)))
    (local.set $offset (i32.wrap_i64 (i64.and (local.get $result) (i64.const 0xffffffff))))
    (local.set $flags (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (i32.store (local.get $scratch) (local.get $offset))
    (i32.store (i32.add (local.get $scratch) (i32.const 4)) (i32.and (local.get $flags) (i32.const 1)))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (i32.const 8)))
    i32.const 8)
