;; OAuth JSON Value Extract Stage — slot 116
  ;; Config: key pointer + key length (8 bytes at cfg)
  (func $process_oauth_json_value (export "process_oauth_json_value")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32) (local $read i32) (local $cap i32) (local $key_len i32)
    (local $result i64) (local $status i32) (local $written i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.eqz (local.get $read)) (then (return (i32.const 0))))
    (drop (call $pipe_read (local.get $input) (i32.const 0x3000) (local.get $read)))
    (local.set $cap (i32.sub (local.get $scap) (i32.const 8)))
    (local.set $key_len (i32.load (i32.add (local.get $cfg) (i32.const 4))))
    (local.set $result (call $oauth_json_value
      (i32.const 0x3000) (local.get $read)
      (i32.load (local.get $cfg)) (local.get $key_len)
      (local.get $scratch) (local.get $cap)))
    (local.set $status (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (local.set $written (i32.wrap_i64 (local.get $result)))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (local.get $written)))
    (local.get $written))
