;; TLS Record Header Encode Stage — slot 125
  (func $process_tls_record_header_encode (export "process_tls_record_header_encode")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32) (local $read i32) (local $result i64) (local $status i32) (local $written i32)
    (local $content_type i32) (local $version i32) (local $fragment_len i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.lt_u (local.get $read) (i32.const 12)) (then (return (i32.const 0))))
    (drop (call $pipe_read (local.get $input) (i32.const 0x3000) (i32.const 12)))
    (local.set $content_type (i32.load (i32.const 0x3000)))
    (local.set $version (i32.load (i32.const 0x3004)))
    (local.set $fragment_len (i32.load (i32.const 0x3008)))
    (local.set $result (call $tls_record_header_encode (local.get $content_type) (local.get $version) (local.get $fragment_len) (i32.const 0x4000) (i32.const 64)))
    (local.set $status (i32.wrap_i64 (i64.and (local.get $result) (i64.const 0xffffffff))))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (drop (call $pipe_write (local.get $output) (i32.const 0x4000) (local.get $written)))
    local.get $written)
