;; TLS Handshake Header Decode Stage — slot 126
  (func $process_tls_handshake_header_decode (export "process_tls_handshake_header_decode")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $result i64) (local $status i32)
    (local $handshake_type i32) (local $body_len i32) (local $read i32)
    (local.set $read (call $stage_read_input (local.get $input) (local.get $scratch) (local.get $scap)))
    (if (i32.lt_u (local.get $read) (i32.const 4)) (then (return (i32.const 0))))
    (local.set $result (call $tls_handshake_header_decode (global.get $SCRATCH_BUF) (local.get $read)))
    (local.set $status (i32.wrap_i64 (i64.and (local.get $result) (i64.const 0xffff))))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (local.set $handshake_type (i32.wrap_i64 (i64.and (i64.shr_u (local.get $result) (i64.const 16)) (i64.const 0xff))))
    (local.set $body_len (i32.wrap_i64 (i64.and (i64.shr_u (local.get $result) (i64.const 24)) (i64.const 0xffffff))))
    (i32.store (local.get $scratch) (local.get $handshake_type))
    (i32.store (i32.add (local.get $scratch) (i32.const 4)) (local.get $body_len))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (i32.const 8)))
    i32.const 8)
