;; WebSocket Write Frame Header Stage — slot 101
  ;; Config: 20 bytes {opcode, flags, payload_len_low, payload_len_high, mask_present, mask}
  (func $process_ws_write_frame_header (export "process_ws_write_frame_header")
    (param $input i32) (param $output i32) (param $cfg i32) (param $clen i32)
    (param $scratch i32) (param $scap i32) (param $state i32) (result i32)
    (local $len_slot i32) (local $read i32) (local $cap i32)
    (local $result i64) (local $status i32) (local $written i32)
    (local.set $len_slot (i32.sub (i32.add (local.get $scratch) (local.get $scap)) (i32.const 4)))
    (drop (call $pipe_read_ptr (local.get $input) (local.get $len_slot)))
    (local.set $read (i32.load (local.get $len_slot)))
    (if (i32.eqz (local.get $read)) (then (return (i32.const 0))))
    (drop (call $pipe_read (local.get $input) (i32.const 0x3000) (local.get $read)))
    (local.set $cap (i32.sub (local.get $scap) (i32.const 16)))
    (local.set $result (call $ws_write_hdr
      (i32.load (local.get $cfg))
      (i32.load (i32.add (local.get $cfg) (i32.const 4)))
      (i32.load (i32.add (local.get $cfg) (i32.const 8)))
      (i32.load (i32.add (local.get $cfg) (i32.const 12)))
      (i32.load (i32.add (local.get $cfg) (i32.const 16)))
      (i32.load (i32.add (local.get $cfg) (i32.const 20)))
      (local.get $scratch) (local.get $cap)))
    (local.set $status (i32.wrap_i64 (i64.shr_u (local.get $result) (i64.const 32))))
    (local.set $written (i32.wrap_i64 (local.get $result)))
    (if (local.get $status) (then (return (i32.sub (i32.const 0) (local.get $status)))))
    (drop (call $pipe_write (local.get $output) (local.get $scratch) (local.get $written)))
    (local.get $written))
