[package]
edition.workspace = true
license.workspace = true
name = "codex-protocol"
version.workspace = true

[lib]
name = "codex_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
edgerun-encoding = { workspace = true, features = ["text-encoding"] }
edgerun-error = { workspace = true }
edgerun-http = { workspace = true }
edgerun-json = { workspace = true, features = ["derive", "schemars", "std", "ts-rs"] }
edgerun-locale = { workspace = true }
edgerun-time = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
edgerun-strum = { workspace = true }
edgerun-strum-macros = { workspace = true }
edgerun-tokio = { workspace = true }
tracing = { workspace = true }
ts-rs = { workspace = true, features = [
    "no-serde-warnings",
] }

[target.'cfg(target_os = "linux")'.dependencies]
landlock = { workspace = true }
seccompiler = { workspace = true }

[dev-dependencies]
anyhow = { package = "edgerun-anyhow", path = "../../utility/edgerun-anyhow" }
edgerun-http = { workspace = true }
pretty_assertions = { package = "edgerun-pretty-assertions", path = "../../utility/edgerun-pretty-assertions" }
tempfile = { package = "edgerun-tempfile", path = "../../utility/edgerun-tempfile" }
