[package]
edition.workspace = true
license.workspace = true
name = "codex-protocol"
version.workspace = true

[lib]
name = "codex_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
edgerun-encoding = { workspace = true, features = ["text-encoding"] }
edgerun-error = { workspace = true }
edgerun-glob = { workspace = true }
edgerun-json = { workspace = true, features = ["serde-compat"] }
edgerun-locale = { workspace = true }
edgerun-quick-xml = { workspace = true, features = ["serialize"] }
edgerun-time = { workspace = true }
edgerun-uuid = { workspace = true }
icu_decimal = { workspace = true }
icu_locale_core = { workspace = true }
icu_provider = { workspace = true, features = ["sync"] }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
edgerun-serde-with = { workspace = true, features = ["macros", "base64"] }
edgerun-strum = { workspace = true }
edgerun-strum-macros = { workspace = true }
edgerun-tokio = { workspace = true }
tracing = { workspace = true }
ts-rs = { workspace = true, features = [
    "uuid-impl",
    "serde-json-impl",
    "no-serde-warnings",
] }

[target.'cfg(target_os = "linux")'.dependencies]
landlock = { workspace = true }
seccompiler = { workspace = true }

[dev-dependencies]
edgerun-http = { workspace = true }
