[package]
name = "edgerun-stream"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-core = { path = "../edgerun-core" }
edgerun-hardware-signing = { path = "../edgerun-hardware-signing" }
edgerun-crypto = { workspace = true, default-features = false, features = ["p256"] }
prost-types.workspace = true

[dev-dependencies]

[lints]
workspace = true
