[package]
name = "edgerun-smtp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Async SMTP server and client (RFC 5321) using edgerun-rt"

[features]
default = []
tls = ["dep:edgerun-tls"]

[lints]
workspace = true

[dependencies]
edgerun-rt = { path = "../edgerun-rt" }
edgerun-log = { path = "../edgerun-log" }
edgerun-dns = { path = "../edgerun-dns" }
edgerun-email-auth = { path = "../edgerun-email-auth" }
edgerun-tls = { path = "../edgerun-tls", optional = true }
