[package]
name = "edgerun-tuya"
version.workspace = true
edition.workspace = true

[dependencies]
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-bare-rt = { path = "../edgerun-bare-rt" }
edgerun-json = { path = "../edgerun-json", default-features = false, features = ["alloc", "serde"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

[[bin]]
name = "tuya-discover"
path = "src/bin/tuya-discover.rs"

[[bin]]
name = "tuya-control"
path = "src/bin/tuya-control.rs"

[lints]
workspace = true
