(global (export "cache_index_data_ptr") i32 (i32.const 0))
  (global (export "cache_index_data_len") i32 (i32.const 8))
  (global (export "cache_index_cursor") i32 (i32.const 16))
  (global (export "cache_index_end") i32 (i32.const 24))
  (global (export "cache_index_rows") i32 (i32.const 32))
  (global (export "cache_index_id") i32 (i32.const 2097184))
  (global (export "cache_index_protocol") i32 (i32.const 2097188))
  (global (export "cache_index_flags") i32 (i32.const 2097192))
  (global (export "cache_index_revision") i32 (i32.const 2097196))
  (global (export "cache_index_archive_count") i32 (i32.const 2097200))
  (global (export "cache_index_total_files") i32 (i32.const 2097204))
  (global (export "cache_index_max_files") i32 (i32.const 2097208))
  (global (export "cache_index_error") i32 (i32.const 2097212))
  (global $ERR_BOUNDS_CACHE i32 (i32.const -1))
  (global $ERR_PROTOCOL i32 (i32.const -2))
  (global $ERR_CAPACITY i32 (i32.const -3))
  (global $ERR_FLAGS i32 (i32.const -4))
  (global $RA i32 (i32.const 0))
  (global $RNH i32 (i32.const 4))
  (global $RCRC i32 (i32.const 8))
  (global $RCS i32 (i32.const 12))
  (global $RDS i32 (i32.const 16))
  (global $RREV i32 (i32.const 20))
  (global $RFC i32 (i32.const 24))
  (global $RFO i32 (i32.const 28))

  (func $cache_read_u8 (result i32)
    (local $ptr i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (if (i32.ge_u (local.get $ptr) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS_CACHE))
        (return (global.get $ERR_BOUNDS_CACHE))
      )
    )
    (i32.store (i32.const 16) (i32.add (local.get $ptr) (i32.const 1)))
    (i32.load8_u (local.get $ptr))
  )

  (func $read_u16 (result i32)
    (local $ptr i32) (local $next i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (local.set $next (i32.add (local.get $ptr) (i32.const 2)))
    (if (i32.gt_u (local.get $next) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS_CACHE))
        (return (global.get $ERR_BOUNDS_CACHE))
      )
    )
    (i32.store (i32.const 16) (local.get $next))
    (i32.or
      (i32.shl (i32.load8_u (local.get $ptr)) (i32.const 8))
      (i32.load8_u (i32.add (local.get $ptr) (i32.const 1)))
    )
  )

  (func $read_u32 (result i32)
    (local $ptr i32) (local $next i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (local.set $next (i32.add (local.get $ptr) (i32.const 4)))
    (if (i32.gt_u (local.get $next) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS_CACHE))
        (return (global.get $ERR_BOUNDS_CACHE))
      )
    )
    (i32.store (i32.const 16) (local.get $next))
    (i32.or
      (i32.or
        (i32.or
          (i32.shl (i32.load8_u (local.get $ptr)) (i32.const 24))
          (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 1))) (i32.const 16))
        )
        (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 2))) (i32.const 8))
      )
      (i32.load8_u (i32.add (local.get $ptr) (i32.const 3)))
    )
  )

  (func $read_big_smart (result i32)
    (local $ptr i32)
    (local.set $ptr (i32.load (i32.const 16)))
    (if (i32.ge_u (local.get $ptr) (i32.load (i32.const 24)))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS_CACHE))
        (return (global.get $ERR_BOUNDS_CACHE))
      )
    )
    (if (i32.lt_u (i32.load8_u (local.get $ptr)) (i32.const 128))
      (then (return (call $read_u16)))
    )
    (i32.and (call $read_u32) (i32.const 0x7fffffff))
  )

  (func (export "cache_index_get_summary") (result i32)
    (i32.const 2097184)
  )

  (func (export "cache_index_get_row_table") (result i32 i32)
    (i32.const 32)
    (i32.load (i32.const 2097200))
  )

  (func (export "cache_index_region_archive_id") (param $x i32) (param $y i32) (result i32)
    (i32.or (i32.shl (local.get $x) (i32.const 8)) (i32.and (local.get $y) (i32.const 255)))
  )

  (func (export "cache_index_parse_protocol7") (param $data i32) (param $len i32) (param $index_id i32) (result i32)
    (local $v i32) (local $row_count i32) (local $row_idx i32) (local $cumulative i32) (local $row_ptr i32) (local $file_count i32) (local $file_idx i32)
    (if (i32.eqz (local.get $data))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS_CACHE))
        (return (global.get $ERR_BOUNDS_CACHE))
      )
    )
    (if (i32.lt_u (local.get $len) (i32.const 4))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_BOUNDS_CACHE))
        (return (global.get $ERR_BOUNDS_CACHE))
      )
    )
    (i32.store (i32.const 0) (local.get $data))
    (i32.store (i32.const 8) (local.get $len))
    (i32.store (i32.const 16) (local.get $data))
    (i32.store (i32.const 24) (i32.add (local.get $data) (local.get $len)))
    (i32.store (i32.const 2097184) (local.get $index_id))
    (i32.store (i32.const 2097200) (i32.const 0))
    (i32.store (i32.const 2097204) (i32.const 0))
    (i32.store (i32.const 2097208) (i32.const 0))
    (i32.store (i32.const 2097212) (global.get $OK))
    (local.set $v (call $cache_read_u8))
    (if (i32.lt_s (local.get $v) (i32.const 0))
      (then (return (local.get $v)))
    )
    (i32.store (i32.const 2097188) (local.get $v))
    (if (i32.ne (local.get $v) (i32.const 7))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_PROTOCOL))
        (return (global.get $ERR_PROTOCOL))
      )
    )
    (local.set $v (call $read_u32))
    (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
      (then (return (i32.load (i32.const 2097212))))
    )
    (i32.store (i32.const 2097196) (local.get $v))
    (local.set $v (call $cache_read_u8))
    (if (i32.lt_s (local.get $v) (i32.const 0))
      (then (return (local.get $v)))
    )
    (i32.store (i32.const 2097192) (local.get $v))
    (if (i32.and (local.get $v) (i32.const 250))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_FLAGS))
        (return (global.get $ERR_FLAGS))
      )
    )
    (local.set $v (call $read_big_smart))
    (if (i32.lt_s (local.get $v) (i32.const 0))
      (then (return (local.get $v)))
    )
    (if (i32.gt_u (local.get $v) (global.get $MAX_ROWS))
      (then
        (i32.store (i32.const 2097212) (global.get $ERR_CAPACITY))
        (return (global.get $ERR_CAPACITY))
      )
    )
    (i32.store (i32.const 2097200) (local.get $v))
    (local.set $row_count (local.get $v))

    (local.set $row_idx (i32.const 0))
    (local.set $cumulative (i32.const 0))
    (block $b_ids
      (loop $l_ids
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_ids))
        )
        (local.set $v (call $read_big_smart))
        (if (i32.lt_s (local.get $v) (i32.const 0))
          (then (return (local.get $v)))
        )
        (local.set $cumulative (i32.add (local.get $cumulative) (local.get $v)))
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (local.get $row_ptr) (local.get $cumulative))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RNH)) (i32.const 0))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RCS)) (i32.const 0))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RDS)) (i32.const 0))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RFO)) (i32.const 0))
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_ids)
      )
    )

    (if (i32.and (i32.load (i32.const 2097192)) (i32.const 1))
      (then
        (local.set $row_idx (i32.const 0))
        (block $b_nm
          (loop $l_nm
            (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
              (then (br $b_nm))
            )
            (local.set $v (call $read_u32))
            (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
              (then (return (i32.load (i32.const 2097212))))
            )
            (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
            (i32.store (i32.add (local.get $row_ptr) (global.get $RNH)) (local.get $v))
            (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
            (br $l_nm)
          )
        )
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_crc
      (loop $l_crc
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_crc))
        )
        (local.set $v (call $read_u32))
        (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
          (then (return (i32.load (i32.const 2097212))))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RCRC)) (local.get $v))
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_crc)
      )
    )

    (if (i32.and (i32.load (i32.const 2097192)) (i32.const 4))
      (then
        (local.set $row_idx (i32.const 0))
        (block $b_sz
          (loop $l_sz
            (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
              (then (br $b_sz))
            )
            (local.set $v (call $read_u32))
            (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
              (then (return (i32.load (i32.const 2097212))))
            )
            (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
            (i32.store (i32.add (local.get $row_ptr) (global.get $RCS)) (local.get $v))
            (local.set $v (call $read_u32))
            (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
              (then (return (i32.load (i32.const 2097212))))
            )
            (i32.store (i32.add (local.get $row_ptr) (global.get $RDS)) (local.get $v))
            (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
            (br $l_sz)
          )
        )
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_rev
      (loop $l_rev
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_rev))
        )
        (local.set $v (call $read_u32))
        (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
          (then (return (i32.load (i32.const 2097212))))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RREV)) (local.get $v))
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_rev)
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_fc
      (loop $l_fc
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_fc))
        )
        (local.set $v (call $read_big_smart))
        (if (i32.lt_s (local.get $v) (i32.const 0))
          (then (return (local.get $v)))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store (i32.add (local.get $row_ptr) (global.get $RFC)) (local.get $v))
        (i32.store (i32.const 2097204) (i32.add (i32.load (i32.const 2097204)) (local.get $v)))
        (if (i32.gt_u (local.get $v) (i32.load (i32.const 2097208)))
          (then (i32.store (i32.const 2097208) (local.get $v)))
        )
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_fc)
      )
    )

    (local.set $row_idx (i32.const 0))
    (block $b_fid
      (loop $l_fid
        (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
          (then (br $b_fid))
        )
        (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
        (i32.store
          (i32.add (local.get $row_ptr) (global.get $RFO))
          (i32.sub (i32.load (i32.const 16)) (i32.load (i32.const 0)))
        )
        (local.set $file_count (i32.load (i32.add (local.get $row_ptr) (global.get $RFC))))
        (local.set $file_idx (i32.const 0))
        (block $b_fid_in
          (loop $l_fid_in
            (if (i32.ge_u (local.get $file_idx) (local.get $file_count))
              (then (br $b_fid_in))
            )
            (local.set $v (call $read_big_smart))
            (if (i32.lt_s (local.get $v) (i32.const 0))
              (then (return (local.get $v)))
            )
            (local.set $file_idx (i32.add (local.get $file_idx) (i32.const 1)))
            (br $l_fid_in)
          )
        )
        (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
        (br $l_fid)
      )
    )

    (if (i32.and (i32.load (i32.const 2097192)) (i32.const 1))
      (then
        (local.set $row_idx (i32.const 0))
        (block $b_fnh
          (loop $l_fnh
            (if (i32.ge_u (local.get $row_idx) (local.get $row_count))
              (then (br $b_fnh))
            )
            (local.set $row_ptr (i32.add (i32.const 32) (i32.mul (local.get $row_idx) (global.get $ROW_SIZE))))
            (local.set $file_count (i32.load (i32.add (local.get $row_ptr) (global.get $RFC))))
            (local.set $file_idx (i32.const 0))
            (block $b_fnh_in
              (loop $l_fnh_in
                (if (i32.ge_u (local.get $file_idx) (local.get $file_count))
                  (then (br $b_fnh_in))
                )
                (local.set $v (call $read_u32))
                (if (i32.ne (i32.load (i32.const 2097212)) (global.get $OK))
                  (then (return (i32.load (i32.const 2097212))))
                )
                (local.set $file_idx (i32.add (local.get $file_idx) (i32.const 1)))
                (br $l_fnh_in)
              )
            )
            (local.set $row_idx (i32.add (local.get $row_idx) (i32.const 1)))
            (br $l_fnh)
          )
        )
      )
    )

    (i32.const 0)
  )

  (func (export "cache_index_find_archive") (param $archive_id i32) (result i32 i32)
    (local $count i32) (local $idx i32) (local $ptr i32)
    (local.set $count (i32.load (i32.const 2097200)))
    (local.set $idx (i32.const 0))
    (local.set $ptr (i32.const 32))
    (loop $l_fa
      (if (i32.ge_u (local.get $idx) (local.get $count))
        (then (return (i32.const 0) (i32.const 0)))
      )
      (if (i32.eq (i32.load (local.get $ptr)) (local.get $archive_id))
        (then (return (local.get $ptr) (local.get $idx)))
      )
      (local.set $ptr (i32.add (local.get $ptr) (global.get $ROW_SIZE)))
      (local.set $idx (i32.add (local.get $idx) (i32.const 1)))
      (br $l_fa)
    )
    (unreachable)
  )

  (func (export "cache_index_find_name_hash") (param $name_hash i32) (result i32 i32)
    (local $count i32) (local $idx i32) (local $ptr i32)
    (local.set $count (i32.load (i32.const 2097200)))
    (local.set $idx (i32.const 0))
    (local.set $ptr (i32.const 32))
    (loop $l_fh
      (if (i32.ge_u (local.get $idx) (local.get $count))
        (then (return (i32.const 0) (i32.const 0)))
      )
      (if (i32.eq (i32.load (i32.add (local.get $ptr) (global.get $RNH))) (local.get $name_hash))
        (then (return (local.get $ptr) (local.get $idx)))
      )
      (local.set $ptr (i32.add (local.get $ptr) (global.get $ROW_SIZE)))
      (local.set $idx (i32.add (local.get $idx) (i32.const 1)))
      (br $l_fh)
    )
    (unreachable)
  )

(global (export "js5_cache_request_state") i32 (i32.const 0))
  (global (export "js5_cache_socket_fd") i32 (i32.const 136))
  (global (export "js5_cache_last_status") i32 (i32.const 144))
  (global (export "js5_cache_last_error") i32 (i32.const 148))
  (global (export "js5_cache_last_index_id") i32 (i32.const 152))
  (global (export "js5_cache_last_archive_id") i32 (i32.const 156))
  (global (export "js5_cache_container_type") i32 (i32.const 160))
  (global (export "js5_cache_container_len") i32 (i32.const 164))
  (global (export "js5_cache_decompressed_len") i32 (i32.const 168))
  (global (export "js5_cache_payload_ptr") i32 (i32.const 172))
  (global (export "js5_cache_payload_len") i32 (i32.const 180))
  (global (export "js5_cache_decompressed_ptr") i32 (i32.const 188))
  (global (export "js5_cache_request_bytes") i32 (i32.const 196))
  (global (export "js5_cache_response_header") i32 (i32.const 200))
  (global (export "js5_cache_continue_byte") i32 (i32.const 208))
  (global (export "js5_cache_gzip_header_len") i32 (i32.const 212))
  (global (export "js5_cache_gzip_deflate_ptr") i32 (i32.const 220))
  (global (export "js5_cache_gzip_deflate_len") i32 (i32.const 228))
  (global (export "js5_cache_gzip_footer_ptr") i32 (i32.const 236))
  (global (export "js5_cache_gzip_footer_crc32") i32 (i32.const 244))
  (global (export "js5_cache_gzip_footer_isize") i32 (i32.const 248))
  (global (export "js5_cache_deflate_in_ptr") i32 (i32.const 252))
  (global (export "js5_cache_deflate_in_end") i32 (i32.const 260))
  (global (export "js5_cache_deflate_out_ptr") i32 (i32.const 268))
  (global (export "js5_cache_deflate_out_start") i32 (i32.const 276))
  (global (export "js5_cache_deflate_out_end") i32 (i32.const 284))
  (global (export "js5_cache_deflate_bitbuf") i32 (i32.const 292))
  (global (export "js5_cache_deflate_bitcount") i32 (i32.const 300))
  (global (export "js5_cache_deflate_last") i32 (i32.const 304))
  (global (export "js5_cache_deflate_btype") i32 (i32.const 308))
  (global (export "js5_cache_response_buffer") i32 (i32.const 312))
  (global (export "js5_cache_decompress_buffer") i32 (i32.const 1048888))

  (global $REQ_INDEX_ID i32 (i32.const 0))
  (global $REQ_ARCHIVE_ID i32 (i32.const 4))
  (global $REQ_STATUS i32 (i32.const 8))
  (global $REQ_ERROR i32 (i32.const 12))
  (global $REQ_SOCKET_FD i32 (i32.const 16))
  (global $REQ_DEST_PTR i32 (i32.const 24))
  (global $REQ_DEST_CAP i32 (i32.const 32))
  (global $REQ_CONTAINER_PTR i32 (i32.const 40))
  (global $REQ_CONTAINER_LEN i32 (i32.const 48))
  (global $REQ_PAYLOAD_PTR i32 (i32.const 56))
  (global $REQ_PAYLOAD_LEN i32 (i32.const 64))
  (global $REQ_DECOMP_PTR i32 (i32.const 72))
  (global $REQ_DECOMP_LEN i32 (i32.const 80))
  (global $REQ_COMP_TYPE i32 (i32.const 88))
  (global $REQ_COMP_LEN i32 (i32.const 92))
  (global $REQ_HEADER_POS i32 (i32.const 96))
  (global $REQ_PAYLOAD_POS i32 (i32.const 104))
  (global $REQ_PAYLOAD_TOTAL i32 (i32.const 112))
  (global $REQ_CHUNK_LEFT i32 (i32.const 120))
  (global $REQ_REQUEST_POS i32 (i32.const 128))
  (global $REQ_SIZE i32 (i32.const 136))
  (global $REQ_SIZE_QWORDS i32 (i32.const 17))

  (global $ERR_BUSY i32 (i32.const -1))
  (global $ERR_NOSOCK i32 (i32.const -2))
  (global $ERR_IO i32 (i32.const -4))
  (global $ERR_HEADER i32 (i32.const -5))
  (global $ERR_DECOMP i32 (i32.const -6))

  (global $STATE_IDLE i32 (i32.const 0))
  (global $STATE_QUEUED i32 (i32.const 1))
  (global $STATE_SENT i32 (i32.const 2))
  (global $STATE_HEADER i32 (i32.const 3))
  (global $STATE_PAYLOAD i32 (i32.const 4))
  (global $STATE_DONE i32 (i32.const 5))
  (global $STATE_ERROR i32 (i32.const 6))

  (global $CONTAINER_NONE i32 (i32.const 0))
  (global $CONTAINER_BZIP i32 (i32.const 1))
  (global $CONTAINER_GZIP i32 (i32.const 2))
  (global $FIRST_CHUNK i32 (i32.const 504))
  (global $NEXT_CHUNK i32 (i32.const 511))

  ;; === init ===
  (func (export "js5_cache_init") (result i32)
    (drop (call $reset_request))
    (i64.store (i32.const 136) (i64.const -1))
    (i32.const 0)
  )

  ;; === reset_request ===
  (func $reset_request (export "js5_cache_reset_request") (result i32)
    (local $i i32)
    (local.set $i (i32.const 0))
    (block $b
      (loop $l
        (if (i32.eq (local.get $i) (global.get $REQ_SIZE_QWORDS)) (then (br $b)))
        (i64.store (i32.add (i32.const 0) (i32.mul (local.get $i) (i32.const 8))) (i64.const 0))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $l)
      )
    )
    (i32.store (i32.const 8) (global.get $STATE_IDLE))
    (i32.store (i32.const 12) (global.get $OK))
    (i64.store (i32.const 16) (i64.const -1))
    (i32.store (i32.const 144) (global.get $STATE_IDLE))
    (i32.store (i32.const 148) (global.get $OK))
    (i32.const 0)
  )

  ;; === set_socket_fd ===
  (func (export "js5_cache_set_socket_fd") (param $fd i32) (result i32)
    (i64.store (i32.const 136) (i64.extend_i32_s (local.get $fd)))
    (i64.store (i32.const 16) (i64.extend_i32_s (local.get $fd)))
    (i32.const 0)
  )

  ;; === queue_archive_request ===
  (func (export "js5_cache_queue_archive_request") (param $index_id i32) (param $archive_id i32) (param $dest_ptr i32) (param $dest_cap i32) (result i32)
    (local $v i32)
    (local.set $v (i32.load (i32.const 8)))
    (block $chk
      (if (i32.eq (local.get $v) (global.get $STATE_IDLE)) (then (br $chk)))
      (if (i32.eq (local.get $v) (global.get $STATE_DONE)) (then (br $chk)))
      (if (i32.ne (local.get $v) (global.get $STATE_ERROR)) (then (return (global.get $ERR_BUSY))))
    )
    (i32.store (i32.const 152) (local.get $index_id))
    (i32.store (i32.const 156) (local.get $archive_id))
    (i32.store (i32.const 0) (local.get $index_id))
    (i32.store (i32.const 4) (local.get $archive_id))
    (if (i32.eqz (local.get $dest_ptr))
      (then
        (local.set $dest_ptr (i32.const 312))
        (local.set $dest_cap (global.get $DEFAULT_BYTES))
      )
    )
    (if (i32.eqz (local.get $dest_cap))
      (then
        (i32.store (i32.const 8) (global.get $STATE_ERROR))
        (i32.store (i32.const 12) (global.get $ERR_BOUNDS_CACHE))
        (i32.store (i32.const 148) (global.get $ERR_BOUNDS_CACHE))
        (return (global.get $ERR_BOUNDS_CACHE))
      )
    )
    (i64.store (i32.const 24) (i64.extend_i32_s (local.get $dest_ptr)))
    (i64.store (i32.const 32) (i64.extend_i32_s (local.get $dest_cap)))
    (i64.store (i32.const 40) (i64.const 0))
    (i64.store (i32.const 48) (i64.const 0))
    (i64.store (i32.const 56) (i64.const 0))
    (i64.store (i32.const 64) (i64.const 0))
    (i64.store (i32.const 72) (i64.const 0))
    (i64.store (i32.const 80) (i64.const 0))
    (i64.store (i32.const 96) (i64.const 0))
    (i64.store (i32.const 104) (i64.const 0))
    (i64.store (i32.const 112) (i64.const 0))
    (i64.store (i32.const 120) (i64.extend_i32_s (global.get $FIRST_CHUNK)))
    (i64.store (i32.const 128) (i64.const 0))
    (i32.store (i32.const 12) (global.get $OK))
    (i32.store8 (i32.const 196) (i32.const 1))
    (i32.store8 (i32.const 197) (local.get $index_id))
    (local.set $v (i32.shr_u (local.get $archive_id) (i32.const 8)))
    (i32.store8 (i32.const 198) (local.get $v))
    (i32.store8 (i32.const 199) (local.get $archive_id))
    (i32.store (i32.const 8) (global.get $STATE_QUEUED))
    (i32.store (i32.const 144) (global.get $STATE_QUEUED))
    (i32.const 0)
  )

  ;; === poll_response (stub - no syscalls in WASM) ===
  (func (export "js5_cache_poll_response") (result i32)
    (if (i32.lt_s (i32.load (i32.const 136)) (i32.const 0))
      (then
        (i32.store (i32.const 148) (global.get $ERR_NOSOCK))
        (return (global.get $ERR_NOSOCK))
      )
    )
    (global.get $ERR_NOSOCK)
  )

  ;; === read_response_blocking (stub) ===
  (func (export "js5_cache_read_response_blocking") (result i32)
    (global.get $ERR_NOSOCK)
  )

  ;; === get_request_state ===
  (func (export "js5_cache_get_request_state") (result i32)
    (i32.const 0)
  )

  ;; === get_payload ===
  (func (export "js5_cache_get_payload") (result i32 i32)
    (i32.load (i32.const 172))
    (i32.load (i32.const 180))
  )

  ;; === get_decompressed ===
  (func (export "js5_cache_get_decompressed") (result i32 i32)
    (i32.load (i32.const 188))
    (i32.load (i32.const 168))
  )

  ;; === parse_container_header ===
  (func (export "js5_cache_parse_container_header") (param $ptr i32) (param $len i32) (result i32)
    (local $type i32) (local $clen i32) (local $dlen i32) (local $p i32)
    (if (i32.lt_u (local.get $len) (i32.const 5))
      (then
        (i32.store (i32.const 148) (global.get $ERR_HEADER))
        (return (global.get $ERR_HEADER))
      )
    )
    (local.set $type (i32.load8_u (local.get $ptr)))
    (i32.store (i32.const 160) (local.get $type))
    (local.set $clen
      (i32.or
        (i32.or
          (i32.or
            (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 1))) (i32.const 24))
            (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 2))) (i32.const 16))
          )
          (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 3))) (i32.const 8))
        )
        (i32.load8_u (i32.add (local.get $ptr) (i32.const 4)))
      )
    )
    (i32.store (i32.const 164) (local.get $clen))
    (if (i32.eq (local.get $type) (global.get $CONTAINER_NONE))
      (then
        (local.set $p (i32.add (local.get $ptr) (i32.const 5)))
        (if (i32.lt_u (local.get $len) (i32.add (local.get $clen) (i32.const 5)))
          (then
            (i32.store (i32.const 148) (global.get $ERR_HEADER))
            (return (global.get $ERR_HEADER))
          )
        )
        (i32.store (i32.const 172) (local.get $p))
        (i32.store (i32.const 180) (local.get $clen))
        (i32.store (i32.const 188) (local.get $p))
        (i32.store (i32.const 168) (local.get $clen))
        (i64.store (i32.const 56) (i64.extend_i32_s (local.get $p)))
        (i64.store (i32.const 64) (i64.extend_i32_s (local.get $clen)))
        (i64.store (i32.const 72) (i64.extend_i32_s (local.get $p)))
        (i64.store (i32.const 80) (i64.extend_i32_s (local.get $clen)))
        (return (i32.const 0))
      )
    )
    (if (i32.lt_u (local.get $len) (i32.const 9))
      (then
        (i32.store (i32.const 148) (global.get $ERR_HEADER))
        (return (global.get $ERR_HEADER))
      )
    )
    (local.set $dlen
      (i32.or
        (i32.or
          (i32.or
            (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 5))) (i32.const 24))
            (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 6))) (i32.const 16))
          )
          (i32.shl (i32.load8_u (i32.add (local.get $ptr) (i32.const 7))) (i32.const 8))
        )
        (i32.load8_u (i32.add (local.get $ptr) (i32.const 8)))
      )
    )
    (i32.store (i32.const 168) (local.get $dlen))
    (local.set $p (i32.add (local.get $ptr) (i32.const 9)))
    (if (i32.lt_u (local.get $len) (i32.add (local.get $clen) (i32.const 9)))
      (then
        (i32.store (i32.const 148) (global.get $ERR_HEADER))
        (return (global.get $ERR_HEADER))
      )
    )
    (i32.store (i32.const 172) (local.get $p))
    (i32.store (i32.const 180) (local.get $clen))
    (i64.store (i32.const 188) (i64.const 0))
    (i64.store (i32.const 56) (i64.extend_i32_s (local.get $p)))
    (i64.store (i32.const 64) (i64.extend_i32_s (local.get $clen)))
    (i64.store (i32.const 72) (i64.const 0))
    (i64.store (i32.const 80) (i64.extend_i32_s (local.get $dlen)))
    (if (i32.eq (local.get $type) (global.get $CONTAINER_BZIP))
      (then (return (call $bzip_dispatch)))
    )
    (if (i32.eq (local.get $type) (global.get $CONTAINER_GZIP))
      (then (return (call $gzip_dispatch)))
    )
    (i32.store (i32.const 148) (global.get $ERR_HEADER))
    (global.get $ERR_HEADER)
  )

  ;; === publish_payload ===
  (func (export "js5_cache_publish_payload") (param $payload_ptr i32) (param $payload_len i32) (param $decomp_ptr i32) (param $decomp_len i32) (result i32)
    (i32.store (i32.const 172) (local.get $payload_ptr))
    (i32.store (i32.const 180) (local.get $payload_len))
    (i32.store (i32.const 188) (local.get $decomp_ptr))
    (i32.store (i32.const 168) (local.get $decomp_len))
    (i64.store (i32.const 56) (i64.extend_i32_s (local.get $payload_ptr)))
    (i64.store (i32.const 64) (i64.extend_i32_s (local.get $payload_len)))
    (i64.store (i32.const 72) (i64.extend_i32_s (local.get $decomp_ptr)))
    (i64.store (i32.const 80) (i64.extend_i32_s (local.get $decomp_len)))
    (i32.store (i32.const 8) (global.get $STATE_DONE))
    (i32.store (i32.const 144) (global.get $STATE_DONE))
    (i32.const 0)
  )

  ;; === bzip_dispatch ===
  (func $bzip_dispatch (export "js5_cache_bzip_dispatch") (result i32)
    (local $p i32) (local $len i32)
    (local.set $p (i32.load (i32.const 172)))
    (local.set $len (i32.load (i32.const 180)))
    (block $bad
      (if (i32.lt_u (local.get $len) (i32.const 6)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (local.get $p)) (i32.const 0x31)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $p) (i32.const 1))) (i32.const 0x41)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $p) (i32.const 2))) (i32.const 0x59)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $p) (i32.const 3))) (i32.const 0x26)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $p) (i32.const 4))) (i32.const 0x53)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $p) (i32.const 5))) (i32.const 0x59)) (then (br $bad)))
      (i32.store (i32.const 148) (global.get $ERR_DECOMP))
      (return (global.get $ERR_DECOMP))
    )
    (i32.store (i32.const 148) (global.get $ERR_DECOMP))
    (global.get $ERR_DECOMP)
  )

  ;; === gzip_dispatch ===
  (func $gzip_dispatch (export "js5_cache_gzip_dispatch") (result i32)
    (local $p i32) (local $end i32) (local $payload_ptr i32) (local $payload_len i32)
    (local $flags i32) (local $v i32) (local $xlen i32)
    (local.set $payload_ptr (i32.load (i32.const 172)))
    (local.set $payload_len (i32.load (i32.const 180)))
    (block $bad
      (if (i32.lt_u (local.get $payload_len) (i32.const 18)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (local.get $payload_ptr)) (i32.const 0x1f)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $payload_ptr) (i32.const 1))) (i32.const 0x8b)) (then (br $bad)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $payload_ptr) (i32.const 2))) (i32.const 8)) (then (br $bad)))
      (local.set $flags (i32.load8_u (i32.add (local.get $payload_ptr) (i32.const 3))))
      (if (i32.and (local.get $flags) (i32.const 0xe0)) (then (br $bad)))
      (local.set $p (i32.add (local.get $payload_ptr) (i32.const 10)))
      (local.set $end (i32.sub (i32.add (local.get $payload_ptr) (local.get $payload_len)) (i32.const 8)))
      (if (i32.gt_u (local.get $p) (local.get $end)) (then (br $bad)))
      ;; extra
      (if (i32.and (local.get $flags) (i32.const 4))
        (then
          (if (i32.gt_u (i32.add (local.get $p) (i32.const 2)) (local.get $end)) (then (br $bad)))
          (local.set $xlen
            (i32.or
              (i32.load8_u (local.get $p))
              (i32.shl (i32.load8_u (i32.add (local.get $p) (i32.const 1))) (i32.const 8))
            )
          )
          (local.set $p (i32.add (i32.add (local.get $p) (i32.const 2)) (local.get $xlen)))
          (if (i32.gt_u (local.get $p) (local.get $end)) (then (br $bad)))
        )
      )
      ;; name
      (if (i32.and (local.get $flags) (i32.const 8))
        (then
          (block $name_done
            (loop $name_loop
              (if (i32.ge_u (local.get $p) (local.get $end)) (then (br $bad)))
              (br_if $name_done (i32.eqz (i32.load8_u (local.get $p))))
              (local.set $p (i32.add (local.get $p) (i32.const 1)))
              (br $name_loop)
            )
          )
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
        )
      )
      ;; comment
      (if (i32.and (local.get $flags) (i32.const 16))
        (then
          (block $comm_done
            (loop $comm_loop
              (if (i32.ge_u (local.get $p) (local.get $end)) (then (br $bad)))
              (br_if $comm_done (i32.eqz (i32.load8_u (local.get $p))))
              (local.set $p (i32.add (local.get $p) (i32.const 1)))
              (br $comm_loop)
            )
          )
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
        )
      )
      ;; hcrc
      (if (i32.and (local.get $flags) (i32.const 2))
        (then
          (local.set $p (i32.add (local.get $p) (i32.const 2)))
          (if (i32.gt_u (local.get $p) (local.get $end)) (then (br $bad)))
        )
      )
      (i64.store (i32.const 220) (i64.extend_i32_s (local.get $p)))
      (i64.store (i32.const 228) (i64.extend_i32_s (i32.sub (local.get $end) (local.get $p))))
      (i64.store (i32.const 236) (i64.extend_i32_s (local.get $end)))
      (i64.store (i32.const 212) (i64.extend_i32_s (i32.sub (local.get $p) (local.get $payload_ptr))))
      (i32.store (i32.const 244) (i32.load (local.get $end)))
      (i32.store (i32.const 248) (i32.load (i32.add (local.get $end) (i32.const 4))))
      (if (i32.gt_u (i32.load (i32.const 168)) (global.get $DEFAULT_BYTES)) (then (br $bad)))
      (if (i32.ne (i32.load (i32.const 248)) (i32.load (i32.const 168))) (then (br $bad)))
      (local.set $v (call $deflate_decode_stored))
      (if (i32.lt_s (local.get $v) (i32.const 0)) (then (return (local.get $v))))
      (i32.store (i32.const 172) (local.get $payload_ptr))
      (i32.store (i32.const 180) (local.get $payload_len))
      (i32.store (i32.const 188) (i32.const 1048888))
      (i32.store (i32.const 168) (i32.load (i32.const 248)))
      (i64.store (i32.const 56) (i64.extend_i32_s (local.get $payload_ptr)))
      (i64.store (i32.const 64) (i64.extend_i32_s (local.get $payload_len)))
      (i64.store (i32.const 72) (i64.extend_i32_s (i32.const 1048888)))
      (i64.store (i32.const 80) (i64.extend_i32_s (i32.load (i32.const 248))))
      (i32.store (i32.const 8) (global.get $STATE_DONE))
      (i32.store (i32.const 144) (global.get $STATE_DONE))
      (i32.const 0)
      return
    )
    (i32.store (i32.const 148) (global.get $ERR_DECOMP))
    (global.get $ERR_DECOMP)
  )

  ;; === deflate_decode_stored ===
  (func $deflate_decode_stored (result i32)
    (local $in_ptr i32) (local $in_end i32) (local $out_ptr i32) (local $out_start i32) (local $out_end i32)
    (local $len i32) (local $nlen i32) (local $v i32) (local $i i32)
    (local.set $in_ptr (i32.load (i32.const 220)))
    (i32.store (i32.const 252) (local.get $in_ptr))
    (local.set $in_end (i32.add (local.get $in_ptr) (i32.load (i32.const 228))))
    (i32.store (i32.const 260) (local.get $in_end))
    (local.set $out_start (i32.const 1048888))
    (i32.store (i32.const 276) (local.get $out_start))
    (i32.store (i32.const 268) (local.get $out_start))
    (local.set $out_end (i32.add (local.get $out_start) (i32.load (i32.const 168))))
    (i32.store (i32.const 284) (local.get $out_end))
    (i64.store (i32.const 292) (i64.const 0))
    (i32.store (i32.const 300) (i32.const 0))
    (i32.store (i32.const 304) (i32.const 0))
    (block $block_loop
      (loop $block_loop_l
        (local.set $v (call $deflate_read_bits (i32.const 1)))
        (if (i32.lt_s (local.get $v) (i32.const 0)) (then (return (local.get $v))))
        (i32.store (i32.const 304) (local.get $v))
        (local.set $v (call $deflate_read_bits (i32.const 2)))
        (if (i32.lt_s (local.get $v) (i32.const 0)) (then (return (local.get $v))))
        (i32.store (i32.const 308) (local.get $v))
        (block $stored
          (if (i32.eqz (local.get $v))
            (then
              (i64.store (i32.const 292) (i64.const 0))
              (i32.store (i32.const 300) (i32.const 0))
              (local.set $in_ptr (i32.load (i32.const 252)))
              (local.set $in_end (i32.load (i32.const 260)))
              (block $bad
                (if (i32.gt_u (i32.add (local.get $in_ptr) (i32.const 4)) (local.get $in_end)) (then (br $bad)))
                (local.set $len
                  (i32.or
                    (i32.load8_u (local.get $in_ptr))
                    (i32.shl (i32.load8_u (i32.add (local.get $in_ptr) (i32.const 1))) (i32.const 8))
                  )
                )
                (local.set $nlen
                  (i32.or
                    (i32.load8_u (i32.add (local.get $in_ptr) (i32.const 2)))
                    (i32.shl (i32.load8_u (i32.add (local.get $in_ptr) (i32.const 3))) (i32.const 8))
                  )
                )
                (if (i32.ne (i32.xor (local.get $len) (local.get $nlen)) (i32.const 0xffff)) (then (br $bad)))
                (local.set $in_ptr (i32.add (local.get $in_ptr) (i32.const 4)))
                (if (i32.gt_u (i32.add (local.get $in_ptr) (local.get $len)) (i32.load (i32.const 260))) (then (br $bad)))
                (local.set $out_ptr (i32.load (i32.const 268)))
                (if (i32.gt_u (i32.add (local.get $out_ptr) (local.get $len)) (i32.load (i32.const 284))) (then (br $bad)))
                (local.set $i (i32.const 0))
                (block $cpy_done
                  (loop $cpy_loop
                    (if (i32.eq (local.get $i) (local.get $len)) (then (br $cpy_done)))
                    (i32.store8
                      (i32.add (local.get $out_ptr) (local.get $i))
                      (i32.load8_u (i32.add (local.get $in_ptr) (local.get $i)))
                    )
                    (local.set $i (i32.add (local.get $i) (i32.const 1)))
                    (br $cpy_loop)
                  )
                )
                (i32.store (i32.const 252) (i32.add (local.get $in_ptr) (local.get $len)))
                (i32.store (i32.const 268) (i32.add (local.get $out_ptr) (local.get $len)))
                (br $stored)
              )
              (i32.store (i32.const 148) (global.get $ERR_DECOMP))
              (return (global.get $ERR_DECOMP))
            )
          )
        )
        (if (i32.eq (local.get $v) (i32.const 1))
          (then
            (i32.store (i32.const 148) (global.get $ERR_HEADER))
            (return (global.get $ERR_HEADER))
          )
        )
        (if (i32.eq (local.get $v) (i32.const 2))
          (then
            (i32.store (i32.const 148) (global.get $ERR_HEADER))
            (return (global.get $ERR_HEADER))
          )
        )
        (if (i32.eqz (i32.load (i32.const 304)))
          (then (br $block_loop_l))
        )
        (local.set $v
          (i32.sub
            (i32.load (i32.const 268))
            (i32.load (i32.const 276))
          )
        )
        (if (i32.ne (local.get $v) (i32.load (i32.const 168)))
          (then
            (i32.store (i32.const 148) (global.get $ERR_DECOMP))
            (return (global.get $ERR_DECOMP))
          )
        )
        (i32.const 0)
        return
      )
    )
    (i32.store (i32.const 148) (global.get $ERR_DECOMP))
    (global.get $ERR_DECOMP)
  )

  ;; === deflate_read_bits ===
  (func $deflate_read_bits (param $count i32) (result i32)
    (local $r9 i32) (local $bitbuf i64) (local $bitcount i32) (local $in_ptr i32) (local $in_end i32)
    (local $v i32)
    (local.set $r9 (local.get $count))
    (if (i32.eqz (local.get $r9))
      (then (return (i32.const 0)))
    )
    (block $bad
      (if (i32.gt_u (local.get $r9) (i32.const 16)) (then (br $bad)))
      (local.set $bitbuf (i64.load (i32.const 292)))
      (local.set $bitcount (i32.load (i32.const 300)))
      (local.set $in_ptr (i32.load (i32.const 252)))
      (local.set $in_end (i32.load (i32.const 260)))
      (block $fill
        (loop $fill_loop
          (if (i32.ge_u (local.get $bitcount) (local.get $r9)) (then (br $fill)))
          (if (i32.ge_u (local.get $in_ptr) (local.get $in_end))
            (then (br $bad))
          )
          (local.set $v (i32.load8_u (local.get $in_ptr)))
          (local.set $in_ptr (i32.add (local.get $in_ptr) (i32.const 1)))
          (local.set $bitbuf
            (i64.or
              (local.get $bitbuf)
              (i64.shl (i64.extend_i32_s (local.get $v)) (i64.extend_i32_s (local.get $bitcount)))
            )
          )
          (local.set $bitcount (i32.add (local.get $bitcount) (i32.const 8)))
          (br $fill_loop)
        )
      )
      (i64.store (i32.const 292)
        (i64.shr_u (local.get $bitbuf) (i64.extend_i32_s (local.get $r9)))
      )
      (i32.store (i32.const 300) (i32.sub (local.get $bitcount) (local.get $r9)))
      (i32.store (i32.const 252) (local.get $in_ptr))
      (return
        (i32.and (i32.wrap_i64 (local.get $bitbuf))
          (i32.sub (i32.shl (i32.const 1) (local.get $r9)) (i32.const 1))
        )
      )
    )
    (i32.store (i32.const 148) (global.get $ERR_DECOMP))
    (global.get $ERR_DECOMP)
  )

  ;; === stub dispatch re-exports ===
  (func (export "js5_cache_todo_bzip_dispatch") (result i32)
    (call $bzip_dispatch)
  )

  (func (export "js5_cache_todo_gzip_dispatch") (result i32)
    (call $gzip_dispatch)
  )

  (func (export "js5_cache_todo_deflate_fixed_huffman") (result i32)
    (i32.store (i32.const 148) (global.get $ERR_HEADER))
    (global.get $ERR_HEADER)
  )

  (func (export "js5_cache_todo_deflate_dynamic_huffman") (result i32)
    (i32.store (i32.const 148) (global.get $ERR_HEADER))
    (global.get $ERR_HEADER)
  )
