[package]
name = "edgerun-scheduler"
version.workspace = true
edition.workspace = true

[dependencies]
edgerun-solana = { path = "../edgerun-solana" }
edgerun-config = { path = "../edgerun-config" }
edgerun-mesh = { path = "../edgerun-mesh" }
edgerun-bare-rt = { path = "../edgerun-bare-rt" }
edgerun-error.workspace = true
edgerun-json = { path = "../edgerun-json", features = ["serde"] }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
