[package]
edition.workspace = true
license.workspace = true
name = "codex-tools"
version.workspace = true

[lints]
workspace = true

[features]
default = ["mcp"]
mcp = ["dep:codex-app-server-protocol", "dep:rmcp"]

[dependencies]
codex-app-server-protocol = { workspace = true, optional = true }
codex-code-mode = { workspace = true }
codex-protocol = { workspace = true }
edgerun-json = { workspace = true }
rmcp = { workspace = true, default-features = false, features = [
    "base64",
    "macros",
], optional = true }
tracing = { workspace = true }

[dev-dependencies]
codex_utils_absolute_path = { package = "edgerun-codex-utils-absolute-path", path = "../../utility/edgerun-codex-utils-absolute-path" }
pretty_assertions = { package = "edgerun-pretty-assertions", path = "../../utility/edgerun-pretty-assertions" }
