[package]
name = "edgerun-platform"
version = "0.1.0"
edition.workspace = true
license = "MIT"
publish.workspace = true
description = "Bare-metal and host platform primitives for Edgerun runtimes"

[dependencies]
edgerun-wifi = { path = "../edgerun-wifi" }

[features]
default = []
esp32s3-wifi-blob = []

[target.'cfg(target_arch = "x86_64")'.dependencies]

[target.'cfg(target_arch = "aarch64")'.dependencies]

[target.'cfg(target_arch = "riscv64")'.dependencies]

[lints]
workspace = true
