[package]
name = "edgerun-linux-npu"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Linux NPU discovery adapter for Edgerun"
autobins = false

[dependencies]
edgerun-devices.workspace = true
edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }

[features]
std = []

[lints]
workspace = true
