;; ── JIT backend runtime dispatch ──
(global $JIT_BACKEND (export "JIT_BACKEND") (mut i32) (i32.const 0))

(func $jit_compile (export "jit_compile") (param $func_idx i32) (param $backend i32) (result i32)
  (if (i32.eq (local.get $backend) (i32.const 0))
    (then (return (call $jit_compile_x86_64 (local.get $func_idx))))
  )
  (if (i32.eq (local.get $backend) (i32.const 1))
    (then (return (call $jit_compile_arm32 (local.get $func_idx))))
  )
  (if (i32.eq (local.get $backend) (i32.const 2))
    (then (return (call $jit_compile_aarch64 (local.get $func_idx))))
  )
  (i32.const -1)
)

(func $compile_to_elf (export "compile_to_elf") (param $func_idx i32) (param $backend i32) (result i32 i32)
  (if (i32.eq (local.get $backend) (i32.const 0))
    (then (return (call $compile_to_elf_x86_64 (local.get $func_idx))))
  )
  (if (i32.eq (local.get $backend) (i32.const 1))
    (then (return (call $compile_to_elf_arm32 (local.get $func_idx))))
  )
  (if (i32.eq (local.get $backend) (i32.const 2))
    (then (return (call $compile_to_elf_aarch64 (local.get $func_idx))))
  )
  (i32.const 0) (i32.const 0)
)

(func $compile_to_bin (export "compile_to_bin") (param $func_idx i32) (param $backend i32) (result i32 i32)
  (if (i32.eq (local.get $backend) (i32.const 0))
    (then (return (i32.const 0) (i32.const 0)))
  )
  (if (i32.eq (local.get $backend) (i32.const 1))
    (then (return (call $compile_to_bin_arm32 (local.get $func_idx))))
  )
  (if (i32.eq (local.get $backend) (i32.const 2))
    (then (return (call $compile_to_bin_aarch64 (local.get $func_idx))))
  )
  (i32.const 0) (i32.const 0)
)
