  ;; Auto-generated SIMD/control fallback wrappers for x86 dispatch template calls
  (global $JIT_ERROR_x86_64 (mut i32) (i32.const 0))
  (global $OFF_SYSCALL_MAP i32 (i32.const 0x90000))


  (func $emit_x86_mov_eax_imm (param $val i32)
    (call $emit_x86_byte (i32.const 0xB8))
    (call $emit_x86_dword (local.get $val))
  )

  (func $emit_syscall
    (call $emit_x86_byte (i32.const 0x0F))
    (call $emit_x86_byte (i32.const 0x05))
  )

  (func $emit_x86_syscall
    (call $emit_syscall)
  )

  (func $emit_x86_load_rdi_rsp_disp (param $disp i32)
    (call $emit_x86_rex_w)
    (call $emit_x86_byte (i32.const 0x8B))
    (call $emit_x86_byte (i32.const 0xBC))
    (call $emit_x86_sib (i32.const 0) (i32.const 4) (i32.const 4))
    (call $emit_x86_dword (local.get $disp))
  )

  (func $emit_x86_load_rsi_rsp_disp (param $disp i32)
    (call $emit_x86_rex_w)
    (call $emit_x86_byte (i32.const 0x8B))
    (call $emit_x86_byte (i32.const 0xB4))
    (call $emit_x86_sib (i32.const 0) (i32.const 4) (i32.const 4))
    (call $emit_x86_dword (local.get $disp))
  )

  (func $emit_x86_load_rdx_rsp_disp (param $disp i32)
    (call $emit_x86_rex_w)
    (call $emit_x86_byte (i32.const 0x8B))
    (call $emit_x86_byte (i32.const 0x94))
    (call $emit_x86_sib (i32.const 0) (i32.const 4) (i32.const 4))
    (call $emit_x86_dword (local.get $disp))
  )

  (func $emit_x86_load_r10_rsp_disp (param $disp i32)
    (call $emit_x86_byte (i32.const 0x4C))
    (call $emit_x86_byte (i32.const 0x8B))
    (call $emit_x86_byte (i32.const 0x94))
    (call $emit_x86_sib (i32.const 0) (i32.const 4) (i32.const 4))
    (call $emit_x86_dword (local.get $disp))
  )

  (func $emit_x86_load_r8_rsp_disp (param $disp i32)
    (call $emit_x86_byte (i32.const 0x4C))
    (call $emit_x86_byte (i32.const 0x8B))
    (call $emit_x86_byte (i32.const 0x84))
    (call $emit_x86_sib (i32.const 0) (i32.const 4) (i32.const 4))
    (call $emit_x86_dword (local.get $disp))
  )

  (func $emit_x86_load_r9_rsp_disp (param $disp i32)
    (call $emit_x86_byte (i32.const 0x4C))
    (call $emit_x86_byte (i32.const 0x8B))
    (call $emit_x86_byte (i32.const 0x8C))
    (call $emit_x86_sib (i32.const 0) (i32.const 4) (i32.const 4))
    (call $emit_x86_dword (local.get $disp))
  )

  (func $emit_epilogue
    (call $emit_x86_epilogue)
  )

  ;; ── Control flow templates (using helpers from templates-x86-64.wat) ──

  (func $template_x86_block (param $dec_ptr i32)
    (call $push_label (global.get $JIT_LABEL_BLOCK_x86_64))
  )

  (func $template_x86_loop (param $dec_ptr i32)
    (local $depth i32)
    (call $push_label (global.get $JIT_LABEL_LOOP_x86_64))
    (local.set $depth (i32.sub (i32.load (global.get $JS_LABEL_DEPTH_x86_64)) (i32.const 1)))
    (call $set_label_offset (local.get $depth) (i32.load (global.get $JS_CODE_PTR_x86_64)))
  )

  (func $template_x86_if (param $dec_ptr i32)
    (local $depth i32)
    (call $emit_x86_pop_rax)
    (call $emit_x86_test_eax)
    (call $emit_x86_jz_rel32 (i32.const 0))
    (call $push_label (global.get $JIT_LABEL_IF_x86_64))
    (local.set $depth (i32.sub (i32.load (global.get $JS_LABEL_DEPTH_x86_64)) (i32.const 1)))
    (call $set_label_if_jz (local.get $depth) (i32.load (global.get $JS_CODE_PTR_x86_64)))
  )

  (func $template_x86_else (param $dec_ptr i32)
    (local $depth i32) (local $kind i32) (local $jz_off i32) (local $code_ptr i32) (local $disp i32)
    (local.set $depth (call $pop_label))
    (local.set $kind (call $get_label_kind (local.get $depth)))
    (local.set $code_ptr (i32.load (global.get $JS_CODE_PTR_x86_64)))
    (local.set $jz_off (call $get_label_if_jz (local.get $depth)))
    (local.set $disp (i32.sub (local.get $code_ptr) (i32.add (local.get $jz_off) (i32.const 4))))
    (i32.store (i32.add (global.get $JIT_CACHE) (local.get $jz_off)) (local.get $disp))
    (call $emit_x86_jmp_rel32 (i32.const 0))
    (call $push_label (global.get $JIT_LABEL_ELSE))
    (call $set_label_offset (local.get $depth) (i32.sub (i32.load (global.get $JS_CODE_PTR_x86_64)) (i32.const 4)))
  )

  (func $template_x86_end (param $dec_ptr i32)
    (local $depth i32) (local $kind i32) (local $code_ptr i32) (local $disp i32) (local $loop_start i32)
    (local.set $depth (call $pop_label))
    (local.set $kind (call $get_label_kind (local.get $depth)))
    (local.set $code_ptr (i32.load (global.get $JS_CODE_PTR_x86_64)))
    (if (i32.eq (local.get $kind) (global.get $JIT_LABEL_LOOP_x86_64))
      (then
        (local.set $loop_start (call $get_label_offset (local.get $depth)))
        (local.set $disp (i32.sub (local.get $loop_start) (i32.add (local.get $code_ptr) (i32.const 5))))
        (call $emit_x86_jmp_rel32 (local.get $disp))
      )
      (else
        (call $patch_fixups (local.get $depth))
        (if (i32.eq (local.get $kind) (global.get $JIT_LABEL_IF_x86_64))
          (then
            (local.set $loop_start (call $get_label_if_jz (local.get $depth)))
            (local.set $disp (i32.sub (local.get $code_ptr) (i32.add (local.get $loop_start) (i32.const 4))))
            (i32.store (i32.add (global.get $JIT_CACHE) (local.get $loop_start)) (local.get $disp))
          )
        )
        (if (i32.eq (local.get $kind) (global.get $JIT_LABEL_ELSE))
          (then
            (local.set $loop_start (call $get_label_offset (local.get $depth)))
            (local.set $disp (i32.sub (local.get $code_ptr) (i32.add (local.get $loop_start) (i32.const 4))))
            (i32.store (i32.add (global.get $JIT_CACHE) (local.get $loop_start)) (local.get $disp))
          )
        )
      )
    )
  )

  (func $template_x86_br (param $dec_ptr i32)
    (local $depth i32) (local $target_depth i32) (local $kind i32) (local $code_ptr i32) (local $disp i32)
    (local.set $depth (i32.load (i32.add (local.get $dec_ptr) (i32.const 4))))
    (local.set $target_depth (i32.sub (i32.sub (i32.load (global.get $JS_LABEL_DEPTH_x86_64)) (i32.const 1)) (local.get $depth)))
    (local.set $kind (call $get_label_kind (local.get $target_depth)))
    (local.set $code_ptr (i32.load (global.get $JS_CODE_PTR_x86_64)))
    (if (i32.eq (local.get $kind) (global.get $JIT_LABEL_LOOP_x86_64))
      (then
        (local.set $disp (i32.sub (call $get_label_offset (local.get $target_depth)) (i32.add (local.get $code_ptr) (i32.const 5))))
        (call $emit_x86_jmp_rel32 (local.get $disp))
      )
      (else
        (call $emit_x86_jmp_rel32 (i32.const 0))
        (call $push_fixup (local.get $target_depth))
      )
    )
  )

  (func $template_x86_br_if (param $dec_ptr i32)
    (local $depth i32) (local $target_depth i32) (local $kind i32) (local $code_ptr i32) (local $disp i32)
    (call $emit_x86_pop_rax)
    (call $emit_x86_test_eax)
    (local.set $depth (i32.load (i32.add (local.get $dec_ptr) (i32.const 4))))
    (local.set $target_depth (i32.sub (i32.sub (i32.load (global.get $JS_LABEL_DEPTH_x86_64)) (i32.const 1)) (local.get $depth)))
    (local.set $kind (call $get_label_kind (local.get $target_depth)))
    (local.set $code_ptr (i32.load (global.get $JS_CODE_PTR_x86_64)))
    (if (i32.eq (local.get $kind) (global.get $JIT_LABEL_LOOP_x86_64))
      (then
        (local.set $disp (i32.sub (call $get_label_offset (local.get $target_depth)) (i32.add (local.get $code_ptr) (i32.const 6))))
        (call $emit_x86_jne_rel32 (local.get $disp))
      )
      (else
        (call $emit_x86_jne_rel32 (i32.const 0))
        (call $push_fixup (local.get $target_depth))
      )
    )
  )

  (func $template_x86_br_table (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_add (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_eq (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_extract_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_ge (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_gt (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_le (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_lt (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_max (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_min (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_mul (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_ne (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_neg (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_replace_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f32x4_sub (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_add (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_eq (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_extract_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_ge (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_gt (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_le (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_lt (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_max (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_min (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_mul (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_ne (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_neg (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_replace_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_f64x2_sub (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_add (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_avgr_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_eq (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_extract_lane_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_extract_lane_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_ge_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_ge_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_gt_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_gt_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_le_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_le_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_lt_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_lt_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_max_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_min_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_mul (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_ne (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_neg (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_replace_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i16x8_sub (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_add (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_eq (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_extract_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_ge_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_ge_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_gt_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_gt_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_le_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_le_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_lt_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_lt_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_mul (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_ne (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_neg (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_replace_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i32x4_sub (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i64x2_add (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i64x2_extract_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i64x2_neg (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i64x2_replace_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i64x2_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i64x2_sub (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_add (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_and (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_avgr_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_eq (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_extract_lane_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_extract_lane_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_ge_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_ge_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_gt_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_gt_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_le_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_le_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_lt_s (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_lt_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_max_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_min_u (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_mul (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_ne (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_neg (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_or (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_replace_lane (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_sub (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_swizzle (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_i8x16_xor (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_return (param $dec_ptr i32)
    ;; Pop return value into EAX, then epilogue
    (call $emit_x86_byte (i32.const 0x58))  ;; pop rax
    (call $emit_x86_epilogue)
  )

  (func $template_x86_return_call (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_bitselect (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_const (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_load (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_load16_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_load32_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_load64_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_load8_splat (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_not (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

  (func $template_x86_v128_store (param $dec_ptr i32)
    (call $template_x86_unsupported (local.get $dec_ptr))
  )

(func $jit_compile_x86_64 (export "jit_compile_x86_64") (param $func_idx i32) (result i32)
    (local $dec_ptr i32) (local $opcode i32) (local $imm0 i32)
    (local $code_start i32) (local $label_level i32)
    (local $loop_top_offset i32)
    (local $decoded_ops_base i32) (local $decoded_ops_count i32)

    ;; Reset label depth (NOT code ptr or fixup count — caller manages those for multi-function)
    (i32.store (global.get $JS_LABEL_DEPTH_x86_64) (i32.const 0))

    ;; Get decoded_ops base from imported global
    (local.set $decoded_ops_base (global.get $OFF_DECODED_OPS))

    ;; ── Record this function's offset in func_off_table ────────────
    (i32.store
      (i32.add (global.get $FUNC_OFF_TABLE_x86_64) (i32.shl (local.get $func_idx) (i32.const 2)))
      (i32.load (global.get $JS_CODE_PTR_x86_64))
    )

    ;; ── Emit prologue ─────────────────────────────────────────────
    (call $emit_x86_prologue)

    ;; ── Main compile loop ─────────────────────────────────────────
    (local.set $dec_ptr (local.get $decoded_ops_base))
    (block $compile_done
      (loop $compile_loop
        ;; Read opcode
        (local.set $opcode (i32.load (local.get $dec_ptr)))

        ;; Read next opcode for peephole (at dec_ptr + DEC_SZ)
        ;; Dispatch by opcode (flat if+br pattern)
        (block $dispatch_done
          (if (i32.eqz (local.get $opcode))
            (then (call $template_x86_unreachable (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x01))
            (then (call $template_x86_nop (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x02))
            (then (call $template_x86_block (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x03))
            (then
              (local.set $loop_top_offset (i32.load (global.get $JS_CODE_PTR_x86_64)))
              (call $template_x86_loop (local.get $dec_ptr))
              (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x04))
            (then (call $template_x86_if (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x05))
            (then (call $template_x86_else (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0B))
            (then (call $template_x86_end (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0C))
            (then (call $template_x86_br (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0D))
            (then (call $template_x86_br_if (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0E))
            (then (call $template_x86_br_table (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0F))
            (then (call $template_x86_return (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x10))
            (then (call $template_x86_call (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x12))
            (then (call $template_x86_return_call (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x1A))
            (then (call $template_x86_drop (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x1B))
            (then (call $template_x86_select (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x20))
            (then (call $template_x86_local_get (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x21))
            (then (call $template_x86_local_set (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x22))
            (then (call $template_x86_local_tee (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x23))
            (then (call $template_x86_global_get (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x24))
            (then (call $template_x86_global_set (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x25))
            (then (call $template_x86_table_get (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x26))
            (then (call $template_x86_table_set (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x28))
            (then (call $template_x86_i32_load (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x29))
            (then (call $template_x86_i64_load (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2C))
            (then (call $template_x86_i32_load8_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2D))
            (then (call $template_x86_i32_load8_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2E))
            (then (call $template_x86_i32_load16_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2F))
            (then (call $template_x86_i32_load16_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x36))
            (then (call $template_x86_i32_store (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x37))
            (then (call $template_x86_i64_store (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x3A))
            (then (call $template_x86_i32_store8 (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x3B))
            (then (call $template_x86_i32_store16 (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x3F))
            (then (call $template_x86_memory_size (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x40))
            (then (call $template_x86_memory_grow (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x41))
            (then (call $template_x86_i32_const (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x42))
            (then (call $template_x86_i64_const (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x45))
            (then (call $template_x86_i32_eqz (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x46))
            (then (call $template_x86_i32_eq (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x47))
            (then (call $template_x86_i32_ne (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x48))
            (then (call $template_x86_i32_lt_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x49))
            (then (call $template_x86_i32_lt_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4A))
            (then (call $template_x86_i32_gt_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4B))
            (then (call $template_x86_i32_gt_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4C))
            (then (call $template_x86_i32_le_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4D))
            (then (call $template_x86_i32_le_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x50))
            (then (call $template_x86_i64_eqz (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x51))
            (then (call $template_x86_i64_eq (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x52))
            (then (call $template_x86_i64_ne (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x53))
            (then (call $template_x86_i64_lt_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x54))
            (then (call $template_x86_i64_lt_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x55))
            (then (call $template_x86_i64_gt_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x56))
            (then (call $template_x86_i64_gt_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x57))
            (then (call $template_x86_i64_le_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x58))
            (then (call $template_x86_i64_le_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x67))
            (then (call $template_x86_i32_clz (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x68))
            (then (call $template_x86_i32_ctz (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x69))
            (then (call $template_x86_i32_popcnt (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6A))
            (then (call $template_x86_i32_add (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6B))
            (then (call $template_x86_i32_sub (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6C))
            (then (call $template_x86_i32_mul (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6D))
            (then (call $template_x86_i32_div_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6E))
            (then (call $template_x86_i32_div_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6F))
            (then (call $template_x86_i32_rem_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x70))
            (then (call $template_x86_i32_rem_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x71))
            (then (call $template_x86_i32_and (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x72))
            (then (call $template_x86_i32_or (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x73))
            (then (call $template_x86_i32_xor (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x74))
            (then (call $template_x86_i32_shl (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x75))
            (then (call $template_x86_i32_shr_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x76))
            (then (call $template_x86_i32_shr_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x77))
            (then (call $template_x86_i32_rotl (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x78))
            (then (call $template_x86_i32_rotr (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x79))
            (then (call $template_x86_i64_clz (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7A))
            (then (call $template_x86_i64_ctz (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7B))
            (then (call $template_x86_i64_popcnt (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7C))
            (then (call $template_x86_i64_add (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7D))
            (then (call $template_x86_i64_sub (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7E))
            (then (call $template_x86_i64_mul (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7F))
            (then (call $template_x86_i64_div_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x80))
            (then (call $template_x86_i64_div_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x81))
            (then (call $template_x86_i64_rem_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x82))
            (then (call $template_x86_i64_rem_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x83))
            (then (call $template_x86_i64_and (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x84))
            (then (call $template_x86_i64_or (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x85))
            (then (call $template_x86_i64_xor (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x86))
            (then (call $template_x86_i64_shl (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x87))
            (then (call $template_x86_i64_shr_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x88))
            (then (call $template_x86_i64_shr_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x89))
            (then (call $template_x86_i64_rotl (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x8A))
            (then (call $template_x86_i64_rotr (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xA7))
            (then (call $template_x86_i32_wrap_i64 (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAC))
            (then (call $template_x86_i64_extend_i32_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAD))
            (then (call $template_x86_i64_extend_i32_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBC))
            (then (call $template_x86_i32_reinterpret_f32 (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBD))
            (then (call $template_x86_f32_reinterpret_i32 (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBE))
            (then (call $template_x86_i64_reinterpret_f64 (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBF))
            (then (call $template_x86_f64_reinterpret_i64 (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xA8))
            (then (call $template_x86_i32_trunc_f32_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xA9))
            (then (call $template_x86_i32_trunc_f32_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAA))
            (then (call $template_x86_i32_trunc_f64_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAB))
            (then (call $template_x86_i32_trunc_f64_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAE))
            (then (call $template_x86_i64_trunc_f32_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAF))
            (then (call $template_x86_i64_trunc_f32_u (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xB0))
            (then (call $template_x86_i64_trunc_f64_s (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xB1))
            (then (call $template_x86_i64_trunc_f64_u (local.get $dec_ptr)) (br $dispatch_done)))
          ;; 0xFC prefix - dispatch on imm0
          (if (i32.eq (local.get $opcode) (i32.const 0xFC))
            (then
              (local.set $imm0 (i32.load (i32.add (local.get $dec_ptr) (i32.const 4))))
              (block $fc_done
                (if (i32.eq (local.get $imm0) (i32.const 0x00))
                  (then (call $template_x86_i32_trunc_sat_f32_s (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x01))
                  (then (call $template_x86_i32_trunc_sat_f32_u (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x02))
                  (then (call $template_x86_i32_trunc_sat_f64_s (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x03))
                  (then (call $template_x86_i32_trunc_sat_f64_u (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x04))
                  (then (call $template_x86_i64_trunc_sat_f32_s (local.get $dec_ptr)) (br $fc_done)))
                ;; Unknown 0xFC sub-opcode
                (global.set $JIT_ERROR_x86_64 (i32.const -3))
              )
              (br $dispatch_done)
            )
          )
          ;; 0xFD prefix (SIMD) - dispatch on imm0
          (if (i32.eq (local.get $opcode) (i32.const 0xFD))
            (then
              (local.set $imm0 (i32.load (i32.add (local.get $dec_ptr) (i32.const 4))))
              (block $fd_done
                ;; v128.load (0x00)
                (if (i32.eq (local.get $imm0) (i32.const 0x00))
                  (then (call $template_x86_v128_load (local.get $dec_ptr)) (br $fd_done)))
                ;; v128.store (0x1B)
                (if (i32.eq (local.get $imm0) (i32.const 0x1B))
                  (then (call $template_x86_v128_store (local.get $dec_ptr)) (br $fd_done)))
                ;; v128.const (0x0C)
                (if (i32.eq (local.get $imm0) (i32.const 0x0C))
                  (then (call $template_x86_v128_const (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.splat (0x2D)
                (if (i32.eq (local.get $imm0) (i32.const 0x2D))
                  (then (call $template_x86_i8x16_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.splat (0x31)
                (if (i32.eq (local.get $imm0) (i32.const 0x31))
                  (then (call $template_x86_i16x8_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.splat (0x35)
                (if (i32.eq (local.get $imm0) (i32.const 0x35))
                  (then (call $template_x86_i32x4_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; i64x2.splat (0x39)
                (if (i32.eq (local.get $imm0) (i32.const 0x39))
                  (then (call $template_x86_i64x2_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.splat (0x3A)
                (if (i32.eq (local.get $imm0) (i32.const 0x3A))
                  (then (call $template_x86_f32x4_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.splat (0x3D)
                (if (i32.eq (local.get $imm0) (i32.const 0x3D))
                  (then (call $template_x86_f64x2_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.extract_lane_s (0x2E)
                (if (i32.eq (local.get $imm0) (i32.const 0x2E))
                  (then (call $template_x86_i8x16_extract_lane_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.extract_lane_u (0x2F)
                (if (i32.eq (local.get $imm0) (i32.const 0x2F))
                  (then (call $template_x86_i8x16_extract_lane_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.extract_lane_s (0x32)
                (if (i32.eq (local.get $imm0) (i32.const 0x32))
                  (then (call $template_x86_i16x8_extract_lane_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.extract_lane_u (0x33)
                (if (i32.eq (local.get $imm0) (i32.const 0x33))
                  (then (call $template_x86_i16x8_extract_lane_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.extract_lane (0x36)
                (if (i32.eq (local.get $imm0) (i32.const 0x36))
                  (then (call $template_x86_i32x4_extract_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; i64x2.extract_lane (0x38)
                (if (i32.eq (local.get $imm0) (i32.const 0x38))
                  (then (call $template_x86_i64x2_extract_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.extract_lane (0x3B)
                (if (i32.eq (local.get $imm0) (i32.const 0x3B))
                  (then (call $template_x86_f32x4_extract_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.extract_lane (0x3E)
                (if (i32.eq (local.get $imm0) (i32.const 0x3E))
                  (then (call $template_x86_f64x2_extract_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.replace_lane (0x30)
                (if (i32.eq (local.get $imm0) (i32.const 0x30))
                  (then (call $template_x86_i8x16_replace_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.replace_lane (0x34)
                (if (i32.eq (local.get $imm0) (i32.const 0x34))
                  (then (call $template_x86_i16x8_replace_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.replace_lane (0x37)
                (if (i32.eq (local.get $imm0) (i32.const 0x37))
                  (then (call $template_x86_i32x4_replace_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; i64x2.replace_lane (0xAB) — canonical ID, not in old encoding
                ;; f32x4.replace_lane (0x3C)
                (if (i32.eq (local.get $imm0) (i32.const 0x3C))
                  (then (call $template_x86_f32x4_replace_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.replace_lane (0x3F)
                (if (i32.eq (local.get $imm0) (i32.const 0x3F))
                  (then (call $template_x86_f64x2_replace_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.add (0x40)
                (if (i32.eq (local.get $imm0) (i32.const 0x40))
                  (then (call $template_x86_i8x16_add (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.add (0x51)
                (if (i32.eq (local.get $imm0) (i32.const 0x51))
                  (then (call $template_x86_i16x8_add (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.add (0x62)
                (if (i32.eq (local.get $imm0) (i32.const 0x62))
                  (then (call $template_x86_i32x4_add (local.get $dec_ptr)) (br $fd_done)))
                ;; i64x2.add (0x73)
                (if (i32.eq (local.get $imm0) (i32.const 0x73))
                  (then (call $template_x86_i64x2_add (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.add (0x84)
                (if (i32.eq (local.get $imm0) (i32.const 0x84))
                  (then (call $template_x86_f32x4_add (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.add (0x95)
                (if (i32.eq (local.get $imm0) (i32.const 0x95))
                  (then (call $template_x86_f64x2_add (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.sub (0x41)
                (if (i32.eq (local.get $imm0) (i32.const 0x41))
                  (then (call $template_x86_i8x16_sub (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.sub (0x52)
                (if (i32.eq (local.get $imm0) (i32.const 0x52))
                  (then (call $template_x86_i16x8_sub (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.sub (0x63)
                (if (i32.eq (local.get $imm0) (i32.const 0x63))
                  (then (call $template_x86_i32x4_sub (local.get $dec_ptr)) (br $fd_done)))
                ;; i64x2.sub (0x74)
                (if (i32.eq (local.get $imm0) (i32.const 0x74))
                  (then (call $template_x86_i64x2_sub (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.sub (0x85)
                (if (i32.eq (local.get $imm0) (i32.const 0x85))
                  (then (call $template_x86_f32x4_sub (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.sub (0x96)
                (if (i32.eq (local.get $imm0) (i32.const 0x96))
                  (then (call $template_x86_f64x2_sub (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.mul (0x50)
                (if (i32.eq (local.get $imm0) (i32.const 0x50))
                  (then (call $template_x86_i8x16_mul (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.mul (0x61)
                (if (i32.eq (local.get $imm0) (i32.const 0x61))
                  (then (call $template_x86_i16x8_mul (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.mul (0x72)
                (if (i32.eq (local.get $imm0) (i32.const 0x72))
                  (then (call $template_x86_i32x4_mul (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.mul (0x87)
                (if (i32.eq (local.get $imm0) (i32.const 0x87))
                  (then (call $template_x86_f32x4_mul (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.mul (0x98)
                (if (i32.eq (local.get $imm0) (i32.const 0x98))
                  (then (call $template_x86_f64x2_mul (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.neg (0x46)
                (if (i32.eq (local.get $imm0) (i32.const 0x46))
                  (then (call $template_x86_i8x16_neg (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.neg (0x57)
                (if (i32.eq (local.get $imm0) (i32.const 0x57))
                  (then (call $template_x86_i16x8_neg (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.neg (0x68)
                (if (i32.eq (local.get $imm0) (i32.const 0x68))
                  (then (call $template_x86_i32x4_neg (local.get $dec_ptr)) (br $fd_done)))
                ;; i64x2.neg (0x79)
                (if (i32.eq (local.get $imm0) (i32.const 0x79))
                  (then (call $template_x86_i64x2_neg (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.neg (0x8A)
                (if (i32.eq (local.get $imm0) (i32.const 0x8A))
                  (then (call $template_x86_f32x4_neg (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.neg (0x9B)
                (if (i32.eq (local.get $imm0) (i32.const 0x9B))
                  (then (call $template_x86_f64x2_neg (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.eq (0x47)
                (if (i32.eq (local.get $imm0) (i32.const 0x47))
                  (then (call $template_x86_i8x16_eq (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.eq (0x58)
                (if (i32.eq (local.get $imm0) (i32.const 0x58))
                  (then (call $template_x86_i16x8_eq (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.eq (0x69)
                (if (i32.eq (local.get $imm0) (i32.const 0x69))
                  (then (call $template_x86_i32x4_eq (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.eq (0x8C)
                (if (i32.eq (local.get $imm0) (i32.const 0x8C))
                  (then (call $template_x86_f32x4_eq (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.eq (0x9D)
                (if (i32.eq (local.get $imm0) (i32.const 0x9D))
                  (then (call $template_x86_f64x2_eq (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.ne (0x48)
                (if (i32.eq (local.get $imm0) (i32.const 0x48))
                  (then (call $template_x86_i8x16_ne (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.ne (0x59)
                (if (i32.eq (local.get $imm0) (i32.const 0x59))
                  (then (call $template_x86_i16x8_ne (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.ne (0x6A)
                (if (i32.eq (local.get $imm0) (i32.const 0x6A))
                  (then (call $template_x86_i32x4_ne (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.ne (0x8B)
                (if (i32.eq (local.get $imm0) (i32.const 0x8B))
                  (then (call $template_x86_f32x4_ne (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.ne (0x9C)
                (if (i32.eq (local.get $imm0) (i32.const 0x9C))
                  (then (call $template_x86_f64x2_ne (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.lt_s (0x4B)
                (if (i32.eq (local.get $imm0) (i32.const 0x4B))
                  (then (call $template_x86_i8x16_lt_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.lt_u (0x4A)
                (if (i32.eq (local.get $imm0) (i32.const 0x4A))
                  (then (call $template_x86_i8x16_lt_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.lt_s (0x5C)
                (if (i32.eq (local.get $imm0) (i32.const 0x5C))
                  (then (call $template_x86_i16x8_lt_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.lt_u (0x5B)
                (if (i32.eq (local.get $imm0) (i32.const 0x5B))
                  (then (call $template_x86_i16x8_lt_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.lt_s (0x6D)
                (if (i32.eq (local.get $imm0) (i32.const 0x6D))
                  (then (call $template_x86_i32x4_lt_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.lt_u (0x6C)
                (if (i32.eq (local.get $imm0) (i32.const 0x6C))
                  (then (call $template_x86_i32x4_lt_u (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.lt (0x8E)
                (if (i32.eq (local.get $imm0) (i32.const 0x8E))
                  (then (call $template_x86_f32x4_lt (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.lt (0x9F)
                (if (i32.eq (local.get $imm0) (i32.const 0x9F))
                  (then (call $template_x86_f64x2_lt (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.gt_s (0x4D)
                (if (i32.eq (local.get $imm0) (i32.const 0x4D))
                  (then (call $template_x86_i8x16_gt_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.gt_u (0x4C)
                (if (i32.eq (local.get $imm0) (i32.const 0x4C))
                  (then (call $template_x86_i8x16_gt_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.gt_s (0x5E)
                (if (i32.eq (local.get $imm0) (i32.const 0x5E))
                  (then (call $template_x86_i16x8_gt_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.gt_u (0x5D)
                (if (i32.eq (local.get $imm0) (i32.const 0x5D))
                  (then (call $template_x86_i16x8_gt_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.gt_s (0x6F)
                (if (i32.eq (local.get $imm0) (i32.const 0x6F))
                  (then (call $template_x86_i32x4_gt_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.gt_u (0x6E)
                (if (i32.eq (local.get $imm0) (i32.const 0x6E))
                  (then (call $template_x86_i32x4_gt_u (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.gt (0x90)
                (if (i32.eq (local.get $imm0) (i32.const 0x90))
                  (then (call $template_x86_f32x4_gt (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.gt (0xA1)
                (if (i32.eq (local.get $imm0) (i32.const 0xA1))
                  (then (call $template_x86_f64x2_gt (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.le_s (0x4F)
                (if (i32.eq (local.get $imm0) (i32.const 0x4F))
                  (then (call $template_x86_i8x16_le_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.le_u (0x4E)
                (if (i32.eq (local.get $imm0) (i32.const 0x4E))
                  (then (call $template_x86_i8x16_le_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.le_s (0x60)
                (if (i32.eq (local.get $imm0) (i32.const 0x60))
                  (then (call $template_x86_i16x8_le_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.le_u (0x5F)
                (if (i32.eq (local.get $imm0) (i32.const 0x5F))
                  (then (call $template_x86_i16x8_le_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.le_s (0x71)
                (if (i32.eq (local.get $imm0) (i32.const 0x71))
                  (then (call $template_x86_i32x4_le_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.le_u (0x70)
                (if (i32.eq (local.get $imm0) (i32.const 0x70))
                  (then (call $template_x86_i32x4_le_u (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.le (0x92)
                (if (i32.eq (local.get $imm0) (i32.const 0x92))
                  (then (call $template_x86_f32x4_le (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.le (0xA3)
                (if (i32.eq (local.get $imm0) (i32.const 0xA3))
                  (then (call $template_x86_f64x2_le (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.ge_s (0x49)
                (if (i32.eq (local.get $imm0) (i32.const 0x49))
                  (then (call $template_x86_i8x16_ge_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.ge_s (0x5A)
                (if (i32.eq (local.get $imm0) (i32.const 0x5A))
                  (then (call $template_x86_i16x8_ge_s (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.ge_s (0x6B)
                (if (i32.eq (local.get $imm0) (i32.const 0x6B))
                  (then (call $template_x86_i32x4_ge_s (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.ge (0x94)
                (if (i32.eq (local.get $imm0) (i32.const 0x94))
                  (then (call $template_x86_f32x4_ge (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.ge (0xA5)
                (if (i32.eq (local.get $imm0) (i32.const 0xA5))
                  (then (call $template_x86_f64x2_ge (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.and (0x43)
                (if (i32.eq (local.get $imm0) (i32.const 0x43))
                  (then (call $template_x86_i8x16_and (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.or (0x44)
                (if (i32.eq (local.get $imm0) (i32.const 0x44))
                  (then (call $template_x86_i8x16_or (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.xor (0x45)
                (if (i32.eq (local.get $imm0) (i32.const 0x45))
                  (then (call $template_x86_i8x16_xor (local.get $dec_ptr)) (br $fd_done)))
                ;; ── New canonical ops (0xA6+, not in old encoding) ──
                ;; v128.load8_splat (0xA6)
                (if (i32.eq (local.get $imm0) (i32.const 0xA6))
                  (then (call $template_x86_v128_load8_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; v128.load16_splat (0xA7)
                (if (i32.eq (local.get $imm0) (i32.const 0xA7))
                  (then (call $template_x86_v128_load16_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; v128.load32_splat (0xA8)
                (if (i32.eq (local.get $imm0) (i32.const 0xA8))
                  (then (call $template_x86_v128_load32_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; v128.load64_splat (0xA9)
                (if (i32.eq (local.get $imm0) (i32.const 0xA9))
                  (then (call $template_x86_v128_load64_splat (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.swizzle (0xAA)
                (if (i32.eq (local.get $imm0) (i32.const 0xAA))
                  (then (call $template_x86_i8x16_swizzle (local.get $dec_ptr)) (br $fd_done)))
                ;; i64x2.replace_lane (0xAB)
                (if (i32.eq (local.get $imm0) (i32.const 0xAB))
                  (then (call $template_x86_i64x2_replace_lane (local.get $dec_ptr)) (br $fd_done)))
                ;; v128.not (0xAC)
                (if (i32.eq (local.get $imm0) (i32.const 0xAC))
                  (then (call $template_x86_v128_not (local.get $dec_ptr)) (br $fd_done)))
                ;; v128.bitselect (0xAD)
                (if (i32.eq (local.get $imm0) (i32.const 0xAD))
                  (then (call $template_x86_v128_bitselect (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.ge_u (0xAE)
                (if (i32.eq (local.get $imm0) (i32.const 0xAE))
                  (then (call $template_x86_i8x16_ge_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.ge_u (0xAF)
                (if (i32.eq (local.get $imm0) (i32.const 0xAF))
                  (then (call $template_x86_i16x8_ge_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i32x4.ge_u (0xB0)
                (if (i32.eq (local.get $imm0) (i32.const 0xB0))
                  (then (call $template_x86_i32x4_ge_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.min_u (0xB8)
                (if (i32.eq (local.get $imm0) (i32.const 0xB8))
                  (then (call $template_x86_i8x16_min_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.max_u (0xBA)
                (if (i32.eq (local.get $imm0) (i32.const 0xBA))
                  (then (call $template_x86_i8x16_max_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i8x16.avgr_u (0xBB)
                (if (i32.eq (local.get $imm0) (i32.const 0xBB))
                  (then (call $template_x86_i8x16_avgr_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.min_u (0xBC)
                (if (i32.eq (local.get $imm0) (i32.const 0xBC))
                  (then (call $template_x86_i16x8_min_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.max_u (0xBE)
                (if (i32.eq (local.get $imm0) (i32.const 0xBE))
                  (then (call $template_x86_i16x8_max_u (local.get $dec_ptr)) (br $fd_done)))
                ;; i16x8.avgr_u (0xBF)
                (if (i32.eq (local.get $imm0) (i32.const 0xBF))
                  (then (call $template_x86_i16x8_avgr_u (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.min (0xE1)
                (if (i32.eq (local.get $imm0) (i32.const 0xE1))
                  (then (call $template_x86_f32x4_min (local.get $dec_ptr)) (br $fd_done)))
                ;; f32x4.max (0xE2)
                (if (i32.eq (local.get $imm0) (i32.const 0xE2))
                  (then (call $template_x86_f32x4_max (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.min (0xE3)
                (if (i32.eq (local.get $imm0) (i32.const 0xE3))
                  (then (call $template_x86_f64x2_min (local.get $dec_ptr)) (br $fd_done)))
                ;; f64x2.max (0xE4)
                (if (i32.eq (local.get $imm0) (i32.const 0xE4))
                  (then (call $template_x86_f64x2_max (local.get $dec_ptr)) (br $fd_done)))
                ;; Unknown 0xFD sub-opcode
                (global.set $JIT_ERROR_x86_64 (i32.const -4))
              )
              (br $dispatch_done)
            )
          )
          ;; Unknown opcode
          (global.set $JIT_ERROR_x86_64 (i32.const -2))
        )
        ;; Advance to next decoded op
        (local.set $dec_ptr (i32.add (local.get $dec_ptr) (global.get $DEC_SZ)))
        ;; return (0x0F) is always function end
        (br_if $compile_done (i32.eq (local.get $opcode) (i32.const 0x0F)))
        ;; end (0x0B): stop only when block_depth went negative (function end)
        (br_if $compile_done (i32.lt_s (i32.load (global.get $JS_LABEL_DEPTH_x86_64)) (i32.const 0)))
        (br $compile_loop)
      )
    )

    ;; ── Pop return value into EAX, then epilogue ──────────────────
    (call $emit_x86_byte (i32.const 0x58))  ;; pop rax
    (call $emit_epilogue)

    ;; ── Return code size ──────────────────────────────────────────
    (i32.load (global.get $JS_CODE_PTR_x86_64))
  )
