;; ═════════════════════════════════════════════════════════════════════
  ;; JIT Compile Dispatch — generated from jit-dispatch.in.wat
  ;; Use SFFX placeholder for arch suffix (x86_64 / arm32 / aarch64)
  ;; ═════════════════════════════════════════════════════════════════════
  (func $jit_compile_SFFX (export "jit_compile_SFFX") (param $func_idx i32) (result i32)
    (local $dec_ptr i32) (local $opcode i32) (local $imm0 i32)
    (local $code_start i32) (local $label_level i32)
    (local $loop_top_offset i32)
    (local $decoded_ops_base i32) (local $decoded_ops_count i32)

    ;; Reset label depth (NOT code ptr or fixup count — caller manages those for multi-function)
    (i32.store (global.get $JS_LABEL_DEPTH_SFFX) (i32.const 0))

    ;; Get decoded_ops base from imported global
    (local.set $decoded_ops_base (global.get $OFF_DECODED_OPS))

    ;; ── Record this function's offset in func_off_table ────────────
    (i32.store
      (i32.add (global.get $FUNC_OFF_TABLE_SFFX) (i32.shl (local.get $func_idx) (i32.const 2)))
      (i32.load (global.get $JS_CODE_PTR_SFFX))
    )

    ;; ── Emit prologue ─────────────────────────────────────────────
    (call $EMIT_PROLOGUE)

    ;; ── Read next op for peephole ─────────────────────────────────
    (if (i32.load (i32.add (local.get $dec_ptr) (global.get $DEC_SZ)))
      (then (global.set $NEXT_OP_SFFX (i32.load (i32.add (local.get $dec_ptr) (global.get $DEC_SZ)))))
      (else (global.set $NEXT_OP_SFFX (i32.const 0)))
    )

    ;; ── Main compile loop ─────────────────────────────────────────
    (local.set $dec_ptr (local.get $decoded_ops_base))
    (block $compile_done
      (loop $compile_loop
        ;; Read opcode
        (local.set $opcode (i32.load (local.get $dec_ptr)))

        ;; Read next opcode for peephole (at dec_ptr + DEC_SZ)
        (if (i32.load (i32.add (local.get $dec_ptr) (global.get $DEC_SZ)))
          (then
            (global.set $NEXT_OP_SFFX (i32.load (i32.add (local.get $dec_ptr) (global.get $DEC_SZ))))
          )
          (else
            (global.set $NEXT_OP_SFFX (i32.const 0))
          )
        )

        ;; Dispatch by opcode (flat if+br pattern)
        (block $dispatch_done
          (if (i32.eqz (local.get $opcode))
            (then (call $template_unreachable_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x01))
            (then (call $template_nop_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x02))
            (then (call $template_block_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x03))
            (then
              (local.set $loop_top_offset (i32.load (global.get $JS_CODE_PTR_SFFX)))
              (call $template_loop_SFFX (local.get $dec_ptr))
              (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x04))
            (then (call $template_if_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x05))
            (then (call $template_else_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0B))
            (then (call $template_end_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0C))
            (then (call $template_br_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0D))
            (then (call $template_br_if_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0E))
            (then (call $template_br_table_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x0F))
            (then (call $template_return_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x10))
            (then (call $template_call_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x12))
            (then (call $template_return_call_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x1A))
            (then (call $template_drop_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x1B))
            (then (call $template_select_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x20))
            (then (call $template_local_get_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x21))
            (then (call $template_local_set_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x22))
            (then (call $template_local_tee_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x23))
            (then (call $template_global_get_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x24))
            (then (call $template_global_set_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x25))
            (then (call $template_table_get_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x26))
            (then (call $template_table_set_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x28))
            (then (call $template_i32_load_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x29))
            (then (call $template_i64_load_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2C))
            (then (call $template_i32_load8_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2D))
            (then (call $template_i32_load8_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2E))
            (then (call $template_i32_load16_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x2F))
            (then (call $template_i32_load16_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x36))
            (then (call $template_i32_store_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x37))
            (then (call $template_i64_store_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x3A))
            (then (call $template_i32_store8_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x3B))
            (then (call $template_i32_store16_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x3F))
            (then (call $template_memory_size_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x40))
            (then (call $template_memory_grow_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x41))
            (then (call $template_i32_const_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x42))
            (then (call $template_i64_const_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x45))
            (then (call $template_i32_eqz_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x46))
            (then (call $template_i32_eq_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x47))
            (then (call $template_i32_ne_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x48))
            (then (call $template_i32_lt_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x49))
            (then (call $template_i32_lt_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4A))
            (then (call $template_i32_gt_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4B))
            (then (call $template_i32_gt_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4C))
            (then (call $template_i32_le_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x4D))
            (then (call $template_i32_le_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x50))
            (then (call $template_i64_eqz_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x51))
            (then (call $template_i64_eq_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x52))
            (then (call $template_i64_ne_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x53))
            (then (call $template_i64_lt_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x54))
            (then (call $template_i64_lt_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x55))
            (then (call $template_i64_gt_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x56))
            (then (call $template_i64_gt_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x57))
            (then (call $template_i64_le_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x58))
            (then (call $template_i64_le_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x67))
            (then (call $template_i32_clz_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x68))
            (then (call $template_i32_ctz_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x69))
            (then (call $template_i32_popcnt_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6A))
            (then (call $template_i32_add_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6B))
            (then (call $template_i32_sub_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6C))
            (then (call $template_i32_mul_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6D))
            (then (call $template_i32_div_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6E))
            (then (call $template_i32_div_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x6F))
            (then (call $template_i32_rem_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x70))
            (then (call $template_i32_rem_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x71))
            (then (call $template_i32_and_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x72))
            (then (call $template_i32_or_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x73))
            (then (call $template_i32_xor_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x74))
            (then (call $template_i32_shl_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x75))
            (then (call $template_i32_shr_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x76))
            (then (call $template_i32_shr_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x77))
            (then (call $template_i32_rotl_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x78))
            (then (call $template_i32_rotr_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x79))
            (then (call $template_i64_clz_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7A))
            (then (call $template_i64_ctz_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7B))
            (then (call $template_i64_popcnt_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7C))
            (then (call $template_i64_add_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7D))
            (then (call $template_i64_sub_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7E))
            (then (call $template_i64_mul_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x7F))
            (then (call $template_i64_div_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x80))
            (then (call $template_i64_div_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x81))
            (then (call $template_i64_rem_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x82))
            (then (call $template_i64_rem_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x83))
            (then (call $template_i64_and_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x84))
            (then (call $template_i64_or_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x85))
            (then (call $template_i64_xor_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x86))
            (then (call $template_i64_shl_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x87))
            (then (call $template_i64_shr_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x88))
            (then (call $template_i64_shr_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x89))
            (then (call $template_i64_rotl_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0x8A))
            (then (call $template_i64_rotr_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xA7))
            (then (call $template_i32_wrap_i64_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAC))
            (then (call $template_i64_extend_i32_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAD))
            (then (call $template_i64_extend_i32_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBC))
            (then (call $template_i32_reinterpret_f32_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBD))
            (then (call $template_f32_reinterpret_i32_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBE))
            (then (call $template_i64_reinterpret_f64_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xBF))
            (then (call $template_f64_reinterpret_i64_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xA8))
            (then (call $template_i32_trunc_f32_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xA9))
            (then (call $template_i32_trunc_f32_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAA))
            (then (call $template_i32_trunc_f64_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAB))
            (then (call $template_i32_trunc_f64_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAE))
            (then (call $template_i64_trunc_f32_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xAF))
            (then (call $template_i64_trunc_f32_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xB0))
            (then (call $template_i64_trunc_f64_s_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          (if (i32.eq (local.get $opcode) (i32.const 0xB1))
            (then (call $template_i64_trunc_f64_u_SFFX (local.get $dec_ptr)) (br $dispatch_done)))
          ;; 0xFC prefix - dispatch on imm0
          (if (i32.eq (local.get $opcode) (i32.const 0xFC))
            (then
              (local.set $imm0 (i32.load (i32.add (local.get $dec_ptr) (i32.const 4))))
              (block $fc_done
                (if (i32.eq (local.get $imm0) (i32.const 0x00))
                  (then (call $template_i32_trunc_sat_f32_s_SFFX (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x01))
                  (then (call $template_i32_trunc_sat_f32_u_SFFX (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x02))
                  (then (call $template_i32_trunc_sat_f64_s_SFFX (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x03))
                  (then (call $template_i32_trunc_sat_f64_u_SFFX (local.get $dec_ptr)) (br $fc_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x04))
                  (then (call $template_i64_trunc_sat_f32_s_SFFX (local.get $dec_ptr)) (br $fc_done)))
                ;; Unknown 0xFC sub-opcode
                (global.set $JIT_ERROR_SFFX (i32.const -3))
              )
              (br $dispatch_done)
            )
          )
          ;; 0xFD prefix (SIMD) - dispatch on imm0
          (if (i32.eq (local.get $opcode) (i32.const 0xFD))
            (then
              (local.set $imm0 (i32.load (i32.add (local.get $dec_ptr) (i32.const 4))))
              (block $fd_done
                (if (i32.eq (local.get $imm0) (i32.const 0x00))
                  (then (call $template_v128_load_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x1B))
                  (then (call $template_v128_store_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x0C))
                  (then (call $template_v128_const_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x2D))
                  (then (call $template_i8x16_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x31))
                  (then (call $template_i16x8_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x35))
                  (then (call $template_i32x4_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x39))
                  (then (call $template_i64x2_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x3A))
                  (then (call $template_f32x4_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x3D))
                  (then (call $template_f64x2_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x2E))
                  (then (call $template_i8x16_extract_lane_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x2F))
                  (then (call $template_i8x16_extract_lane_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x32))
                  (then (call $template_i16x8_extract_lane_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x33))
                  (then (call $template_i16x8_extract_lane_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x36))
                  (then (call $template_i32x4_extract_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x38))
                  (then (call $template_i64x2_extract_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x3B))
                  (then (call $template_f32x4_extract_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x3E))
                  (then (call $template_f64x2_extract_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x30))
                  (then (call $template_i8x16_replace_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x34))
                  (then (call $template_i16x8_replace_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x37))
                  (then (call $template_i32x4_replace_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x3C))
                  (then (call $template_f32x4_replace_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x3F))
                  (then (call $template_f64x2_replace_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x40))
                  (then (call $template_i8x16_add_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x51))
                  (then (call $template_i16x8_add_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x62))
                  (then (call $template_i32x4_add_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x73))
                  (then (call $template_i64x2_add_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x84))
                  (then (call $template_f32x4_add_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x95))
                  (then (call $template_f64x2_add_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x41))
                  (then (call $template_i8x16_sub_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x52))
                  (then (call $template_i16x8_sub_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x63))
                  (then (call $template_i32x4_sub_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x74))
                  (then (call $template_i64x2_sub_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x85))
                  (then (call $template_f32x4_sub_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x96))
                  (then (call $template_f64x2_sub_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x50))
                  (then (call $template_i8x16_mul_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x61))
                  (then (call $template_i16x8_mul_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x72))
                  (then (call $template_i32x4_mul_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x87))
                  (then (call $template_f32x4_mul_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x98))
                  (then (call $template_f64x2_mul_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x46))
                  (then (call $template_i8x16_neg_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x57))
                  (then (call $template_i16x8_neg_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x68))
                  (then (call $template_i32x4_neg_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x79))
                  (then (call $template_i64x2_neg_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x8A))
                  (then (call $template_f32x4_neg_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x9B))
                  (then (call $template_f64x2_neg_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x47))
                  (then (call $template_i8x16_eq_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x58))
                  (then (call $template_i16x8_eq_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x69))
                  (then (call $template_i32x4_eq_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x8C))
                  (then (call $template_f32x4_eq_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x9D))
                  (then (call $template_f64x2_eq_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x48))
                  (then (call $template_i8x16_ne_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x59))
                  (then (call $template_i16x8_ne_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x6A))
                  (then (call $template_i32x4_ne_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x8B))
                  (then (call $template_f32x4_ne_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x9C))
                  (then (call $template_f64x2_ne_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x4B))
                  (then (call $template_i8x16_lt_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x4A))
                  (then (call $template_i8x16_lt_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x5C))
                  (then (call $template_i16x8_lt_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x5B))
                  (then (call $template_i16x8_lt_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x6D))
                  (then (call $template_i32x4_lt_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x6C))
                  (then (call $template_i32x4_lt_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x8E))
                  (then (call $template_f32x4_lt_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x9F))
                  (then (call $template_f64x2_lt_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x4D))
                  (then (call $template_i8x16_gt_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x4C))
                  (then (call $template_i8x16_gt_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x5E))
                  (then (call $template_i16x8_gt_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x5D))
                  (then (call $template_i16x8_gt_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x6F))
                  (then (call $template_i32x4_gt_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x6E))
                  (then (call $template_i32x4_gt_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x90))
                  (then (call $template_f32x4_gt_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xA1))
                  (then (call $template_f64x2_gt_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x4F))
                  (then (call $template_i8x16_le_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x4E))
                  (then (call $template_i8x16_le_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x60))
                  (then (call $template_i16x8_le_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x5F))
                  (then (call $template_i16x8_le_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x71))
                  (then (call $template_i32x4_le_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x70))
                  (then (call $template_i32x4_le_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x92))
                  (then (call $template_f32x4_le_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xA3))
                  (then (call $template_f64x2_le_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x49))
                  (then (call $template_i8x16_ge_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x5A))
                  (then (call $template_i16x8_ge_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x6B))
                  (then (call $template_i32x4_ge_s_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x94))
                  (then (call $template_f32x4_ge_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xA5))
                  (then (call $template_f64x2_ge_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x43))
                  (then (call $template_i8x16_and_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x44))
                  (then (call $template_i8x16_or_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0x45))
                  (then (call $template_i8x16_xor_SFFX (local.get $dec_ptr)) (br $fd_done)))
                ;; ── New canonical ops (0xA6+) ──
                (if (i32.eq (local.get $imm0) (i32.const 0xA6))
                  (then (call $template_v128_load8_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xA7))
                  (then (call $template_v128_load16_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xA8))
                  (then (call $template_v128_load32_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xA9))
                  (then (call $template_v128_load64_splat_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xAA))
                  (then (call $template_i8x16_swizzle_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xAB))
                  (then (call $template_i64x2_replace_lane_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xAC))
                  (then (call $template_v128_not_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xAD))
                  (then (call $template_v128_bitselect_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xAE))
                  (then (call $template_i8x16_ge_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xAF))
                  (then (call $template_i16x8_ge_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xB0))
                  (then (call $template_i32x4_ge_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xB8))
                  (then (call $template_i8x16_min_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xBA))
                  (then (call $template_i8x16_max_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xBB))
                  (then (call $template_i8x16_avgr_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xBC))
                  (then (call $template_i16x8_min_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xBE))
                  (then (call $template_i16x8_max_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xBF))
                  (then (call $template_i16x8_avgr_u_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xE1))
                  (then (call $template_f32x4_min_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xE2))
                  (then (call $template_f32x4_max_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xE3))
                  (then (call $template_f64x2_min_SFFX (local.get $dec_ptr)) (br $fd_done)))
                (if (i32.eq (local.get $imm0) (i32.const 0xE4))
                  (then (call $template_f64x2_max_SFFX (local.get $dec_ptr)) (br $fd_done)))
                ;; Unknown 0xFD sub-opcode
                (global.set $JIT_ERROR_SFFX (i32.const -4))
              )
              (br $dispatch_done)
            )
          )
          ;; Unknown opcode
          (global.set $JIT_ERROR_SFFX (i32.const -2))
        )
        ;; Advance to next decoded op
        (local.set $dec_ptr (i32.add (local.get $dec_ptr) (global.get $DEC_SZ)))
        ;; return (0x0F) is always function end
        (br_if $compile_done (i32.eq (local.get $opcode) (i32.const 0x0F)))
        ;; end (0x0B): stop only when block_depth went negative (function end)
        (br_if $compile_done (i32.lt_s (i32.load (global.get $JS_LABEL_DEPTH_SFFX)) (i32.const 0)))
        (br $compile_loop)
      )
    )

    ;; ── Pop return value into x0/rax, then epilogue ────────────────
    (call $EMIT_EPILOGUE)

    ;; ── Return code size ──────────────────────────────────────────
    (i32.load (global.get $JS_CODE_PTR_SFFX))
  )
