[package]
name = "edgerun-network-interface"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Network interface capability abstractions for Edgerun"

[dependencies]
edgerun-capabilities = { version = "0.1", path = "../edgerun-capabilities" }
edgerun-quectel-ec200a = { version = "0.1", path = "../edgerun-quectel-ec200a" }

[lints]
workspace = true
