[package]
name = "edgerun-acme"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-rt.workspace = true
edgerun-log.workspace = true
edgerun-crypto.workspace = true
edgerun-http.workspace = true
edgerun-dns.workspace = true
edgerun-encoding.workspace = true
edgerun-secret-service.workspace = true
edgerun-json.workspace = true

sha2 = { workspace = true }
base64 = "0.22"
time = { version = "0.3", features = ["formatting", "parsing"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = { version = "2", features = ["serde"] }
thiserror = "2"
log = "0.4"

[dev-dependencies]

[features]
default = ["client"]
client = []
http_challenge = ["client"]
dns_challenge = ["client"]
