[package]
name = "edgerun-acme"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-rt.workspace = true
edgerun-log.workspace = true
edgerun-crypto = { workspace = true, default-features = false, features = ["p256"] }
edgerun-http = { workspace = true, default-features = false, features = ["client", "tls"] }
edgerun-dns.workspace = true
edgerun-encoding.workspace = true
edgerun-url = { path = "../edgerun-url", features = ["serde"] }
edgerun-secret-service.workspace = true
edgerun-json = { workspace = true, features = ["serde"] }
edgerun-error.workspace = true

sha2 = { workspace = true }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }

[dev-dependencies]

[features]
default = ["client"]
client = []
http_challenge = ["client"]
dns_challenge = ["client"]
