[package]
name = "edgerun-acme"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "ACME certificate automation for Edgerun services"

[dependencies]
edgerun-rt.workspace = true
edgerun-crypto = { workspace = true, default-features = false, features = ["p256"] }
edgerun-http = { workspace = true, default-features = false, features = ["client", "tls"] }
edgerun-dns.workspace = true
edgerun-encoding.workspace = true
edgerun-url = { version = "0.1", path = "../utility/edgerun-url" }
edgerun-secret-service.workspace = true
edgerun-json.workspace = true
edgerun-error.workspace = true
edgerun-tls.workspace = true

[dev-dependencies]

[features]
default = ["client"]
client = []
http_challenge = ["client"]
dns_challenge = ["client"]

[lints]
workspace = true
