[package]
name = "edgerun-sdk-unit-cbor-rfc8949"
version = "0.1.1"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[package.metadata.edgerun.unit]
id = "cbor-rfc8949"
standard = "RFC8949"

[dependencies]
edgerun-unit = { path = "../../../../edgerun-unit" }

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true
