[package]
name = "edgerun-wasm-interpreter"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Lightweight WASM interpreter for EdgeRun execution units"

[dependencies]
edgerun-wasm-parser = { path = "../edgerun-wasm-parser" }

[features]
std = []

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
