  ;; ═════════════════════════════════════════════════════════════════════
  ;; WASM SIMD (0xFD prefix) — AArch64 NEON implementations
  ;; ═════════════════════════════════════════════════════════════════════

  ;; ── v128.const (0xFD 0x0C): load 16-byte constant from decoded op ──
  (func $template_v128_const (param $dec_ptr i32)
    (local $addr i32)
    (local.set $addr (i32.add (local.get $dec_ptr) (i32.const 16)))
    (call $emit_load_addr_x1 (local.get $addr))
    (call $emit_v128_load_reg)
    (call $emit_v128_push)
  )

  ;; ── v128.load (0xFD 0x00): pop addr, load 16 bytes from mem ─────────
  (func $template_v128_load (param $dec_ptr i32)
    (call $emit_pop_x0)
    (call $emit_ldr_mem_ptr)
    (call $emit_instr_add_64 (global.get $REG_X1) (global.get $REG_X2) (global.get $REG_X0))
    (call $emit_v128_load_reg)
    (call $emit_v128_push)
  )

  ;; ── v128.store (0xFD 0x1B): pop value, pop addr, store 16 bytes ─────
  (func $template_v128_store (param $dec_ptr i32)
    (call $emit_v128_pop)
    (call $emit_pop_x0)
    (call $emit_ldr_mem_ptr)
    (call $emit_instr_add_64 (global.get $REG_X1) (global.get $REG_X2) (global.get $REG_X0))
    (call $emit_v128_store_reg)
  )

  ;; ── Splat templates ───────────────────────────────────────────────
  (func $template_i8x16_splat (param $dec_ptr i32)
    (call $emit_pop_x0)
    (call $emit_instr (i32.const 0x4E000800))
    (call $emit_v128_push)
  )
  (func $template_i16x8_splat (param $dec_ptr i32)
    (call $emit_pop_x0)
    (call $emit_instr (i32.const 0x4E001000))
    (call $emit_v128_push)
  )
  (func $template_i32x4_splat (param $dec_ptr i32)
    (call $emit_pop_x0)
    (call $emit_instr (i32.const 0x4E002000))
    (call $emit_v128_push)
  )
  (func $template_i64x2_splat (param $dec_ptr i32)
    (call $emit_pop_x0)
    (call $emit_instr (i32.const 0x4E004000))
    (call $emit_v128_push)
  )
  (func $template_f32x4_splat (param $dec_ptr i32)
    (call $emit_pop_x0)
    (call $emit_instr (i32.const 0x4E002000))
    (call $emit_v128_push)
  )
  (func $template_f64x2_splat (param $dec_ptr i32)
    (call $emit_pop_x0)
    (call $emit_instr (i32.const 0x4E004000))
    (call $emit_v128_push)
  )

  ;; ── Integer binary ops ────────────────────────────────────────────
  (func $template_i8x16_add (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_add_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i16x8_add (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_add_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i32x4_add (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_add_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i64x2_add (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_add_2d (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i8x16_sub (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_sub_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i16x8_sub (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_sub_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i32x4_sub (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_sub_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i64x2_sub (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_sub_2d (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Float binary ops ──────────────────────────────────────────────
  (func $template_f32x4_add (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_instr (i32.const 0x4E20D400))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_f64x2_add (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_instr (i32.const 0x4E60D400))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_f32x4_sub (param $dec_ptr i32)
    (global.set $JIT_ERROR (i32.const -4))
  )
  (func $template_f64x2_sub (param $dec_ptr i32)
    (global.set $JIT_ERROR (i32.const -4))
  )

  ;; ── Bitwise ops ───────────────────────────────────────────────────
  (func $template_i8x16_and (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_and_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i8x16_or (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_orr_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i8x16_xor (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_eor_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Comparisons ───────────────────────────────────────────────────
  (func $template_i8x16_eq (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_cmeq_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i16x8_eq (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_cmeq_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i32x4_eq (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_cmeq_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_i8x16_gt_s (param $dec_ptr i32)
    (call $emit_instr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_instr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_neon_cmgt_16b_s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_instr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_instr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Stubs ─────────────────────────────────────────────────────────
  (func $template_i8x16_extract_lane_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_extract_lane_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_extract_lane_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_extract_lane_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i64x2_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i64x2_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_eq (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_eq (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_ne (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_ne (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_ne (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_ne (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_ne (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_lt_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_lt_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_lt_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_lt_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_lt_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_lt_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_lt (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_lt (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_gt_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_gt_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_gt_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_gt_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_gt_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_gt (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_gt (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_le_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_le_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_le_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_le_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_le_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_le_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_le (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_le (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_ge_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_ge_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_ge_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_ge (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_ge (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_neg (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_neg (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_neg (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i64x2_neg (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_neg (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_neg (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i8x16_mul (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i16x8_mul (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_i32x4_mul (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f32x4_mul (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_f64x2_mul (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
