[package]
name = "edgerun-linux-wifi"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-capabilities = { path = "../edgerun-capabilities" }
edgerun-linux-netif = { path = "../edgerun-linux-netif" }
edgerun-linux-sysfs = { path = "../edgerun-linux-sysfs" }
edgerun-network-interface = { path = "../edgerun-network-interface" }
edgerun-wifi = { path = "../edgerun-wifi" }
libc = { path = "../libc" }
pbkdf2 = { path = "../pbkdf2" }
sha1 = { path = "../sha1" }
hmac = { path = "../edgerun-hmac" }
