[package]
name = "edgerun-term-server"
version = "0.1.0"
edition = "2024"

[dependencies]
edgerun-crypto = { path = "../../utility/edgerun-crypto", default-features = false, features = ["sha1"] }
edgerun-encoding = { path = "../../utility/edgerun-encoding", default-features = false }
edgerun-pty = { path = "../../utility/edgerun-pty" }
