[package]
name = "edgerun-exchange-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun Exchange HTTP API service"

[dependencies]
edgerun-core = { version = "0.1", path = "../protocol/edgerun-core" }
edgerun-exchange = { version = "0.1", path = "../edgerun-exchange" }
edgerun-wallet = { version = "0.1", path = "../edgerun-wallet" }
edgerun-http = { version = "0.1", path = "../edgerun-http", features = ["server", "runtime"] }
edgerun-json = { version = "0.1", path = "../utility/edgerun-json" }
edgerun-log = { version = "0.1", path = "../utility/edgerun-log" }
edgerun-rt = { version = "0.1", path = "../edgerun-rt" }
edgerun-url = { version = "0.1", path = "../utility/edgerun-url" }

[lints]
workspace = true
