[package]
name = "lifegraph-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
getrandom.workspace = true
hex.workspace = true
lifegraph-proto = { path = "../lifegraph-proto" }
prost.workspace = true
surrealdb.workspace = true
tokio.workspace = true
