[package]
name = "hpack-patched"
version = "0.3.0"
authors = ["Marko Lalic <marko.lalic@gmail.com>"]
description = "A library implementing HPACK coding. Patched from the original crate."
license = "MIT"
repository = "https://github.com/sno2/hpack-rs-patched"
keywords = ["hpack", "http2", "encoding", "decoding"]
edition = "2021"

[dependencies]
log = "^0.3"
rustc-serialize = { version = "^0.3", optional = true }

[features]
interop_tests = ["rustc-serialize"]
