[package]
name = "edgerun-async-channel"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun async channel compatibility surface"

[dependencies]
async-channel = "2.3.1"

[lints]
workspace = true
