[package]
name = "edgerun-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-proto = { path = "../edgerun-proto" }
edgerun-crypto.workspace = true
prost.workspace = true
prost-types.workspace = true

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
hex = "0.4"

[lints]
workspace = true
