[package]
name = "edgerun-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-proto = { path = "../edgerun-proto" }
edgerun-crypto = { workspace = true, default-features = false, features = ["hmac", "p256"] }
edgerun-encoding = { path = "../edgerun-encoding", default-features = false, features = ["alloc"] }
edgerun-json = { path = "../edgerun-json", default-features = false, features = ["alloc", "yaml", "serde"] }
prost.workspace = true
prost-types.workspace = true

[dev-dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }

[lints]
workspace = true
