[package]
name = "edgerun-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-proto = { path = "../edgerun-proto" }
p256.workspace = true
prost.workspace = true
prost-types.workspace = true
rand_core.workspace = true

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
p256 = { path = "../edgerun-p256", features = ["ecdsa", "sha256"] }
sha2 = { path = "../sha2" }
