# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edgerun/v0/html/entities.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'edgerun/v0/html/entities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65\x64gerun/v0/html/entities.proto\x12\x18\x65\x64gerun.v0.html.entities\"c\n\x0bNamedEntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ode_point_1\x18\x02 \x01(\r\x12\x14\n\x0c\x63ode_point_2\x18\x03 \x01(\r\x12\x1a\n\x12semicolon_required\x18\x04 \x01(\x08\"\xbb\x01\n\rEntityCatalog\x12\x14\n\x0cspec_section\x18\x01 \x01(\t\x12\x11\n\tspec_date\x18\x02 \x01(\t\x12\x37\n\x08\x65ntities\x18\x03 \x03(\x0b\x32%.edgerun.v0.html.entities.NamedEntity\x12\x16\n\x0etotal_entities\x18\x04 \x01(\x05\x12\x30\n\x04trie\x18\x05 \x03(\x0b\x32\".edgerun.v0.html.entities.TrieNode\"h\n\x08TrieNode\x12\x10\n\x08key_char\x18\x01 \x01(\t\x12\x34\n\x08\x63hildren\x18\x02 \x03(\x0b\x32\".edgerun.v0.html.entities.TrieNode\x12\x14\n\x0c\x65ntity_index\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edgerun.v0.html.entities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAMEDENTITY']._serialized_start=60
  _globals['_NAMEDENTITY']._serialized_end=159
  _globals['_ENTITYCATALOG']._serialized_start=162
  _globals['_ENTITYCATALOG']._serialized_end=349
  _globals['_TRIENODE']._serialized_start=351
  _globals['_TRIENODE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
