[package]
name = "edgerun-oci-registry"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-crypto.workspace = true
edgerun-oci-runtime = { path = "../edgerun-oci-runtime" }
edgerun-core = { path = "../edgerun-core" }
edgerun-http = { path = "../edgerun-http", features = ["tls"] }
edgerun-json = { path = "../edgerun-json", features = ["serde"] }
edgerun-secret-service = { path = "../edgerun-secret-service" }
flate2 = "1"
serde = { version = "1", features = ["derive"] }
tar = "0.4"
zstd = "0.13"

[lints]
workspace = true
