[package]
name = "edgerun-oci-registry"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-oci-runtime = { path = "../edgerun-oci-runtime" }
edgerun-core = { path = "../edgerun-core" }
edgerun-json = { path = "../edgerun-json" }
flate2 = "1"
tar = "0.4"
zstd = "0.13"
