[package]
name = "edgerun-sdk-unit-edgerun-sign-v1"
version = "0.1.1"
edition = "2021"
publish = false

[package.metadata.edgerun.unit]
id = "edgerun-sign-v1"
standard = "edgerun.v0.sign"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
edgerun-crypto = { path = "../../../../utility/edgerun-crypto", default-features = false, features = ["p256"] }
edgerun-unit = { path = "../../../../edgerun-unit" }

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true
