[package]
name = "edgerun-tcl-usb-ap-bridge"
version = "0.1.0"
authors = ["ken <ken@fw>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/Sylchi/edgerun_reference_core"
homepage = "https://github.com/Sylchi/edgerun_reference_core"

[workspace]

[[bin]]
name = "edgerun-tcl-usb-ap-bridge"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"
[dependencies]
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["components/usb_ppp_ap_bridge"]

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_tinyusb", version = "^2.0.0" }
