import { readdir, readFile, writeFile } from "node:fs/promises";
import { fragments } from "./fragments.mjs";

const expected = new Set(fragments.map((path) => path.slice("src/".length)));
for (const file of await readdir(new URL("src", import.meta.url))) {
  if (file.endsWith(".wat") && !expected.has(file)) {
    throw new Error(`unexpected WAT fragment: src/${file}`);
  }
}

let output = ";; Generated by build_wat.mjs from src/*.wat. Edit fragments, not this file.\n";
for (const path of fragments) {
  const text = await readFile(new URL(path, import.meta.url), "utf8");
  output += text.endsWith("\n") ? text : `${text}\n`;
}

await writeFile(new URL("ui_framework.wat", import.meta.url), output);
