//! edgerun-dom-events — DOM Event types from WHATWG DOM Living Standard.
//! Generated from DOM specification.
#![cfg_attr(not(test), no_std)]

/// DOM event phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventPhase {
    None = 0,
    CapturingPhase = 1,
    AtTarget = 2,
    BubblingPhase = 3,
}

/// All DOM event types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DomEventType {
    Abort,
    Blur,
    Focus,
    Click,
    Dblclick,
    Mousedown,
    Mouseup,
    Mousemove,
    Mouseenter,
    Mouseleave,
    Keydown,
    Keyup,
    Keypress,
    Load,
    Unload,
    Beforeunload,
    Resize,
    Scroll,
    Error,
    Input,
    Change,
    Submit,
    Reset,
    Domcontentloaded,
    Readystatechange,
    Hashchange,
    Popstate,
    Pageshow,
    Pagehide,
    Touchstart,
    Touchend,
    Touchmove,
    Touchcancel,
    Wheel,
    Contextmenu,
    Animationstart,
    Animationend,
    Animationiteration,
    Transitionend,
    Pointerdown,
    Pointerup,
    Pointermove,
    Drag,
    Dragstart,
    Dragend,
    Dragover,
    Drop,
    Copy,
    Cut,
    Paste,
    Message,
    Open,
    Close,
    Compositionstart,
    Compositionend,
    Compositionupdate,
    Beforeinput,
    Select,
    Selectstart,
    Selectionchange,
    Visibilitychange,
    Fullscreenchange,
    Fullscreenerror,
    Pointerenter,
    Pointerleave,
    Gotpointercapture,
    Lostpointercapture,
}

impl DomEventType {
    pub fn as_str(&self) -> &'static str {
        match self {
            DomEventType::Abort => "abort",
            DomEventType::Blur => "blur",
            DomEventType::Focus => "focus",
            DomEventType::Click => "click",
            DomEventType::Dblclick => "dblclick",
            DomEventType::Mousedown => "mousedown",
            DomEventType::Mouseup => "mouseup",
            DomEventType::Mousemove => "mousemove",
            DomEventType::Mouseenter => "mouseenter",
            DomEventType::Mouseleave => "mouseleave",
            DomEventType::Keydown => "keydown",
            DomEventType::Keyup => "keyup",
            DomEventType::Keypress => "keypress",
            DomEventType::Load => "load",
            DomEventType::Unload => "unload",
            DomEventType::Beforeunload => "beforeunload",
            DomEventType::Resize => "resize",
            DomEventType::Scroll => "scroll",
            DomEventType::Error => "error",
            DomEventType::Input => "input",
            DomEventType::Change => "change",
            DomEventType::Submit => "submit",
            DomEventType::Reset => "reset",
            DomEventType::Domcontentloaded => "DOMContentLoaded",
            DomEventType::Readystatechange => "readystatechange",
            DomEventType::Hashchange => "hashchange",
            DomEventType::Popstate => "popstate",
            DomEventType::Pageshow => "pageshow",
            DomEventType::Pagehide => "pagehide",
            DomEventType::Touchstart => "touchstart",
            DomEventType::Touchend => "touchend",
            DomEventType::Touchmove => "touchmove",
            DomEventType::Touchcancel => "touchcancel",
            DomEventType::Wheel => "wheel",
            DomEventType::Contextmenu => "contextmenu",
            DomEventType::Animationstart => "animationstart",
            DomEventType::Animationend => "animationend",
            DomEventType::Animationiteration => "animationiteration",
            DomEventType::Transitionend => "transitionend",
            DomEventType::Pointerdown => "pointerdown",
            DomEventType::Pointerup => "pointerup",
            DomEventType::Pointermove => "pointermove",
            DomEventType::Drag => "drag",
            DomEventType::Dragstart => "dragstart",
            DomEventType::Dragend => "dragend",
            DomEventType::Dragover => "dragover",
            DomEventType::Drop => "drop",
            DomEventType::Copy => "copy",
            DomEventType::Cut => "cut",
            DomEventType::Paste => "paste",
            DomEventType::Message => "message",
            DomEventType::Open => "open",
            DomEventType::Close => "close",
            DomEventType::Compositionstart => "compositionstart",
            DomEventType::Compositionend => "compositionend",
            DomEventType::Compositionupdate => "compositionupdate",
            DomEventType::Beforeinput => "beforeinput",
            DomEventType::Select => "select",
            DomEventType::Selectstart => "selectstart",
            DomEventType::Selectionchange => "selectionchange",
            DomEventType::Visibilitychange => "visibilitychange",
            DomEventType::Fullscreenchange => "fullscreenchange",
            DomEventType::Fullscreenerror => "fullscreenerror",
            DomEventType::Pointerenter => "pointerenter",
            DomEventType::Pointerleave => "pointerleave",
            DomEventType::Gotpointercapture => "gotpointercapture",
            DomEventType::Lostpointercapture => "lostpointercapture",
        }
    }

    pub fn from_str(name: &str) -> Option<Self> {
        match name {
            "abort" => Some(DomEventType::Abort),
            "blur" => Some(DomEventType::Blur),
            "focus" => Some(DomEventType::Focus),
            "click" => Some(DomEventType::Click),
            "dblclick" => Some(DomEventType::Dblclick),
            "mousedown" => Some(DomEventType::Mousedown),
            "mouseup" => Some(DomEventType::Mouseup),
            "mousemove" => Some(DomEventType::Mousemove),
            "mouseenter" => Some(DomEventType::Mouseenter),
            "mouseleave" => Some(DomEventType::Mouseleave),
            "keydown" => Some(DomEventType::Keydown),
            "keyup" => Some(DomEventType::Keyup),
            "keypress" => Some(DomEventType::Keypress),
            "load" => Some(DomEventType::Load),
            "unload" => Some(DomEventType::Unload),
            "beforeunload" => Some(DomEventType::Beforeunload),
            "resize" => Some(DomEventType::Resize),
            "scroll" => Some(DomEventType::Scroll),
            "error" => Some(DomEventType::Error),
            "input" => Some(DomEventType::Input),
            "change" => Some(DomEventType::Change),
            "submit" => Some(DomEventType::Submit),
            "reset" => Some(DomEventType::Reset),
            "DOMContentLoaded" => Some(DomEventType::Domcontentloaded),
            "readystatechange" => Some(DomEventType::Readystatechange),
            "hashchange" => Some(DomEventType::Hashchange),
            "popstate" => Some(DomEventType::Popstate),
            "pageshow" => Some(DomEventType::Pageshow),
            "pagehide" => Some(DomEventType::Pagehide),
            "touchstart" => Some(DomEventType::Touchstart),
            "touchend" => Some(DomEventType::Touchend),
            "touchmove" => Some(DomEventType::Touchmove),
            "touchcancel" => Some(DomEventType::Touchcancel),
            "wheel" => Some(DomEventType::Wheel),
            "contextmenu" => Some(DomEventType::Contextmenu),
            "animationstart" => Some(DomEventType::Animationstart),
            "animationend" => Some(DomEventType::Animationend),
            "animationiteration" => Some(DomEventType::Animationiteration),
            "transitionend" => Some(DomEventType::Transitionend),
            "pointerdown" => Some(DomEventType::Pointerdown),
            "pointerup" => Some(DomEventType::Pointerup),
            "pointermove" => Some(DomEventType::Pointermove),
            "drag" => Some(DomEventType::Drag),
            "dragstart" => Some(DomEventType::Dragstart),
            "dragend" => Some(DomEventType::Dragend),
            "dragover" => Some(DomEventType::Dragover),
            "drop" => Some(DomEventType::Drop),
            "copy" => Some(DomEventType::Copy),
            "cut" => Some(DomEventType::Cut),
            "paste" => Some(DomEventType::Paste),
            "message" => Some(DomEventType::Message),
            "open" => Some(DomEventType::Open),
            "close" => Some(DomEventType::Close),
            "compositionstart" => Some(DomEventType::Compositionstart),
            "compositionend" => Some(DomEventType::Compositionend),
            "compositionupdate" => Some(DomEventType::Compositionupdate),
            "beforeinput" => Some(DomEventType::Beforeinput),
            "select" => Some(DomEventType::Select),
            "selectstart" => Some(DomEventType::Selectstart),
            "selectionchange" => Some(DomEventType::Selectionchange),
            "visibilitychange" => Some(DomEventType::Visibilitychange),
            "fullscreenchange" => Some(DomEventType::Fullscreenchange),
            "fullscreenerror" => Some(DomEventType::Fullscreenerror),
            "pointerenter" => Some(DomEventType::Pointerenter),
            "pointerleave" => Some(DomEventType::Pointerleave),
            "gotpointercapture" => Some(DomEventType::Gotpointercapture),
            "lostpointercapture" => Some(DomEventType::Lostpointercapture),
            _ => None,
        }
    }
}
