[package]
name = "edgerun-tokio-tungstenite"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun compatibility surface for tokio-tungstenite-style APIs"

[features]
default = ["connect", "handshake", "proxy", "stream"]
connect = ["stream", "handshake"]
handshake = ["edgerun-tungstenite/handshake"]
proxy = ["edgerun-tungstenite/proxy"]
stream = []

[dependencies]
edgerun-tungstenite = { version = "0.1", path = "../edgerun-tungstenite", features = ["deflate"] }
edgerun-futures = { version = "0.1", path = "../edgerun-futures" }
edgerun-tokio = { version = "0.1", path = "../edgerun-tokio", default-features = false, features = ["edgerun-runtime", "net"] }

[lints]
workspace = true
