[package]
name = "lifegraph-linux-power"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
lifegraph-capabilities = { path = "../lifegraph-capabilities" }
lifegraph-linux-sysfs = { path = "../lifegraph-linux-sysfs" }
lifegraph-power = { path = "../lifegraph-power" }
