[package]
name = "adler2"
version = "2.0.1"
edition = "2021"
license = "0BSD OR MIT OR Apache-2.0"
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned Adler-32 checksum compatibility crate"

[features]
default = ["std"]
rustc-dep-of-std = []
std = []

[lints]
workspace = true
