[package]
name = "edgerun-opentelemetry-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun shim for opentelemetry_sdk"

[dependencies]
opentelemetry_sdk = "0.31.0"

[lints]
workspace = true
