[package]
name = "edgerun-network-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Frame-oriented network driver abstraction for Edgerun runtimes"

[features]
default = []
alloc = []
rtl8125 = []
std = []
tap = ["std"]
virtio = ["dep:edgerun-virtio"]

[dependencies]
edgerun-virtio = { workspace = true, optional = true }

[lints]
workspace = true
