[package]
name = "edgerun-quectel-ec200a"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Quectel EC200A modem support for Edgerun"
autobins = false

[dependencies]
edgerun-protocols = { workspace = true, default-features = false, features = ["quectel-ec200a"] }

[features]
std = []

[lints]
workspace = true
