[package]
name = "edgerun-yubikey"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "YubiKey signing provider for Edgerun hardware identities"

[dependencies]
edgerun-protocols = { workspace = true, default-features = false, features = ["core"] }
edgerun-linux-sysfs = { version = "0.1", path = "../../linux-adapters/edgerun-linux-sysfs" }
edgerun-encoding = { version = "0.1", path = "../../utility/edgerun-encoding" }

[lints]
workspace = true
