(func (export "compositor_global_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 16) (i32.const 13)) (then (return (i32.const 1))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 29) (i32.const 6)) (then (return (i32.const 2))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 35) (i32.const 7)) (then (return (i32.const 3))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 42) (i32.const 11)) (then (return (i32.const 4))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 53) (i32.const 9)) (then (return (i32.const 5))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 62) (i32.const 19)) (then (return (i32.const 6))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 81) (i32.const 16)) (then (return (i32.const 8))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 97) (i32.const 13)) (then (return (i32.const 11))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 110) (i32.const 17)) (then (return (i32.const 12))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 127) (i32.const 20)) (then (return (i32.const 21))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 147) (i32.const 15)) (then (return (i32.const 25))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 162) (i32.const 25)) (then (return (i32.const 31))))
    (if (call $m51eq (local.get $ptr) (local.get $len) (i32.const 187) (i32.const 19)) (then (return (i32.const 33))))
    i32.const 0)

  (func (export "compositor_surface_commit_result") (param $buffer_kind i32) (param $valid_layout i32) (result i32)
    (if (i32.eq (local.get $buffer_kind) (i32.const 0)) (then (return (i32.const 0))))
    (if (i32.eq (local.get $buffer_kind) (i32.const 4)) (then (return (i32.const 2))))
    (if (local.get $valid_layout) (then (return (i32.const 1))))
    i32.const 3)

  (func (export "compositor_buffer_layout_len") (param $offset i32) (param $width i32) (param $height i32) (param $stride i32) (result i32)
    (local $row i32)
    (if (i32.or (i32.or (i32.lt_s (local.get $offset) (i32.const 0)) (i32.le_s (local.get $width) (i32.const 0))) (i32.or (i32.le_s (local.get $height) (i32.const 0)) (i32.le_s (local.get $stride) (i32.const 0)))) (then (return (i32.const -1))))
    (local.set $row (i32.shl (local.get $width) (i32.const 2)))
    (if (i32.lt_u (local.get $stride) (local.get $row)) (then (return (i32.const -1))))
    (i32.mul (local.get $stride) (local.get $height)))

  (func $scale (param $v i32) (result i32)
    (if (i32.gt_s (local.get $v) (i32.const 1)) (then (return (local.get $v))))
    i32.const 1)

  (func (export "compositor_logical_width") (param $sample_w i32) (param $sample_h i32) (param $transform i32) (param $scale i32) (param $dst_w i32) (result i32)
    (if (i32.gt_s (local.get $dst_w) (i32.const 0)) (then (return (local.get $dst_w))))
    (if (i32.or (i32.or (i32.eq (local.get $transform) (i32.const 1)) (i32.eq (local.get $transform) (i32.const 3))) (i32.or (i32.eq (local.get $transform) (i32.const 5)) (i32.eq (local.get $transform) (i32.const 7))))
      (then (return (i32.div_u (local.get $sample_h) (call $scale (local.get $scale))))))
    (i32.div_u (local.get $sample_w) (call $scale (local.get $scale))))

  (func (export "compositor_logical_height") (param $sample_w i32) (param $sample_h i32) (param $transform i32) (param $scale i32) (param $dst_h i32) (result i32)
    (if (i32.gt_s (local.get $dst_h) (i32.const 0)) (then (return (local.get $dst_h))))
    (if (i32.or (i32.or (i32.eq (local.get $transform) (i32.const 1)) (i32.eq (local.get $transform) (i32.const 3))) (i32.or (i32.eq (local.get $transform) (i32.const 5)) (i32.eq (local.get $transform) (i32.const 7))))
      (then (return (i32.div_u (local.get $sample_w) (call $scale (local.get $scale))))))
    (i32.div_u (local.get $sample_h) (call $scale (local.get $scale))))

  (func (export "compositor_sample_coord_x") (param $tx i32) (param $ty i32) (param $x i32) (param $y i32) (param $w i32) (param $h i32) (param $transform i32) (result i32)
    (if (i32.eq (local.get $transform) (i32.const 1)) (then (return (i32.add (local.get $x) (i32.sub (i32.sub (local.get $w) (i32.const 1)) (local.get $ty))))))
    (if (i32.eq (local.get $transform) (i32.const 2)) (then (return (i32.add (local.get $x) (i32.sub (i32.sub (local.get $w) (i32.const 1)) (local.get $tx))))))
    (if (i32.eq (local.get $transform) (i32.const 3)) (then (return (i32.add (local.get $x) (local.get $ty)))))
    (if (i32.eq (local.get $transform) (i32.const 4)) (then (return (i32.add (local.get $x) (i32.sub (i32.sub (local.get $w) (i32.const 1)) (local.get $tx))))))
    (if (i32.eq (local.get $transform) (i32.const 5)) (then (return (i32.add (local.get $x) (i32.sub (i32.sub (local.get $w) (i32.const 1)) (local.get $ty))))))
    (if (i32.eq (local.get $transform) (i32.const 7)) (then (return (i32.add (local.get $x) (local.get $ty)))))
    (i32.add (local.get $x) (local.get $tx)))

  (func (export "compositor_sample_coord_y") (param $tx i32) (param $ty i32) (param $x i32) (param $y i32) (param $w i32) (param $h i32) (param $transform i32) (result i32)
    (if (i32.eq (local.get $transform) (i32.const 1)) (then (return (i32.add (local.get $y) (local.get $tx)))))
    (if (i32.eq (local.get $transform) (i32.const 2)) (then (return (i32.add (local.get $y) (i32.sub (i32.sub (local.get $h) (i32.const 1)) (local.get $ty))))))
    (if (i32.eq (local.get $transform) (i32.const 3)) (then (return (i32.add (local.get $y) (i32.sub (i32.sub (local.get $h) (i32.const 1)) (local.get $tx))))))
    (if (i32.eq (local.get $transform) (i32.const 5)) (then (return (i32.add (local.get $y) (i32.sub (i32.sub (local.get $h) (i32.const 1)) (local.get $tx))))))
    (if (i32.eq (local.get $transform) (i32.const 6)) (then (return (i32.add (local.get $y) (i32.sub (i32.sub (local.get $h) (i32.const 1)) (local.get $ty))))))
    (if (i32.eq (local.get $transform) (i32.const 7)) (then (return (i32.add (local.get $y) (local.get $tx)))))
    (i32.add (local.get $y) (local.get $ty)))

  (func (export "compositor_render_phase") (param $surface_class i32) (param $layer i32) (result i32)
    (if (i32.eq (local.get $surface_class) (i32.const 4)) (then (return (i32.const 5))))
    (if (i32.eq (local.get $surface_class) (i32.const 3)) (then (return (i32.const 4))))
    (if (i32.eq (local.get $surface_class) (i32.const 2))
      (then
        (if (i32.lt_u (local.get $layer) (i32.const 2)) (then (return (i32.const 1))))
        (return (i32.const 3))))
    (if (i32.eq (local.get $surface_class) (i32.const 1)) (then (return (i32.const 2))))
    i32.const 0)

  (func (export "compositor_pixel_format_code") (param $format i32) (result i32)
    (if (i32.eq (local.get $format) (i32.const 0x34325258)) (then (return (i32.const 1))))
    (if (i32.eq (local.get $format) (i32.const 0x34325241)) (then (return (i32.const 2))))
    (if (i32.eq (local.get $format) (i32.const 0x34324241)) (then (return (i32.const 3))))
    i32.const 1)

  (func (export "compositor_blend_channel") (param $src i32) (param $dst i32) (param $alpha i32) (result i32)
    (if (i32.eqz (local.get $alpha)) (then (return (local.get $dst))))
    (if (i32.eq (local.get $alpha) (i32.const 255)) (then (return (local.get $src))))
    (i32.div_u
      (i32.add (i32.mul (local.get $src) (local.get $alpha)) (i32.mul (local.get $dst) (i32.sub (i32.const 255) (local.get $alpha))))
      (i32.const 255)))

  (func (export "compositor_toplevel_state_mask") (param $fullscreen i32) (param $maximized i32) (param $resizing i32) (result i32)
    (local $mask i32)
    (if (local.get $fullscreen) (then (local.set $mask (i32.or (local.get $mask) (i32.const 2)))))
    (if (local.get $maximized) (then (local.set $mask (i32.or (local.get $mask) (i32.const 4)))))
    (if (local.get $resizing) (then (local.set $mask (i32.or (local.get $mask) (i32.const 8)))))
    (if (i32.and (i32.eqz (local.get $fullscreen)) (i32.eqz (local.get $maximized))) (then (local.set $mask (i32.or (local.get $mask) (i32.const 1)))))
    local.get $mask)

  (func (export "compositor_layer_width") (param $output_w i32) (param $anchor i32) (param $desired_w i32) (param $margin_l i32) (param $margin_r i32) (result i32)
    (if (i32.gt_u (local.get $desired_w) (i32.const 0)) (then (return (local.get $desired_w))))
    (if (i32.eq (i32.and (local.get $anchor) (i32.const 12)) (i32.const 12))
      (then (return (i32.sub (i32.sub (local.get $output_w) (local.get $margin_l)) (local.get $margin_r)))))
    local.get $output_w)

  (func (export "compositor_layer_height") (param $output_h i32) (param $anchor i32) (param $desired_h i32) (param $margin_t i32) (param $margin_b i32) (result i32)
    (if (i32.gt_u (local.get $desired_h) (i32.const 0)) (then (return (local.get $desired_h))))
    (if (i32.eq (i32.and (local.get $anchor) (i32.const 3)) (i32.const 3))
      (then (return (i32.sub (i32.sub (local.get $output_h) (local.get $margin_t)) (local.get $margin_b)))))
    local.get $output_h)

  (func (export "compositor_layer_x") (param $output_w i32) (param $w i32) (param $anchor i32) (param $margin_l i32) (param $margin_r i32) (result i32)
    (if (i32.ne (i32.and (local.get $anchor) (i32.const 4)) (i32.const 0)) (then (return (local.get $margin_l))))
    (if (i32.ne (i32.and (local.get $anchor) (i32.const 8)) (i32.const 0)) (then (return (i32.sub (i32.sub (local.get $output_w) (local.get $w)) (local.get $margin_r)))))
    (i32.div_s (i32.sub (local.get $output_w) (local.get $w)) (i32.const 2)))

  (func (export "compositor_layer_y") (param $output_h i32) (param $h i32) (param $anchor i32) (param $margin_t i32) (param $margin_b i32) (result i32)
    (if (i32.ne (i32.and (local.get $anchor) (i32.const 1)) (i32.const 0)) (then (return (local.get $margin_t))))
    (if (i32.ne (i32.and (local.get $anchor) (i32.const 2)) (i32.const 0)) (then (return (i32.sub (i32.sub (local.get $output_h) (local.get $h)) (local.get $margin_b)))))
    (i32.div_s (i32.sub (local.get $output_h) (local.get $h)) (i32.const 2)))

  (func (export "compositor_surface_accepts_point") (param $has_buffer i32) (param $local_x i32) (param $local_y i32) (param $logical_w i32) (param $logical_h i32) (param $has_region i32) (param $rx i32) (param $ry i32) (param $rw i32) (param $rh i32) (result i32)
    (if (i32.eqz (local.get $has_buffer)) (then (return (i32.const 0))))
    (if (i32.or (i32.or (i32.lt_s (local.get $local_x) (i32.const 0)) (i32.lt_s (local.get $local_y) (i32.const 0))) (i32.or (i32.ge_s (local.get $local_x) (local.get $logical_w)) (i32.ge_s (local.get $local_y) (local.get $logical_h)))) (then (return (i32.const 0))))
    (if (i32.eqz (local.get $has_region)) (then (return (i32.const 1))))
    (if (i32.and (i32.and (i32.ge_s (local.get $local_x) (local.get $rx)) (i32.lt_s (local.get $local_x) (i32.add (local.get $rx) (local.get $rw)))) (i32.and (i32.ge_s (local.get $local_y) (local.get $ry)) (i32.lt_s (local.get $local_y) (i32.add (local.get $ry) (local.get $rh)))))
      (then (return (i32.const 1))))
    i32.const 0)

  (func (export "compositor_focus_changed") (param $current i32) (param $next i32) (result i32)
    (i32.ne (local.get $current) (local.get $next)))

  (func (export "compositor_frontmost_tearing") (param $front_has_buffer i32) (param $front_hint i32) (param $fallback_hint i32) (result i32)
    (if (local.get $front_has_buffer) (then (return (i32.eq (local.get $front_hint) (i32.const 2)))))
    (i32.eq (local.get $fallback_hint) (i32.const 2)))

  (func (export "compositor_presentation_next_seq") (param $seq i64) (result i64)
    (i64.add (local.get $seq) (i64.const 1)))

  (data (i32.const 16) "wl_compositorwl_shmwl_seatxdg_wm_basewl_outputzwp_linux_dmabuf_v1wl_subcompositorwp_viewporterxdg_activation_v1wp_linux_drm_syncobjzwlr_screencopyzwp_text_input_manager_v3zwlr_layer_shell_v1")
