[package]
name = "edgerun-sdk-unit-base32hex-rfc4648"
version = "0.1.1"
edition = "2021"
publish = false

[package.metadata.edgerun.unit]
id = "base32hex-rfc4648"
standard = "RFC4648"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
edgerun-encoding = { version = "0.1.1", path = "../../../../utility/edgerun-encoding", default-features = false }
edgerun-unit = { version = "0.1.1", path = "../../../../edgerun-unit" }

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true
