[package]
name = "edgerun-http"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "HTTP/1.1, HTTP/2, and HTTP/3 with HPACK/QPACK compression"

[features]
default = []
connection-middleware = []

[dependencies]
edgerun-tls = { path = "../edgerun-tls" }
edgerun-crypto = { path = "../edgerun-crypto" }
edgerun-rt = { path = "../edgerun-rt" }
edgerun-log = { path = "../edgerun-log" }
edgerun-dns = { path = "../edgerun-dns" }
edgerun-encoding = { path = "../edgerun-encoding" }
edgerun-hpack = { path = "../edgerun-hpack" }
edgerun-qpack = { path = "../edgerun-qpack" }
flate2.workspace = true
brotli.workspace = true

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
edgerun-json = { workspace = true }
futures = "0.3"

[lints]
workspace = true