// DO NOT EDIT. Generated by scripts/generate_wgsl.py
// Source: proto/edgerun/v0/css/ + crates/edgerun-rasterizer/src/
//
// This shader implements the painter's algorithm: every fragment
// iterates all styled rectangles back-to-front, computing the
// topmost pixel color. This replaces the CPU scanline rasterizer.

// Vertex shader: emits a triangle covering the entire viewport.
// Vertices at (-1,-1), (3,-1), (-1,3) cover the full NDC space and beyond.

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32) -> VertexOutput {
    var pos = array<vec2<f32>, 3>(
        vec2<f32>(-1.0, -1.0),
        vec2<f32>( 3.0, -1.0),
        vec2<f32>(-1.0,  3.0),
    );
    return VertexOutput(vec4<f32>(pos[vertex_index], 0.0, 1.0));
}


// --- Uniform Buffer Layout ---
// Generated from proto data + rasterizer LUTs

struct GradientStop {
    color: vec4<f32>,    // RGBA
    position: f32,
    _pad0: f32,
    _pad1: f32,
    _pad2: f32,
}

struct RectStyle {
    // Background color (from CssColor)
    bg_color: vec4<f32>,

    // Gradient (from css_images.proto GradientKind)
    gradient_type: u32,      // 0=none, 1=linear, 2=radial, 3=conic
    gradient_angle: f32,     // Linear: angle; Conic: from_angle
    gradient_cx: f32,        // Radial/Conic center X (0-1)
    gradient_cy: f32,        // Radial/Conic center Y (0-1)
    gradient_stops: array<GradientStop, 16>,
    gradient_stop_count: u32,
    _pad_gs: u32,

    // Border (from css_box.proto + border_lut)
    border_width_top: f32,
    border_width_right: f32,
    border_width_bottom: f32,
    border_width_left: f32,
    _pad_border_align: vec2<u32>,  // 8 bytes padding for border_color vec4 alignment
    border_color: vec4<f32>,
    border_style: u32,       // 0=none, 1=solid, 2=dashed, ...
    border_radius_tl: f32,
    border_radius_tr: f32,
    border_radius_br: f32,
    border_radius_bl: f32,

    // Compositing (from blend_lut)
    opacity: f32,            // OPACITY property
    blend_mode: u32,         // 0=normal, 1=multiply, ...
    _pad_cm: u32,

    // Box Shadow (from css_box.proto)
    shadow_color: vec4<f32>, // Shadow RGBA
    shadow_blur: f32,        // Blur radius
    shadow_spread: f32,      // Spread distance
    shadow_offset_x: f32,    // Horizontal offset
    shadow_offset_y: f32,    // Vertical offset
    shadow_type: u32,        // 0=drop, 1=inset
    shadow_active: u32,      // 1 if shadow should render
    _pad_shadow: u32,

    // Layout (computed, not from cascade)
    x: f32, y: f32, w: f32, h: f32,
    paint_order: u32,        // For back-to-front sort
    _pad_layout: u32,
    _pad_final2: u32,
    _pad_final3: u32,
}

struct Uniforms {
    fb_width: f32,
    fb_height: f32,
    rect_count: u32,
    text_cmd_count: u32,
}

@group(0) @binding(0) var<uniform> u: Uniforms;
@group(0) @binding(1) var<storage, read> rects: array<RectStyle>;

// --- Text Command ---
// Each text command renders a string of glyphs
struct TextCommand {
    x: f32, y: f32,
    color_r: f32, color_g: f32, color_b: f32,
    glyph_count: u32,
    _pad_tc: u32,
    // Glyph indices (ASCII, max 128 chars per command)
    glyphs: array<u32, 128>,
}

@group(0) @binding(2) var<storage, read> text_cmds: array<TextCommand>;


// --- Named Color LUT ---
// Generated from color_lut.rs (148 colors)

const NAMED_COLOR_COUNT: u32 = 148u;
const NAMED_COLORS: array<vec4<f32>, 148> = array<vec4<f32>, 148>(
    vec4<f32>(0.00000, 0.00000, 0.00000, 1.00000),  // 0: black
    vec4<f32>(1.00000, 1.00000, 1.00000, 1.00000),  // 1: white
    vec4<f32>(1.00000, 0.00000, 0.00000, 1.00000),  // 2: red
    vec4<f32>(0.00000, 0.50196, 0.00000, 1.00000),  // 3: green
    vec4<f32>(0.00000, 0.00000, 1.00000, 1.00000),  // 4: blue
    vec4<f32>(1.00000, 1.00000, 0.00000, 1.00000),  // 5: yellow
    vec4<f32>(0.00000, 1.00000, 1.00000, 1.00000),  // 6: cyan
    vec4<f32>(1.00000, 0.00000, 1.00000, 1.00000),  // 7: magenta
    vec4<f32>(1.00000, 0.64706, 0.00000, 1.00000),  // 8: orange
    vec4<f32>(0.50196, 0.00000, 0.50196, 1.00000),  // 9: purple
    vec4<f32>(1.00000, 0.75294, 0.79608, 1.00000),  // 10: pink
    vec4<f32>(0.64706, 0.16471, 0.16471, 1.00000),  // 11: brown
    vec4<f32>(0.00000, 0.00000, 0.00000, 0.00000),  // 12: transparent
    vec4<f32>(0.94118, 0.97255, 1.00000, 1.00000),  // 13: aliceblue
    vec4<f32>(0.98039, 0.92157, 0.84314, 1.00000),  // 14: antiquewhite
    vec4<f32>(0.49804, 1.00000, 0.83137, 1.00000),  // 15: aquamarine
    vec4<f32>(0.94118, 1.00000, 1.00000, 1.00000),  // 16: azure
    vec4<f32>(0.96078, 0.96078, 0.86275, 1.00000),  // 17: beige
    vec4<f32>(1.00000, 0.89412, 0.76863, 1.00000),  // 18: bisque
    vec4<f32>(1.00000, 0.92157, 0.80392, 1.00000),  // 19: blanchedalmond
    vec4<f32>(0.54118, 0.16863, 0.88627, 1.00000),  // 20: blueviolet
    vec4<f32>(0.87059, 0.72157, 0.52941, 1.00000),  // 21: burlywood
    vec4<f32>(0.37255, 0.61961, 0.62745, 1.00000),  // 22: cadetblue
    vec4<f32>(0.49804, 1.00000, 0.00000, 1.00000),  // 23: chartreuse
    vec4<f32>(0.82353, 0.41176, 0.11765, 1.00000),  // 24: chocolate
    vec4<f32>(1.00000, 0.49804, 0.31373, 1.00000),  // 25: coral
    vec4<f32>(0.39216, 0.58431, 0.92941, 1.00000),  // 26: cornflowerblue
    vec4<f32>(1.00000, 0.97255, 0.86275, 1.00000),  // 27: cornsilk
    vec4<f32>(0.86275, 0.07843, 0.23529, 1.00000),  // 28: crimson
    vec4<f32>(0.00000, 1.00000, 1.00000, 1.00000),  // 29: darkcyan
    vec4<f32>(0.72157, 0.52549, 0.04314, 1.00000),  // 30: darkgoldenrod
    vec4<f32>(0.66275, 0.66275, 0.66275, 1.00000),  // 31: darkgray
    vec4<f32>(0.00000, 0.39216, 0.00000, 1.00000),  // 32: darkgreen
    vec4<f32>(0.74118, 0.71373, 0.46275, 1.00000),  // 33: darkkhaki
    vec4<f32>(0.54510, 0.00000, 0.54510, 1.00000),  // 34: darkmagenta
    vec4<f32>(0.33333, 0.41961, 0.18431, 1.00000),  // 35: darkolivegreen
    vec4<f32>(1.00000, 0.54902, 0.00000, 1.00000),  // 36: darkorange
    vec4<f32>(0.60000, 0.19608, 0.80000, 1.00000),  // 37: darkorchid
    vec4<f32>(0.54510, 0.00000, 0.00000, 1.00000),  // 38: darkred
    vec4<f32>(0.91373, 0.58824, 0.47843, 1.00000),  // 39: darksalmon
    vec4<f32>(0.56078, 0.73725, 0.56078, 1.00000),  // 40: darkseagreen
    vec4<f32>(0.28235, 0.23922, 0.54510, 1.00000),  // 41: darkslateblue
    vec4<f32>(0.18431, 0.30980, 0.30980, 1.00000),  // 42: darkslategray
    vec4<f32>(0.00000, 0.80784, 0.81961, 1.00000),  // 43: darkturquoise
    vec4<f32>(0.58039, 0.00000, 0.82745, 1.00000),  // 44: darkviolet
    vec4<f32>(1.00000, 0.07843, 0.57647, 1.00000),  // 45: deeppink
    vec4<f32>(0.00000, 0.74902, 1.00000, 1.00000),  // 46: deepskyblue
    vec4<f32>(0.41176, 0.41176, 0.41176, 1.00000),  // 47: dimgray
    vec4<f32>(0.11765, 0.56471, 1.00000, 1.00000),  // 48: dodgerblue
    vec4<f32>(0.69804, 0.13333, 0.13333, 1.00000),  // 49: firebrick
    vec4<f32>(1.00000, 0.98039, 0.94118, 1.00000),  // 50: floralwhite
    vec4<f32>(0.13333, 0.54510, 0.13333, 1.00000),  // 51: forestgreen
    vec4<f32>(0.86275, 0.86275, 0.86275, 1.00000),  // 52: gainsboro
    vec4<f32>(0.97255, 0.97255, 1.00000, 1.00000),  // 53: ghostwhite
    vec4<f32>(0.85490, 0.64706, 0.12549, 1.00000),  // 54: goldenrod
    vec4<f32>(0.67843, 0.84706, 0.90196, 1.00000),  // 55: lightblue
    vec4<f32>(0.94118, 0.50196, 0.50196, 1.00000),  // 56: lightcoral
    vec4<f32>(0.87843, 1.00000, 0.87843, 1.00000),  // 57: lightgreen
    vec4<f32>(0.82745, 0.82745, 0.82745, 1.00000),  // 58: lightgray
    vec4<f32>(1.00000, 0.71373, 0.75686, 1.00000),  // 59: lightpink
    vec4<f32>(0.12549, 0.69804, 0.66667, 1.00000),  // 60: lightseagreen
    vec4<f32>(0.52941, 0.80784, 0.98039, 1.00000),  // 61: lightskyblue
    vec4<f32>(0.46667, 0.53333, 0.60000, 1.00000),  // 62: lightslategray
    vec4<f32>(0.69020, 0.76863, 0.87059, 1.00000),  // 63: lightsteelblue
    vec4<f32>(1.00000, 1.00000, 0.87843, 1.00000),  // 64: lightyellow
    vec4<f32>(0.19608, 0.80392, 0.19608, 1.00000),  // 65: limegreen
    vec4<f32>(0.98039, 0.94118, 0.90196, 1.00000),  // 66: linen
    vec4<f32>(0.00000, 1.00000, 0.49804, 1.00000),  // 67: mediumspringgreen
    vec4<f32>(0.57647, 0.43922, 0.85882, 1.00000),  // 68: mediumpurple
    vec4<f32>(0.23529, 0.70196, 0.44314, 1.00000),  // 69: mediumseagreen
    vec4<f32>(0.48235, 0.40784, 0.93333, 1.00000),  // 70: mediumslateblue
    vec4<f32>(0.00000, 0.98039, 0.60392, 1.00000),  // 71: mediumaquamarine
    vec4<f32>(0.80392, 0.52157, 0.24706, 1.00000),  // 72: peru
    vec4<f32>(1.00000, 0.62745, 0.47843, 1.00000),  // 73: lightsalmon
    vec4<f32>(1.00000, 0.38824, 0.27843, 1.00000),  // 74: tomato
    vec4<f32>(0.25098, 0.87843, 0.81569, 1.00000),  // 75: turquoise
    vec4<f32>(0.93333, 0.50980, 0.93333, 1.00000),  // 76: violet
    vec4<f32>(0.96078, 0.87059, 0.70196, 1.00000),  // 77: wheat
    vec4<f32>(0.96078, 0.96078, 0.96078, 1.00000),  // 78: whitesmoke
    vec4<f32>(0.60392, 0.80392, 0.19608, 1.00000),  // 79: yellowgreen
    vec4<f32>(0.80392, 0.52157, 0.24706, 1.00000),  // 80: sandybrown
    vec4<f32>(0.18039, 0.54510, 0.34118, 1.00000),  // 81: seagreen
    vec4<f32>(1.00000, 0.98039, 0.80392, 1.00000),  // 82: lemonchiffon
    vec4<f32>(0.52941, 0.80784, 0.92157, 1.00000),  // 83: skyblue
    vec4<f32>(0.41569, 0.35294, 0.80392, 1.00000),  // 84: slateblue
    vec4<f32>(0.43922, 0.50196, 0.56471, 1.00000),  // 85: slategray
    vec4<f32>(1.00000, 0.98039, 0.80392, 1.00000),  // 86: lemonchiffon
    vec4<f32>(0.00000, 0.98039, 0.60392, 1.00000),  // 87: mediumspringgreen
    vec4<f32>(1.00000, 0.27059, 0.00000, 1.00000),  // 88: orangered
    vec4<f32>(0.29412, 0.00000, 0.50980, 1.00000),  // 89: indigo
    vec4<f32>(1.00000, 0.84314, 0.00000, 1.00000),  // 90: gold
    vec4<f32>(1.00000, 0.41176, 0.70588, 1.00000),  // 91: hotpink
    vec4<f32>(0.25490, 0.41176, 0.88235, 1.00000),  // 92: royalblue
    vec4<f32>(0.00000, 0.50196, 0.50196, 1.00000),  // 93: teal
    vec4<f32>(0.50196, 0.00000, 0.00000, 1.00000),  // 94: maroon
    vec4<f32>(0.00000, 0.50196, 0.50196, 1.00000),  // 95: teal
    vec4<f32>(0.00000, 1.00000, 0.00000, 1.00000),  // 96: lime
    vec4<f32>(0.50196, 0.50196, 0.00000, 1.00000),  // 97: olive
    vec4<f32>(0.00000, 0.00000, 0.50196, 1.00000),  // 98: navy
    vec4<f32>(0.50196, 0.50196, 0.50196, 1.00000),  // 99: gray
    vec4<f32>(0.75294, 0.75294, 0.75294, 1.00000),  // 100: silver
    vec4<f32>(1.00000, 1.00000, 1.00000, 1.00000),  // 101: white
    vec4<f32>(0.00000, 0.00000, 0.00000, 1.00000),  // 102: black
    vec4<f32>(0.94118, 0.90196, 0.54902, 1.00000),  // 103: khaki
    vec4<f32>(0.90196, 0.90196, 0.98039, 1.00000),  // 104: lavender
    vec4<f32>(1.00000, 0.94118, 0.96078, 1.00000),  // 105: lavenderblush
    vec4<f32>(0.00000, 0.39216, 0.00000, 1.00000),  // 106: darkgreen
    vec4<f32>(0.00000, 0.00000, 0.54510, 1.00000),  // 107: darkblue
    vec4<f32>(0.00000, 0.00000, 0.80392, 1.00000),  // 108: mediumblue
    vec4<f32>(0.09804, 0.09804, 0.43922, 1.00000),  // 109: midnightblue
    vec4<f32>(0.18431, 0.30980, 0.30980, 1.00000),  // 110: darkslategray
    vec4<f32>(0.00000, 0.54510, 0.54510, 1.00000),  // 111: darkcyan
    vec4<f32>(0.33333, 0.41961, 0.18431, 1.00000),  // 112: darkolivegreen
    vec4<f32>(0.72157, 0.52549, 0.04314, 1.00000),  // 113: darkgoldenrod
    vec4<f32>(0.33333, 0.41961, 0.18431, 1.00000),  // 114: olive
    vec4<f32>(0.41961, 0.55686, 0.13725, 1.00000),  // 115: olivedrab
    vec4<f32>(0.48627, 0.98824, 0.00000, 1.00000),  // 116: lawngreen
    vec4<f32>(0.59608, 0.98431, 0.59608, 1.00000),  // 117: palegreen
    vec4<f32>(0.56471, 0.93333, 0.56471, 1.00000),  // 118: palegreen
    vec4<f32>(0.85882, 0.43922, 0.57647, 1.00000),  // 119: palevioletred
    vec4<f32>(0.68627, 0.93333, 0.93333, 1.00000),  // 120: paleturquoise
    vec4<f32>(0.93333, 0.50980, 0.93333, 1.00000),  // 121: paleviolet
    vec4<f32>(1.00000, 0.89412, 0.88235, 1.00000),  // 122: mistyrose
    vec4<f32>(1.00000, 0.89412, 0.70980, 1.00000),  // 123: moccasin
    vec4<f32>(1.00000, 0.87059, 0.67843, 1.00000),  // 124: peachpuff
    vec4<f32>(0.80392, 0.52157, 0.24706, 1.00000),  // 125: peru
    vec4<f32>(0.73725, 0.56078, 0.56078, 1.00000),  // 126: rosybrown
    vec4<f32>(0.27451, 0.50980, 0.70588, 1.00000),  // 127: steelblue
    vec4<f32>(0.82353, 0.70588, 0.54902, 1.00000),  // 128: tan
    vec4<f32>(0.84706, 0.74902, 0.84706, 1.00000),  // 129: thistle
    vec4<f32>(1.00000, 0.38824, 0.27843, 1.00000),  // 130: tomato
    vec4<f32>(0.25098, 0.87843, 0.81569, 1.00000),  // 131: turquoise
    vec4<f32>(0.93333, 0.50980, 0.93333, 1.00000),  // 132: violet
    vec4<f32>(0.96078, 0.87059, 0.70196, 1.00000),  // 133: wheat
    vec4<f32>(0.96078, 0.96078, 0.96078, 1.00000),  // 134: whitesmoke
    vec4<f32>(0.60392, 0.80392, 0.19608, 1.00000),  // 135: yellowgreen
    vec4<f32>(0.54510, 0.27059, 0.07451, 1.00000),  // 136: saddlebrown
    vec4<f32>(0.98039, 0.92157, 0.84314, 1.00000),  // 137: antiquewhite
    vec4<f32>(1.00000, 0.96078, 0.93333, 1.00000),  // 138: seashell
    vec4<f32>(0.99216, 0.84706, 0.83529, 1.00000),  // 139: salmon
    vec4<f32>(0.98039, 0.50196, 0.44706, 1.00000),  // 140: salmon
    vec4<f32>(0.49804, 1.00000, 0.00000, 1.00000),  // 141: chartreuse
    vec4<f32>(0.18039, 0.54510, 0.34118, 1.00000),  // 142: seagreen
    vec4<f32>(0.94118, 1.00000, 1.00000, 1.00000),  // 143: azure
    vec4<f32>(1.00000, 0.94118, 0.96078, 1.00000),  // 144: lavenderblush
    vec4<f32>(0.96078, 0.96078, 0.86275, 1.00000),  // 145: beige
    vec4<f32>(1.00000, 0.89412, 0.76863, 1.00000),  // 146: bisque
    vec4<f32>(1.00000, 0.89412, 0.88235, 1.00000),  // 147: mistyrose
);

fn lookup_named_color(index: u32) -> vec4<f32> {
    return NAMED_COLORS[min(index, NAMED_COLOR_COUNT - 1u)];
}


// --- Border Dash Patterns ---
// Generated from border_lut.rs (9 patterns, 8 bytes each)

const BORDER_PATTERN_NONE: array<u32, 8> = array<u32, 8>(0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u);
const BORDER_PATTERN_SOLID: array<u32, 8> = array<u32, 8>(1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u);
const BORDER_PATTERN_DASHED: array<u32, 8> = array<u32, 8>(1u, 1u, 1u, 1u, 0u, 0u, 0u, 0u);
const BORDER_PATTERN_DOTTED: array<u32, 8> = array<u32, 8>(1u, 0u, 0u, 0u, 1u, 0u, 0u, 0u);
const BORDER_PATTERN_DOUBLE: array<u32, 8> = array<u32, 8>(1u, 1u, 0u, 1u, 1u, 0u, 0u, 0u);
const BORDER_PATTERN_GROOVE: array<u32, 8> = array<u32, 8>(1u, 0u, 1u, 0u, 1u, 0u, 1u, 0u);
const BORDER_PATTERN_RIDGE: array<u32, 8> = array<u32, 8>(1u, 0u, 1u, 0u, 1u, 0u, 1u, 0u);
const BORDER_PATTERN_INSET: array<u32, 8> = array<u32, 8>(1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u);
const BORDER_PATTERN_OUTSET: array<u32, 8> = array<u32, 8>(1u, 1u, 1u, 1u, 1u, 1u, 1u, 1u);

fn border_pattern(style: u32) -> array<u32, 8> {
    switch style {
        case 0u: { return BORDER_PATTERN_NONE; }
        case 1u: { return BORDER_PATTERN_SOLID; }
        case 2u: { return BORDER_PATTERN_DASHED; }
        case 3u: { return BORDER_PATTERN_DOTTED; }
        case 4u: { return BORDER_PATTERN_DOUBLE; }
        case 5u: { return BORDER_PATTERN_GROOVE; }
        case 6u: { return BORDER_PATTERN_RIDGE; }
        case 7u: { return BORDER_PATTERN_INSET; }
        case 8u: { return BORDER_PATTERN_OUTSET; }
        default: { return BORDER_PATTERN_NONE; }
    }
}

fn border_dash_test(pixel_offset: u32, style: u32) -> bool {
    let pattern = border_pattern(style);
    return pattern[pixel_offset % 8u] == 1u;
}


// --- Blend Modes ---
// Generated from blend_lut.rs (CSS Compositing Level 1)
// 12 per-channel blend modes, converted from 0-255 integer to 0-1 float

// Per-channel blend functions (0-1 float range)
fn blend_normal(src: f32, dst: f32) -> f32 {
    return clamp(src, 0.0, 1.0);
}

fn blend_multiply(src: f32, dst: f32) -> f32 {
    return clamp(src * dst, 0.0, 1.0);
}

fn blend_screen(src: f32, dst: f32) -> f32 {
    return clamp(1.0 - (1.0 - src) * (1.0 - dst), 0.0, 1.0);
}

fn blend_overlay(src: f32, dst: f32) -> f32 {
    var result: f32;
    if (dst < 0.5) { result = 2.0 * src * dst; }
    else { result = 1.0 - 2.0 * (1.0 - src) * (1.0 - dst); }
    return clamp(result, 0.0, 1.0);
}

fn blend_darken(src: f32, dst: f32) -> f32 {
    return clamp(min(src, dst), 0.0, 1.0);
}

fn blend_lighten(src: f32, dst: f32) -> f32 {
    return clamp(max(src, dst), 0.0, 1.0);
}

fn blend_colordodge(src: f32, dst: f32) -> f32 {
    var result: f32;
    if (dst == 0.0) { result = 0.0; }
    else if (src == 1.0) { result = 1.0; }
    else { result = clamp(dst / (1.0 - src), 0.0, 1.0); }
    return clamp(result, 0.0, 1.0);
}

fn blend_colorburn(src: f32, dst: f32) -> f32 {
    var result: f32;
    if (dst == 1.0) { result = 1.0; }
    else if (src == 0.0) { result = 0.0; }
    else { result = clamp(1.0 - (1.0 - dst) / src, 0.0, 1.0); }
    return clamp(result, 0.0, 1.0);
}

fn blend_hardlight(src: f32, dst: f32) -> f32 {
    var result: f32;
    if (src < 0.5) { result = 2.0 * src * dst; }
    else { result = 1.0 - 2.0 * (1.0 - src) * (1.0 - dst); }
    return clamp(result, 0.0, 1.0);
}

fn blend_softlight(src: f32, dst: f32) -> f32 {
    var result: f32;
    if (src <= 0.5) {
        result = dst - (1.0 - dst) * dst * (0.5 - src);
    } else {
        let v = select(sqrt(dst) * 0.25, dst, dst <= 0.25);
        result = dst + dst * (1.0 - dst) * (src - 0.5) / max(v, 0.001);
    }
    return clamp(result, 0.0, 1.0);
}

fn blend_difference(src: f32, dst: f32) -> f32 {
    return clamp(abs(src - dst), 0.0, 1.0);
}

fn blend_exclusion(src: f32, dst: f32) -> f32 {
    return clamp(src + dst - 2.0 * src * dst, 0.0, 1.0);
}

// Blend mode dispatch
fn blend_channel(src: f32, dst: f32, mode: u32) -> f32 {
    switch mode {
        case 0u: { return blend_normal(src, dst); }
        case 1u: { return blend_multiply(src, dst); }
        case 2u: { return blend_screen(src, dst); }
        case 3u: { return blend_overlay(src, dst); }
        case 4u: { return blend_darken(src, dst); }
        case 5u: { return blend_lighten(src, dst); }
        case 6u: { return blend_colordodge(src, dst); }
        case 7u: { return blend_colorburn(src, dst); }
        case 8u: { return blend_hardlight(src, dst); }
        case 9u: { return blend_softlight(src, dst); }
        case 10u: { return blend_difference(src, dst); }
        case 11u: { return blend_exclusion(src, dst); }
        default: { return src; }
    }
}

fn apply_blend_mode(src: vec4<f32>, dst: vec4<f32>, mode: u32) -> vec4<f32> {
    return vec4<f32>(
        blend_channel(src.r, dst.r, mode),
        blend_channel(src.g, dst.g, mode),
        blend_channel(src.b, dst.b, mode),
        src.a,
    );
}


// --- 8x8 Bitmap Font ---
// Generated from text_bitmap.rs FONT_8X8 (128 glyphs, 8 bytes each)

const GLYPH_WIDTH: u32 = 8u;
const GLYPH_HEIGHT: u32 = 8u;

// Glyph bitmap data: glyph_index * 8 + row = byte with 8 pixel bits (MSB=left)
const GLYPH_DATA: array<u32, 1024> = array<u32, 1024>(
    255u, // glyph 0, row 0
    129u, // glyph 0, row 1
    129u, // glyph 0, row 2
    129u, // glyph 0, row 3
    129u, // glyph 0, row 4
    129u, // glyph 0, row 5
    129u, // glyph 0, row 6
    255u, // glyph 0, row 7
    255u, // glyph 1, row 0
    129u, // glyph 1, row 1
    129u, // glyph 1, row 2
    129u, // glyph 1, row 3
    129u, // glyph 1, row 4
    129u, // glyph 1, row 5
    129u, // glyph 1, row 6
    255u, // glyph 1, row 7
    255u, // glyph 2, row 0
    129u, // glyph 2, row 1
    129u, // glyph 2, row 2
    129u, // glyph 2, row 3
    129u, // glyph 2, row 4
    129u, // glyph 2, row 5
    129u, // glyph 2, row 6
    255u, // glyph 2, row 7
    255u, // glyph 3, row 0
    129u, // glyph 3, row 1
    129u, // glyph 3, row 2
    129u, // glyph 3, row 3
    129u, // glyph 3, row 4
    129u, // glyph 3, row 5
    129u, // glyph 3, row 6
    255u, // glyph 3, row 7
    255u, // glyph 4, row 0
    129u, // glyph 4, row 1
    129u, // glyph 4, row 2
    129u, // glyph 4, row 3
    129u, // glyph 4, row 4
    129u, // glyph 4, row 5
    129u, // glyph 4, row 6
    255u, // glyph 4, row 7
    255u, // glyph 5, row 0
    129u, // glyph 5, row 1
    129u, // glyph 5, row 2
    129u, // glyph 5, row 3
    129u, // glyph 5, row 4
    129u, // glyph 5, row 5
    129u, // glyph 5, row 6
    255u, // glyph 5, row 7
    255u, // glyph 6, row 0
    129u, // glyph 6, row 1
    129u, // glyph 6, row 2
    129u, // glyph 6, row 3
    129u, // glyph 6, row 4
    129u, // glyph 6, row 5
    129u, // glyph 6, row 6
    255u, // glyph 6, row 7
    255u, // glyph 7, row 0
    129u, // glyph 7, row 1
    129u, // glyph 7, row 2
    129u, // glyph 7, row 3
    129u, // glyph 7, row 4
    129u, // glyph 7, row 5
    129u, // glyph 7, row 6
    255u, // glyph 7, row 7
    255u, // glyph 8, row 0
    129u, // glyph 8, row 1
    129u, // glyph 8, row 2
    129u, // glyph 8, row 3
    129u, // glyph 8, row 4
    129u, // glyph 8, row 5
    129u, // glyph 8, row 6
    255u, // glyph 8, row 7
    255u, // glyph 9, row 0
    129u, // glyph 9, row 1
    129u, // glyph 9, row 2
    129u, // glyph 9, row 3
    129u, // glyph 9, row 4
    129u, // glyph 9, row 5
    129u, // glyph 9, row 6
    255u, // glyph 9, row 7
    255u, // glyph 10, row 0
    129u, // glyph 10, row 1
    129u, // glyph 10, row 2
    129u, // glyph 10, row 3
    129u, // glyph 10, row 4
    129u, // glyph 10, row 5
    129u, // glyph 10, row 6
    255u, // glyph 10, row 7
    255u, // glyph 11, row 0
    129u, // glyph 11, row 1
    129u, // glyph 11, row 2
    129u, // glyph 11, row 3
    129u, // glyph 11, row 4
    129u, // glyph 11, row 5
    129u, // glyph 11, row 6
    255u, // glyph 11, row 7
    255u, // glyph 12, row 0
    129u, // glyph 12, row 1
    129u, // glyph 12, row 2
    129u, // glyph 12, row 3
    129u, // glyph 12, row 4
    129u, // glyph 12, row 5
    129u, // glyph 12, row 6
    255u, // glyph 12, row 7
    255u, // glyph 13, row 0
    129u, // glyph 13, row 1
    129u, // glyph 13, row 2
    129u, // glyph 13, row 3
    129u, // glyph 13, row 4
    129u, // glyph 13, row 5
    129u, // glyph 13, row 6
    255u, // glyph 13, row 7
    255u, // glyph 14, row 0
    129u, // glyph 14, row 1
    129u, // glyph 14, row 2
    129u, // glyph 14, row 3
    129u, // glyph 14, row 4
    129u, // glyph 14, row 5
    129u, // glyph 14, row 6
    255u, // glyph 14, row 7
    255u, // glyph 15, row 0
    129u, // glyph 15, row 1
    129u, // glyph 15, row 2
    129u, // glyph 15, row 3
    129u, // glyph 15, row 4
    129u, // glyph 15, row 5
    129u, // glyph 15, row 6
    255u, // glyph 15, row 7
    255u, // glyph 16, row 0
    129u, // glyph 16, row 1
    129u, // glyph 16, row 2
    129u, // glyph 16, row 3
    129u, // glyph 16, row 4
    129u, // glyph 16, row 5
    129u, // glyph 16, row 6
    255u, // glyph 16, row 7
    255u, // glyph 17, row 0
    129u, // glyph 17, row 1
    129u, // glyph 17, row 2
    129u, // glyph 17, row 3
    129u, // glyph 17, row 4
    129u, // glyph 17, row 5
    129u, // glyph 17, row 6
    255u, // glyph 17, row 7
    255u, // glyph 18, row 0
    129u, // glyph 18, row 1
    129u, // glyph 18, row 2
    129u, // glyph 18, row 3
    129u, // glyph 18, row 4
    129u, // glyph 18, row 5
    129u, // glyph 18, row 6
    255u, // glyph 18, row 7
    255u, // glyph 19, row 0
    129u, // glyph 19, row 1
    129u, // glyph 19, row 2
    129u, // glyph 19, row 3
    129u, // glyph 19, row 4
    129u, // glyph 19, row 5
    129u, // glyph 19, row 6
    255u, // glyph 19, row 7
    255u, // glyph 20, row 0
    129u, // glyph 20, row 1
    129u, // glyph 20, row 2
    129u, // glyph 20, row 3
    129u, // glyph 20, row 4
    129u, // glyph 20, row 5
    129u, // glyph 20, row 6
    255u, // glyph 20, row 7
    255u, // glyph 21, row 0
    129u, // glyph 21, row 1
    129u, // glyph 21, row 2
    129u, // glyph 21, row 3
    129u, // glyph 21, row 4
    129u, // glyph 21, row 5
    129u, // glyph 21, row 6
    255u, // glyph 21, row 7
    255u, // glyph 22, row 0
    129u, // glyph 22, row 1
    129u, // glyph 22, row 2
    129u, // glyph 22, row 3
    129u, // glyph 22, row 4
    129u, // glyph 22, row 5
    129u, // glyph 22, row 6
    255u, // glyph 22, row 7
    255u, // glyph 23, row 0
    129u, // glyph 23, row 1
    129u, // glyph 23, row 2
    129u, // glyph 23, row 3
    129u, // glyph 23, row 4
    129u, // glyph 23, row 5
    129u, // glyph 23, row 6
    255u, // glyph 23, row 7
    255u, // glyph 24, row 0
    129u, // glyph 24, row 1
    129u, // glyph 24, row 2
    129u, // glyph 24, row 3
    129u, // glyph 24, row 4
    129u, // glyph 24, row 5
    129u, // glyph 24, row 6
    255u, // glyph 24, row 7
    255u, // glyph 25, row 0
    129u, // glyph 25, row 1
    129u, // glyph 25, row 2
    129u, // glyph 25, row 3
    129u, // glyph 25, row 4
    129u, // glyph 25, row 5
    129u, // glyph 25, row 6
    255u, // glyph 25, row 7
    255u, // glyph 26, row 0
    129u, // glyph 26, row 1
    129u, // glyph 26, row 2
    129u, // glyph 26, row 3
    129u, // glyph 26, row 4
    129u, // glyph 26, row 5
    129u, // glyph 26, row 6
    255u, // glyph 26, row 7
    255u, // glyph 27, row 0
    129u, // glyph 27, row 1
    129u, // glyph 27, row 2
    129u, // glyph 27, row 3
    129u, // glyph 27, row 4
    129u, // glyph 27, row 5
    129u, // glyph 27, row 6
    255u, // glyph 27, row 7
    255u, // glyph 28, row 0
    129u, // glyph 28, row 1
    129u, // glyph 28, row 2
    129u, // glyph 28, row 3
    129u, // glyph 28, row 4
    129u, // glyph 28, row 5
    129u, // glyph 28, row 6
    255u, // glyph 28, row 7
    255u, // glyph 29, row 0
    129u, // glyph 29, row 1
    129u, // glyph 29, row 2
    129u, // glyph 29, row 3
    129u, // glyph 29, row 4
    129u, // glyph 29, row 5
    129u, // glyph 29, row 6
    255u, // glyph 29, row 7
    255u, // glyph 30, row 0
    129u, // glyph 30, row 1
    129u, // glyph 30, row 2
    129u, // glyph 30, row 3
    129u, // glyph 30, row 4
    129u, // glyph 30, row 5
    129u, // glyph 30, row 6
    255u, // glyph 30, row 7
    255u, // glyph 31, row 0
    129u, // glyph 31, row 1
    129u, // glyph 31, row 2
    129u, // glyph 31, row 3
    129u, // glyph 31, row 4
    129u, // glyph 31, row 5
    129u, // glyph 31, row 6
    255u, // glyph 31, row 7
    255u, // glyph 32, row 0
    129u, // glyph 32, row 1
    129u, // glyph 32, row 2
    129u, // glyph 32, row 3
    129u, // glyph 32, row 4
    129u, // glyph 32, row 5
    129u, // glyph 32, row 6
    255u, // glyph 32, row 7
    24u, // glyph 33, row 0
    24u, // glyph 33, row 1
    24u, // glyph 33, row 2
    24u, // glyph 33, row 3
    24u, // glyph 33, row 4
    0u, // glyph 33, row 5
    24u, // glyph 33, row 6
    0u, // glyph 33, row 7
    108u, // glyph 34, row 0
    108u, // glyph 34, row 1
    108u, // glyph 34, row 2
    0u, // glyph 34, row 3
    0u, // glyph 34, row 4
    0u, // glyph 34, row 5
    0u, // glyph 34, row 6
    0u, // glyph 34, row 7
    0u, // glyph 35, row 0
    108u, // glyph 35, row 1
    254u, // glyph 35, row 2
    108u, // glyph 35, row 3
    108u, // glyph 35, row 4
    254u, // glyph 35, row 5
    108u, // glyph 35, row 6
    0u, // glyph 35, row 7
    24u, // glyph 36, row 0
    62u, // glyph 36, row 1
    96u, // glyph 36, row 2
    60u, // glyph 36, row 3
    6u, // glyph 36, row 4
    124u, // glyph 36, row 5
    24u, // glyph 36, row 6
    0u, // glyph 36, row 7
    0u, // glyph 37, row 0
    102u, // glyph 37, row 1
    108u, // glyph 37, row 2
    24u, // glyph 37, row 3
    48u, // glyph 37, row 4
    102u, // glyph 37, row 5
    0u, // glyph 37, row 6
    0u, // glyph 37, row 7
    255u, // glyph 38, row 0
    129u, // glyph 38, row 1
    129u, // glyph 38, row 2
    129u, // glyph 38, row 3
    129u, // glyph 38, row 4
    129u, // glyph 38, row 5
    129u, // glyph 38, row 6
    255u, // glyph 38, row 7
    255u, // glyph 39, row 0
    129u, // glyph 39, row 1
    129u, // glyph 39, row 2
    129u, // glyph 39, row 3
    129u, // glyph 39, row 4
    129u, // glyph 39, row 5
    129u, // glyph 39, row 6
    255u, // glyph 39, row 7
    255u, // glyph 40, row 0
    129u, // glyph 40, row 1
    129u, // glyph 40, row 2
    129u, // glyph 40, row 3
    129u, // glyph 40, row 4
    129u, // glyph 40, row 5
    129u, // glyph 40, row 6
    255u, // glyph 40, row 7
    255u, // glyph 41, row 0
    129u, // glyph 41, row 1
    129u, // glyph 41, row 2
    129u, // glyph 41, row 3
    129u, // glyph 41, row 4
    129u, // glyph 41, row 5
    129u, // glyph 41, row 6
    255u, // glyph 41, row 7
    255u, // glyph 42, row 0
    129u, // glyph 42, row 1
    129u, // glyph 42, row 2
    129u, // glyph 42, row 3
    129u, // glyph 42, row 4
    129u, // glyph 42, row 5
    129u, // glyph 42, row 6
    255u, // glyph 42, row 7
    255u, // glyph 43, row 0
    129u, // glyph 43, row 1
    129u, // glyph 43, row 2
    129u, // glyph 43, row 3
    129u, // glyph 43, row 4
    129u, // glyph 43, row 5
    129u, // glyph 43, row 6
    255u, // glyph 43, row 7
    255u, // glyph 44, row 0
    129u, // glyph 44, row 1
    129u, // glyph 44, row 2
    129u, // glyph 44, row 3
    129u, // glyph 44, row 4
    129u, // glyph 44, row 5
    129u, // glyph 44, row 6
    255u, // glyph 44, row 7
    255u, // glyph 45, row 0
    129u, // glyph 45, row 1
    129u, // glyph 45, row 2
    129u, // glyph 45, row 3
    129u, // glyph 45, row 4
    129u, // glyph 45, row 5
    129u, // glyph 45, row 6
    255u, // glyph 45, row 7
    255u, // glyph 46, row 0
    129u, // glyph 46, row 1
    129u, // glyph 46, row 2
    129u, // glyph 46, row 3
    129u, // glyph 46, row 4
    129u, // glyph 46, row 5
    129u, // glyph 46, row 6
    255u, // glyph 46, row 7
    255u, // glyph 47, row 0
    129u, // glyph 47, row 1
    129u, // glyph 47, row 2
    129u, // glyph 47, row 3
    129u, // glyph 47, row 4
    129u, // glyph 47, row 5
    129u, // glyph 47, row 6
    255u, // glyph 47, row 7
    60u, // glyph 48, row 0
    102u, // glyph 48, row 1
    110u, // glyph 48, row 2
    118u, // glyph 48, row 3
    102u, // glyph 48, row 4
    102u, // glyph 48, row 5
    60u, // glyph 48, row 6
    0u, // glyph 48, row 7
    24u, // glyph 49, row 0
    56u, // glyph 49, row 1
    24u, // glyph 49, row 2
    24u, // glyph 49, row 3
    24u, // glyph 49, row 4
    24u, // glyph 49, row 5
    126u, // glyph 49, row 6
    0u, // glyph 49, row 7
    60u, // glyph 50, row 0
    102u, // glyph 50, row 1
    6u, // glyph 50, row 2
    28u, // glyph 50, row 3
    48u, // glyph 50, row 4
    96u, // glyph 50, row 5
    126u, // glyph 50, row 6
    0u, // glyph 50, row 7
    60u, // glyph 51, row 0
    102u, // glyph 51, row 1
    6u, // glyph 51, row 2
    28u, // glyph 51, row 3
    6u, // glyph 51, row 4
    102u, // glyph 51, row 5
    60u, // glyph 51, row 6
    0u, // glyph 51, row 7
    12u, // glyph 52, row 0
    28u, // glyph 52, row 1
    60u, // glyph 52, row 2
    108u, // glyph 52, row 3
    126u, // glyph 52, row 4
    12u, // glyph 52, row 5
    30u, // glyph 52, row 6
    0u, // glyph 52, row 7
    126u, // glyph 53, row 0
    96u, // glyph 53, row 1
    124u, // glyph 53, row 2
    6u, // glyph 53, row 3
    6u, // glyph 53, row 4
    102u, // glyph 53, row 5
    60u, // glyph 53, row 6
    0u, // glyph 53, row 7
    28u, // glyph 54, row 0
    48u, // glyph 54, row 1
    96u, // glyph 54, row 2
    124u, // glyph 54, row 3
    102u, // glyph 54, row 4
    102u, // glyph 54, row 5
    60u, // glyph 54, row 6
    0u, // glyph 54, row 7
    126u, // glyph 55, row 0
    6u, // glyph 55, row 1
    12u, // glyph 55, row 2
    24u, // glyph 55, row 3
    48u, // glyph 55, row 4
    48u, // glyph 55, row 5
    48u, // glyph 55, row 6
    0u, // glyph 55, row 7
    60u, // glyph 56, row 0
    102u, // glyph 56, row 1
    102u, // glyph 56, row 2
    60u, // glyph 56, row 3
    102u, // glyph 56, row 4
    102u, // glyph 56, row 5
    60u, // glyph 56, row 6
    0u, // glyph 56, row 7
    60u, // glyph 57, row 0
    102u, // glyph 57, row 1
    102u, // glyph 57, row 2
    62u, // glyph 57, row 3
    6u, // glyph 57, row 4
    12u, // glyph 57, row 5
    56u, // glyph 57, row 6
    0u, // glyph 57, row 7
    255u, // glyph 58, row 0
    129u, // glyph 58, row 1
    129u, // glyph 58, row 2
    129u, // glyph 58, row 3
    129u, // glyph 58, row 4
    129u, // glyph 58, row 5
    129u, // glyph 58, row 6
    255u, // glyph 58, row 7
    255u, // glyph 59, row 0
    129u, // glyph 59, row 1
    129u, // glyph 59, row 2
    129u, // glyph 59, row 3
    129u, // glyph 59, row 4
    129u, // glyph 59, row 5
    129u, // glyph 59, row 6
    255u, // glyph 59, row 7
    255u, // glyph 60, row 0
    129u, // glyph 60, row 1
    129u, // glyph 60, row 2
    129u, // glyph 60, row 3
    129u, // glyph 60, row 4
    129u, // glyph 60, row 5
    129u, // glyph 60, row 6
    255u, // glyph 60, row 7
    255u, // glyph 61, row 0
    129u, // glyph 61, row 1
    129u, // glyph 61, row 2
    129u, // glyph 61, row 3
    129u, // glyph 61, row 4
    129u, // glyph 61, row 5
    129u, // glyph 61, row 6
    255u, // glyph 61, row 7
    255u, // glyph 62, row 0
    129u, // glyph 62, row 1
    129u, // glyph 62, row 2
    129u, // glyph 62, row 3
    129u, // glyph 62, row 4
    129u, // glyph 62, row 5
    129u, // glyph 62, row 6
    255u, // glyph 62, row 7
    255u, // glyph 63, row 0
    129u, // glyph 63, row 1
    129u, // glyph 63, row 2
    129u, // glyph 63, row 3
    129u, // glyph 63, row 4
    129u, // glyph 63, row 5
    129u, // glyph 63, row 6
    255u, // glyph 63, row 7
    255u, // glyph 64, row 0
    129u, // glyph 64, row 1
    129u, // glyph 64, row 2
    129u, // glyph 64, row 3
    129u, // glyph 64, row 4
    129u, // glyph 64, row 5
    129u, // glyph 64, row 6
    255u, // glyph 64, row 7
    24u, // glyph 65, row 0
    60u, // glyph 65, row 1
    102u, // glyph 65, row 2
    102u, // glyph 65, row 3
    126u, // glyph 65, row 4
    102u, // glyph 65, row 5
    102u, // glyph 65, row 6
    0u, // glyph 65, row 7
    124u, // glyph 66, row 0
    102u, // glyph 66, row 1
    102u, // glyph 66, row 2
    124u, // glyph 66, row 3
    102u, // glyph 66, row 4
    102u, // glyph 66, row 5
    124u, // glyph 66, row 6
    0u, // glyph 66, row 7
    60u, // glyph 67, row 0
    102u, // glyph 67, row 1
    96u, // glyph 67, row 2
    96u, // glyph 67, row 3
    96u, // glyph 67, row 4
    102u, // glyph 67, row 5
    60u, // glyph 67, row 6
    0u, // glyph 67, row 7
    120u, // glyph 68, row 0
    108u, // glyph 68, row 1
    102u, // glyph 68, row 2
    102u, // glyph 68, row 3
    102u, // glyph 68, row 4
    108u, // glyph 68, row 5
    120u, // glyph 68, row 6
    0u, // glyph 68, row 7
    126u, // glyph 69, row 0
    96u, // glyph 69, row 1
    96u, // glyph 69, row 2
    124u, // glyph 69, row 3
    96u, // glyph 69, row 4
    96u, // glyph 69, row 5
    126u, // glyph 69, row 6
    0u, // glyph 69, row 7
    126u, // glyph 70, row 0
    96u, // glyph 70, row 1
    96u, // glyph 70, row 2
    124u, // glyph 70, row 3
    96u, // glyph 70, row 4
    96u, // glyph 70, row 5
    96u, // glyph 70, row 6
    0u, // glyph 70, row 7
    60u, // glyph 71, row 0
    102u, // glyph 71, row 1
    96u, // glyph 71, row 2
    110u, // glyph 71, row 3
    102u, // glyph 71, row 4
    102u, // glyph 71, row 5
    62u, // glyph 71, row 6
    0u, // glyph 71, row 7
    102u, // glyph 72, row 0
    102u, // glyph 72, row 1
    102u, // glyph 72, row 2
    126u, // glyph 72, row 3
    102u, // glyph 72, row 4
    102u, // glyph 72, row 5
    102u, // glyph 72, row 6
    0u, // glyph 72, row 7
    60u, // glyph 73, row 0
    24u, // glyph 73, row 1
    24u, // glyph 73, row 2
    24u, // glyph 73, row 3
    24u, // glyph 73, row 4
    24u, // glyph 73, row 5
    60u, // glyph 73, row 6
    0u, // glyph 73, row 7
    30u, // glyph 74, row 0
    12u, // glyph 74, row 1
    12u, // glyph 74, row 2
    12u, // glyph 74, row 3
    12u, // glyph 74, row 4
    108u, // glyph 74, row 5
    56u, // glyph 74, row 6
    0u, // glyph 74, row 7
    102u, // glyph 75, row 0
    108u, // glyph 75, row 1
    120u, // glyph 75, row 2
    112u, // glyph 75, row 3
    120u, // glyph 75, row 4
    108u, // glyph 75, row 5
    102u, // glyph 75, row 6
    0u, // glyph 75, row 7
    96u, // glyph 76, row 0
    96u, // glyph 76, row 1
    96u, // glyph 76, row 2
    96u, // glyph 76, row 3
    96u, // glyph 76, row 4
    96u, // glyph 76, row 5
    126u, // glyph 76, row 6
    0u, // glyph 76, row 7
    99u, // glyph 77, row 0
    119u, // glyph 77, row 1
    127u, // glyph 77, row 2
    107u, // glyph 77, row 3
    99u, // glyph 77, row 4
    99u, // glyph 77, row 5
    99u, // glyph 77, row 6
    0u, // glyph 77, row 7
    102u, // glyph 78, row 0
    118u, // glyph 78, row 1
    126u, // glyph 78, row 2
    110u, // glyph 78, row 3
    102u, // glyph 78, row 4
    102u, // glyph 78, row 5
    102u, // glyph 78, row 6
    0u, // glyph 78, row 7
    60u, // glyph 79, row 0
    102u, // glyph 79, row 1
    102u, // glyph 79, row 2
    102u, // glyph 79, row 3
    102u, // glyph 79, row 4
    102u, // glyph 79, row 5
    60u, // glyph 79, row 6
    0u, // glyph 79, row 7
    124u, // glyph 80, row 0
    102u, // glyph 80, row 1
    102u, // glyph 80, row 2
    124u, // glyph 80, row 3
    96u, // glyph 80, row 4
    96u, // glyph 80, row 5
    96u, // glyph 80, row 6
    0u, // glyph 80, row 7
    60u, // glyph 81, row 0
    102u, // glyph 81, row 1
    102u, // glyph 81, row 2
    102u, // glyph 81, row 3
    106u, // glyph 81, row 4
    108u, // glyph 81, row 5
    54u, // glyph 81, row 6
    0u, // glyph 81, row 7
    124u, // glyph 82, row 0
    102u, // glyph 82, row 1
    102u, // glyph 82, row 2
    124u, // glyph 82, row 3
    120u, // glyph 82, row 4
    108u, // glyph 82, row 5
    102u, // glyph 82, row 6
    0u, // glyph 82, row 7
    60u, // glyph 83, row 0
    102u, // glyph 83, row 1
    96u, // glyph 83, row 2
    60u, // glyph 83, row 3
    6u, // glyph 83, row 4
    102u, // glyph 83, row 5
    60u, // glyph 83, row 6
    0u, // glyph 83, row 7
    126u, // glyph 84, row 0
    24u, // glyph 84, row 1
    24u, // glyph 84, row 2
    24u, // glyph 84, row 3
    24u, // glyph 84, row 4
    24u, // glyph 84, row 5
    24u, // glyph 84, row 6
    0u, // glyph 84, row 7
    102u, // glyph 85, row 0
    102u, // glyph 85, row 1
    102u, // glyph 85, row 2
    102u, // glyph 85, row 3
    102u, // glyph 85, row 4
    102u, // glyph 85, row 5
    60u, // glyph 85, row 6
    0u, // glyph 85, row 7
    102u, // glyph 86, row 0
    102u, // glyph 86, row 1
    102u, // glyph 86, row 2
    102u, // glyph 86, row 3
    102u, // glyph 86, row 4
    60u, // glyph 86, row 5
    24u, // glyph 86, row 6
    0u, // glyph 86, row 7
    99u, // glyph 87, row 0
    99u, // glyph 87, row 1
    99u, // glyph 87, row 2
    107u, // glyph 87, row 3
    127u, // glyph 87, row 4
    119u, // glyph 87, row 5
    99u, // glyph 87, row 6
    0u, // glyph 87, row 7
    102u, // glyph 88, row 0
    102u, // glyph 88, row 1
    60u, // glyph 88, row 2
    24u, // glyph 88, row 3
    60u, // glyph 88, row 4
    102u, // glyph 88, row 5
    102u, // glyph 88, row 6
    0u, // glyph 88, row 7
    102u, // glyph 89, row 0
    102u, // glyph 89, row 1
    102u, // glyph 89, row 2
    60u, // glyph 89, row 3
    24u, // glyph 89, row 4
    24u, // glyph 89, row 5
    24u, // glyph 89, row 6
    0u, // glyph 89, row 7
    126u, // glyph 90, row 0
    6u, // glyph 90, row 1
    12u, // glyph 90, row 2
    24u, // glyph 90, row 3
    48u, // glyph 90, row 4
    96u, // glyph 90, row 5
    126u, // glyph 90, row 6
    0u, // glyph 90, row 7
    255u, // glyph 91, row 0
    129u, // glyph 91, row 1
    129u, // glyph 91, row 2
    129u, // glyph 91, row 3
    129u, // glyph 91, row 4
    129u, // glyph 91, row 5
    129u, // glyph 91, row 6
    255u, // glyph 91, row 7
    255u, // glyph 92, row 0
    129u, // glyph 92, row 1
    129u, // glyph 92, row 2
    129u, // glyph 92, row 3
    129u, // glyph 92, row 4
    129u, // glyph 92, row 5
    129u, // glyph 92, row 6
    255u, // glyph 92, row 7
    255u, // glyph 93, row 0
    129u, // glyph 93, row 1
    129u, // glyph 93, row 2
    129u, // glyph 93, row 3
    129u, // glyph 93, row 4
    129u, // glyph 93, row 5
    129u, // glyph 93, row 6
    255u, // glyph 93, row 7
    255u, // glyph 94, row 0
    129u, // glyph 94, row 1
    129u, // glyph 94, row 2
    129u, // glyph 94, row 3
    129u, // glyph 94, row 4
    129u, // glyph 94, row 5
    129u, // glyph 94, row 6
    255u, // glyph 94, row 7
    255u, // glyph 95, row 0
    129u, // glyph 95, row 1
    129u, // glyph 95, row 2
    129u, // glyph 95, row 3
    129u, // glyph 95, row 4
    129u, // glyph 95, row 5
    129u, // glyph 95, row 6
    255u, // glyph 95, row 7
    255u, // glyph 96, row 0
    129u, // glyph 96, row 1
    129u, // glyph 96, row 2
    129u, // glyph 96, row 3
    129u, // glyph 96, row 4
    129u, // glyph 96, row 5
    129u, // glyph 96, row 6
    255u, // glyph 96, row 7
    0u, // glyph 97, row 0
    0u, // glyph 97, row 1
    60u, // glyph 97, row 2
    6u, // glyph 97, row 3
    62u, // glyph 97, row 4
    102u, // glyph 97, row 5
    62u, // glyph 97, row 6
    0u, // glyph 97, row 7
    96u, // glyph 98, row 0
    96u, // glyph 98, row 1
    124u, // glyph 98, row 2
    102u, // glyph 98, row 3
    102u, // glyph 98, row 4
    102u, // glyph 98, row 5
    124u, // glyph 98, row 6
    0u, // glyph 98, row 7
    0u, // glyph 99, row 0
    0u, // glyph 99, row 1
    60u, // glyph 99, row 2
    96u, // glyph 99, row 3
    96u, // glyph 99, row 4
    96u, // glyph 99, row 5
    60u, // glyph 99, row 6
    0u, // glyph 99, row 7
    6u, // glyph 100, row 0
    6u, // glyph 100, row 1
    62u, // glyph 100, row 2
    102u, // glyph 100, row 3
    102u, // glyph 100, row 4
    102u, // glyph 100, row 5
    62u, // glyph 100, row 6
    0u, // glyph 100, row 7
    0u, // glyph 101, row 0
    0u, // glyph 101, row 1
    60u, // glyph 101, row 2
    102u, // glyph 101, row 3
    126u, // glyph 101, row 4
    96u, // glyph 101, row 5
    60u, // glyph 101, row 6
    0u, // glyph 101, row 7
    28u, // glyph 102, row 0
    48u, // glyph 102, row 1
    48u, // glyph 102, row 2
    124u, // glyph 102, row 3
    48u, // glyph 102, row 4
    48u, // glyph 102, row 5
    48u, // glyph 102, row 6
    0u, // glyph 102, row 7
    0u, // glyph 103, row 0
    0u, // glyph 103, row 1
    62u, // glyph 103, row 2
    102u, // glyph 103, row 3
    102u, // glyph 103, row 4
    62u, // glyph 103, row 5
    6u, // glyph 103, row 6
    60u, // glyph 103, row 7
    96u, // glyph 104, row 0
    96u, // glyph 104, row 1
    124u, // glyph 104, row 2
    102u, // glyph 104, row 3
    102u, // glyph 104, row 4
    102u, // glyph 104, row 5
    102u, // glyph 104, row 6
    0u, // glyph 104, row 7
    24u, // glyph 105, row 0
    0u, // glyph 105, row 1
    56u, // glyph 105, row 2
    24u, // glyph 105, row 3
    24u, // glyph 105, row 4
    24u, // glyph 105, row 5
    60u, // glyph 105, row 6
    0u, // glyph 105, row 7
    12u, // glyph 106, row 0
    0u, // glyph 106, row 1
    28u, // glyph 106, row 2
    12u, // glyph 106, row 3
    12u, // glyph 106, row 4
    12u, // glyph 106, row 5
    108u, // glyph 106, row 6
    56u, // glyph 106, row 7
    96u, // glyph 107, row 0
    96u, // glyph 107, row 1
    108u, // glyph 107, row 2
    120u, // glyph 107, row 3
    108u, // glyph 107, row 4
    102u, // glyph 107, row 5
    102u, // glyph 107, row 6
    0u, // glyph 107, row 7
    56u, // glyph 108, row 0
    24u, // glyph 108, row 1
    24u, // glyph 108, row 2
    24u, // glyph 108, row 3
    24u, // glyph 108, row 4
    24u, // glyph 108, row 5
    60u, // glyph 108, row 6
    0u, // glyph 108, row 7
    0u, // glyph 109, row 0
    0u, // glyph 109, row 1
    102u, // glyph 109, row 2
    127u, // glyph 109, row 3
    127u, // glyph 109, row 4
    107u, // glyph 109, row 5
    99u, // glyph 109, row 6
    0u, // glyph 109, row 7
    0u, // glyph 110, row 0
    0u, // glyph 110, row 1
    124u, // glyph 110, row 2
    102u, // glyph 110, row 3
    102u, // glyph 110, row 4
    102u, // glyph 110, row 5
    102u, // glyph 110, row 6
    0u, // glyph 110, row 7
    0u, // glyph 111, row 0
    0u, // glyph 111, row 1
    60u, // glyph 111, row 2
    102u, // glyph 111, row 3
    102u, // glyph 111, row 4
    102u, // glyph 111, row 5
    60u, // glyph 111, row 6
    0u, // glyph 111, row 7
    0u, // glyph 112, row 0
    0u, // glyph 112, row 1
    124u, // glyph 112, row 2
    102u, // glyph 112, row 3
    102u, // glyph 112, row 4
    124u, // glyph 112, row 5
    96u, // glyph 112, row 6
    96u, // glyph 112, row 7
    0u, // glyph 113, row 0
    0u, // glyph 113, row 1
    62u, // glyph 113, row 2
    102u, // glyph 113, row 3
    102u, // glyph 113, row 4
    62u, // glyph 113, row 5
    6u, // glyph 113, row 6
    6u, // glyph 113, row 7
    0u, // glyph 114, row 0
    0u, // glyph 114, row 1
    124u, // glyph 114, row 2
    102u, // glyph 114, row 3
    96u, // glyph 114, row 4
    96u, // glyph 114, row 5
    96u, // glyph 114, row 6
    0u, // glyph 114, row 7
    0u, // glyph 115, row 0
    0u, // glyph 115, row 1
    62u, // glyph 115, row 2
    96u, // glyph 115, row 3
    60u, // glyph 115, row 4
    6u, // glyph 115, row 5
    124u, // glyph 115, row 6
    0u, // glyph 115, row 7
    24u, // glyph 116, row 0
    24u, // glyph 116, row 1
    126u, // glyph 116, row 2
    24u, // glyph 116, row 3
    24u, // glyph 116, row 4
    24u, // glyph 116, row 5
    14u, // glyph 116, row 6
    0u, // glyph 116, row 7
    0u, // glyph 117, row 0
    0u, // glyph 117, row 1
    102u, // glyph 117, row 2
    102u, // glyph 117, row 3
    102u, // glyph 117, row 4
    102u, // glyph 117, row 5
    62u, // glyph 117, row 6
    0u, // glyph 117, row 7
    0u, // glyph 118, row 0
    0u, // glyph 118, row 1
    102u, // glyph 118, row 2
    102u, // glyph 118, row 3
    102u, // glyph 118, row 4
    60u, // glyph 118, row 5
    24u, // glyph 118, row 6
    0u, // glyph 118, row 7
    0u, // glyph 119, row 0
    0u, // glyph 119, row 1
    99u, // glyph 119, row 2
    107u, // glyph 119, row 3
    127u, // glyph 119, row 4
    127u, // glyph 119, row 5
    54u, // glyph 119, row 6
    0u, // glyph 119, row 7
    0u, // glyph 120, row 0
    0u, // glyph 120, row 1
    102u, // glyph 120, row 2
    60u, // glyph 120, row 3
    24u, // glyph 120, row 4
    60u, // glyph 120, row 5
    102u, // glyph 120, row 6
    0u, // glyph 120, row 7
    0u, // glyph 121, row 0
    0u, // glyph 121, row 1
    102u, // glyph 121, row 2
    102u, // glyph 121, row 3
    62u, // glyph 121, row 4
    6u, // glyph 121, row 5
    60u, // glyph 121, row 6
    0u, // glyph 121, row 7
    0u, // glyph 122, row 0
    0u, // glyph 122, row 1
    126u, // glyph 122, row 2
    12u, // glyph 122, row 3
    24u, // glyph 122, row 4
    48u, // glyph 122, row 5
    126u, // glyph 122, row 6
    0u, // glyph 122, row 7
    255u, // glyph 123, row 0
    129u, // glyph 123, row 1
    129u, // glyph 123, row 2
    129u, // glyph 123, row 3
    129u, // glyph 123, row 4
    129u, // glyph 123, row 5
    129u, // glyph 123, row 6
    255u, // glyph 123, row 7
    255u, // glyph 124, row 0
    129u, // glyph 124, row 1
    129u, // glyph 124, row 2
    129u, // glyph 124, row 3
    129u, // glyph 124, row 4
    129u, // glyph 124, row 5
    129u, // glyph 124, row 6
    255u, // glyph 124, row 7
    255u, // glyph 125, row 0
    129u, // glyph 125, row 1
    129u, // glyph 125, row 2
    129u, // glyph 125, row 3
    129u, // glyph 125, row 4
    129u, // glyph 125, row 5
    129u, // glyph 125, row 6
    255u, // glyph 125, row 7
    255u, // glyph 126, row 0
    129u, // glyph 126, row 1
    129u, // glyph 126, row 2
    129u, // glyph 126, row 3
    129u, // glyph 126, row 4
    129u, // glyph 126, row 5
    129u, // glyph 126, row 6
    255u, // glyph 126, row 7
    255u, // glyph 127, row 0
    129u, // glyph 127, row 1
    129u, // glyph 127, row 2
    129u, // glyph 127, row 3
    129u, // glyph 127, row 4
    129u, // glyph 127, row 5
    129u, // glyph 127, row 6
    255u, // glyph 127, row 7
);

// Sample a single pixel from a glyph bitmap
// Returns 1.0 if the pixel is set, 0.0 otherwise
fn glyph_pixel(glyph_index: u32, row: u32, col: u32) -> f32 {
    if (glyph_index >= 128u || row >= 8u || col >= 8u) { return 0.0; }
    let byte_idx = glyph_index * 8u + row;
    let bits = GLYPH_DATA[byte_idx];
    let mask = 0x80u >> col;
    return select(0.0, 1.0, (bits & mask) != 0u);
}


// --- Border Rendering ---
// Generated from css_box.proto + border_lut.rs

// Returns the border width at a given pixel position on the rect edge
// Returns > 0 if in border region, 0 if in content area
fn border_width_at(px: f32, py: f32, r: RectStyle) -> f32 {
    let rel_x = px - r.x;
    let rel_y = py - r.y;
    // Distance from each edge
    let dist_left = rel_x;
    let dist_right = r.w - rel_x;
    let dist_top = rel_y;
    let dist_bottom = r.h - rel_y;

    // Determine which border segment we're on
    // Top/bottom borders span full width, left/right span between top and bottom border
    var bw: f32 = 0.0;

    // Check if in corner regions (use max of adjacent border widths)
    let in_top_left = rel_x < r.border_radius_tl && rel_y < r.border_radius_tl;
    let in_top_right = (r.w - rel_x) < r.border_radius_tr && rel_y < r.border_radius_tr;
    let in_bottom_right = (r.w - rel_x) < r.border_radius_br && (r.h - rel_y) < r.border_radius_br;
    let in_bottom_left = rel_x < r.border_radius_bl && (r.h - rel_y) < r.border_radius_bl;

    if (in_top_left || in_top_right || in_bottom_right || in_bottom_left) {
        // Corner: use the max border width of adjacent edges
        bw = max(max(r.border_width_top, r.border_width_bottom),
                 max(r.border_width_left, r.border_width_right));
    } else if (dist_top <= r.border_width_top) {
        bw = r.border_width_top;
    } else if (dist_bottom <= r.border_width_bottom) {
        bw = r.border_width_bottom;
    } else if (dist_left <= r.border_width_left) {
        bw = r.border_width_left;
    } else if (dist_right <= r.border_width_right) {
        bw = r.border_width_right;
    }

    return bw;
}

// Compute a dash pattern pixel offset for border dashing
fn border_pixel_offset(px: f32, py: f32, r: RectStyle) -> u32 {
    let rel_x = u32(px - r.x);
    let rel_y = u32(py - r.y);
    // Simple: use Manhattan distance as pattern offset
    return (rel_x + rel_y) % 8u;
}


// --- SDF Box Shadow Rendering ---
// Generated from css_box.proto box-shadow properties

// Compute signed distance from rounded rect edge
// Returns negative distance inside, positive outside
fn sdf_rounded_rect(px: f32, py: f32, x: f32, y: f32, w: f32, h: f32, tl: f32, tr: f32, br: f32, bl: f32) -> f32 {
    // Simple box SDF (corners handled separately for rounded rects)
    let cx = x + w * 0.5;
    let cy = y + h * 0.5;
    let hx = abs(px - cx) - w * 0.5;
    let hy = abs(py - cy) - h * 0.5;
    let d = min(max(hx, hy), 0.0);
    let dx = max(hx, 0.0);
    let dy = max(hy, 0.0);
    return sqrt(dx * dx + dy * dy) + d;
}

// Render drop shadow for a rect
fn render_drop_shadow(px: f32, py: f32, r: RectStyle) -> vec4<f32> {
    if (r.shadow_active == 0u) { return vec4<f32>(0.0, 0.0, 0.0, 0.0); }
    if (r.shadow_type != 0u) { return vec4<f32>(0.0, 0.0, 0.0, 0.0); } // drop only

    // Shadow rect: expanded by spread+blur, offset
    let expand = r.shadow_spread + r.shadow_blur;
    let sx = r.x + r.shadow_offset_x - expand;
    let sy = r.y + r.shadow_offset_y - expand;
    let sw = r.w + expand * 2.0;
    let sh = r.h + expand * 2.0;

    // Compute SDF distance from shadow rect edge
    let dist = sdf_rounded_rect(px, py, sx, sy, sw, sh,
        r.border_radius_tl + expand, r.border_radius_tr + expand,
        r.border_radius_br + expand, r.border_radius_bl + expand);

    // Convert distance to alpha (smooth falloff)
    var alpha = 0.0;
    if (dist < 0.0) {
        // Inside shadow rect: full opacity at edge
        alpha = 1.0;
    } else {
        // Outside: fade over blur distance
        if (r.shadow_blur > 0.001) {
            alpha = 1.0 - clamp(dist / r.shadow_blur, 0.0, 1.0);
        }
    }

    return vec4<f32>(r.shadow_color.rgb, alpha * r.shadow_color.a);
}

// Render inset shadow for a rect
fn render_inset_shadow(px: f32, py: f32, r: RectStyle) -> vec4<f32> {
    if (r.shadow_active == 0u) { return vec4<f32>(0.0, 0.0, 0.0, 0.0); }
    if (r.shadow_type != 1u) { return vec4<f32>(0.0, 0.0, 0.0, 0.0); } // inset only

    // Inset shadow: contracts from rect edge
    let expand = r.shadow_spread + r.shadow_blur;
    let ix = r.x + expand - r.shadow_offset_x;
    let iy = r.y + expand - r.shadow_offset_y;
    let iw = r.w - expand * 2.0;
    let ih = r.h - expand * 2.0;

    if (iw <= 0.0 || ih <= 0.0) { return vec4<f32>(0.0, 0.0, 0.0, 0.0); }

    // Compute SDF distance from inner rect edge
    let dist = -sdf_rounded_rect(px, py, ix, iy, iw, ih,
        max(r.border_radius_tl - expand, 0.0), max(r.border_radius_tr - expand, 0.0),
        max(r.border_radius_br - expand, 0.0), max(r.border_radius_bl - expand, 0.0));

    // Convert distance to alpha
    var alpha = 0.0;
    if (dist >= 0.0) {
        alpha = 1.0;
    } else {
        if (r.shadow_blur > 0.001) {
            alpha = clamp(-dist / r.shadow_blur, 0.0, 1.0);
        }
    }

    return vec4<f32>(r.shadow_color.rgb, alpha * r.shadow_color.a);
}


// --- Gradient T-Parameter Functions ---
// Generated from css_images.proto + gradient.rs

// Linear gradient: projects pixel onto the gradient line
fn linear_gradient_t(px: f32, py: f32, r: RectStyle) -> f32 {
    let rel_x = (px - r.x) / r.w;
    let rel_y = (py - r.y) / r.h;
    let cos_a = cos(r.gradient_angle);
    let sin_a = sin(r.gradient_angle);
    let t = (rel_x * cos_a + rel_y * sin_a) / (r.w + r.h) * 2.0;
    return clamp(t, 0.0, 1.0);
}

// Radial gradient: distance from center, normalized
fn radial_gradient_t(px: f32, py: f32, r: RectStyle) -> f32 {
    let center_x = r.x + r.w * r.gradient_cx;
    let center_y = r.y + r.h * r.gradient_cy;
    let dx = px - center_x;
    let dy = py - center_y;
    let max_dist = sqrt(r.w * r.w + r.h * r.h) * 0.5;
    let dist = sqrt(dx * dx + dy * dy) / max_dist;
    return clamp(dist, 0.0, 1.0);
}

// Conic gradient: angle from center, with from_angle offset
fn conic_gradient_t(px: f32, py: f32, r: RectStyle) -> f32 {
    let center_x = r.x + r.w * r.gradient_cx;
    let center_y = r.y + r.h * r.gradient_cy;
    let dx = px - center_x;
    let dy = py - center_y;
    var angle: f32 = atan2(dy, dx) + 3.141592653589793 - r.gradient_angle;
    if (angle < 0.0) { angle = angle + 6.283185307179586; }
    return angle / 6.283185307179586;
}

// Sample color stops with linear interpolation
// Generated from gradient.rs lerp_stops + find_stops
fn sample_stops(r: RectStyle, t: f32) -> vec4<f32> {
    if (r.gradient_stop_count == 0u) {
        return vec4<f32>(1.0, 0.0, 0.0, 1.0);  // Error: red
    }
    if (r.gradient_stop_count == 1u) {
        return r.gradient_stops[0].color;
    }

    // Find bracketing stops
    var prev = r.gradient_stops[0];
    var next = r.gradient_stops[1];
    var i: u32 = 1u;
    loop {
        if (i >= r.gradient_stop_count) { break; }
        if (r.gradient_stops[i].position >= t) {
            next = r.gradient_stops[i];
            break;
        }
        prev = r.gradient_stops[i];
        next = r.gradient_stops[i];
        i = i + 1u;
    }

    let span = next.position - prev.position;
    var local_t: f32 = 0.0;
    if (span > 0.0001) {
        local_t = clamp((t - prev.position) / span, 0.0, 1.0);
    }
    return mix(prev.color, next.color, local_t);
}


// --- Rounded Rectangle SDF ---
// Generated from css_box.proto border-radius

// Returns true if point (px, py) is inside the rounded rect
fn contains_rounded_rect(px: f32, py: f32, r: RectStyle) -> bool {
    // Quick AABB test
    if (px < r.x || px >= r.x + r.w || py < r.y || py >= r.y + r.h) {
        return false;
    }

    // Corner radii
    let tl = r.border_radius_tl;
    let tr = r.border_radius_tr;
    let br = r.border_radius_br;
    let bl = r.border_radius_bl;

    // Determine which corner region we're in
    let in_left = px < r.x + tl;
    let in_right = px > r.x + r.w - tr;
    let in_top = py < r.y + tl;
    let in_bottom = py > r.y + r.h - bl;

    // Top-left corner
    if (in_left && in_top) {
        let dx = px - (r.x + tl);
        let dy = py - (r.y + tl);
        return dx * dx + dy * dy <= tl * tl;
    }
    // Top-right corner
    if (in_right && in_top) {
        let dx = px - (r.x + r.w - tr);
        let dy = py - (r.y + tr);
        return dx * dx + dy * dy <= tr * tr;
    }
    // Bottom-right corner
    if (in_right && in_bottom) {
        let dx = px - (r.x + r.w - br);
        let dy = py - (r.y + r.h - bl);
        return dx * dx + dy * dy <= br * br;
    }
    // Bottom-left corner
    if (in_left && in_bottom) {
        let dx = px - (r.x + bl);
        let dy = py - (r.y + r.h - bl);
        return dx * dx + dy * dy <= bl * bl;
    }

    return true;  // Inside the non-corner region
}


// --- Fragment Shader: Painter's Algorithm ---
// Every pixel iterates all rectangles back-to-front

@fragment
fn fs_main(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
    let px = pos.x;
    let py = pos.y;

    // Default canvas background (from Framebuffer::clear)
    var color = vec4<f32>(0.10196, 0.10196, 0.18039, 1.0);  // #1a1a2e

    // Painter's algorithm: iterate back-to-front
    for (var i: u32 = 0u; i < u.rect_count; i = i + 1u) {
        let r = rects[i];

        // Containment test (rounded rect SDF)
        if (!contains_rounded_rect(px, py, r)) { continue; }

        // --- Drop Shadow Pass ---
        // Render shadows BEFORE rect content (painter's algorithm)
        // Check if this pixel falls within the shadow area of ANY preceding rect
        // For efficiency, we render the shadow of THIS rect if the pixel
        // falls within its shadow bounding box but not the rect itself

        // Shadow rect containment test (expanded by spread+blur+offset)
        let expand = r.shadow_spread + r.shadow_blur;
        let shadow_x = r.x + r.shadow_offset_x - expand;
        let shadow_y = r.y + r.shadow_offset_y - expand;
        let shadow_w = r.w + expand * 2.0;
        let shadow_h = r.h + expand * 2.0;
        let in_shadow = px >= shadow_x && px < shadow_x + shadow_w &&
                        py >= shadow_y && py < shadow_y + shadow_h;
        let in_rect = contains_rounded_rect(px, py, r);

        // Drop shadow: render if in shadow area but not in rect
        if (r.shadow_active != 0u && r.shadow_type == 0u && in_shadow && !in_rect) {
            let shadow = render_drop_shadow(px, py, r);
            if (shadow.a > 0.001) {
                color = mix(color, vec4<f32>(shadow.rgb, 1.0), shadow.a);
            }
        }

        var pixel_color: vec4<f32>;

        // Gradient dispatch (from css_images.proto GradientKind)
        switch r.gradient_type {
            case 0u: {  // None — solid bg_color
                pixel_color = r.bg_color;
            }
            case 1u: {  // LinearGradient
                let t = linear_gradient_t(px, py, r);
                pixel_color = sample_stops(r, t);
            }
            case 2u: {  // RadialGradient
                let t = radial_gradient_t(px, py, r);
                pixel_color = sample_stops(r, t);
            }
            case 3u: {  // ConicGradient
                let t = conic_gradient_t(px, py, r);
                pixel_color = sample_stops(r, t);
            }
            default: {
                pixel_color = r.bg_color;
            }
        }

        // --- Border Rendering Pass ---
        let bw = border_width_at(px, py, r);
        if (bw > 0.0 && r.border_style != 0u) {
            // Check dash pattern
            let dash_offset = border_pixel_offset(px, py, r);
            let dash_visible = border_dash_test(dash_offset, r.border_style);
            if (dash_visible) {
                pixel_color = r.border_color;
            }
        }

        // Blend mode application (from blend_lut)
        pixel_color = apply_blend_mode(pixel_color, color, r.blend_mode);

        // Opacity compositing
        color = mix(color, pixel_color, r.opacity);
    }

    // --- Text Rendering Pass ---
    // For each text command, check if this pixel falls within any glyph
    for (var ti: u32 = 0u; ti < u.text_cmd_count; ti = ti + 1u) {
        let tc = text_cmds[ti];
        for (var gi: u32 = 0u; gi < tc.glyph_count; gi = gi + 1u) {
            let glyph_x = tc.x + f32(gi) * 8.0;
            let glyph_y = tc.y;
            // Bounding box test
            if (px >= glyph_x && px < glyph_x + 8.0 && py >= glyph_y && py < glyph_y + 8.0) {
                let col = u32(px - glyph_x);
                let row = u32(py - glyph_y);
                let sample_val = glyph_pixel(tc.glyphs[gi], row, col);
                if (sample_val > 0.5) {
                    let text_color = vec4<f32>(tc.color_r, tc.color_g, tc.color_b, 1.0);
                    color = mix(color, text_color, 1.0);
                }
            }
        }
    }

    return color;
}
