[package]
name = "edgerun-marketplace-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "edgerun-marketplace"
path = "src/main.rs"
required-features = ["std"]

[dependencies]
edgerun-solana = { path = "../edgerun-solana" }
edgerun-rt = { path = "../edgerun-rt" }
edgerun-log = { path = "../edgerun-log" }
edgerun-json = { path = "../edgerun-json", default-features = false, features = ["alloc"] }

[target.'cfg(not(target_os = "none"))'.dependencies]
edgerun-clap = { path = "../edgerun-clap", features = ["std"] }

[features]
std = []
