[package]
name = "edgerun-oci-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-json = { path = "../edgerun-json", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
libc = "0.2"

[[bin]]
name = "ert"
path = "src/bin/ert.rs"



[lints]
workspace = true
