pub(crate) mod api_bridge;
pub(crate) mod auth;
pub(crate) mod common;
pub(crate) mod endpoint;
pub(crate) mod error;
#[cfg(feature = "native-transport")]
pub(crate) mod files;
pub(crate) mod provider;
pub(crate) mod rate_limits;
pub(crate) mod requests;
pub(crate) mod sse;
pub(crate) mod telemetry;

pub use crate::requests::headers::build_session_headers;
pub use codex_client::HttpTransport;
pub use codex_client::RequestTelemetry;
#[cfg(feature = "native-transport")]
pub use codex_client::ReqwestTransport;
pub use codex_client::TransportError;

pub use crate::api_bridge::map_api_error;
pub use crate::auth::AuthError;
pub use crate::auth::AuthHeaderTelemetry;
pub use crate::auth::AuthProvider;
pub use crate::auth::SharedAuthProvider;
pub use crate::auth::auth_header_telemetry;
pub use crate::common::CompactionInput;
pub use crate::common::MemorySummarizeInput;
pub use crate::common::MemorySummarizeOutput;
pub use crate::common::OpenAiVerbosity;
pub use crate::common::RawMemory;
pub use crate::common::RawMemoryMetadata;
pub use crate::common::Reasoning;
pub use crate::common::ResponseCreateWsRequest;
pub use crate::common::ResponseEvent;
pub use crate::common::ResponseProcessedWsRequest;
pub use crate::common::ResponseStream;
pub use crate::common::ResponsesApiRequest;
pub use crate::common::ResponsesWsRequest;
pub use crate::common::TextControls;
pub use crate::common::WS_REQUEST_HEADER_TRACEPARENT_CLIENT_METADATA_KEY;
pub use crate::common::WS_REQUEST_HEADER_TRACESTATE_CLIENT_METADATA_KEY;
pub use crate::common::create_text_param_for_request;
pub use crate::common::response_create_client_metadata;
pub use crate::endpoint::CompactClient;
pub use crate::endpoint::MemoriesClient;
pub use crate::endpoint::ModelsClient;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeCallClient;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeCallResponse;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeEventParser;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeOutputModality;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeSessionConfig;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeSessionMode;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeWebsocketClient;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeWebsocketConnection;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeWebsocketEvents;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::RealtimeWebsocketWriter;
pub use crate::endpoint::ResponsesClient;
pub use crate::endpoint::ResponsesOptions;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::ResponsesWebsocketClient;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::ResponsesWebsocketConnection;
#[cfg(feature = "native-transport")]
pub use crate::endpoint::session_update_session_json;
pub use crate::error::ApiError;
#[cfg(feature = "native-transport")]
pub use crate::files::upload_local_file;
pub use crate::provider::Provider;
pub use crate::provider::RetryConfig;
pub use crate::provider::is_azure_responses_provider;
pub use crate::requests::Compression;
#[cfg(feature = "native-transport")]
pub use crate::sse::stream_from_fixture;
pub use crate::telemetry::SseTelemetry;
#[cfg(feature = "native-transport")]
pub use crate::telemetry::WebsocketTelemetry;
pub use codex_protocol::protocol::RealtimeAudioFrame;
pub use codex_protocol::protocol::RealtimeEvent;
