[package]
name = "memchr"
version = "2.8.0"
edition = "2021"
rust-version = "1.61"
license = "Unlicense OR MIT"
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned byte search compatibility crate"

[features]
alloc = []
default = ["std"]
libc = []
logging = ["dep:log"]
rustc-dep-of-std = []
std = ["alloc"]
use_std = ["std"]

[dependencies]
log = { path = "../edgerun-log-upstream", optional = true }

[lints]
workspace = true
