(func $m187eq (param $ptr i32) (param $len i32) (param $off i32) (param $mlen i32) (result i32)
    (local $i i32)
    (if (i32.ne (local.get $len) (local.get $mlen)) (then (return (i32.const 0))))
    (loop $loop
      (if (i32.eq (local.get $i) (local.get $len)) (then (return (i32.const 1))))
      (if (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $i))) (i32.load8_u (i32.add (local.get $off) (local.get $i))))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $loop))
    i32.const 0)
  (func (export "telemetry_tracing_level_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 16) (i32.const 5)) (then (return (i32.const 5))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 21) (i32.const 5)) (then (return (i32.const 4))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 26) (i32.const 4)) (then (return (i32.const 3))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 30) (i32.const 4)) (then (return (i32.const 2))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 34) (i32.const 5)) (then (return (i32.const 1))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 39) (i32.const 3)) (then (return (i32.const 0))))
    i32.const -1)

  (func $tracing_level_allows (export "tracing_level_allows") (param $filter i32) (param $event_level i32) (result i32)
    (if (i32.and (i32.ge_s (local.get $filter) (local.get $event_level)) (i32.gt_s (local.get $event_level) (i32.const 0))) (then (return (i32.const 1))))
    i32.const 0)

  (func (export "tracing_directive_specificity") (param $target_len i32) (param $field_count i32) (result i32)
    (i32.add (i32.mul (local.get $target_len) (i32.const 256)) (local.get $field_count)))

  (func (export "tracing_directive_allows") (param $filter_level i32) (param $event_level i32) (param $target_match i32) (param $fields_required i32) (param $fields_present i32) (result i32)
    (if (i32.eqz (local.get $target_match)) (then (return (i32.const 0))))
    (if (i32.lt_s (local.get $fields_present) (local.get $fields_required)) (then (return (i32.const 0))))
    (call $tracing_level_allows (local.get $filter_level) (local.get $event_level)))

  (func (export "telemetry_tracing_interest_join") (param $outer i32) (param $inner i32) (result i32)
    (if (i32.or (i32.eqz (local.get $outer)) (i32.eqz (local.get $inner))) (then (return (i32.const 0))))
    (if (i32.and (i32.eq (local.get $outer) (i32.const 2)) (i32.eq (local.get $inner) (i32.const 2))) (then (return (i32.const 2))))
    i32.const 1)

  (func (export "tracing_layer_event_order") (param $phase i32) (result i32)
    (if (i32.eq (local.get $phase) (i32.const 1)) (then (return (i32.const 10))))
    (if (i32.eq (local.get $phase) (i32.const 2)) (then (return (i32.const 20))))
    (if (i32.eq (local.get $phase) (i32.const 3)) (then (return (i32.const 30))))
    (if (i32.eq (local.get $phase) (i32.const 4)) (then (return (i32.const 40))))
    (if (i32.eq (local.get $phase) (i32.const 5)) (then (return (i32.const 50))))
    i32.const 0)

  (func (export "otel_span_kind_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 48) (i32.const 6)) (then (return (i32.const 1))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 54) (i32.const 6)) (then (return (i32.const 2))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 60) (i32.const 8)) (then (return (i32.const 3))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 68) (i32.const 8)) (then (return (i32.const 4))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 76) (i32.const 8)) (then (return (i32.const 5))))
    i32.const 0)

  (func (export "otel_status_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 96) (i32.const 2)) (then (return (i32.const 1))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 98) (i32.const 5)) (then (return (i32.const 2))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 103) (i32.const 5)) (then (return (i32.const 0))))
    i32.const 0)

  (func (export "otel_sampler_decision") (param $sampler i32) (param $parent_present i32) (param $parent_sampled i32) (param $delegate_decision i32) (param $ratio_permille i32) (param $trace_low63 i64) (result i32)
    (local $threshold i64)
    (if (i32.eq (local.get $sampler) (i32.const 1)) (then (return (i32.const 2))))
    (if (i32.eq (local.get $sampler) (i32.const 2)) (then (return (i32.const 0))))
    (if (i32.eq (local.get $sampler) (i32.const 4))
      (then
        (if (local.get $parent_present)
          (then (return (select (i32.const 2) (i32.const 0) (local.get $parent_sampled)))))
        (return (local.get $delegate_decision))))
    (if (i32.le_s (local.get $ratio_permille) (i32.const 0)) (then (return (i32.const 0))))
    (if (i32.ge_s (local.get $ratio_permille) (i32.const 1000)) (then (return (i32.const 2))))
    (local.set $threshold (i64.mul (i64.const 9223372036854775) (i64.extend_i32_u (local.get $ratio_permille))))
    (if (i64.lt_u (local.get $trace_low63) (local.get $threshold)) (then (return (i32.const 2))))
    i32.const 0)

  (func (export "otel_batch_action") (param $current_size i32) (param $max_batch i32) (param $queue_full i32) (param $disconnected i32) (param $force_flush i32) (param $shutdown i32) (param $timer i32) (result i32)
    (if (local.get $disconnected) (then (return (i32.const 5))))
    (if (local.get $queue_full) (then (return (i32.const 4))))
    (if (local.get $shutdown) (then (return (i32.const 3))))
    (if (local.get $force_flush) (then (return (i32.const 2))))
    (if (i32.or (local.get $timer) (i32.ge_s (local.get $current_size) (local.get $max_batch))) (then (return (i32.const 1))))
    i32.const 0)

  (func (export "otel_metric_instrument_code") (param $ptr i32) (param $len i32) (result i32)
    (if (i32.and (i32.ge_u (local.get $len) (i32.const 18)) (call $m187eq (local.get $ptr) (i32.const 18) (i32.const 128) (i32.const 18))) (then (return (i32.const 1))))
    (if (i32.and (i32.ge_u (local.get $len) (i32.const 8)) (call $m187eq (local.get $ptr) (i32.const 8) (i32.const 146) (i32.const 8))) (then (return (i32.const 2))))
    (if (i32.and (i32.ge_u (local.get $len) (i32.const 10)) (call $m187eq (local.get $ptr) (i32.const 10) (i32.const 154) (i32.const 10))) (then (return (i32.const 3))))
    (if (i32.and (i32.ge_u (local.get $len) (i32.const 6)) (call $m187eq (local.get $ptr) (i32.const 6) (i32.const 164) (i32.const 6))) (then (return (i32.const 4))))
    i32.const 0)

  (func (export "otel_aggregation_valid") (param $aggregation i32) (param $boundaries_monotonic i32) (param $max_scale i32) (result i32)
    (if (i32.and (i32.ge_s (local.get $aggregation) (i32.const 1)) (i32.le_s (local.get $aggregation) (i32.const 4))) (then (return (i32.const 1))))
    (if (i32.eq (local.get $aggregation) (i32.const 5)) (then (return (local.get $boundaries_monotonic))))
    (if (i32.eq (local.get $aggregation) (i32.const 6))
      (then (return (i32.and (i32.ge_s (local.get $max_scale) (i32.const -10)) (i32.le_s (local.get $max_scale) (i32.const 20))))))
    i32.const 0)

  (func (export "otel_export_result_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 192) (i32.const 2)) (then (return (i32.const 1))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 194) (i32.const 7)) (then (return (i32.const 2))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 201) (i32.const 12)) (then (return (i32.const 3))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 213) (i32.const 12)) (then (return (i32.const 4))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 225) (i32.const 6)) (then (return (i32.const 5))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 231) (i32.const 14)) (then (return (i32.const 6))))
    i32.const 0)

  (func (export "tracing_format_mode_code") (param $ptr i32) (param $len i32) (result i32)
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 256) (i32.const 4)) (then (return (i32.const 1))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 260) (i32.const 7)) (then (return (i32.const 2))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 267) (i32.const 6)) (then (return (i32.const 3))))
    (if (call $m187eq (local.get $ptr) (local.get $len) (i32.const 273) (i32.const 4)) (then (return (i32.const 4))))
    i32.const 0)

  (data (i32.const 16) "tracedebuginfowarnerroroff")
  (data (i32.const 48) "serverclientproducerconsumerinternal")
  (data (i32.const 96) "okerrorunset")
  (data (i32.const 128) "monotonic_counter.counter.histogram.gauge.")
  (data (i32.const 192) "oktimeoutchannel_fulldisconnectedpoisonexporter_error")
  (data (i32.const 256) "jsoncompactprettyfull")
