;; ═════════════════════════════════════════════════════════════════════
  ;; WASM SIMD (0xFD prefix) — AArch64 NEON implementations
  ;; ═════════════════════════════════════════════════════════════════════

  ;; ── v128.const (0xFD 0x0C): load 16-byte constant from decoded op ──
  (func $template_aarch64_v128_const (param $dec_ptr i32)
    (local $addr i32)
    (local.set $addr (i32.add (local.get $dec_ptr) (i32.const 16)))
    (call $emit_aarch64_bload_addr_x1 (local.get $addr))
    (call $emit_aarch64_bv128_load_reg)
    (call $emit_aarch64_bv128_push)
  )

  ;; ── v128.load (0xFD 0x00): pop addr, load 16 bytes from mem ─────────
  (func $template_aarch64_v128_load (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_bldr_mem_ptr)
    (call $emit_aarch64_binstr_add_64 (global.get $REG_X1) (global.get $REG_X2) (global.get $REG_X0))
    (call $emit_aarch64_bv128_load_reg)
    (call $emit_aarch64_bv128_push)
  )

  ;; ── v128.store (0xFD 0x1B): pop value, pop addr, store 16 bytes ─────
  (func $template_aarch64_v128_store (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_bldr_mem_ptr)
    (call $emit_aarch64_binstr_add_64 (global.get $REG_X1) (global.get $REG_X2) (global.get $REG_X0))
    (call $emit_aarch64_bv128_store_reg)
  )

  ;; ── Splat templates ───────────────────────────────────────────────
  (func $template_aarch64_i8x16_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_binstr (i32.const 0x4E000800))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_i16x8_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_binstr (i32.const 0x4E001000))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_i32x4_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_binstr (i32.const 0x4E002000))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_i64x2_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_binstr (i32.const 0x4E004000))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_f32x4_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_binstr (i32.const 0x4E002000))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_f64x2_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_binstr (i32.const 0x4E004000))
    (call $emit_aarch64_bv128_push)
  )

  ;; ── Integer binary ops ────────────────────────────────────────────
  (func $template_aarch64_i8x16_add (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_add_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_add (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_add_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_add (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_add_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i64x2_add (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_add_2d (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i8x16_sub (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_sub_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_sub (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_sub_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_sub (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_sub_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i64x2_sub (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_sub_2d (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Float binary ops ──────────────────────────────────────────────
  (func $template_aarch64_f32x4_add (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E20D400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_f64x2_add (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E60D400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_sub: FSUB V0.4S, V0.4S, V1.4S = 0x4E22D400
  (func $template_aarch64_f32x4_sub (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E22D400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_sub: FSUB V0.2D, V0.2D, V1.2D = 0x4E62D400
  (func $template_aarch64_f64x2_sub (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E62D400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Bitwise ops ───────────────────────────────────────────────────
  (func $template_aarch64_i8x16_and (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_and_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i8x16_or (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_orr_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i8x16_xor (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_eor_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Comparisons ───────────────────────────────────────────────────
  (func $template_aarch64_i8x16_eq (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmeq_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_eq (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmeq_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_eq (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmeq_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i8x16_gt_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_16b_s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── GE (signed) implementations ──────────────────────────────────
  (func $template_aarch64_i8x16_ge_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_16b_s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_ge_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_3same (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0x07)
                           (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_ge_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_3same (i32.const 1) (i32.const 2) (i32.const 0) (i32.const 0x07)
                           (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── GE (unsigned) implementations ────────────────────────────────
  (func $template_aarch64_i8x16_ge_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_16b_u (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_ge_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_8h_u (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_ge_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_4s_u (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── UMIN / UMAX / URHADD implementations ─────────────────────────
  (func $template_aarch64_i8x16_min_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_umin_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_min_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_umin_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i8x16_max_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_umax_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_max_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_umax_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i8x16_avgr_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_urhadd_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_avgr_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_urhadd_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Additional integer comparison templates ──────────────────────
  (func $template_aarch64_i16x8_gt_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_8h_s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_gt_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_4s_s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i8x16_gt_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_16b_u (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_gt_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_8h_u (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_gt_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_4s_u (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; lt_s: a < b = b > a → CMGT(V1, V0) with Rn=V1, Rm=V0
  (func $template_aarch64_i8x16_lt_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_16b_s (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_lt_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_8h_s (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_lt_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_4s_s (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; lt_u: a < b = b > a → CMHI(V1, V0)
  (func $template_aarch64_i8x16_lt_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_16b_u (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_lt_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_8h_u (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_lt_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmgt_4s_u (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; le_s: a <= b = b >= a → CMGE(V1, V0) with Rn=V1, Rm=V0
  (func $template_aarch64_i8x16_le_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_16b_s (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_le_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_3same (i32.const 1) (i32.const 1) (i32.const 0) (i32.const 0x07)
                           (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_le_s (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_3same (i32.const 1) (i32.const 2) (i32.const 0) (i32.const 0x07)
                           (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; le_u: a <= b = b >= a → CMHS(V1, V0)
  (func $template_aarch64_i8x16_le_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_16b_u (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_le_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_8h_u (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_le_u (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmge_4s_u (global.get $REG_V0) (global.get $REG_V1) (global.get $REG_V0))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; ne: a != b = NOT(CMEQ(a, b)) → CMEQ + MVN
  (func $template_aarch64_i8x16_ne (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmeq_16b (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr (i32.const 0x4E205800))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i16x8_ne (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmeq_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr (i32.const 0x4E205800))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_ne (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_cmeq_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr (i32.const 0x4E205800))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Float comparison templates ────────────────────────────────────
  ;; f32x4_eq: FCMEQ V0.4S, V0.4S, V1.4S = 0x4E20E400
  (func $template_aarch64_f32x4_eq (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E20E400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_eq: FCMEQ V0.2D, V0.2D, V1.2D = 0x4E60E400
  (func $template_aarch64_f64x2_eq (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E60E400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_ne: NOT(FCMEQ V0.4S, V0.4S, V1.4S) = FCMEQ + MVN
  (func $template_aarch64_f32x4_ne (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E20E400))
    (call $emit_aarch64_binstr (i32.const 0x4E205800))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_ne: NOT(FCMEQ V0.2D, V0.2D, V1.2D) = FCMEQ + MVN
  (func $template_aarch64_f64x2_ne (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E60E400))
    (call $emit_aarch64_binstr (i32.const 0x4E205800))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_lt: a < b = b > a → FCMGT V0.4S, V1.4S, V0.4S = 0x4E22E420
  (func $template_aarch64_f32x4_lt (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E22E420))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_lt: FCMGT V0.2D, V1.2D, V0.2D = 0x4E62E420
  (func $template_aarch64_f64x2_lt (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E62E420))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_gt: FCMGT V0.4S, V0.4S, V1.4S = 0x4E22E400
  (func $template_aarch64_f32x4_gt (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E22E400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_gt: FCMGT V0.2D, V0.2D, V1.2D = 0x4E62E400
  (func $template_aarch64_f64x2_gt (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E62E400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_le: a <= b = b >= a → FCMGE V0.4S, V1.4S, V0.4S = 0x4E20E820
  (func $template_aarch64_f32x4_le (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E20E820))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_le: FCMGE V0.2D, V1.2D, V0.2D = 0x4E60E820
  (func $template_aarch64_f64x2_le (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E60E820))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_ge: FCMGE V0.4S, V0.4S, V1.4S = 0x4E20E800
  (func $template_aarch64_f32x4_ge (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E20E800))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_ge: FCMGE V0.2D, V0.2D, V1.2D = 0x4E60E800
  (func $template_aarch64_f64x2_ge (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E60E800))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Float min/max templates ────────────────────────────────────────
  ;; f32x4_min: FMIN V0.4S, V0.4S, V1.4S = 0x4E22F400
  (func $template_aarch64_f32x4_min (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E22F400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_max: FMAX V0.4S, V0.4S, V1.4S = 0x4E20F400
  (func $template_aarch64_f32x4_max (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E20F400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_min: FMIN V0.2D, V0.2D, V1.2D = 0x4E62F400
  (func $template_aarch64_f64x2_min (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E62F400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_max: FMAX V0.2D, V0.2D, V1.2D = 0x4E60F400
  (func $template_aarch64_f64x2_max (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E60F400))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )

  ;; ── Stubs (extract/replace lane, neg, mul) ───────────────────────
  (func $template_aarch64_i8x16_extract_lane_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i8x16_extract_lane_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i16x8_extract_lane_s (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i16x8_extract_lane_u (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i32x4_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i64x2_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_f32x4_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_f64x2_extract_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i8x16_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i16x8_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i32x4_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i64x2_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_f32x4_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_f64x2_replace_lane (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i8x16_neg (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_bneon_neg (i32.const 0) (global.get $REG_V0) (global.get $REG_V0))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_i16x8_neg (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_bneon_neg (i32.const 1) (global.get $REG_V0) (global.get $REG_V0))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_i32x4_neg (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_bneon_neg (i32.const 2) (global.get $REG_V0) (global.get $REG_V0))
    (call $emit_aarch64_bv128_push)
  )
  (func $template_aarch64_i64x2_neg (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_bneon_neg (i32.const 3) (global.get $REG_V0) (global.get $REG_V0))
    (call $emit_aarch64_bv128_push)
  )
  ;; f32x4_neg: FNEG V0.4S = 0x4EE0F800
  (func $template_aarch64_f32x4_neg (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_binstr (i32.const 0x4EE0F800))
    (call $emit_aarch64_bv128_push)
  )
  ;; f64x2_neg: FNEG V0.2D = 0x4EE1F800
  (func $template_aarch64_f64x2_neg (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_binstr (i32.const 0x4EE1F800))
    (call $emit_aarch64_bv128_push)
  )
  ;; i8x16_mul: no NEON MUL for byte — keep as stub (needs PMULL + complex)
  (func $template_aarch64_i8x16_mul (param $dec_ptr i32) (global.set $JIT_ERROR (i32.const -4)))
  (func $template_aarch64_i16x8_mul (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_mul_8h (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  (func $template_aarch64_i32x4_mul (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_bneon_mul_4s (global.get $REG_V0) (global.get $REG_V0) (global.get $REG_V1))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f32x4_mul: FMUL V0.4S, V0.4S, V1.4S = 0x4E22DC00
  (func $template_aarch64_f32x4_mul (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E22DC00))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; f64x2_mul: FMUL V0.2D, V0.2D, V1.2D = 0x4E62DC00
  (func $template_aarch64_f64x2_mul (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E62DC00))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; ── Loadsplat templates (LD1R) ────────────────────────────────────
  ;; v128.load8_splat: LD1R { V0.16B }, [X0]
  (func $template_aarch64_v128_load8_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_bldr_mem_ptr)
    (call $emit_aarch64_binstr (i32.const 0x4D40C000))
    (call $emit_aarch64_bv128_push)
  )
  ;; v128.load16_splat: LD1R { V0.8H }, [X0]  (size=01)
  (func $template_aarch64_v128_load16_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_bldr_mem_ptr)
    (call $emit_aarch64_binstr (i32.const 0x4D41C000))
    (call $emit_aarch64_bv128_push)
  )
  ;; v128.load32_splat: LD1R { V0.4S }, [X0]  (size=10)
  (func $template_aarch64_v128_load32_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_bldr_mem_ptr)
    (call $emit_aarch64_binstr (i32.const 0x4D42C000))
    (call $emit_aarch64_bv128_push)
  )
  ;; v128.load64_splat: LD1R { V0.2D }, [X0]  (size=11)
  (func $template_aarch64_v128_load64_splat (param $dec_ptr i32)
    (call $emit_aarch64_bpop_x0)
    (call $emit_aarch64_bldr_mem_ptr)
    (call $emit_aarch64_binstr (i32.const 0x4D43C000))
    (call $emit_aarch64_bv128_push)
  )
  ;; i8x16.swizzle: pop index, pop table, TBL V0.16B, {V1.16B}, V0.16B
  (func $template_aarch64_i8x16_swizzle (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr (i32.const 0x4E000020))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 16))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 0))
  )
  ;; v128.not: MVN V0.16B, V0.16B = 0x4E205800
  (func $template_aarch64_v128_not (param $dec_ptr i32)
    (call $emit_aarch64_bv128_pop)
    (call $emit_aarch64_binstr (i32.const 0x4E205800))
    (call $emit_aarch64_bv128_push)
  )
  ;; v128.bitselect: pop mask(V1), pop b(V0), pop a(V2); BSL V1, V0, V2
  ;; V1 = (V1 & V0) | (~V1 & V2) = (mask & b) | (~mask & a)
  ;; Stack: [SP]=mask, [SP+16]=b, [SP+32]=a (deepest)
  ;; Result replaces 'a' position: SP += 32, str_q at new SP
  ;; BSL V1.16B, V0.16B, V2.16B = 0x4E021C01
  (func $template_aarch64_v128_bitselect (param $dec_ptr i32)
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V0) (global.get $REG_SP) (i32.const 1))
    (call $emit_aarch64_binstr_ldr_q_off (global.get $REG_V2) (global.get $REG_SP) (i32.const 2))
    (call $emit_aarch64_binstr (i32.const 0x4E021C01))
    (call $emit_aarch64_binstr_addi_64 (global.get $REG_SP) (global.get $REG_SP) (i32.const 32))
    (call $emit_aarch64_binstr_str_q_off (global.get $REG_V1) (global.get $REG_SP) (i32.const 0))
  )
