[package]
name = "edgerun-tpm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "TPM command and signing support for Edgerun"

[dependencies]
edgerun-crypto = { version = "0.1", path = "../edgerun-crypto", default-features = false }
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding", default-features = false }

[features]
default = []
std = []

[lints]
workspace = true
