[package]
name = "codex-app-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codex_app_server_protocol"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codex-protocol = { workspace = true }
codex-shell-command = { workspace = true }
edgerun-error = { workspace = true }
edgerun-json = { workspace = true }
edgerun-similar = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
edgerun-strum-macros = { workspace = true }
rmcp = { workspace = true, default-features = false, features = [
    "base64",
    "macros",
] }
ts-rs = { workspace = true }
edgerun-inventory = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
codex_utils_cargo_bin = { package = "edgerun-codex-utils-cargo-bin", path = "../../utility/edgerun-codex-utils-cargo-bin" }
pretty_assertions = { package = "edgerun-pretty-assertions", path = "../../utility/edgerun-pretty-assertions" }
tempfile = { package = "edgerun-tempfile", path = "../../utility/edgerun-tempfile" }
