[package]
name = "provider-registry"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/Sylchi/edgerun_reference_core"
homepage = "https://github.com/Sylchi/edgerun_reference_core"

[workspace]

[dependencies]
solana-program = "4.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
