//! HTML parsing layer — WHATWG tokenizer + tree builder → DOM tree.
//!
//! ## Files
//!
//! | File | Lines | Origin |
//! |------|-------|--------|
//! | `tokenizer.rs` | 4,550 | Auto-generated by `cmd/html-codegen/` |
//! | `tree_builder.rs` | 2,263 | Auto-generated by `cmd/html-codegen/` |
//! | `html_parser.rs` | 130 | Auto-generated wrapper (DOM types + parse_html) |
//! | `entity_decoder/` | 96 | Auto-generated entity lookup table |

mod tokenizer;
mod tree_builder;
mod html_parser;
pub mod entity_decoder;

pub use tokenizer::{Tokenizer, Token, State, VOID_ELEMENTS, RAW_TEXT_ELEMENTS};
pub use tree_builder::{TreeBuilder, InsertionMode, TokenizerMode};
pub use html_parser::{
    parse_html, Node, Element, BLOCK_ELEMENTS, INLINE_ELEMENTS, VOID_ELEMENTS as HTML_VOID_ELEMENTS,
};
pub use entity_decoder::decode_entities_in_text;
