[package]
name = "lifegraph-audio-calibration"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
lifegraph-alsa-microphone = { path = "../lifegraph-alsa-microphone" }
lifegraph-alsa-speaker = { path = "../lifegraph-alsa-speaker" }
lifegraph-microphone = { path = "../lifegraph-microphone" }
lifegraph-speaker = { path = "../lifegraph-speaker" }
lifegraph-capabilities = { path = "../lifegraph-capabilities" }
