[package]
name = "edgerun-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Durable event, object, index, and blob storage for Edgerun nodes"

[dependencies]
edgerun-protocols = { workspace = true, default-features = false, features = ["sign-p256", "keygen", "core", "block", "wire"] }
edgerun-virtual-disk = { version = "0.1", path = "../edgerun-virtual-disk", default-features = false }
edgerun-crypto = { workspace = true, default-features = false, features = ["aead", "hmac"] }
edgerun-encoding = { version = "0.1", path = "../../utility/edgerun-encoding", default-features = false }
edgerun-log = { version = "0.1", path = "../../utility/edgerun-log" }

[features]
default = ["std"]
bare-rt = []
std = []

[lints]
workspace = true
