// Spec catalog messages — intermediate format for code generation.
// Produced by `edgerun spec extract <domain>` commands.
// Consumed by `edgerun gen <target>` commands.
//
// All extractors output proto binary to stdout. All generators read proto binary.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: spec_catalog.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncodingType int32

const (
	EncodingType_ENCODING_TYPE_UNSPECIFIED EncodingType = 0
	EncodingType_ENCODING_TYPE_UTF8        EncodingType = 1
	EncodingType_ENCODING_TYPE_UTF16       EncodingType = 2
	EncodingType_ENCODING_TYPE_LEGACY      EncodingType = 3
	EncodingType_ENCODING_TYPE_REPLACEMENT EncodingType = 4
)

// Enum value maps for EncodingType.
var (
	EncodingType_name = map[int32]string{
		0: "ENCODING_TYPE_UNSPECIFIED",
		1: "ENCODING_TYPE_UTF8",
		2: "ENCODING_TYPE_UTF16",
		3: "ENCODING_TYPE_LEGACY",
		4: "ENCODING_TYPE_REPLACEMENT",
	}
	EncodingType_value = map[string]int32{
		"ENCODING_TYPE_UNSPECIFIED": 0,
		"ENCODING_TYPE_UTF8":        1,
		"ENCODING_TYPE_UTF16":       2,
		"ENCODING_TYPE_LEGACY":      3,
		"ENCODING_TYPE_REPLACEMENT": 4,
	}
)

func (x EncodingType) Enum() *EncodingType {
	p := new(EncodingType)
	*p = x
	return p
}

func (x EncodingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncodingType) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_catalog_proto_enumTypes[0].Descriptor()
}

func (EncodingType) Type() protoreflect.EnumType {
	return &file_spec_catalog_proto_enumTypes[0]
}

func (x EncodingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncodingType.Descriptor instead.
func (EncodingType) EnumDescriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{0}
}

type WebIdlTypeKind int32

const (
	WebIdlTypeKind_WEBIDL_TYPE_UNSPECIFIED   WebIdlTypeKind = 0
	WebIdlTypeKind_WEBIDL_TYPE_PRIMITIVE     WebIdlTypeKind = 1
	WebIdlTypeKind_WEBIDL_TYPE_STRING        WebIdlTypeKind = 2
	WebIdlTypeKind_WEBIDL_TYPE_OBJECT        WebIdlTypeKind = 3
	WebIdlTypeKind_WEBIDL_TYPE_SPECIAL       WebIdlTypeKind = 4
	WebIdlTypeKind_WEBIDL_TYPE_EXTENDED_ATTR WebIdlTypeKind = 5
)

// Enum value maps for WebIdlTypeKind.
var (
	WebIdlTypeKind_name = map[int32]string{
		0: "WEBIDL_TYPE_UNSPECIFIED",
		1: "WEBIDL_TYPE_PRIMITIVE",
		2: "WEBIDL_TYPE_STRING",
		3: "WEBIDL_TYPE_OBJECT",
		4: "WEBIDL_TYPE_SPECIAL",
		5: "WEBIDL_TYPE_EXTENDED_ATTR",
	}
	WebIdlTypeKind_value = map[string]int32{
		"WEBIDL_TYPE_UNSPECIFIED":   0,
		"WEBIDL_TYPE_PRIMITIVE":     1,
		"WEBIDL_TYPE_STRING":        2,
		"WEBIDL_TYPE_OBJECT":        3,
		"WEBIDL_TYPE_SPECIAL":       4,
		"WEBIDL_TYPE_EXTENDED_ATTR": 5,
	}
)

func (x WebIdlTypeKind) Enum() *WebIdlTypeKind {
	p := new(WebIdlTypeKind)
	*p = x
	return p
}

func (x WebIdlTypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebIdlTypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_catalog_proto_enumTypes[1].Descriptor()
}

func (WebIdlTypeKind) Type() protoreflect.EnumType {
	return &file_spec_catalog_proto_enumTypes[1]
}

func (x WebIdlTypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebIdlTypeKind.Descriptor instead.
func (WebIdlTypeKind) EnumDescriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{1}
}

// Top-level catalog containing all spec domains.
type Catalog struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SpecName              string                 `protobuf:"bytes,1,opt,name=spec_name,json=specName,proto3" json:"spec_name,omitempty"`
	SpecDate              string                 `protobuf:"bytes,2,opt,name=spec_date,json=specDate,proto3" json:"spec_date,omitempty"`
	CssProperties         []*CssProperty         `protobuf:"bytes,3,rep,name=css_properties,json=cssProperties,proto3" json:"css_properties,omitempty"`
	CssValueTypes         []*CssValueType        `protobuf:"bytes,4,rep,name=css_value_types,json=cssValueTypes,proto3" json:"css_value_types,omitempty"`
	CssAtRules            []*CssAtRule           `protobuf:"bytes,5,rep,name=css_at_rules,json=cssAtRules,proto3" json:"css_at_rules,omitempty"`
	DomInterfaces         []*DomInterface        `protobuf:"bytes,6,rep,name=dom_interfaces,json=domInterfaces,proto3" json:"dom_interfaces,omitempty"`
	DomEvents             []*DomEvent            `protobuf:"bytes,7,rep,name=dom_events,json=domEvents,proto3" json:"dom_events,omitempty"`
	HtmlElements          []*HtmlElement         `protobuf:"bytes,8,rep,name=html_elements,json=htmlElements,proto3" json:"html_elements,omitempty"`
	PseudoClasses         []*PseudoClassDef      `protobuf:"bytes,9,rep,name=pseudo_classes,json=pseudoClasses,proto3" json:"pseudo_classes,omitempty"`
	PseudoElements        []*PseudoElementDef    `protobuf:"bytes,10,rep,name=pseudo_elements,json=pseudoElements,proto3" json:"pseudo_elements,omitempty"`
	Combinators           []*CombinatorDef       `protobuf:"bytes,11,rep,name=combinators,proto3" json:"combinators,omitempty"`
	AttrMatchOps          []*AttrMatchOpDef      `protobuf:"bytes,12,rep,name=attr_match_ops,json=attrMatchOps,proto3" json:"attr_match_ops,omitempty"`
	JsBuiltins            []*JsBuiltInObjectDef  `protobuf:"bytes,13,rep,name=js_builtins,json=jsBuiltins,proto3" json:"js_builtins,omitempty"`
	JsAbstractOps         []*JsAbstractOpDef     `protobuf:"bytes,14,rep,name=js_abstract_ops,json=jsAbstractOps,proto3" json:"js_abstract_ops,omitempty"`
	JsWellKnownSymbols    []string               `protobuf:"bytes,15,rep,name=js_well_known_symbols,json=jsWellKnownSymbols,proto3" json:"js_well_known_symbols,omitempty"`
	JsWellKnownIntrinsics []string               `protobuf:"bytes,16,rep,name=js_well_known_intrinsics,json=jsWellKnownIntrinsics,proto3" json:"js_well_known_intrinsics,omitempty"`
	Encodings             []*EncodingDef         `protobuf:"bytes,17,rep,name=encodings,proto3" json:"encodings,omitempty"`
	BomTable              []*BomEntry            `protobuf:"bytes,18,rep,name=bom_table,json=bomTable,proto3" json:"bom_table,omitempty"`
	FetchEnums            []*FetchEnumDef        `protobuf:"bytes,19,rep,name=fetch_enums,json=fetchEnums,proto3" json:"fetch_enums,omitempty"`
	UrlStates             []*UrlParserStateDef   `protobuf:"bytes,20,rep,name=url_states,json=urlStates,proto3" json:"url_states,omitempty"`
	KeyEvents             []*KeyEventDef         `protobuf:"bytes,21,rep,name=key_events,json=keyEvents,proto3" json:"key_events,omitempty"`
	WebidlTypes           []*WebIdlType          `protobuf:"bytes,22,rep,name=webidl_types,json=webidlTypes,proto3" json:"webidl_types,omitempty"`
	FlexboxProperties     []*FlexPropertyDef     `protobuf:"bytes,23,rep,name=flexbox_properties,json=flexboxProperties,proto3" json:"flexbox_properties,omitempty"`
	GridProperties        []*GridPropertyDef     `protobuf:"bytes,24,rep,name=grid_properties,json=gridProperties,proto3" json:"grid_properties,omitempty"`
	ColorDefs             []*ColorDef            `protobuf:"bytes,25,rep,name=color_defs,json=colorDefs,proto3" json:"color_defs,omitempty"`
	MediaProperties       []*MediaPropertyDef    `protobuf:"bytes,26,rep,name=media_properties,json=mediaProperties,proto3" json:"media_properties,omitempty"`
	SyntaxDefs            []*SyntaxDef           `protobuf:"bytes,27,rep,name=syntax_defs,json=syntaxDefs,proto3" json:"syntax_defs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_spec_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalog) GetSpecName() string {
	if x != nil {
		return x.SpecName
	}
	return ""
}

func (x *Catalog) GetSpecDate() string {
	if x != nil {
		return x.SpecDate
	}
	return ""
}

func (x *Catalog) GetCssProperties() []*CssProperty {
	if x != nil {
		return x.CssProperties
	}
	return nil
}

func (x *Catalog) GetCssValueTypes() []*CssValueType {
	if x != nil {
		return x.CssValueTypes
	}
	return nil
}

func (x *Catalog) GetCssAtRules() []*CssAtRule {
	if x != nil {
		return x.CssAtRules
	}
	return nil
}

func (x *Catalog) GetDomInterfaces() []*DomInterface {
	if x != nil {
		return x.DomInterfaces
	}
	return nil
}

func (x *Catalog) GetDomEvents() []*DomEvent {
	if x != nil {
		return x.DomEvents
	}
	return nil
}

func (x *Catalog) GetHtmlElements() []*HtmlElement {
	if x != nil {
		return x.HtmlElements
	}
	return nil
}

func (x *Catalog) GetPseudoClasses() []*PseudoClassDef {
	if x != nil {
		return x.PseudoClasses
	}
	return nil
}

func (x *Catalog) GetPseudoElements() []*PseudoElementDef {
	if x != nil {
		return x.PseudoElements
	}
	return nil
}

func (x *Catalog) GetCombinators() []*CombinatorDef {
	if x != nil {
		return x.Combinators
	}
	return nil
}

func (x *Catalog) GetAttrMatchOps() []*AttrMatchOpDef {
	if x != nil {
		return x.AttrMatchOps
	}
	return nil
}

func (x *Catalog) GetJsBuiltins() []*JsBuiltInObjectDef {
	if x != nil {
		return x.JsBuiltins
	}
	return nil
}

func (x *Catalog) GetJsAbstractOps() []*JsAbstractOpDef {
	if x != nil {
		return x.JsAbstractOps
	}
	return nil
}

func (x *Catalog) GetJsWellKnownSymbols() []string {
	if x != nil {
		return x.JsWellKnownSymbols
	}
	return nil
}

func (x *Catalog) GetJsWellKnownIntrinsics() []string {
	if x != nil {
		return x.JsWellKnownIntrinsics
	}
	return nil
}

func (x *Catalog) GetEncodings() []*EncodingDef {
	if x != nil {
		return x.Encodings
	}
	return nil
}

func (x *Catalog) GetBomTable() []*BomEntry {
	if x != nil {
		return x.BomTable
	}
	return nil
}

func (x *Catalog) GetFetchEnums() []*FetchEnumDef {
	if x != nil {
		return x.FetchEnums
	}
	return nil
}

func (x *Catalog) GetUrlStates() []*UrlParserStateDef {
	if x != nil {
		return x.UrlStates
	}
	return nil
}

func (x *Catalog) GetKeyEvents() []*KeyEventDef {
	if x != nil {
		return x.KeyEvents
	}
	return nil
}

func (x *Catalog) GetWebidlTypes() []*WebIdlType {
	if x != nil {
		return x.WebidlTypes
	}
	return nil
}

func (x *Catalog) GetFlexboxProperties() []*FlexPropertyDef {
	if x != nil {
		return x.FlexboxProperties
	}
	return nil
}

func (x *Catalog) GetGridProperties() []*GridPropertyDef {
	if x != nil {
		return x.GridProperties
	}
	return nil
}

func (x *Catalog) GetColorDefs() []*ColorDef {
	if x != nil {
		return x.ColorDefs
	}
	return nil
}

func (x *Catalog) GetMediaProperties() []*MediaPropertyDef {
	if x != nil {
		return x.MediaProperties
	}
	return nil
}

func (x *Catalog) GetSyntaxDefs() []*SyntaxDef {
	if x != nil {
		return x.SyntaxDefs
	}
	return nil
}

type CssProperty struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value          string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Initial        string                 `protobuf:"bytes,3,opt,name=initial,proto3" json:"initial,omitempty"`
	AppliesTo      string                 `protobuf:"bytes,4,opt,name=applies_to,json=appliesTo,proto3" json:"applies_to,omitempty"`
	Inherited      bool                   `protobuf:"varint,5,opt,name=inherited,proto3" json:"inherited,omitempty"`
	Percentages    string                 `protobuf:"bytes,6,opt,name=percentages,proto3" json:"percentages,omitempty"`
	ComputedValue  string                 `protobuf:"bytes,7,opt,name=computed_value,json=computedValue,proto3" json:"computed_value,omitempty"`
	AnimationType  string                 `protobuf:"bytes,8,opt,name=animation_type,json=animationType,proto3" json:"animation_type,omitempty"`
	CanonicalOrder string                 `protobuf:"bytes,9,opt,name=canonical_order,json=canonicalOrder,proto3" json:"canonical_order,omitempty"`
	SourceFile     string                 `protobuf:"bytes,10,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CssProperty) Reset() {
	*x = CssProperty{}
	mi := &file_spec_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CssProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CssProperty) ProtoMessage() {}

func (x *CssProperty) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CssProperty.ProtoReflect.Descriptor instead.
func (*CssProperty) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CssProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CssProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CssProperty) GetInitial() string {
	if x != nil {
		return x.Initial
	}
	return ""
}

func (x *CssProperty) GetAppliesTo() string {
	if x != nil {
		return x.AppliesTo
	}
	return ""
}

func (x *CssProperty) GetInherited() bool {
	if x != nil {
		return x.Inherited
	}
	return false
}

func (x *CssProperty) GetPercentages() string {
	if x != nil {
		return x.Percentages
	}
	return ""
}

func (x *CssProperty) GetComputedValue() string {
	if x != nil {
		return x.ComputedValue
	}
	return ""
}

func (x *CssProperty) GetAnimationType() string {
	if x != nil {
		return x.AnimationType
	}
	return ""
}

func (x *CssProperty) GetCanonicalOrder() string {
	if x != nil {
		return x.CanonicalOrder
	}
	return ""
}

func (x *CssProperty) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

type CssValueType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "value" or "type"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CssValueType) Reset() {
	*x = CssValueType{}
	mi := &file_spec_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CssValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CssValueType) ProtoMessage() {}

func (x *CssValueType) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CssValueType.ProtoReflect.Descriptor instead.
func (*CssValueType) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CssValueType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CssValueType) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CssAtRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CssAtRule) Reset() {
	*x = CssAtRule{}
	mi := &file_spec_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CssAtRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CssAtRule) ProtoMessage() {}

func (x *CssAtRule) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CssAtRule.ProtoReflect.Descriptor instead.
func (*CssAtRule) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *CssAtRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DomInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent        string                 `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Attributes    []*DomAttribute        `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Methods       []*DomMethod           `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomInterface) Reset() {
	*x = DomInterface{}
	mi := &file_spec_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomInterface) ProtoMessage() {}

func (x *DomInterface) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomInterface.ProtoReflect.Descriptor instead.
func (*DomInterface) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *DomInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomInterface) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DomInterface) GetAttributes() []*DomAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *DomInterface) GetMethods() []*DomMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type DomAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomAttribute) Reset() {
	*x = DomAttribute{}
	mi := &file_spec_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomAttribute) ProtoMessage() {}

func (x *DomAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomAttribute.ProtoReflect.Descriptor instead.
func (*DomAttribute) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *DomAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomAttribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DomAttribute) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type DomMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReturnType    string                 `protobuf:"bytes,2,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	Parameters    []*DomParameter        `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomMethod) Reset() {
	*x = DomMethod{}
	mi := &file_spec_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomMethod) ProtoMessage() {}

func (x *DomMethod) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomMethod.ProtoReflect.Descriptor instead.
func (*DomMethod) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *DomMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomMethod) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

func (x *DomMethod) GetParameters() []*DomParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DomParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomParameter) Reset() {
	*x = DomParameter{}
	mi := &file_spec_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomParameter) ProtoMessage() {}

func (x *DomParameter) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomParameter.ProtoReflect.Descriptor instead.
func (*DomParameter) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *DomParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DomParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomEvent) Reset() {
	*x = DomEvent{}
	mi := &file_spec_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomEvent) ProtoMessage() {}

func (x *DomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomEvent.ProtoReflect.Descriptor instead.
func (*DomEvent) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *DomEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HtmlElement struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TagName             string                 `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	Categories          []string               `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Contexts            []string               `protobuf:"bytes,3,rep,name=contexts,proto3" json:"contexts,omitempty"`
	ContentModel        string                 `protobuf:"bytes,4,opt,name=content_model,json=contentModel,proto3" json:"content_model,omitempty"`
	TagOmission         string                 `protobuf:"bytes,5,opt,name=tag_omission,json=tagOmission,proto3" json:"tag_omission,omitempty"`
	HasGlobalAttributes bool                   `protobuf:"varint,6,opt,name=has_global_attributes,json=hasGlobalAttributes,proto3" json:"has_global_attributes,omitempty"`
	ElementAttrs        []*HtmlAttrDef         `protobuf:"bytes,7,rep,name=element_attrs,json=elementAttrs,proto3" json:"element_attrs,omitempty"`
	DomInterface        string                 `protobuf:"bytes,8,opt,name=dom_interface,json=domInterface,proto3" json:"dom_interface,omitempty"`
	Idl                 string                 `protobuf:"bytes,9,opt,name=idl,proto3" json:"idl,omitempty"`
	Represents          string                 `protobuf:"bytes,10,opt,name=represents,proto3" json:"represents,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HtmlElement) Reset() {
	*x = HtmlElement{}
	mi := &file_spec_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HtmlElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HtmlElement) ProtoMessage() {}

func (x *HtmlElement) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HtmlElement.ProtoReflect.Descriptor instead.
func (*HtmlElement) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *HtmlElement) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *HtmlElement) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *HtmlElement) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *HtmlElement) GetContentModel() string {
	if x != nil {
		return x.ContentModel
	}
	return ""
}

func (x *HtmlElement) GetTagOmission() string {
	if x != nil {
		return x.TagOmission
	}
	return ""
}

func (x *HtmlElement) GetHasGlobalAttributes() bool {
	if x != nil {
		return x.HasGlobalAttributes
	}
	return false
}

func (x *HtmlElement) GetElementAttrs() []*HtmlAttrDef {
	if x != nil {
		return x.ElementAttrs
	}
	return nil
}

func (x *HtmlElement) GetDomInterface() string {
	if x != nil {
		return x.DomInterface
	}
	return ""
}

func (x *HtmlElement) GetIdl() string {
	if x != nil {
		return x.Idl
	}
	return ""
}

func (x *HtmlElement) GetRepresents() string {
	if x != nil {
		return x.Represents
	}
	return ""
}

type HtmlAttrDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HtmlAttrDef) Reset() {
	*x = HtmlAttrDef{}
	mi := &file_spec_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HtmlAttrDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HtmlAttrDef) ProtoMessage() {}

func (x *HtmlAttrDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HtmlAttrDef.ProtoReflect.Descriptor instead.
func (*HtmlAttrDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *HtmlAttrDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HtmlAttrDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PseudoClassDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PseudoClassDef) Reset() {
	*x = PseudoClassDef{}
	mi := &file_spec_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PseudoClassDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PseudoClassDef) ProtoMessage() {}

func (x *PseudoClassDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PseudoClassDef.ProtoReflect.Descriptor instead.
func (*PseudoClassDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *PseudoClassDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PseudoClassDef) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *PseudoClassDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PseudoElementDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PseudoElementDef) Reset() {
	*x = PseudoElementDef{}
	mi := &file_spec_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PseudoElementDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PseudoElementDef) ProtoMessage() {}

func (x *PseudoElementDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PseudoElementDef.ProtoReflect.Descriptor instead.
func (*PseudoElementDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *PseudoElementDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CombinatorDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Syntax        string                 `protobuf:"bytes,2,opt,name=syntax,proto3" json:"syntax,omitempty"`
	Char          string                 `protobuf:"bytes,3,opt,name=char,proto3" json:"char,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinatorDef) Reset() {
	*x = CombinatorDef{}
	mi := &file_spec_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinatorDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinatorDef) ProtoMessage() {}

func (x *CombinatorDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinatorDef.ProtoReflect.Descriptor instead.
func (*CombinatorDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *CombinatorDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CombinatorDef) GetSyntax() string {
	if x != nil {
		return x.Syntax
	}
	return ""
}

func (x *CombinatorDef) GetChar() string {
	if x != nil {
		return x.Char
	}
	return ""
}

func (x *CombinatorDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AttrMatchOpDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Operator      string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrMatchOpDef) Reset() {
	*x = AttrMatchOpDef{}
	mi := &file_spec_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrMatchOpDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrMatchOpDef) ProtoMessage() {}

func (x *AttrMatchOpDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrMatchOpDef.ProtoReflect.Descriptor instead.
func (*AttrMatchOpDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *AttrMatchOpDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttrMatchOpDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AttrMatchOpDef) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

type JsBuiltInObjectDef struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StaticMethods        []*JsMethodDef         `protobuf:"bytes,2,rep,name=static_methods,json=staticMethods,proto3" json:"static_methods,omitempty"`
	PrototypeMethods     []*JsMethodDef         `protobuf:"bytes,3,rep,name=prototype_methods,json=prototypeMethods,proto3" json:"prototype_methods,omitempty"`
	StaticProperties     []string               `protobuf:"bytes,4,rep,name=static_properties,json=staticProperties,proto3" json:"static_properties,omitempty"`
	PrototypeProperties  []string               `protobuf:"bytes,5,rep,name=prototype_properties,json=prototypeProperties,proto3" json:"prototype_properties,omitempty"`
	ConstructorSignature string                 `protobuf:"bytes,6,opt,name=constructor_signature,json=constructorSignature,proto3" json:"constructor_signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *JsBuiltInObjectDef) Reset() {
	*x = JsBuiltInObjectDef{}
	mi := &file_spec_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsBuiltInObjectDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsBuiltInObjectDef) ProtoMessage() {}

func (x *JsBuiltInObjectDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsBuiltInObjectDef.ProtoReflect.Descriptor instead.
func (*JsBuiltInObjectDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *JsBuiltInObjectDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JsBuiltInObjectDef) GetStaticMethods() []*JsMethodDef {
	if x != nil {
		return x.StaticMethods
	}
	return nil
}

func (x *JsBuiltInObjectDef) GetPrototypeMethods() []*JsMethodDef {
	if x != nil {
		return x.PrototypeMethods
	}
	return nil
}

func (x *JsBuiltInObjectDef) GetStaticProperties() []string {
	if x != nil {
		return x.StaticProperties
	}
	return nil
}

func (x *JsBuiltInObjectDef) GetPrototypeProperties() []string {
	if x != nil {
		return x.PrototypeProperties
	}
	return nil
}

func (x *JsBuiltInObjectDef) GetConstructorSignature() string {
	if x != nil {
		return x.ConstructorSignature
	}
	return ""
}

type JsMethodDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReturnType    string                 `protobuf:"bytes,2,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	Parameters    []string               `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsMethodDef) Reset() {
	*x = JsMethodDef{}
	mi := &file_spec_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsMethodDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsMethodDef) ProtoMessage() {}

func (x *JsMethodDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsMethodDef.ProtoReflect.Descriptor instead.
func (*JsMethodDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *JsMethodDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JsMethodDef) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

func (x *JsMethodDef) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type JsAbstractOpDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    []string               `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsAbstractOpDef) Reset() {
	*x = JsAbstractOpDef{}
	mi := &file_spec_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsAbstractOpDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsAbstractOpDef) ProtoMessage() {}

func (x *JsAbstractOpDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsAbstractOpDef.ProtoReflect.Descriptor instead.
func (*JsAbstractOpDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *JsAbstractOpDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JsAbstractOpDef) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *JsAbstractOpDef) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type EncodingDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Type          EncodingType           `protobuf:"varint,3,opt,name=type,proto3,enum=edgerun.v0.spec.EncodingType" json:"type,omitempty"`
	Endianness    string                 `protobuf:"bytes,4,opt,name=endianness,proto3" json:"endianness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodingDef) Reset() {
	*x = EncodingDef{}
	mi := &file_spec_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodingDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodingDef) ProtoMessage() {}

func (x *EncodingDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodingDef.ProtoReflect.Descriptor instead.
func (*EncodingDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *EncodingDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EncodingDef) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EncodingDef) GetType() EncodingType {
	if x != nil {
		return x.Type
	}
	return EncodingType_ENCODING_TYPE_UNSPECIFIED
}

func (x *EncodingDef) GetEndianness() string {
	if x != nil {
		return x.Endianness
	}
	return ""
}

type BomEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoding      string                 `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BomEntry) Reset() {
	*x = BomEntry{}
	mi := &file_spec_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BomEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomEntry) ProtoMessage() {}

func (x *BomEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomEntry.ProtoReflect.Descriptor instead.
func (*BomEntry) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *BomEntry) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *BomEntry) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type FetchEnumDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Variants      []string               `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchEnumDef) Reset() {
	*x = FetchEnumDef{}
	mi := &file_spec_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEnumDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEnumDef) ProtoMessage() {}

func (x *FetchEnumDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEnumDef.ProtoReflect.Descriptor instead.
func (*FetchEnumDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *FetchEnumDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetchEnumDef) GetVariants() []string {
	if x != nil {
		return x.Variants
	}
	return nil
}

type UrlParserStateDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlParserStateDef) Reset() {
	*x = UrlParserStateDef{}
	mi := &file_spec_catalog_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlParserStateDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlParserStateDef) ProtoMessage() {}

func (x *UrlParserStateDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlParserStateDef.ProtoReflect.Descriptor instead.
func (*UrlParserStateDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{21}
}

func (x *UrlParserStateDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type KeyEventDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "keyboard", "mouse", "modifier"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEventDef) Reset() {
	*x = KeyEventDef{}
	mi := &file_spec_catalog_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEventDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEventDef) ProtoMessage() {}

func (x *KeyEventDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEventDef.ProtoReflect.Descriptor instead.
func (*KeyEventDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{22}
}

func (x *KeyEventDef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyEventDef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type WebIdlType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          WebIdlTypeKind         `protobuf:"varint,2,opt,name=kind,proto3,enum=edgerun.v0.spec.WebIdlTypeKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebIdlType) Reset() {
	*x = WebIdlType{}
	mi := &file_spec_catalog_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebIdlType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebIdlType) ProtoMessage() {}

func (x *WebIdlType) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebIdlType.ProtoReflect.Descriptor instead.
func (*WebIdlType) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{23}
}

func (x *WebIdlType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebIdlType) GetKind() WebIdlTypeKind {
	if x != nil {
		return x.Kind
	}
	return WebIdlTypeKind_WEBIDL_TYPE_UNSPECIFIED
}

type FlexPropertyDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"` // "container" or "child"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexPropertyDef) Reset() {
	*x = FlexPropertyDef{}
	mi := &file_spec_catalog_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexPropertyDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexPropertyDef) ProtoMessage() {}

func (x *FlexPropertyDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexPropertyDef.ProtoReflect.Descriptor instead.
func (*FlexPropertyDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{24}
}

func (x *FlexPropertyDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlexPropertyDef) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *FlexPropertyDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FlexPropertyDef) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GridPropertyDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridPropertyDef) Reset() {
	*x = GridPropertyDef{}
	mi := &file_spec_catalog_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridPropertyDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridPropertyDef) ProtoMessage() {}

func (x *GridPropertyDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridPropertyDef.ProtoReflect.Descriptor instead.
func (*GridPropertyDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{25}
}

func (x *GridPropertyDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GridPropertyDef) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GridPropertyDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ColorDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ColorSpace    string                 `protobuf:"bytes,2,opt,name=color_space,json=colorSpace,proto3" json:"color_space,omitempty"`
	Components    []float64              `protobuf:"fixed64,3,rep,packed,name=components,proto3" json:"components,omitempty"`
	Alpha         string                 `protobuf:"bytes,4,opt,name=alpha,proto3" json:"alpha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorDef) Reset() {
	*x = ColorDef{}
	mi := &file_spec_catalog_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorDef) ProtoMessage() {}

func (x *ColorDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorDef.ProtoReflect.Descriptor instead.
func (*ColorDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{26}
}

func (x *ColorDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColorDef) GetColorSpace() string {
	if x != nil {
		return x.ColorSpace
	}
	return ""
}

func (x *ColorDef) GetComponents() []float64 {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ColorDef) GetAlpha() string {
	if x != nil {
		return x.Alpha
	}
	return ""
}

type MediaPropertyDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaPropertyDef) Reset() {
	*x = MediaPropertyDef{}
	mi := &file_spec_catalog_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaPropertyDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaPropertyDef) ProtoMessage() {}

func (x *MediaPropertyDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaPropertyDef.ProtoReflect.Descriptor instead.
func (*MediaPropertyDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{27}
}

func (x *MediaPropertyDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaPropertyDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MediaPropertyDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SyntaxDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // "token" or "state"
	Variants      []string               `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyntaxDef) Reset() {
	*x = SyntaxDef{}
	mi := &file_spec_catalog_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntaxDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntaxDef) ProtoMessage() {}

func (x *SyntaxDef) ProtoReflect() protoreflect.Message {
	mi := &file_spec_catalog_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntaxDef.ProtoReflect.Descriptor instead.
func (*SyntaxDef) Descriptor() ([]byte, []int) {
	return file_spec_catalog_proto_rawDescGZIP(), []int{28}
}

func (x *SyntaxDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyntaxDef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SyntaxDef) GetVariants() []string {
	if x != nil {
		return x.Variants
	}
	return nil
}

var File_spec_catalog_proto protoreflect.FileDescriptor

const file_spec_catalog_proto_rawDesc = "" +
	"\n" +
	"\x12spec_catalog.proto\x12\x0fedgerun.v0.spec\"\xbe\r\n" +
	"\aCatalog\x12\x1b\n" +
	"\tspec_name\x18\x01 \x01(\tR\bspecName\x12\x1b\n" +
	"\tspec_date\x18\x02 \x01(\tR\bspecDate\x12C\n" +
	"\x0ecss_properties\x18\x03 \x03(\v2\x1c.edgerun.v0.spec.CssPropertyR\rcssProperties\x12E\n" +
	"\x0fcss_value_types\x18\x04 \x03(\v2\x1d.edgerun.v0.spec.CssValueTypeR\rcssValueTypes\x12<\n" +
	"\fcss_at_rules\x18\x05 \x03(\v2\x1a.edgerun.v0.spec.CssAtRuleR\n" +
	"cssAtRules\x12D\n" +
	"\x0edom_interfaces\x18\x06 \x03(\v2\x1d.edgerun.v0.spec.DomInterfaceR\rdomInterfaces\x128\n" +
	"\n" +
	"dom_events\x18\a \x03(\v2\x19.edgerun.v0.spec.DomEventR\tdomEvents\x12A\n" +
	"\rhtml_elements\x18\b \x03(\v2\x1c.edgerun.v0.spec.HtmlElementR\fhtmlElements\x12F\n" +
	"\x0epseudo_classes\x18\t \x03(\v2\x1f.edgerun.v0.spec.PseudoClassDefR\rpseudoClasses\x12J\n" +
	"\x0fpseudo_elements\x18\n" +
	" \x03(\v2!.edgerun.v0.spec.PseudoElementDefR\x0epseudoElements\x12@\n" +
	"\vcombinators\x18\v \x03(\v2\x1e.edgerun.v0.spec.CombinatorDefR\vcombinators\x12E\n" +
	"\x0eattr_match_ops\x18\f \x03(\v2\x1f.edgerun.v0.spec.AttrMatchOpDefR\fattrMatchOps\x12D\n" +
	"\vjs_builtins\x18\r \x03(\v2#.edgerun.v0.spec.JsBuiltInObjectDefR\n" +
	"jsBuiltins\x12H\n" +
	"\x0fjs_abstract_ops\x18\x0e \x03(\v2 .edgerun.v0.spec.JsAbstractOpDefR\rjsAbstractOps\x121\n" +
	"\x15js_well_known_symbols\x18\x0f \x03(\tR\x12jsWellKnownSymbols\x127\n" +
	"\x18js_well_known_intrinsics\x18\x10 \x03(\tR\x15jsWellKnownIntrinsics\x12:\n" +
	"\tencodings\x18\x11 \x03(\v2\x1c.edgerun.v0.spec.EncodingDefR\tencodings\x126\n" +
	"\tbom_table\x18\x12 \x03(\v2\x19.edgerun.v0.spec.BomEntryR\bbomTable\x12>\n" +
	"\vfetch_enums\x18\x13 \x03(\v2\x1d.edgerun.v0.spec.FetchEnumDefR\n" +
	"fetchEnums\x12A\n" +
	"\n" +
	"url_states\x18\x14 \x03(\v2\".edgerun.v0.spec.UrlParserStateDefR\turlStates\x12;\n" +
	"\n" +
	"key_events\x18\x15 \x03(\v2\x1c.edgerun.v0.spec.KeyEventDefR\tkeyEvents\x12>\n" +
	"\fwebidl_types\x18\x16 \x03(\v2\x1b.edgerun.v0.spec.WebIdlTypeR\vwebidlTypes\x12O\n" +
	"\x12flexbox_properties\x18\x17 \x03(\v2 .edgerun.v0.spec.FlexPropertyDefR\x11flexboxProperties\x12I\n" +
	"\x0fgrid_properties\x18\x18 \x03(\v2 .edgerun.v0.spec.GridPropertyDefR\x0egridProperties\x128\n" +
	"\n" +
	"color_defs\x18\x19 \x03(\v2\x19.edgerun.v0.spec.ColorDefR\tcolorDefs\x12L\n" +
	"\x10media_properties\x18\x1a \x03(\v2!.edgerun.v0.spec.MediaPropertyDefR\x0fmediaProperties\x12;\n" +
	"\vsyntax_defs\x18\x1b \x03(\v2\x1a.edgerun.v0.spec.SyntaxDefR\n" +
	"syntaxDefs\"\xc8\x02\n" +
	"\vCssProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\ainitial\x18\x03 \x01(\tR\ainitial\x12\x1d\n" +
	"\n" +
	"applies_to\x18\x04 \x01(\tR\tappliesTo\x12\x1c\n" +
	"\tinherited\x18\x05 \x01(\bR\tinherited\x12 \n" +
	"\vpercentages\x18\x06 \x01(\tR\vpercentages\x12%\n" +
	"\x0ecomputed_value\x18\a \x01(\tR\rcomputedValue\x12%\n" +
	"\x0eanimation_type\x18\b \x01(\tR\ranimationType\x12'\n" +
	"\x0fcanonical_order\x18\t \x01(\tR\x0ecanonicalOrder\x12\x1f\n" +
	"\vsource_file\x18\n" +
	" \x01(\tR\n" +
	"sourceFile\"6\n" +
	"\fCssValueType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"\x1f\n" +
	"\tCssAtRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xaf\x01\n" +
	"\fDomInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12=\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1d.edgerun.v0.spec.DomAttributeR\n" +
	"attributes\x124\n" +
	"\amethods\x18\x04 \x03(\v2\x1a.edgerun.v0.spec.DomMethodR\amethods\"R\n" +
	"\fDomAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\"\x7f\n" +
	"\tDomMethod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vreturn_type\x18\x02 \x01(\tR\n" +
	"returnType\x12=\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2\x1d.edgerun.v0.spec.DomParameterR\n" +
	"parameters\"6\n" +
	"\fDomParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1e\n" +
	"\bDomEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xfa\x02\n" +
	"\vHtmlElement\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\x12\x1e\n" +
	"\n" +
	"categories\x18\x02 \x03(\tR\n" +
	"categories\x12\x1a\n" +
	"\bcontexts\x18\x03 \x03(\tR\bcontexts\x12#\n" +
	"\rcontent_model\x18\x04 \x01(\tR\fcontentModel\x12!\n" +
	"\ftag_omission\x18\x05 \x01(\tR\vtagOmission\x122\n" +
	"\x15has_global_attributes\x18\x06 \x01(\bR\x13hasGlobalAttributes\x12A\n" +
	"\relement_attrs\x18\a \x03(\v2\x1c.edgerun.v0.spec.HtmlAttrDefR\felementAttrs\x12#\n" +
	"\rdom_interface\x18\b \x01(\tR\fdomInterface\x12\x10\n" +
	"\x03idl\x18\t \x01(\tR\x03idl\x12\x1e\n" +
	"\n" +
	"represents\x18\n" +
	" \x01(\tR\n" +
	"represents\"C\n" +
	"\vHtmlAttrDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"d\n" +
	"\x0ePseudoClassDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"&\n" +
	"\x10PseudoElementDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"q\n" +
	"\rCombinatorDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06syntax\x18\x02 \x01(\tR\x06syntax\x12\x12\n" +
	"\x04char\x18\x03 \x01(\tR\x04char\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"b\n" +
	"\x0eAttrMatchOpDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\"\xcd\x02\n" +
	"\x12JsBuiltInObjectDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\x0estatic_methods\x18\x02 \x03(\v2\x1c.edgerun.v0.spec.JsMethodDefR\rstaticMethods\x12I\n" +
	"\x11prototype_methods\x18\x03 \x03(\v2\x1c.edgerun.v0.spec.JsMethodDefR\x10prototypeMethods\x12+\n" +
	"\x11static_properties\x18\x04 \x03(\tR\x10staticProperties\x121\n" +
	"\x14prototype_properties\x18\x05 \x03(\tR\x13prototypeProperties\x123\n" +
	"\x15constructor_signature\x18\x06 \x01(\tR\x14constructorSignature\"b\n" +
	"\vJsMethodDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vreturn_type\x18\x02 \x01(\tR\n" +
	"returnType\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x03(\tR\n" +
	"parameters\"_\n" +
	"\x0fJsAbstractOpDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\tR\n" +
	"parameters\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\"\x8c\x01\n" +
	"\vEncodingDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.edgerun.v0.spec.EncodingTypeR\x04type\x12\x1e\n" +
	"\n" +
	"endianness\x18\x04 \x01(\tR\n" +
	"endianness\"<\n" +
	"\bBomEntry\x12\x1a\n" +
	"\bencoding\x18\x01 \x01(\tR\bencoding\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\fR\x05bytes\">\n" +
	"\fFetchEnumDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bvariants\x18\x02 \x03(\tR\bvariants\"'\n" +
	"\x11UrlParserStateDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\vKeyEventDef\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"U\n" +
	"\n" +
	"WebIdlType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1f.edgerun.v0.spec.WebIdlTypeKindR\x04kind\"{\n" +
	"\x0fFlexPropertyDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"_\n" +
	"\x0fGridPropertyDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"u\n" +
	"\bColorDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vcolor_space\x18\x02 \x01(\tR\n" +
	"colorSpace\x12\x1e\n" +
	"\n" +
	"components\x18\x03 \x03(\x01R\n" +
	"components\x12\x14\n" +
	"\x05alpha\x18\x04 \x01(\tR\x05alpha\"^\n" +
	"\x10MediaPropertyDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"O\n" +
	"\tSyntaxDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\bvariants\x18\x03 \x03(\tR\bvariants*\x97\x01\n" +
	"\fEncodingType\x12\x1d\n" +
	"\x19ENCODING_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENCODING_TYPE_UTF8\x10\x01\x12\x17\n" +
	"\x13ENCODING_TYPE_UTF16\x10\x02\x12\x18\n" +
	"\x14ENCODING_TYPE_LEGACY\x10\x03\x12\x1d\n" +
	"\x19ENCODING_TYPE_REPLACEMENT\x10\x04*\xb0\x01\n" +
	"\x0eWebIdlTypeKind\x12\x1b\n" +
	"\x17WEBIDL_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WEBIDL_TYPE_PRIMITIVE\x10\x01\x12\x16\n" +
	"\x12WEBIDL_TYPE_STRING\x10\x02\x12\x16\n" +
	"\x12WEBIDL_TYPE_OBJECT\x10\x03\x12\x17\n" +
	"\x13WEBIDL_TYPE_SPECIAL\x10\x04\x12\x1d\n" +
	"\x19WEBIDL_TYPE_EXTENDED_ATTR\x10\x05B*Z(github.com/edgerun/edgerun/proto/go/specb\x06proto3"

var (
	file_spec_catalog_proto_rawDescOnce sync.Once
	file_spec_catalog_proto_rawDescData []byte
)

func file_spec_catalog_proto_rawDescGZIP() []byte {
	file_spec_catalog_proto_rawDescOnce.Do(func() {
		file_spec_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spec_catalog_proto_rawDesc), len(file_spec_catalog_proto_rawDesc)))
	})
	return file_spec_catalog_proto_rawDescData
}

var file_spec_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spec_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_spec_catalog_proto_goTypes = []any{
	(EncodingType)(0),          // 0: edgerun.v0.spec.EncodingType
	(WebIdlTypeKind)(0),        // 1: edgerun.v0.spec.WebIdlTypeKind
	(*Catalog)(nil),            // 2: edgerun.v0.spec.Catalog
	(*CssProperty)(nil),        // 3: edgerun.v0.spec.CssProperty
	(*CssValueType)(nil),       // 4: edgerun.v0.spec.CssValueType
	(*CssAtRule)(nil),          // 5: edgerun.v0.spec.CssAtRule
	(*DomInterface)(nil),       // 6: edgerun.v0.spec.DomInterface
	(*DomAttribute)(nil),       // 7: edgerun.v0.spec.DomAttribute
	(*DomMethod)(nil),          // 8: edgerun.v0.spec.DomMethod
	(*DomParameter)(nil),       // 9: edgerun.v0.spec.DomParameter
	(*DomEvent)(nil),           // 10: edgerun.v0.spec.DomEvent
	(*HtmlElement)(nil),        // 11: edgerun.v0.spec.HtmlElement
	(*HtmlAttrDef)(nil),        // 12: edgerun.v0.spec.HtmlAttrDef
	(*PseudoClassDef)(nil),     // 13: edgerun.v0.spec.PseudoClassDef
	(*PseudoElementDef)(nil),   // 14: edgerun.v0.spec.PseudoElementDef
	(*CombinatorDef)(nil),      // 15: edgerun.v0.spec.CombinatorDef
	(*AttrMatchOpDef)(nil),     // 16: edgerun.v0.spec.AttrMatchOpDef
	(*JsBuiltInObjectDef)(nil), // 17: edgerun.v0.spec.JsBuiltInObjectDef
	(*JsMethodDef)(nil),        // 18: edgerun.v0.spec.JsMethodDef
	(*JsAbstractOpDef)(nil),    // 19: edgerun.v0.spec.JsAbstractOpDef
	(*EncodingDef)(nil),        // 20: edgerun.v0.spec.EncodingDef
	(*BomEntry)(nil),           // 21: edgerun.v0.spec.BomEntry
	(*FetchEnumDef)(nil),       // 22: edgerun.v0.spec.FetchEnumDef
	(*UrlParserStateDef)(nil),  // 23: edgerun.v0.spec.UrlParserStateDef
	(*KeyEventDef)(nil),        // 24: edgerun.v0.spec.KeyEventDef
	(*WebIdlType)(nil),         // 25: edgerun.v0.spec.WebIdlType
	(*FlexPropertyDef)(nil),    // 26: edgerun.v0.spec.FlexPropertyDef
	(*GridPropertyDef)(nil),    // 27: edgerun.v0.spec.GridPropertyDef
	(*ColorDef)(nil),           // 28: edgerun.v0.spec.ColorDef
	(*MediaPropertyDef)(nil),   // 29: edgerun.v0.spec.MediaPropertyDef
	(*SyntaxDef)(nil),          // 30: edgerun.v0.spec.SyntaxDef
}
var file_spec_catalog_proto_depIdxs = []int32{
	3,  // 0: edgerun.v0.spec.Catalog.css_properties:type_name -> edgerun.v0.spec.CssProperty
	4,  // 1: edgerun.v0.spec.Catalog.css_value_types:type_name -> edgerun.v0.spec.CssValueType
	5,  // 2: edgerun.v0.spec.Catalog.css_at_rules:type_name -> edgerun.v0.spec.CssAtRule
	6,  // 3: edgerun.v0.spec.Catalog.dom_interfaces:type_name -> edgerun.v0.spec.DomInterface
	10, // 4: edgerun.v0.spec.Catalog.dom_events:type_name -> edgerun.v0.spec.DomEvent
	11, // 5: edgerun.v0.spec.Catalog.html_elements:type_name -> edgerun.v0.spec.HtmlElement
	13, // 6: edgerun.v0.spec.Catalog.pseudo_classes:type_name -> edgerun.v0.spec.PseudoClassDef
	14, // 7: edgerun.v0.spec.Catalog.pseudo_elements:type_name -> edgerun.v0.spec.PseudoElementDef
	15, // 8: edgerun.v0.spec.Catalog.combinators:type_name -> edgerun.v0.spec.CombinatorDef
	16, // 9: edgerun.v0.spec.Catalog.attr_match_ops:type_name -> edgerun.v0.spec.AttrMatchOpDef
	17, // 10: edgerun.v0.spec.Catalog.js_builtins:type_name -> edgerun.v0.spec.JsBuiltInObjectDef
	19, // 11: edgerun.v0.spec.Catalog.js_abstract_ops:type_name -> edgerun.v0.spec.JsAbstractOpDef
	20, // 12: edgerun.v0.spec.Catalog.encodings:type_name -> edgerun.v0.spec.EncodingDef
	21, // 13: edgerun.v0.spec.Catalog.bom_table:type_name -> edgerun.v0.spec.BomEntry
	22, // 14: edgerun.v0.spec.Catalog.fetch_enums:type_name -> edgerun.v0.spec.FetchEnumDef
	23, // 15: edgerun.v0.spec.Catalog.url_states:type_name -> edgerun.v0.spec.UrlParserStateDef
	24, // 16: edgerun.v0.spec.Catalog.key_events:type_name -> edgerun.v0.spec.KeyEventDef
	25, // 17: edgerun.v0.spec.Catalog.webidl_types:type_name -> edgerun.v0.spec.WebIdlType
	26, // 18: edgerun.v0.spec.Catalog.flexbox_properties:type_name -> edgerun.v0.spec.FlexPropertyDef
	27, // 19: edgerun.v0.spec.Catalog.grid_properties:type_name -> edgerun.v0.spec.GridPropertyDef
	28, // 20: edgerun.v0.spec.Catalog.color_defs:type_name -> edgerun.v0.spec.ColorDef
	29, // 21: edgerun.v0.spec.Catalog.media_properties:type_name -> edgerun.v0.spec.MediaPropertyDef
	30, // 22: edgerun.v0.spec.Catalog.syntax_defs:type_name -> edgerun.v0.spec.SyntaxDef
	7,  // 23: edgerun.v0.spec.DomInterface.attributes:type_name -> edgerun.v0.spec.DomAttribute
	8,  // 24: edgerun.v0.spec.DomInterface.methods:type_name -> edgerun.v0.spec.DomMethod
	9,  // 25: edgerun.v0.spec.DomMethod.parameters:type_name -> edgerun.v0.spec.DomParameter
	12, // 26: edgerun.v0.spec.HtmlElement.element_attrs:type_name -> edgerun.v0.spec.HtmlAttrDef
	18, // 27: edgerun.v0.spec.JsBuiltInObjectDef.static_methods:type_name -> edgerun.v0.spec.JsMethodDef
	18, // 28: edgerun.v0.spec.JsBuiltInObjectDef.prototype_methods:type_name -> edgerun.v0.spec.JsMethodDef
	0,  // 29: edgerun.v0.spec.EncodingDef.type:type_name -> edgerun.v0.spec.EncodingType
	1,  // 30: edgerun.v0.spec.WebIdlType.kind:type_name -> edgerun.v0.spec.WebIdlTypeKind
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_spec_catalog_proto_init() }
func file_spec_catalog_proto_init() {
	if File_spec_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spec_catalog_proto_rawDesc), len(file_spec_catalog_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spec_catalog_proto_goTypes,
		DependencyIndexes: file_spec_catalog_proto_depIdxs,
		EnumInfos:         file_spec_catalog_proto_enumTypes,
		MessageInfos:      file_spec_catalog_proto_msgTypes,
	}.Build()
	File_spec_catalog_proto = out.File
	file_spec_catalog_proto_goTypes = nil
	file_spec_catalog_proto_depIdxs = nil
}
