[package]
name = "jni-macros"
version = "0.22.4"
edition = "2024"
license = "MIT OR Apache-2.0"
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned procedural macros for the jni crate"
build = "build.rs"

[lib]
name = "jni_macros"
path = "src/lib.rs"
doctest = false
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, features = ["proc-macro"] }
quote = { workspace = true, features = ["proc-macro"] }
simd_cesu8 = { path = "../edgerun-simd-cesu8" }
syn = { workspace = true, features = ["clone-impls", "derive", "full", "parsing", "printing", "proc-macro"] }

[lints]
workspace = true
