[package]
name = "edgerun-matter"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Matter protocol support for Edgerun device integrations"

[dependencies]
edgerun-bluetooth-gatt = { version = "0.1", path = "../edgerun-bluetooth-gatt" }
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding" }

[lints]
workspace = true
