//! # edgerun-render — Complete HTML/CSS Rendering Pipeline
//!
//! Parses HTML and CSS into a DOM tree, computes layout, emits paint commands,
//! and rasterizes RGBA pixels — all in one crate with clear layer boundaries.
//!
//! ## Pipeline
//!
//! ```text
//! HTML string ──→ Tokenizer ──→ TreeBuilder ──→ DOM tree
//!                                            │
//! CSS string ───→ CssParser ──→ Stylesheet ──┤
//!                                            │
//!                                   layout_builder → RenderObject tree
//!                                                  │
//!                                   position_layout → PositionedNode tree
//!                                                  │
//!                                   paint_node → RasterCommand list
//!                                                  │
//!                                   scanline::rasterize → RGBA pixels
//! ```
//!
//! ## Architecture
//!
//! The crate is organized into four layers, each with a single responsibility:
//!
//! | Layer | Module | Responsibility |
//! |-------|--------|----------------|
//! | **Parse** | [`html`] | WHATWG HTML tokenizer + tree builder → DOM tree |
//! | **Style** | [`css`] | CSS stylesheet parsing + computed style resolution |
//! | **Layout** | [`layout`] | DOM+CSS → RenderObject tree → positioned geometry |
//! | **Paint** | [`render`] | Positioned tree → raster commands → RGBA pixels |
//!
//! ## Incremental Layout
//!
//! When a single CSS property changes, the [`layout::incremental`] module
//! tracks the minimum dirty subtree — typically 5-20 nodes instead of O(N).
//!
//! ## Budget Estimation
//!
//! The [`layout::budget`] module predicts rendering cost before any pixels
//! are drawn, using dirty node counts and calibrated per-phase costs.
//!
//! ## Quick Start
//!
//! ```ignore
//! use edgerun_render::render;
//!
//! let pixels: Vec<u8> = render(
//!     "<p>Hello World</p>",        // HTML
//!     "p { color: white; font-size: 16px; }", // CSS
//!     960,   // width
//!     640,   // height
//! );
//! // pixels is width × height × 4 bytes in RGBA order
//! ```
//!
//! ## Code Generation
//!
//! The following files are auto-generated and MUST NOT be hand-edited:
//!
//! - `html/tokenizer.rs` — Generated by `cmd/html-codegen/` from `data/tokenizer.textproto`
//! - `html/tree_builder.rs` — Generated by `cmd/html-codegen/` from `data/tree_builder.textproto`
//! - `html_parser.rs` — Generated by `cmd/html-codegen/` (thin wrapper)
//! - `entity_decoder/` — Generated by `cmd/html-codegen/` from `data/entities.textproto`
//!
//! Regenerate: `go run ./cmd/html-codegen`
//!
//! The `edgerun-layout` and `edgerun-rasterizer` crates were previously generated
//! by `cmd/generate-renderer/` but their hand-written logic has been consolidated
//! into this crate. The generator should be updated to emit here.

#![cfg_attr(not(test), no_std)]
extern crate alloc;

pub mod html;
pub mod css;
pub mod layout;
pub mod render;

// Re-export top-level convenience
pub use html::parse_html;
pub use css::parse_css;
pub use render::{render, count_nodes};
pub use layout::position_layout::position_tree;
