[package]
name = "edgerun-dns"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "no_std DNS server and client using edgerun-rt"

[features]
default = []
dhcp = ["edgerun-protocols/dhcp"]
dhcp-client = ["dhcp", "dep:edgerun-crypto"]
dnssec = [
    "dep:edgerun-crypto",
    "edgerun-crypto/ed25519",
    "edgerun-crypto/p256",
    "edgerun-crypto/sha1",
]
tsig = ["dep:edgerun-crypto", "edgerun-crypto/hmac", "edgerun-protocols/tsig"]

[[bin]]
name = "edgerun-dns"
path = "src/main.rs"
required-features = ["dnssec"]

[dependencies]
edgerun-rt = { version = "0.1", path = "../edgerun-rt" }
edgerun-log = { version = "0.1", path = "../utility/edgerun-log" }
edgerun-protocols = { workspace = true, default-features = false, features = ["dns", "tftp"] }
edgerun-crypto = { version = "0.1", path = "../utility/edgerun-crypto", default-features = false, optional = true }
edgerun-encoding = { version = "0.1", path = "../utility/edgerun-encoding", default-features = false }

[[test]]
name = "dnssec_integration"
required-features = ["dnssec"]

[lints]
workspace = true
