[package]
name = "edgerun-dns"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "no_std DNS server and client using edgerun-rt"

[features]
default = []
dhcp = ["dep:edgerun-dhcp"]
dhcp-client = ["dhcp", "dep:edgerun-crypto"]
dnssec = [
    "dep:edgerun-crypto",
    "edgerun-crypto/ed25519",
    "edgerun-crypto/p256",
    "edgerun-crypto/sha1",
]
tsig = ["dep:edgerun-crypto", "edgerun-crypto/hmac"]

[dependencies]
edgerun-rt = { version = "0.1", path = "../edgerun-rt" }
edgerun-log = { version = "0.1", path = "../edgerun-log" }
edgerun-dhcp = { version = "0.1", path = "../edgerun-dhcp", optional = true }
edgerun-tftp = { version = "0.1", path = "../edgerun-tftp" }
edgerun-crypto = { version = "0.1", path = "../edgerun-crypto", default-features = false, optional = true }
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding", default-features = false }

[[test]]
name = "dnssec_integration"
required-features = ["dnssec"]

[lints]
workspace = true
