
  ;; Status values: 0 ok, 2 output_short, 3 invalid.
  ;; Packed return: low u32 status, high u32 bytes written.

  (func (export "proto_standard_id") (result i32)
    i32.const 300043)


  (func $m123byte (param $ptr i32) (param $off i32) (result i32)
    (i32.load8_u (i32.add (local.get $ptr) (local.get $off))))

  (func $m123put (param $out_ptr i32) (param $out_cap i32) (param $written i32) (param $c i32) (result i64)
    (if (i32.ge_u (local.get $written) (local.get $out_cap))
      (then (return (call $pack (i32.const 2) (local.get $written)))))
    (i32.store8 (i32.add (local.get $out_ptr) (local.get $written)) (local.get $c))
    (call $pack (i32.const 0) (i32.add (local.get $written) (i32.const 1))))

  (func $m123hex_digit (param $value i32) (result i32)
    (if (i32.lt_u (local.get $value) (i32.const 10))
      (then (return (i32.add (i32.const 48) (local.get $value)))))
    (i32.add (i32.const 87) (local.get $value)))

  (func $emit_bytes (param $in_ptr i32) (param $in_len i32) (param $out_ptr i32) (param $out_cap i32) (param $written i32) (result i64)
    (local $i i32)
    (local $packed i64)
    (loop $again
      (if (i32.ge_u (local.get $i) (local.get $in_len))
        (then (return (call $pack (i32.const 0) (local.get $written)))))
      (local.set $packed
        (call $m123put
          (local.get $out_ptr)
          (local.get $out_cap)
          (local.get $written)
          (call $m123byte (local.get $in_ptr) (local.get $i))))
      (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0))
        (then (return (local.get $packed))))
      (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $again))
    (call $pack (i32.const 0) (local.get $written)))

  (func $emit_literal_from_static (param $kind i32) (param $out_ptr i32) (param $out_cap i32) (result i64)
    ;; kind: 0 null, 1 false, 2 true.
    (if (i32.eq (local.get $kind) (i32.const 0))
      (then
        (i32.store8 (i32.const 16) (i32.const 110))
        (i32.store8 (i32.const 17) (i32.const 117))
        (i32.store8 (i32.const 18) (i32.const 108))
        (i32.store8 (i32.const 19) (i32.const 108))
        (return (call $emit_bytes (i32.const 16) (i32.const 4) (local.get $out_ptr) (local.get $out_cap) (i32.const 0)))))
    (if (i32.eq (local.get $kind) (i32.const 1))
      (then
        (i32.store8 (i32.const 16) (i32.const 102))
        (i32.store8 (i32.const 17) (i32.const 97))
        (i32.store8 (i32.const 18) (i32.const 108))
        (i32.store8 (i32.const 19) (i32.const 115))
        (i32.store8 (i32.const 20) (i32.const 101))
        (return (call $emit_bytes (i32.const 16) (i32.const 5) (local.get $out_ptr) (local.get $out_cap) (i32.const 0)))))
    (if (i32.eq (local.get $kind) (i32.const 2))
      (then
        (i32.store8 (i32.const 16) (i32.const 116))
        (i32.store8 (i32.const 17) (i32.const 114))
        (i32.store8 (i32.const 18) (i32.const 117))
        (i32.store8 (i32.const 19) (i32.const 101))
        (return (call $emit_bytes (i32.const 16) (i32.const 4) (local.get $out_ptr) (local.get $out_cap) (i32.const 0)))))
    (call $pack (i32.const 3) (i32.const 0)))

  (func (export "json_emit_literal") (param $kind i32) (param $out_ptr i32) (param $out_cap i32) (result i64)
    (call $emit_literal_from_static (local.get $kind) (local.get $out_ptr) (local.get $out_cap)))

  (func $emit_u64_at (param $value i64) (param $out_ptr i32) (param $out_cap i32) (param $written i32) (result i64)
    (local $div i64)
    (local $digit i64)
    (local $packed i64)
    (if (i64.eqz (local.get $value))
      (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 48)))))
    (local.set $div (i64.const 10000000000000000000))
    (block $scaled
      (loop $scale
        (br_if $scaled (i64.le_u (local.get $div) (local.get $value)))
        (local.set $div (i64.div_u (local.get $div) (i64.const 10)))
        (br $scale)))
    (loop $digits
      (local.set $digit (i64.div_u (local.get $value) (local.get $div)))
      (local.set $packed
        (call $m123put
          (local.get $out_ptr)
          (local.get $out_cap)
          (local.get $written)
          (i32.add (i32.const 48) (i32.wrap_i64 (local.get $digit)))))
      (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0))
        (then (return (local.get $packed))))
      (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
      (local.set $value (i64.rem_u (local.get $value) (local.get $div)))
      (local.set $div (i64.div_u (local.get $div) (i64.const 10)))
      (br_if $digits (i64.ne (local.get $div) (i64.const 0))))
    (call $pack (i32.const 0) (local.get $written)))

  (func (export "json_emit_u64") (param $value i64) (param $out_ptr i32) (param $out_cap i32) (result i64)
    (call $emit_u64_at (local.get $value) (local.get $out_ptr) (local.get $out_cap) (i32.const 0)))

  (func (export "json_emit_i64") (param $value i64) (param $out_ptr i32) (param $out_cap i32) (result i64)
    (local $written i32)
    (local $packed i64)
    (if (i64.lt_s (local.get $value) (i64.const 0))
      (then
        (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 45)))
        (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0))
          (then (return (local.get $packed))))
        (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
        (return (call $emit_u64_at (i64.sub (i64.const 0) (local.get $value)) (local.get $out_ptr) (local.get $out_cap) (local.get $written)))))
    (call $emit_u64_at (local.get $value) (local.get $out_ptr) (local.get $out_cap) (i32.const 0)))

  (func $emit_control_escape (param $c i32) (param $out_ptr i32) (param $out_cap i32) (param $written i32) (result i64)
    (local $packed i64)
    (if (i32.eq (local.get $c) (i32.const 8)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 98)))))
    (if (i32.eq (local.get $c) (i32.const 12)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 102)))))
    (if (i32.eq (local.get $c) (i32.const 10)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 110)))))
    (if (i32.eq (local.get $c) (i32.const 13)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 114)))))
    (if (i32.eq (local.get $c) (i32.const 9)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 116)))))
    (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 117)))
    (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 48)))
    (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 48)))
    (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (call $m123hex_digit (i32.shr_u (local.get $c) (i32.const 4)))))
    (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (call $m123hex_digit (i32.and (local.get $c) (i32.const 15)))))

  (func $json_emit_string (export "json_emit_string") (param $in_ptr i32) (param $in_len i32) (param $out_ptr i32) (param $out_cap i32) (result i64)
    (local $i i32)
    (local $c i32)
    (local $written i32)
    (local $packed i64)
    (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 34)))
    (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0))
      (then (return (local.get $packed))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (loop $again
      (if (i32.ge_u (local.get $i) (local.get $in_len))
        (then
          (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 34)))
          (return (local.get $packed))))
      (local.set $c (call $m123byte (local.get $in_ptr) (local.get $i)))
      (if (i32.eq (local.get $c) (i32.const 34))
        (then
          (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 92)))
          (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
          (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
          (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 34)))
          (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
          (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $again)))
      (if (i32.eq (local.get $c) (i32.const 92))
        (then
          (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 92)))
          (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
          (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
          (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 92)))
          (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
          (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $again)))
      (if (i32.lt_u (local.get $c) (i32.const 32))
        (then
          (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 92)))
          (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
          (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
          (local.set $packed (call $emit_control_escape (local.get $c) (local.get $out_ptr) (local.get $out_cap) (local.get $written)))
          (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0)) (then (return (local.get $packed))))
          (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $again)))
      (local.set $packed (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (local.get $c)))
      (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0))
        (then (return (local.get $packed))))
      (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $again))
    (call $pack (i32.const 0) (local.get $written)))

  (func (export "json_emit_token") (param $kind i32) (param $out_ptr i32) (param $out_cap i32) (result i64)
    ;; kind: 0 [, 1 ], 2 {, 3 }, 4 comma, 5 colon.
    (if (i32.eq (local.get $kind) (i32.const 0)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 91)))))
    (if (i32.eq (local.get $kind) (i32.const 1)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 93)))))
    (if (i32.eq (local.get $kind) (i32.const 2)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 123)))))
    (if (i32.eq (local.get $kind) (i32.const 3)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 125)))))
    (if (i32.eq (local.get $kind) (i32.const 4)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 44)))))
    (if (i32.eq (local.get $kind) (i32.const 5)) (then (return (call $m123put (local.get $out_ptr) (local.get $out_cap) (i32.const 0) (i32.const 58)))))
    (call $pack (i32.const 3) (i32.const 0)))

  (func (export "json_emit_key") (param $in_ptr i32) (param $in_len i32) (param $out_ptr i32) (param $out_cap i32) (result i64)
    (local $packed i64)
    (local $written i32)
    (local.set $packed (call $json_emit_string (local.get $in_ptr) (local.get $in_len) (local.get $out_ptr) (local.get $out_cap)))
    (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0))
      (then (return (local.get $packed))))
    (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32))))
    (call $m123put (local.get $out_ptr) (local.get $out_cap) (local.get $written) (i32.const 58)))
