  (import "edgerun" "load8_u" (func $m124byte (param i32 i32) (result i32)))

  ;; Status values: 0 ok, 1 input_short, 2 output_short, 3 invalid, 4 overflow, 5 unexpected_end.

  (func $m124is_digit_1_9 (param $c i32) (result i32)
    (i32.and
      (i32.ge_u (local.get $c) (i32.const 49))
      (i32.le_u (local.get $c) (i32.const 57))))

  (func $m124hex_value (param $c i32) (result i32)
    (if (i32.and (i32.ge_u (local.get $c) (i32.const 48)) (i32.le_u (local.get $c) (i32.const 57)))
      (then (return (i32.sub (local.get $c) (i32.const 48)))))
    (if (i32.and (i32.ge_u (local.get $c) (i32.const 65)) (i32.le_u (local.get $c) (i32.const 70)))
      (then (return (i32.add (i32.sub (local.get $c) (i32.const 65)) (i32.const 10)))))
    (if (i32.and (i32.ge_u (local.get $c) (i32.const 97)) (i32.le_u (local.get $c) (i32.const 102)))
      (then (return (i32.add (i32.sub (local.get $c) (i32.const 97)) (i32.const 10)))))
    (i32.const -1))

  (func $read_hex_quad (param $ptr i32) (param $len i32) (param $off i32) (param $out_ptr i32) (result i32)
    (local $i i32)
    (local $d i32)
    (local $value i32)
    (if (i32.gt_u (i32.add (local.get $off) (i32.const 4)) (local.get $len))
      (then (return (i32.const 5))))
    (loop $again
      (local.set $d (call $m124hex_value (call $m124byte (local.get $ptr) (i32.add (local.get $off) (local.get $i)))))
      (if (i32.lt_s (local.get $d) (i32.const 0))
        (then (return (i32.const 3))))
      (local.set $value (i32.or (i32.shl (local.get $value) (i32.const 4)) (local.get $d)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $again (i32.lt_u (local.get $i) (i32.const 4))))
    (i32.store (local.get $out_ptr) (local.get $value))
    (i32.const 0))

  (func $valid_escape (param $c i32) (result i32)
    (i32.or
      (i32.or
        (i32.or (i32.eq (local.get $c) (i32.const 34)) (i32.eq (local.get $c) (i32.const 92)))
        (i32.or (i32.eq (local.get $c) (i32.const 47)) (i32.eq (local.get $c) (i32.const 98))))
      (i32.or
        (i32.or (i32.eq (local.get $c) (i32.const 102)) (i32.eq (local.get $c) (i32.const 110)))
        (i32.or (i32.eq (local.get $c) (i32.const 114)) (i32.eq (local.get $c) (i32.const 116))))))

  (func $json_scan_string_strict (export "json_scan_string_strict") (param $ptr i32) (param $len i32) (param $offset i32) (result i64)
    (local $p i32)
    (local $c i32)
    (local $esc i32)
    (local $scalar i32)
    (local $low i32)
    (if (i32.ge_u (local.get $offset) (local.get $len))
      (then (return (call $pack (i32.const 1) (local.get $offset)))))
    (if (i32.ne (call $m124byte (local.get $ptr) (local.get $offset)) (i32.const 34))
      (then (return (call $pack (i32.const 3) (local.get $offset)))))
    (local.set $p (i32.add (local.get $offset) (i32.const 1)))
    (block $done
      (loop $again
        (if (i32.ge_u (local.get $p) (local.get $len))
          (then (return (call $pack (i32.const 5) (local.get $len)))))
        (local.set $c (call $m124byte (local.get $ptr) (local.get $p)))
        (if (i32.eq (local.get $c) (i32.const 34))
          (then (return (call $pack (i32.const 0) (i32.add (local.get $p) (i32.const 1))))))
        (if (i32.lt_u (local.get $c) (i32.const 32))
          (then (return (call $pack (i32.const 3) (local.get $p)))))
        (if (i32.eq (local.get $c) (i32.const 92))
          (then
            (local.set $esc (local.get $p))
            (local.set $p (i32.add (local.get $p) (i32.const 1)))
            (if (i32.ge_u (local.get $p) (local.get $len))
              (then (return (call $pack (i32.const 5) (local.get $len)))))
            (local.set $c (call $m124byte (local.get $ptr) (local.get $p)))
            (if (i32.eq (local.get $c) (i32.const 117))
              (then
                (if (call $read_hex_quad (local.get $ptr) (local.get $len) (i32.add (local.get $p) (i32.const 1)) (i32.const 0))
                  (then (return (call $pack (i32.const 3) (local.get $esc)))))
                (local.set $scalar (i32.load (i32.const 0)))
                (local.set $p (i32.add (local.get $p) (i32.const 5)))
                (if (i32.and (i32.ge_u (local.get $scalar) (i32.const 55296)) (i32.le_u (local.get $scalar) (i32.const 56319)))
                  (then
                    (if (i32.gt_u (i32.add (local.get $p) (i32.const 6)) (local.get $len))
                      (then (return (call $pack (i32.const 3) (local.get $esc)))))
                    (if (i32.or
                          (i32.ne (call $m124byte (local.get $ptr) (local.get $p)) (i32.const 92))
                          (i32.ne (call $m124byte (local.get $ptr) (i32.add (local.get $p) (i32.const 1))) (i32.const 117)))
                      (then (return (call $pack (i32.const 3) (local.get $esc)))))
                    (if (call $read_hex_quad (local.get $ptr) (local.get $len) (i32.add (local.get $p) (i32.const 2)) (i32.const 0))
                      (then (return (call $pack (i32.const 3) (local.get $esc)))))
                    (local.set $low (i32.load (i32.const 0)))
                    (if (i32.eqz (i32.and (i32.ge_u (local.get $low) (i32.const 56320)) (i32.le_u (local.get $low) (i32.const 57343))))
                      (then (return (call $pack (i32.const 3) (local.get $esc)))))
                    (local.set $p (i32.add (local.get $p) (i32.const 6)))))
                (if (i32.and (i32.ge_u (local.get $scalar) (i32.const 56320)) (i32.le_u (local.get $scalar) (i32.const 57343)))
                  (then (return (call $pack (i32.const 3) (local.get $esc))))))
              (else
                (if (i32.eqz (call $valid_escape (local.get $c)))
                  (then (return (call $pack (i32.const 3) (local.get $esc)))))
                (local.set $p (i32.add (local.get $p) (i32.const 1))))))
          (else
            (local.set $p (i32.add (local.get $p) (i32.const 1)))))
        (br $again)))
    (call $pack (i32.const 5) (local.get $len)))

  (func $write_utf8 (param $cp i32) (param $out_ptr i32) (param $out_cap i32) (param $written i32) (result i64)
    (if (i32.le_u (local.get $cp) (i32.const 127))
      (then
        (if (i32.ge_u (local.get $written) (local.get $out_cap))
          (then (return (call $pack (i32.const 2) (local.get $written)))))
        (i32.store8 (i32.add (local.get $out_ptr) (local.get $written)) (local.get $cp))
        (return (call $pack (i32.const 0) (i32.add (local.get $written) (i32.const 1))))))
    (if (i32.le_u (local.get $cp) (i32.const 2047))
      (then
        (if (i32.gt_u (i32.add (local.get $written) (i32.const 2)) (local.get $out_cap))
          (then (return (call $pack (i32.const 2) (local.get $written)))))
        (i32.store8 (i32.add (local.get $out_ptr) (local.get $written)) (i32.or (i32.const 192) (i32.shr_u (local.get $cp) (i32.const 6))))
        (i32.store8 (i32.add (local.get $out_ptr) (i32.add (local.get $written) (i32.const 1))) (i32.or (i32.const 128) (i32.and (local.get $cp) (i32.const 63))))
        (return (call $pack (i32.const 0) (i32.add (local.get $written) (i32.const 2))))))
    (if (i32.le_u (local.get $cp) (i32.const 65535))
      (then
        (if (i32.gt_u (i32.add (local.get $written) (i32.const 3)) (local.get $out_cap))
          (then (return (call $pack (i32.const 2) (local.get $written)))))
        (i32.store8 (i32.add (local.get $out_ptr) (local.get $written)) (i32.or (i32.const 224) (i32.shr_u (local.get $cp) (i32.const 12))))
        (i32.store8 (i32.add (local.get $out_ptr) (i32.add (local.get $written) (i32.const 1))) (i32.or (i32.const 128) (i32.and (i32.shr_u (local.get $cp) (i32.const 6)) (i32.const 63))))
        (i32.store8 (i32.add (local.get $out_ptr) (i32.add (local.get $written) (i32.const 2))) (i32.or (i32.const 128) (i32.and (local.get $cp) (i32.const 63))))
        (return (call $pack (i32.const 0) (i32.add (local.get $written) (i32.const 3))))))
    (if (i32.gt_u (i32.add (local.get $written) (i32.const 4)) (local.get $out_cap))
      (then (return (call $pack (i32.const 2) (local.get $written)))))
    (i32.store8 (i32.add (local.get $out_ptr) (local.get $written)) (i32.or (i32.const 240) (i32.shr_u (local.get $cp) (i32.const 18))))
    (i32.store8 (i32.add (local.get $out_ptr) (i32.add (local.get $written) (i32.const 1))) (i32.or (i32.const 128) (i32.and (i32.shr_u (local.get $cp) (i32.const 12)) (i32.const 63))))
    (i32.store8 (i32.add (local.get $out_ptr) (i32.add (local.get $written) (i32.const 2))) (i32.or (i32.const 128) (i32.and (i32.shr_u (local.get $cp) (i32.const 6)) (i32.const 63))))
    (i32.store8 (i32.add (local.get $out_ptr) (i32.add (local.get $written) (i32.const 3))) (i32.or (i32.const 128) (i32.and (local.get $cp) (i32.const 63))))
    (call $pack (i32.const 0) (i32.add (local.get $written) (i32.const 4))))

  (func (export "json_unescape_string") (param $in_ptr i32) (param $in_len i32) (param $out_ptr i32) (param $out_cap i32) (result i64)
    (local $scan i64)
    (local $p i32)
    (local $end i32)
    (local $c i32)
    (local $written i32)
    (local $scalar i32)
    (local $low i32)
    (local $packed i64)
    (local.set $scan (call $json_scan_string_strict (local.get $in_ptr) (local.get $in_len) (i32.const 0)))
    (if (i32.ne (i32.wrap_i64 (local.get $scan)) (i32.const 0))
      (then (return (local.get $scan))))
    (local.set $end (i32.sub (i32.wrap_i64 (i64.shr_u (local.get $scan) (i64.const 32))) (i32.const 1)))
    (local.set $p (i32.const 1))
    (loop $again
      (if (i32.ge_u (local.get $p) (local.get $end))
        (then (return (call $pack (i32.const 0) (local.get $written)))))
      (local.set $c (call $m124byte (local.get $in_ptr) (local.get $p)))
      (if (i32.eq (local.get $c) (i32.const 92))
        (then
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (local.set $c (call $m124byte (local.get $in_ptr) (local.get $p)))
          (if (i32.eq (local.get $c) (i32.const 117))
            (then
              (drop (call $read_hex_quad (local.get $in_ptr) (local.get $in_len) (i32.add (local.get $p) (i32.const 1)) (i32.const 0)))
              (local.set $scalar (i32.load (i32.const 0)))
              (local.set $p (i32.add (local.get $p) (i32.const 5)))
              (if (i32.and (i32.ge_u (local.get $scalar) (i32.const 55296)) (i32.le_u (local.get $scalar) (i32.const 56319)))
                (then
                  (drop (call $read_hex_quad (local.get $in_ptr) (local.get $in_len) (i32.add (local.get $p) (i32.const 2)) (i32.const 0)))
                  (local.set $low (i32.load (i32.const 0)))
                  (local.set $scalar
                    (i32.add
                      (i32.const 65536)
                      (i32.or
                        (i32.shl (i32.sub (local.get $scalar) (i32.const 55296)) (i32.const 10))
                        (i32.sub (local.get $low) (i32.const 56320)))))
                  (local.set $p (i32.add (local.get $p) (i32.const 6)))))
              (local.set $packed (call $write_utf8 (local.get $scalar) (local.get $out_ptr) (local.get $out_cap) (local.get $written)))
              (if (i32.ne (i32.wrap_i64 (local.get $packed)) (i32.const 0))
                (then (return (local.get $packed))))
              (local.set $written (i32.wrap_i64 (i64.shr_u (local.get $packed) (i64.const 32)))))
            (else
              (if (i32.eq (local.get $c) (i32.const 34)) (then (local.set $c (i32.const 34))))
              (if (i32.eq (local.get $c) (i32.const 92)) (then (local.set $c (i32.const 92))))
              (if (i32.eq (local.get $c) (i32.const 47)) (then (local.set $c (i32.const 47))))
              (if (i32.eq (local.get $c) (i32.const 98)) (then (local.set $c (i32.const 8))))
              (if (i32.eq (local.get $c) (i32.const 102)) (then (local.set $c (i32.const 12))))
              (if (i32.eq (local.get $c) (i32.const 110)) (then (local.set $c (i32.const 10))))
              (if (i32.eq (local.get $c) (i32.const 114)) (then (local.set $c (i32.const 13))))
              (if (i32.eq (local.get $c) (i32.const 116)) (then (local.set $c (i32.const 9))))
              (if (i32.ge_u (local.get $written) (local.get $out_cap))
                (then (return (call $pack (i32.const 2) (local.get $written)))))
              (i32.store8 (i32.add (local.get $out_ptr) (local.get $written)) (local.get $c))
              (local.set $written (i32.add (local.get $written) (i32.const 1)))
              (local.set $p (i32.add (local.get $p) (i32.const 1))))))
        (else
          (if (i32.ge_u (local.get $written) (local.get $out_cap))
            (then (return (call $pack (i32.const 2) (local.get $written)))))
          (i32.store8 (i32.add (local.get $out_ptr) (local.get $written)) (local.get $c))
          (local.set $written (i32.add (local.get $written) (i32.const 1)))
          (local.set $p (i32.add (local.get $p) (i32.const 1)))))
      (br $again))
    (call $pack (i32.const 0) (local.get $written)))

  (func (export "json_scan_number_strict") (param $ptr i32) (param $len i32) (param $offset i32) (result i64)
    (local $p i32)
    (local $c i32)
    (if (i32.ge_u (local.get $offset) (local.get $len))
      (then (return (call $pack (i32.const 1) (local.get $offset)))))
    (local.set $p (local.get $offset))
    (if (i32.eq (call $m124byte (local.get $ptr) (local.get $p)) (i32.const 45))
      (then
        (local.set $p (i32.add (local.get $p) (i32.const 1)))
        (if (i32.ge_u (local.get $p) (local.get $len))
          (then (return (call $pack (i32.const 5) (local.get $p)))))))
    (local.set $c (call $m124byte (local.get $ptr) (local.get $p)))
    (if (i32.eq (local.get $c) (i32.const 48))
      (then
        (local.set $p (i32.add (local.get $p) (i32.const 1)))
        (if (i32.and (i32.lt_u (local.get $p) (local.get $len)) (call $is_digit (call $m124byte (local.get $ptr) (local.get $p))))
          (then (return (call $pack (i32.const 3) (local.get $offset))))))
      (else
        (if (i32.eqz (call $m124is_digit_1_9 (local.get $c)))
          (then (return (call $pack (i32.const 3) (local.get $offset)))))
        (loop $digits
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (br_if $digits
            (i32.and (i32.lt_u (local.get $p) (local.get $len)) (call $is_digit (call $m124byte (local.get $ptr) (local.get $p))))))))
    (if (i32.and (i32.lt_u (local.get $p) (local.get $len)) (i32.eq (call $m124byte (local.get $ptr) (local.get $p)) (i32.const 46)))
      (then
        (local.set $p (i32.add (local.get $p) (i32.const 1)))
        (if (i32.or (i32.ge_u (local.get $p) (local.get $len)) (i32.eqz (call $is_digit (call $m124byte (local.get $ptr) (local.get $p)))))
          (then (return (call $pack (i32.const 3) (local.get $offset)))))
        (loop $frac
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (br_if $frac
            (i32.and (i32.lt_u (local.get $p) (local.get $len)) (call $is_digit (call $m124byte (local.get $ptr) (local.get $p))))))))
    (if (i32.and
          (i32.lt_u (local.get $p) (local.get $len))
          (i32.or (i32.eq (call $m124byte (local.get $ptr) (local.get $p)) (i32.const 101)) (i32.eq (call $m124byte (local.get $ptr) (local.get $p)) (i32.const 69))))
      (then
        (local.set $p (i32.add (local.get $p) (i32.const 1)))
        (if (i32.and
              (i32.lt_u (local.get $p) (local.get $len))
              (i32.or (i32.eq (call $m124byte (local.get $ptr) (local.get $p)) (i32.const 43)) (i32.eq (call $m124byte (local.get $ptr) (local.get $p)) (i32.const 45))))
          (then (local.set $p (i32.add (local.get $p) (i32.const 1)))))
        (if (i32.or (i32.ge_u (local.get $p) (local.get $len)) (i32.eqz (call $is_digit (call $m124byte (local.get $ptr) (local.get $p)))))
          (then (return (call $pack (i32.const 3) (local.get $offset)))))
        (loop $exp
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (br_if $exp
            (i32.and (i32.lt_u (local.get $p) (local.get $len)) (call $is_digit (call $m124byte (local.get $ptr) (local.get $p))))))))
    (call $pack (i32.const 0) (local.get $p)))

  (func (export "json_parse_u64") (param $ptr i32) (param $len i32) (param $out_ptr i32) (result i32)
    (local $i i32)
    (local $c i32)
    (local $value i64)
    (local $digit i64)
    (if (i32.eqz (local.get $len)) (then (return (i32.const 1))))
    (if (i32.and (i32.gt_u (local.get $len) (i32.const 1)) (i32.eq (call $m124byte (local.get $ptr) (i32.const 0)) (i32.const 48)))
      (then (return (i32.const 3))))
    (loop $again
      (if (i32.ge_u (local.get $i) (local.get $len))
        (then (i64.store (local.get $out_ptr) (local.get $value)) (return (i32.const 0))))
      (local.set $c (call $m124byte (local.get $ptr) (local.get $i)))
      (if (i32.eqz (call $is_digit (local.get $c))) (then (return (i32.const 3))))
      (local.set $digit (i64.extend_i32_u (i32.sub (local.get $c) (i32.const 48))))
      (if (i64.gt_u (local.get $value) (i64.const 1844674407370955161))
        (then (return (i32.const 4))))
      (local.set $value (i64.mul (local.get $value) (i64.const 10)))
      (if (i64.gt_u (local.get $value) (i64.sub (i64.const -1) (local.get $digit)))
        (then (return (i32.const 4))))
      (local.set $value (i64.add (local.get $value) (local.get $digit)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $again))
    (i32.const 5))

  (func (export "json_parse_i64") (param $ptr i32) (param $len i32) (param $out_ptr i32) (result i32)
    (local $i i32)
    (local $neg i32)
    (local $c i32)
    (local $value i64)
    (local $limit i64)
    (local $digit i64)
    (if (i32.eqz (local.get $len)) (then (return (i32.const 1))))
    (local.set $limit (i64.const 9223372036854775807))
    (if (i32.eq (call $m124byte (local.get $ptr) (i32.const 0)) (i32.const 45))
      (then
        (local.set $neg (i32.const 1))
        (local.set $i (i32.const 1))
    (local.set $limit (i64.const -9223372036854775808))
        (if (i32.eq (local.get $len) (i32.const 1)) (then (return (i32.const 3)))))
      (else
        (if (i32.eq (call $m124byte (local.get $ptr) (i32.const 0)) (i32.const 43))
          (then (return (i32.const 3))))))
    (if (i32.and
          (i32.gt_u (i32.sub (local.get $len) (local.get $i)) (i32.const 1))
          (i32.eq (call $m124byte (local.get $ptr) (local.get $i)) (i32.const 48)))
      (then (return (i32.const 3))))
    (loop $again
      (if (i32.ge_u (local.get $i) (local.get $len))
        (then
          (if (local.get $neg)
            (then (i64.store (local.get $out_ptr) (i64.sub (i64.const 0) (local.get $value))))
            (else (i64.store (local.get $out_ptr) (local.get $value))))
          (return (i32.const 0))))
      (local.set $c (call $m124byte (local.get $ptr) (local.get $i)))
      (if (i32.eqz (call $is_digit (local.get $c))) (then (return (i32.const 3))))
      (local.set $digit (i64.extend_i32_u (i32.sub (local.get $c) (i32.const 48))))
      (if (i64.gt_u (local.get $value) (i64.div_u (local.get $limit) (i64.const 10)))
        (then (return (i32.const 4))))
      (local.set $value (i64.mul (local.get $value) (i64.const 10)))
      (if (i64.gt_u (local.get $value) (i64.sub (local.get $limit) (local.get $digit)))
        (then (return (i32.const 4))))
      (local.set $value (i64.add (local.get $value) (local.get $digit)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $again))
    (i32.const 5))
