[package]
name = "futures-macro"
version = "0.3.32"
edition = "2018"
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned futures procedural macro compatibility crate"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { path = "../edgerun-proc-macro2" }
quote = { path = "../edgerun-quote" }
syn = { path = "../edgerun-syn", features = ["full"] }

[lints]
workspace = true
