[package]
name = "edgerun-unikernel"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun unikernel - bare-metal bootable"
build = "build.rs"

[features]
default = []
html-ui = []
esp32s3-ble = ["edgerun-platform/esp32s3-ble"]
esp32s3-ble-blob = ["edgerun-platform/esp32s3-ble-blob", "esp32s3-ble"]
esp32s3-ble-stub = ["edgerun-platform/esp32s3-ble-stub", "esp32s3-ble"]
esp32s3-headless = []
esp32s3-wifi-mmio = ["edgerun-platform/esp32s3-wifi-mmio"]
esp32s3-wifi-blob = ["edgerun-platform/esp32s3-wifi-blob"]
esp32s3-wifi-phy-probe = ["esp32s3-wifi-blob", "edgerun-platform/esp32s3-wifi-phy-probe"]
esp32s3-wifi-ram-phy-patch = ["esp32s3-wifi-blob", "edgerun-platform/esp32s3-wifi-ram-phy-patch"]

[dependencies]
edgerun-devices.workspace = true
edgerun-platform = { version = "0.1", path = "../edgerun-platform" }
edgerun-node = { version = "0.1", path = "../node/edgerun-node", default-features = false, features = ["http"] }
edgerun-protocols = { workspace = true, default-features = false, features = ["dhcp", "ethernet-ipv4", "tftp", "wifi"] }
edgerun-encoding = { workspace = true, default-features = false }
edgerun-tpm = { version = "0.1", path = "../identity/edgerun-tpm", default-features = false }
edgerun-crypto = { version = "0.1", path = "../utility/edgerun-crypto", default-features = false }
edgerun-oci = { version = "0.1", path = "../edgerun-oci", default-features = false, features = ["registry-client", "edgefs"] }
edgerun-edgefs = { version = "0.1", path = "../authority/edgerun-edgefs" }
edgerun-storage = { version = "0.1", path = "../authority/edgerun-storage" }
edgerun-capabilities = { version = "0.1", path = "../capability/edgerun-capabilities" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
edgerun-virtio = { version = "0.1", path = "../edgerun-virtio" }
edgerun-rtl8125 = { version = "0.1", path = "../edgerun-rtl8125" }
edgerun-event = { version = "0.1", path = "../edgerun-event", features = ["virtio"] }

[target.'cfg(target_arch = "xtensa")'.dependencies]

[lints]
workspace = true
