[package]
name = "edgerun-term-compositor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "edgerun-term-compositor"
path = "src/main.rs"

[dependencies]
edgerun-compositor.workspace = true
edgerun-protocols = { workspace = true, default-features = false, features = ["wayland"] }
edgerun-pty.workspace = true
edgerun-terminal-parser.workspace = true
edgerun-term-core.workspace = true
