[package]
name = "edgerun-linux-netif"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Linux network interface adapter for Edgerun"

[dependencies]
edgerun-capabilities = { version = "0.1", path = "../capability/edgerun-capabilities" }
edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }
edgerun-network-interface = { version = "0.1", path = "../edgerun-network-interface" }

[[bin]]
name = "linux-netif-tool"
path = "src/bin/linux-netif-tool.rs"
required-features = ["std"]

[lints]
workspace = true

[features]
std = []
