[package]
name = "zen-client"
version = "0.1.0"
edition = "2021"

[dependencies]
edgerun-http = { workspace = true, features = ["client", "tls"] }
edgerun-json = { workspace = true }
edgerun-rt = { workspace = true }
edgerun-edit = { workspace = true, features = ["std"], optional = true }

[features]
default = []
ast-edit = ["dep:edgerun-edit"]
