[package]
name = "edgerun-tokio-macros"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/edgerun-tech/edgerun"
homepage = "https://github.com/edgerun-tech/edgerun"
description = "EdgeRun-owned Tokio-compatible proc macros"

[lib]
proc-macro = true

[dependencies]

