[package]
name = "edgerun-linux-cec"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Linux HDMI-CEC adapter for Edgerun"
autobins = false

[dependencies]
edgerun-devices.workspace = true
edgerun-capabilities = { version = "0.1", path = "../../capability/edgerun-capabilities" }
edgerun-linux-gpu = { version = "0.1", path = "../edgerun-linux-gpu" }
edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }
edgerun-encoding = { version = "0.1", path = "../../utility/edgerun-encoding" }

[features]
std = []

[lints]
workspace = true
