[package]
name = "edgerun-linux-netif"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Linux network interface adapter for Edgerun"
autobins = false

[dependencies]
edgerun-devices.workspace = true
edgerun-capabilities = { workspace = true }
edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }

[lints]
workspace = true

[features]
std = []
