//! ECMAScript Well-Known Symbols and Intrinsics — ECMA-262.
//! DO NOT EDIT. Regenerate with: scripts/generate_browser.py

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WellKnownSymbol {
    Asynciterator,
    Hasinstance,
    Isconcatspreadable,
    Iterator,
    Match,
    Matchall,
    Name,
    Replace,
    Search,
    Species,
    Split,
    Toprimitive,
    Tostringtag,
    Unscopables,
}

impl WellKnownSymbol {
    pub fn description(&self) -> &'static str {
        match self {
            WellKnownSymbol::Asynciterator => "Symbol.asyncIterator",
            WellKnownSymbol::Hasinstance => "Symbol.hasInstance",
            WellKnownSymbol::Isconcatspreadable => "Symbol.isConcatSpreadable",
            WellKnownSymbol::Iterator => "Symbol.iterator",
            WellKnownSymbol::Match => "Symbol.match",
            WellKnownSymbol::Matchall => "Symbol.matchAll",
            WellKnownSymbol::Name => "Symbol.name",
            WellKnownSymbol::Replace => "Symbol.replace",
            WellKnownSymbol::Search => "Symbol.search",
            WellKnownSymbol::Species => "Symbol.species",
            WellKnownSymbol::Split => "Symbol.split",
            WellKnownSymbol::Toprimitive => "Symbol.toPrimitive",
            WellKnownSymbol::Tostringtag => "Symbol.toStringTag",
            WellKnownSymbol::Unscopables => "Symbol.unscopables",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IntrinsicId {
    Aggregateerror = 1,
    AggregateerrorPrototype = 2,
    Array = 3,
    ArrayPrototype = 4,
    ArrayPrototypeTostring = 5,
    ArrayPrototypeValues = 6,
    Arraybuffer = 7,
    ArraybufferPrototype = 8,
    Arrayiteratorprototype = 9,
    Asyncfromsynciteratorprototype = 10,
    Asyncfunction = 11,
    AsyncfunctionPrototype = 12,
    Asyncgeneratorfunction = 13,
    AsyncgeneratorfunctionPrototype = 14,
    AsyncgeneratorfunctionPrototypePrototype = 15,
    Asyncgeneratorprototype = 16,
    Asynciteratorprototype = 17,
    Atomics = 18,
    Bigint = 19,
    BigintPrototype = 20,
    Bigint64array = 21,
    Biguint64array = 22,
    Boolean = 23,
    BooleanPrototype = 24,
    Dataview = 25,
    DataviewPrototype = 26,
    Date = 27,
    DatePrototype = 28,
    DatePrototypeToutcstring = 29,
    Error = 30,
    ErrorPrototype = 31,
    Evalerror = 32,
    EvalerrorPrototype = 33,
    Finalizationregistry = 34,
    FinalizationregistryPrototype = 35,
    Float16array = 36,
    Float32array = 37,
    Float64array = 38,
    Foriniteratorprototype = 39,
    Function = 40,
    FunctionPrototype = 41,
    Generatorfunction = 42,
    GeneratorfunctionPrototype = 43,
    GeneratorfunctionPrototypePrototype = 44,
    Generatorprototype = 45,
    GeneratorprototypeNext = 46,
    Int16array = 47,
    Int32array = 48,
    Int8array = 49,
    Iterator = 50,
    IteratorPrototype = 51,
    Iteratorhelperprototype = 52,
    Json = 53,
    Map = 54,
    MapPrototype = 55,
    MapPrototypeEntries = 56,
    Mapiteratorprototype = 57,
    Math = 58,
    Number = 59,
    NumberPrototype = 60,
}

impl IntrinsicId {
    pub fn name(&self) -> &'static str {
        match self {
            IntrinsicId::Aggregateerror => "%AggregateError%",
            IntrinsicId::AggregateerrorPrototype => "%AggregateError.prototype%",
            IntrinsicId::Array => "%Array%",
            IntrinsicId::ArrayPrototype => "%Array.prototype%",
            IntrinsicId::ArrayPrototypeTostring => "%Array.prototype.toString%",
            IntrinsicId::ArrayPrototypeValues => "%Array.prototype.values%",
            IntrinsicId::Arraybuffer => "%ArrayBuffer%",
            IntrinsicId::ArraybufferPrototype => "%ArrayBuffer.prototype%",
            IntrinsicId::Arrayiteratorprototype => "%ArrayIteratorPrototype%",
            IntrinsicId::Asyncfromsynciteratorprototype => "%AsyncFromSyncIteratorPrototype%",
            IntrinsicId::Asyncfunction => "%AsyncFunction%",
            IntrinsicId::AsyncfunctionPrototype => "%AsyncFunction.prototype%",
            IntrinsicId::Asyncgeneratorfunction => "%AsyncGeneratorFunction%",
            IntrinsicId::AsyncgeneratorfunctionPrototype => "%AsyncGeneratorFunction.prototype%",
            IntrinsicId::AsyncgeneratorfunctionPrototypePrototype => "%AsyncGeneratorFunction.prototype.prototype%",
            IntrinsicId::Asyncgeneratorprototype => "%AsyncGeneratorPrototype%",
            IntrinsicId::Asynciteratorprototype => "%AsyncIteratorPrototype%",
            IntrinsicId::Atomics => "%Atomics%",
            IntrinsicId::Bigint => "%BigInt%",
            IntrinsicId::BigintPrototype => "%BigInt.prototype%",
            IntrinsicId::Bigint64array => "%BigInt64Array%",
            IntrinsicId::Biguint64array => "%BigUint64Array%",
            IntrinsicId::Boolean => "%Boolean%",
            IntrinsicId::BooleanPrototype => "%Boolean.prototype%",
            IntrinsicId::Dataview => "%DataView%",
            IntrinsicId::DataviewPrototype => "%DataView.prototype%",
            IntrinsicId::Date => "%Date%",
            IntrinsicId::DatePrototype => "%Date.prototype%",
            IntrinsicId::DatePrototypeToutcstring => "%Date.prototype.toUTCString%",
            IntrinsicId::Error => "%Error%",
            IntrinsicId::ErrorPrototype => "%Error.prototype%",
            IntrinsicId::Evalerror => "%EvalError%",
            IntrinsicId::EvalerrorPrototype => "%EvalError.prototype%",
            IntrinsicId::Finalizationregistry => "%FinalizationRegistry%",
            IntrinsicId::FinalizationregistryPrototype => "%FinalizationRegistry.prototype%",
            IntrinsicId::Float16array => "%Float16Array%",
            IntrinsicId::Float32array => "%Float32Array%",
            IntrinsicId::Float64array => "%Float64Array%",
            IntrinsicId::Foriniteratorprototype => "%ForInIteratorPrototype%",
            IntrinsicId::Function => "%Function%",
            IntrinsicId::FunctionPrototype => "%Function.prototype%",
            IntrinsicId::Generatorfunction => "%GeneratorFunction%",
            IntrinsicId::GeneratorfunctionPrototype => "%GeneratorFunction.prototype%",
            IntrinsicId::GeneratorfunctionPrototypePrototype => "%GeneratorFunction.prototype.prototype%",
            IntrinsicId::Generatorprototype => "%GeneratorPrototype%",
            IntrinsicId::GeneratorprototypeNext => "%GeneratorPrototype.next%",
            IntrinsicId::Int16array => "%Int16Array%",
            IntrinsicId::Int32array => "%Int32Array%",
            IntrinsicId::Int8array => "%Int8Array%",
            IntrinsicId::Iterator => "%Iterator%",
            IntrinsicId::IteratorPrototype => "%Iterator.prototype%",
            IntrinsicId::Iteratorhelperprototype => "%IteratorHelperPrototype%",
            IntrinsicId::Json => "%JSON%",
            IntrinsicId::Map => "%Map%",
            IntrinsicId::MapPrototype => "%Map.prototype%",
            IntrinsicId::MapPrototypeEntries => "%Map.prototype.entries%",
            IntrinsicId::Mapiteratorprototype => "%MapIteratorPrototype%",
            IntrinsicId::Math => "%Math%",
            IntrinsicId::Number => "%Number%",
            IntrinsicId::NumberPrototype => "%Number.prototype%",
        }
    }
}