//! CSS Color types — from CSS Color Level 4 specification.
//! DO NOT EDIT. Regenerate with: scripts/generate_web_platform2.py
#![cfg_attr(not(test), no_std)]

extern crate alloc;
use alloc::{string::String, vec::Vec};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorSpace {
    /// sRGB (default web)
    Srgb,
    /// Linear sRGB
    SrgbLinear,
    /// Display P3 (wide gamut)
    DisplayP3,
    /// Adobe RGB (1998)
    A98Rgb,
    /// ProPhoto RGB
    ProphotoRgb,
    /// ITU-R Rec. 2020
    Rec2020,
    /// CIE XYZ (D50 white point)
    Xyz,
    /// CIE Lab
    Lab,
    /// CIE LCh
    Lch,
    /// OK Lab
    Oklab,
    /// OK LCh
    Oklch,
    /// CIE XYZ D50
    XyzD50,
    /// CIE XYZ D65
    XyzD65,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NamedColor {
    Aliceblue,
    Antiquewhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    Blanchedalmond,
    Blue,
    Blueviolet,
    Brown,
    Burlywood,
    Cadetblue,
    Chartreuse,
    Chocolate,
    Coral,
    Cornflowerblue,
    Cornsilk,
    Crimson,
    Cyan,
    Darkblue,
    Darkcyan,
    Darkgoldenrod,
    Darkgray,
    Darkgreen,
    Darkgrey,
    Darkkhaki,
    Darkmagenta,
    Darkolivegreen,
    Darkorange,
    Darkorchid,
    Darkred,
    Darksalmon,
    Darkseagreen,
    Darkslateblue,
    Darkslategray,
    Darkslategrey,
    Darkturquoise,
    Darkviolet,
    Deeppink,
    Deepskyblue,
    Dimgray,
    Dimgrey,
    Dodgerblue,
    Firebrick,
    Floralwhite,
    Forestgreen,
    Fuchsia,
    Gainsboro,
    Ghostwhite,
    Gold,
    Goldenrod,
    Gray,
    Green,
    Greenyellow,
    Grey,
    Honeydew,
    Hotpink,
    Indianred,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    Lavenderblush,
    Lawngreen,
    Lemonchiffon,
    Lightblue,
    Lightcoral,
    Lightcyan,
    Lightgoldenrodyellow,
    Lightgray,
    Lightgreen,
    Lightgrey,
    Lightpink,
    Lightsalmon,
    Lightseagreen,
    Lightskyblue,
    Lightslategray,
    Lightslategrey,
    Lightsteelblue,
    Lightyellow,
    Lime,
    Limegreen,
    Linen,
    Magenta,
    Maroon,
    Mediumaquamarine,
    Mediumblue,
    Mediumorchid,
    Mediumpurple,
    Mediumseagreen,
    Mediumslateblue,
    Mediumspringgreen,
    Mediumturquoise,
    Mediumvioletred,
    Midnightblue,
    Mintcream,
    Mistyrose,
    Moccasin,
    Navajowhite,
    Navy,
    Oldlace,
    Olive,
    Olivedrab,
    Orange,
    Orangered,
    Orchid,
    Palegoldenrod,
    Palegreen,
    Paleturquoise,
    Palevioletred,
    Papayawhip,
    Peachpuff,
    Peru,
    Pink,
    Plum,
    Powderblue,
    Purple,
    Rebeccapurple,
    Red,
    Rosybrown,
    Royalblue,
    Saddlebrown,
    Salmon,
    Sandybrown,
    Seagreen,
    Seashell,
    Sienna,
    Silver,
    Skyblue,
    Slateblue,
    Slategray,
    Slategrey,
    Snow,
    Springgreen,
    Steelblue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    Whitesmoke,
    Yellow,
    Yellowgreen,
}

impl NamedColor {
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "aliceblue" => Some(NamedColor::Aliceblue),
            "antiquewhite" => Some(NamedColor::Antiquewhite),
            "aqua" => Some(NamedColor::Aqua),
            "aquamarine" => Some(NamedColor::Aquamarine),
            "azure" => Some(NamedColor::Azure),
            "beige" => Some(NamedColor::Beige),
            "bisque" => Some(NamedColor::Bisque),
            "black" => Some(NamedColor::Black),
            "blanchedalmond" => Some(NamedColor::Blanchedalmond),
            "blue" => Some(NamedColor::Blue),
            "blueviolet" => Some(NamedColor::Blueviolet),
            "brown" => Some(NamedColor::Brown),
            "burlywood" => Some(NamedColor::Burlywood),
            "cadetblue" => Some(NamedColor::Cadetblue),
            "chartreuse" => Some(NamedColor::Chartreuse),
            "chocolate" => Some(NamedColor::Chocolate),
            "coral" => Some(NamedColor::Coral),
            "cornflowerblue" => Some(NamedColor::Cornflowerblue),
            "cornsilk" => Some(NamedColor::Cornsilk),
            "crimson" => Some(NamedColor::Crimson),
            "cyan" => Some(NamedColor::Cyan),
            "darkblue" => Some(NamedColor::Darkblue),
            "darkcyan" => Some(NamedColor::Darkcyan),
            "darkgoldenrod" => Some(NamedColor::Darkgoldenrod),
            "darkgray" => Some(NamedColor::Darkgray),
            "darkgreen" => Some(NamedColor::Darkgreen),
            "darkgrey" => Some(NamedColor::Darkgrey),
            "darkkhaki" => Some(NamedColor::Darkkhaki),
            "darkmagenta" => Some(NamedColor::Darkmagenta),
            "darkolivegreen" => Some(NamedColor::Darkolivegreen),
            "darkorange" => Some(NamedColor::Darkorange),
            "darkorchid" => Some(NamedColor::Darkorchid),
            "darkred" => Some(NamedColor::Darkred),
            "darksalmon" => Some(NamedColor::Darksalmon),
            "darkseagreen" => Some(NamedColor::Darkseagreen),
            "darkslateblue" => Some(NamedColor::Darkslateblue),
            "darkslategray" => Some(NamedColor::Darkslategray),
            "darkslategrey" => Some(NamedColor::Darkslategrey),
            "darkturquoise" => Some(NamedColor::Darkturquoise),
            "darkviolet" => Some(NamedColor::Darkviolet),
            "deeppink" => Some(NamedColor::Deeppink),
            "deepskyblue" => Some(NamedColor::Deepskyblue),
            "dimgray" => Some(NamedColor::Dimgray),
            "dimgrey" => Some(NamedColor::Dimgrey),
            "dodgerblue" => Some(NamedColor::Dodgerblue),
            "firebrick" => Some(NamedColor::Firebrick),
            "floralwhite" => Some(NamedColor::Floralwhite),
            "forestgreen" => Some(NamedColor::Forestgreen),
            "fuchsia" => Some(NamedColor::Fuchsia),
            "gainsboro" => Some(NamedColor::Gainsboro),
            "ghostwhite" => Some(NamedColor::Ghostwhite),
            "gold" => Some(NamedColor::Gold),
            "goldenrod" => Some(NamedColor::Goldenrod),
            "gray" => Some(NamedColor::Gray),
            "green" => Some(NamedColor::Green),
            "greenyellow" => Some(NamedColor::Greenyellow),
            "grey" => Some(NamedColor::Grey),
            "honeydew" => Some(NamedColor::Honeydew),
            "hotpink" => Some(NamedColor::Hotpink),
            "indianred" => Some(NamedColor::Indianred),
            "indigo" => Some(NamedColor::Indigo),
            "ivory" => Some(NamedColor::Ivory),
            "khaki" => Some(NamedColor::Khaki),
            "lavender" => Some(NamedColor::Lavender),
            "lavenderblush" => Some(NamedColor::Lavenderblush),
            "lawngreen" => Some(NamedColor::Lawngreen),
            "lemonchiffon" => Some(NamedColor::Lemonchiffon),
            "lightblue" => Some(NamedColor::Lightblue),
            "lightcoral" => Some(NamedColor::Lightcoral),
            "lightcyan" => Some(NamedColor::Lightcyan),
            "lightgoldenrodyellow" => Some(NamedColor::Lightgoldenrodyellow),
            "lightgray" => Some(NamedColor::Lightgray),
            "lightgreen" => Some(NamedColor::Lightgreen),
            "lightgrey" => Some(NamedColor::Lightgrey),
            "lightpink" => Some(NamedColor::Lightpink),
            "lightsalmon" => Some(NamedColor::Lightsalmon),
            "lightseagreen" => Some(NamedColor::Lightseagreen),
            "lightskyblue" => Some(NamedColor::Lightskyblue),
            "lightslategray" => Some(NamedColor::Lightslategray),
            "lightslategrey" => Some(NamedColor::Lightslategrey),
            "lightsteelblue" => Some(NamedColor::Lightsteelblue),
            "lightyellow" => Some(NamedColor::Lightyellow),
            "lime" => Some(NamedColor::Lime),
            "limegreen" => Some(NamedColor::Limegreen),
            "linen" => Some(NamedColor::Linen),
            "magenta" => Some(NamedColor::Magenta),
            "maroon" => Some(NamedColor::Maroon),
            "mediumaquamarine" => Some(NamedColor::Mediumaquamarine),
            "mediumblue" => Some(NamedColor::Mediumblue),
            "mediumorchid" => Some(NamedColor::Mediumorchid),
            "mediumpurple" => Some(NamedColor::Mediumpurple),
            "mediumseagreen" => Some(NamedColor::Mediumseagreen),
            "mediumslateblue" => Some(NamedColor::Mediumslateblue),
            "mediumspringgreen" => Some(NamedColor::Mediumspringgreen),
            "mediumturquoise" => Some(NamedColor::Mediumturquoise),
            "mediumvioletred" => Some(NamedColor::Mediumvioletred),
            "midnightblue" => Some(NamedColor::Midnightblue),
            "mintcream" => Some(NamedColor::Mintcream),
            "mistyrose" => Some(NamedColor::Mistyrose),
            "moccasin" => Some(NamedColor::Moccasin),
            "navajowhite" => Some(NamedColor::Navajowhite),
            "navy" => Some(NamedColor::Navy),
            "oldlace" => Some(NamedColor::Oldlace),
            "olive" => Some(NamedColor::Olive),
            "olivedrab" => Some(NamedColor::Olivedrab),
            "orange" => Some(NamedColor::Orange),
            "orangered" => Some(NamedColor::Orangered),
            "orchid" => Some(NamedColor::Orchid),
            "palegoldenrod" => Some(NamedColor::Palegoldenrod),
            "palegreen" => Some(NamedColor::Palegreen),
            "paleturquoise" => Some(NamedColor::Paleturquoise),
            "palevioletred" => Some(NamedColor::Palevioletred),
            "papayawhip" => Some(NamedColor::Papayawhip),
            "peachpuff" => Some(NamedColor::Peachpuff),
            "peru" => Some(NamedColor::Peru),
            "pink" => Some(NamedColor::Pink),
            "plum" => Some(NamedColor::Plum),
            "powderblue" => Some(NamedColor::Powderblue),
            "purple" => Some(NamedColor::Purple),
            "rebeccapurple" => Some(NamedColor::Rebeccapurple),
            "red" => Some(NamedColor::Red),
            "rosybrown" => Some(NamedColor::Rosybrown),
            "royalblue" => Some(NamedColor::Royalblue),
            "saddlebrown" => Some(NamedColor::Saddlebrown),
            "salmon" => Some(NamedColor::Salmon),
            "sandybrown" => Some(NamedColor::Sandybrown),
            "seagreen" => Some(NamedColor::Seagreen),
            "seashell" => Some(NamedColor::Seashell),
            "sienna" => Some(NamedColor::Sienna),
            "silver" => Some(NamedColor::Silver),
            "skyblue" => Some(NamedColor::Skyblue),
            "slateblue" => Some(NamedColor::Slateblue),
            "slategray" => Some(NamedColor::Slategray),
            "slategrey" => Some(NamedColor::Slategrey),
            "snow" => Some(NamedColor::Snow),
            "springgreen" => Some(NamedColor::Springgreen),
            "steelblue" => Some(NamedColor::Steelblue),
            "tan" => Some(NamedColor::Tan),
            "teal" => Some(NamedColor::Teal),
            "thistle" => Some(NamedColor::Thistle),
            "tomato" => Some(NamedColor::Tomato),
            "turquoise" => Some(NamedColor::Turquoise),
            "violet" => Some(NamedColor::Violet),
            "wheat" => Some(NamedColor::Wheat),
            "white" => Some(NamedColor::White),
            "whitesmoke" => Some(NamedColor::Whitesmoke),
            "yellow" => Some(NamedColor::Yellow),
            "yellowgreen" => Some(NamedColor::Yellowgreen),
            _ => None,
        }
    }
}

/// A CSS color value.
#[derive(Debug, Clone, PartialEq)]
pub enum CssColor {
    Named(NamedColor),
    Rgb { r: f64, g: f64, b: f64, alpha: f64 },
    Hsl { h: f64, s: f64, l: f64, alpha: f64 },
    Hwb { h: f64, w: f64, b: f64, alpha: f64 },
    Lab { l: f64, a: f64, b: f64, alpha: f64 },
    Lch { l: f64, c: f64, h: f64, alpha: f64 },
    Oklab { l: f64, a: f64, b: f64, alpha: f64 },
    Oklch { l: f64, c: f64, h: f64, alpha: f64 },
    Generic { space: ColorSpace, components: [f64; 3], alpha: f64 },
    CurrentColor,
    Transparent,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterpolationSpace {
    Oklch,
    Oklab,
    Lab,
    Lch,
    Srgb,
    SrgbLinear,
    Hsl,
    Hwb,
}

/// Color mix operation.
#[derive(Debug, Clone)]
pub struct ColorMix {
    pub space: InterpolationSpace,
    pub color1: CssColor,
    pub color2: CssColor,
    pub percentage: f64, // 0.0 = color1, 1.0 = color2
}