[workspace]
resolver = "2"
members = [
    "crates/browser-authoring",
    "crates/browser-core-slice",
    "crates/browser-host",
    "crates/browser-runtime",
    "crates/browser-wire",
    "crates/browser-work",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/edgerun-tech/edgerun"
homepage = "https://github.com/edgerun-tech/edgerun"
rust-version = "1.95"
version = "0.1.1"

[workspace.lints.rust]
dead_code = "allow"
missing_docs = "allow"
unused_variables = "allow"
unused_assignments = "allow"
unused_imports = "allow"
unused_mut = "allow"
non_upper_case_globals = "allow"
non_snake_case = "allow"
unused_must_use = "allow"
unused_comparisons = "allow"
unexpected_cfgs = "allow"
unused_parens = "allow"
deprecated = "allow"
function_casts_as_integer = "allow"
