#!/usr/bin/env python3
"""
Generate HTML Parser — reads Parser IR (JSON) → generates Rust source.

Reads:
  ir/tokenizer.json  (generated by generate_parser_ir.py)

Writes:
  crates/edgerun-html-render/src/tokenizer.rs  — generated state machine
  crates/edgerun-html-render/src/tree_builder.rs — generated tree builder
  crates/edgerun-html-render/src/entity_decoder.rs — generated entity decoder
  crates/edgerun-html-render/src/html_parser.rs  — generated entry point

The generated code replaces the current 140-line ad-hoc parser.
All generated files are marked "DO NOT EDIT. Regenerate with: scripts/generate_html_parser.py"
"""

import json
import os
import sys
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  Written: {os.path.relpath(path, ROOT)}")


HEADER = """\
// DO NOT EDIT.
// Auto-generated from Parser IR by scripts/generate_html_parser.py
// Regenerate: python3 scripts/generate_parser_ir.py && python3 scripts/generate_html_parser.py
"""

# ---------------------------------------------------------------------------
# Generate tokenizer.rs
# ---------------------------------------------------------------------------

def classify_char(c):
    """Map a Rust char to a char class string matching the IR."""
    if c == '\x00':
        return "NULL"
    if c == '<':
        return "LT"
    if c == '>':
        return "GT"
    if c == '/':
        return "SLASH"
    if c == '&':
        return "AMP"
    if c == '"':
        return "QUOT"
    if c == '\'':
        return "APOS"
    if c == '=':
        return "EQ"
    if c in (' ', '\t', '\n', '\r', '\x0c'):
        return "WS"
    if c.isascii_alpha():
        return "ALPHA"
    if c.isascii_alphanumeric() or c in ('-', '_'):
        return "ALNUM"
    return "OTHER"


def rust_char_literal(c):
    """Escape a char for Rust char literal."""
    if c == '\x00':
        return "'\\0'"
    if c == '\\':
        return "'\\\\'"
    if c == "'":
        return "'\\''"
    return f"'{c}'"


def generate_tokenizer_rs(ir):
    states = ir["states"]
    transitions = ir["transitions"]
    void_elements = ir["void_elements"]
    raw_text_elements = ir["raw_text_elements"]

    # Build transition table: state → char_class → next_state, actions
    # For codegen, we generate a match arm for each state,
    # and inside each state, a match on the char class.

    # Group transitions by (state, char_class)
    from collections import defaultdict
    state_trans = defaultdict(list)
    for t in transitions:
        state_trans[(t["state"], t["char_class"])].append(t)

    # Build state machine code
    state_match_arms = []
    for state_name, state_id in sorted(states.items(), key=lambda x: x[1]):
        rust_state = camel_case(state_name)

        # Get all transitions for this state
        state_transitions = [(k_c, v) for (k_s, k_c), v in state_trans.items() if k_s == state_name]

        char_class_arms = []
        # Sort so that OTHER ("_") wildcard arm is always LAST
        sorted_transitions = sorted(state_transitions, key=lambda x: (x[0] == "OTHER", x[0]))
        for char_class, trans_list in sorted_transitions:
            if len(trans_list) != 1:
                # Multiple transitions for same (state, char_class) — shouldn't happen in valid IR
                continue
            t = trans_list[0]
            next_state = camel_case(t["next"])
            actions = t["actions"]

            # Build the action code
            action_lines = []
            for action in actions:
                if action == "EMIT_CHAR":
                    action_lines.append("self.emit_char();")
                elif action == "EMIT_EOF":
                    action_lines.append("self.done = true;")
                elif action == "START_TAG":
                    action_lines.append("self.start_tag();")
                elif action == "END_TAG":
                    action_lines.append("self.end_tag();")
                elif action == "APPEND_TAG_NAME":
                    action_lines.append("self.append_tag_name(c);")
                elif action == "APPEND_ATTR_NAME":
                    action_lines.append("self.append_attr_name(c);")
                elif action == "APPEND_ATTR_VALUE":
                    action_lines.append("self.append_attr_value(c);")
                elif action == "EMIT_TOKEN":
                    action_lines.append("self.emit_tag();")
                elif action == "SET_SELF_CLOSING":
                    action_lines.append("self.current_token_is_self_closing = true;")
                elif action == "PARSE_ERROR":
                    action_lines.append("self.parse_errors += 1;")

            action_code = "\n                    ".join(action_lines) if action_lines else ""

            # Determine the character match pattern
            if char_class == "ALPHA":
                pattern = "'a'..='z' | 'A'..='Z'"
            elif char_class == "ALNUM":
                pattern = "'a'..='z' | 'A'..='Z' | '0'..='9' | '-' | '_'"
            elif char_class == "WS":
                pattern = "' ' | '\\t' | '\\n' | '\\r' | '\\x0C'"
            elif char_class == "OTHER":
                pattern = "_"
            elif char_class == "NULL":
                pattern = "'\\0'"
            elif char_class == "EOF":
                # EOF is handled at the input level, not in the match
                continue
            else:
                raw_char = {
                    "LT": '<',
                    "GT": '>',
                    "SLASH": '/',
                    "AMP": '&',
                    "QUOT": '"',
                    "APOS": "'",
                    "EQ": '=',
                }.get(char_class, '_')
                pattern = rust_char_literal(raw_char)

            arm = f"                {pattern} => {{\n                    self.state = State::{next_state};\n                    {action_code}\n                }}"
            char_class_arms.append(arm)

        # Default fallthrough for EOF — stay in state
        if "EOF" not in [t.get("char_class") for t in transitions if t.get("state") == state_name]:
            pass  # No EOF transition defined for this state, no arm needed

        arm_body = "\n".join(char_class_arms)
        if not arm_body:
            # No transitions for this state — just stay
            state_match_arms.append(f"""\
            State::{rust_state} => {{
                // No transitions defined — stays in state
            }}""")
        else:
            state_match_arms.append(f"""\
            State::{rust_state} => {{
                match c {{
{arm_body}
                }}
            }}""")

    arms_str = "\n\n".join(state_match_arms)

    # Build the full file
    code = f"""{HEADER}
extern crate alloc;

use alloc::string::{{String, ToString}};
use alloc::vec::Vec;
use alloc::collections::BTreeMap;

use crate::html_parser::{{Node, Element}};

/// Token types emitted by the tokenizer.
#[derive(Debug, Clone)]
pub enum Token {{
    StartTag {{ name: String, attrs: BTreeMap<String, String>, self_closing: bool }},
    EndTag {{ name: String }},
    Character(String),
    Comment(String),
    Eof,
}}

/// Tokenizer states from WHATWG §13.2.5.
#[derive(Debug, Clone, PartialEq, Eq)]
enum State {{
    Data,
    TagOpen,
    EndTagOpen,
    TagName,
    BeforeAttributeName,
    AttributeName,
    AfterAttributeName,
    BeforeAttributeValue,
    AttributeValueDoubleQuoted,
    AttributeValueSingleQuoted,
    AttributeValueUnquoted,
    SelfClosingStartTag,
    Eof,
}}

/// WHATWG §13.2.5 HTML tokenizer — table-driven state machine.
///
/// Generated from Parser IR with {len(transitions)} transitions across {len(states)} states.
/// Each input character maps to a char class, which indexes into the transition table.
pub struct Tokenizer {{
    input: Vec<char>,
    pos: usize,
    state: State,
    current_tag_name: String,
    current_attr_name: String,
    current_attr_value: String,
    current_attr_map: BTreeMap<String, String>,
    current_token_is_self_closing: bool,
    text_buffer: String,
    pending_token: Option<Token>,
    is_start_tag: bool,
    parse_errors: usize,
    done: bool,
}}

impl Tokenizer {{
    pub fn new(input: &str) -> Self {{
        Self {{
            input: input.chars().collect(),
            pos: 0,
            state: State::Data,
            current_tag_name: String::new(),
            current_attr_name: String::new(),
            current_attr_value: String::new(),
            current_attr_map: BTreeMap::new(),
            current_token_is_self_closing: false,
            text_buffer: String::new(),
            pending_token: None,
            is_start_tag: false,
            parse_errors: 0,
            done: false,
        }}
    }}

    /// Run the tokenizer to completion, returning all tokens.
    pub fn tokenize(&mut self) -> Vec<Token> {{
        let mut tokens = Vec::new();
        while let Some(token) = self.step() {{
            tokens.push(token);
        }}
        tokens
    }}

    /// Step the state machine until a token is emitted or we're done.
    /// Returns None only when fully finished (EOF emitted).
    fn step(&mut self) -> Option<Token> {{
        loop {{
            // Return any pending token from previous step
            if let Some(t) = self.pending_token.take() {{
                return Some(t);
            }}

            if self.pos >= self.input.len() {{
                if !self.done {{
                    // Flush buffered text
                    if !self.text_buffer.is_empty() {{
                        let t = Token::Character(self.text_buffer.clone());
                        self.text_buffer.clear();
                        return Some(t);
                    }}
                    self.done = true;
                    return Some(Token::Eof);
                }}
                return None;
            }}

            let c = self.input[self.pos];

            // When in DATA state and we see '<', flush buffered text first
            if self.state == State::Data && c == '<' && !self.text_buffer.is_empty() {{
                let t = Token::Character(self.text_buffer.clone());
                self.text_buffer.clear();
                // Don't consume '<' yet — process it on next step
                return Some(t);
            }}

            self.pos += 1;

            match self.state {{
{arms_str}
            }}
            // If no pending token was set, continue loop to next character
        }}
    }}

    fn emit_char(&mut self) {{
        // Only emit non-whitespace or if we have content
        self.text_buffer.push(self.input[self.pos - 1]);
    }}

    fn start_tag(&mut self) {{
        self.current_tag_name.clear();
        self.current_attr_name.clear();
        self.current_attr_value.clear();
        self.current_attr_map.clear();
        self.current_token_is_self_closing = false;
        self.is_start_tag = true;
    }}

    fn end_tag(&mut self) {{
        self.current_tag_name.clear();
        self.is_start_tag = false;
    }}

    fn append_tag_name(&mut self, c: char) {{
        self.current_tag_name.push(c.to_ascii_lowercase());
    }}

    fn append_attr_name(&mut self, c: char) {{
        self.current_attr_name.push(c);
    }}

    fn append_attr_value(&mut self, c: char) {{
        self.current_attr_value.push(c);
    }}

    fn emit_tag(&mut self) {{
        let tag = self.current_tag_name.clone();
        let attrs = self.current_attr_map.clone();
        let self_closing = self.current_token_is_self_closing;

        if self.is_start_tag {{
            self.pending_token = Some(Token::StartTag {{ name: tag, attrs, self_closing }});
        }} else {{
            self.pending_token = Some(Token::EndTag {{ name: tag }});
        }}
    }}

    pub fn parse_errors(&self) -> usize {{
        self.parse_errors
    }}
}}

/// Raw text element tags that switch the tokenizer to RAWTEXT mode.
pub const RAW_TEXT_ELEMENTS: &[&str] = &{json.dumps(raw_text_elements)};

/// Void element tags that never have children.
pub const VOID_ELEMENTS: &[&str] = &{json.dumps(void_elements)};
"""
    return code


# ---------------------------------------------------------------------------
# Generate tree_builder.rs
# ---------------------------------------------------------------------------

def generate_tree_builder_rs(ir):
    rules = ir["tree_rules"]
    void_elements = ir["void_elements"]

    code = f"""{HEADER}
extern crate alloc;

use alloc::string::{{String, ToString}};
use alloc::vec::Vec;
use alloc::collections::BTreeMap;

use crate::html_parser::{{Node, Element}};
use crate::tokenizer::Token;

/// Insertion modes for the tree builder (Phase 1: IN_BODY only).
#[derive(Debug, Clone, PartialEq, Eq)]
enum InsertionMode {{
    Initial,
    BeforeHtml,
    BeforeHead,
    InHead,
    AfterHead,
    InBody,
    AfterBody,
}}

/// Tree builder — constructs a DOM tree from tokens.
///
/// Generated from Parser IR with {len(rules)} tree rules.
/// Each rule maps (insertion_mode, token_type) → (actions[], next_mode).
pub struct TreeBuilder {{
    mode: InsertionMode,
    /// Stack of indices into the nodes arena.
    stack: Vec<usize>,
    /// Arena of all nodes. Index 0 is the root.
    nodes: Vec<Node>,
}}

impl TreeBuilder {{
    pub fn new() -> Self {{
        Self {{
            mode: InsertionMode::Initial,
            stack: Vec::new(),
            nodes: Vec::new(),
        }}
    }}

    /// Process a token and return any DOM changes.
    pub fn process(&mut self, token: &Token) {{
        match self.mode {{
            InsertionMode::Initial => self.handle_initial(token),
            InsertionMode::InBody => self.handle_in_body(token),
            InsertionMode::AfterBody => {{ /* ignore */ }}
            _ => {{ /* Phase 1: other modes not yet implemented */ }}
        }}
    }}

    fn alloc_node(&mut self, elem: Element) -> usize {{
        let idx = self.nodes.len();
        self.nodes.push(Node::Element(elem));
        idx
    }}

    fn handle_initial(&mut self, token: &Token) {{
        // Always transition to InBody on first token (simplified)
        self.mode = InsertionMode::InBody;
        // Create root element
        let root = Element::new("html");
        self.nodes.push(Node::Element(root));
        let body = Element::new("body");
        self.nodes.push(Node::Element(body));
        self.stack.push(1); // index of body
        self.handle_in_body(token);
    }}

    fn handle_in_body(&mut self, token: &Token) {{
        match token {{
            Token::StartTag {{ name, attrs, self_closing }} => {{
                let mut elem = Element::new(name);
                for (k, v) in attrs {{
                    elem.attrs.insert(k.clone(), v.clone());
                }}
                let idx = self.nodes.len();
                self.nodes.push(Node::Element(elem.clone()));
                // Add to parent
                if let Some(&parent_idx) = self.stack.last() {{
                    if let Some(Node::Element(parent)) = self.nodes.get_mut(parent_idx) {{
                        parent.children.push(Node::Element(elem));
                    }}
                }}
                if !*self_closing && !VOID_ELEMENTS.contains(&name.as_str()) {{
                    self.stack.push(idx);
                }}
            }}
            Token::EndTag {{ name }} => {{
                // Pop until we find the matching tag
                while let Some(idx) = self.stack.pop() {{
                    if let Some(Node::Element(e)) = self.nodes.get(idx) {{
                        if e.tag == *name {{
                            break;
                        }}
                    }}
                }}
            }}
            Token::Character(text) => {{
                if let Some(&parent_idx) = self.stack.last() {{
                    if let Some(Node::Element(parent)) = self.nodes.get_mut(parent_idx) {{
                        if !text.trim().is_empty() {{
                            parent.children.push(Node::Text(text.clone()));
                        }}
                    }}
                }}
            }}
            Token::Comment(text) => {{
                if let Some(&parent_idx) = self.stack.last() {{
                    if let Some(Node::Element(parent)) = self.nodes.get_mut(parent_idx) {{
                        parent.children.push(Node::Comment(text.clone()));
                    }}
                }}
            }}
            Token::Eof => {{
                self.mode = InsertionMode::AfterBody;
            }}
        }}
    }}

    /// Take the constructed DOM tree.
    pub fn take_root(&mut self) -> Option<Node> {{
        self.nodes.first().cloned()
    }}
}}

/// Void elements — never pushed to the stack.
pub const VOID_ELEMENTS: &[&str] = &{json.dumps(void_elements)};
"""
    return code


# ---------------------------------------------------------------------------
# Generate entity_decoder.rs
# ---------------------------------------------------------------------------

def generate_entity_decoder_rs(ir):
    entities = ir["entities"]

    # Build a simple lookup: "&name;" → (char1, char2)
    entity_entries = []
    for e in entities:
        name = e["name"]
        cp1 = e["code_point_1"]
        cp2 = e["code_point_2"]
        char1 = f"char::from_u32({cp1}).unwrap()"
        if cp2:
            char2 = f"char::from_u32({cp2}).unwrap()"
            entity_entries.append(f'        "{name}" => Some(({char1}, Some({char2}))),')
        else:
            entity_entries.append(f'        "{name}" => Some(({char1}, None)),')

    entries_str = "\n".join(entity_entries)

    code = f"""{HEADER}
extern crate alloc;

use alloc::string::String;

/// Entity decoder — maps named character references to Unicode code points.
///
/// Generated from Parser IR with {len(entities)} entities.
/// Phase 1: minimal set (5 entities). Full spec has 2,231.
pub struct EntityDecoder;

impl EntityDecoder {{
    /// Decode a named entity (without & or ;).
    /// Returns (primary_char, optional_secondary_char) or None.
    pub fn decode(name: &str) -> Option<(char, Option<char>)> {{
        match name {{
{entries_str}
            _ => None,
        }}
    }}

    /// Decode a full entity reference including & and optionally ;.
    pub fn decode_full(input: &str) -> Option<(String, usize)> {{
        if !input.starts_with('&') {{
            return None;
        }}
        // Try to find the entity name
        let rest = &input[1..];
        let semi_pos = rest.find(';');
        if let Some(pos) = semi_pos {{
            let name = &rest[..pos];
            if let Some((c1, c2)) = Self::decode(name) {{
                let s = if let Some(c2) = c2 {{
                    format!("{{}}{{}}", c1, c2)
                }} else {{
                    format!("{{}}", c1)
                }};
                return Some((s, pos + 2)); // +2 for & and ;
            }}
        }}
        // Try without semicolon (for legacy entities)
        for len in (1..=rest.len()).rev() {{
            let name = &rest[..len];
            if let Some((c1, c2)) = Self::decode(name) {{
                let s = if let Some(c2) = c2 {{
                    format!("{{}}{{}}", c1, c2)
                }} else {{
                    format!("{{}}", c1)
                }};
                return Some((s, len + 1)); // +1 for &
            }}
        }}
        None
    }}
}}
"""
    return code


# ---------------------------------------------------------------------------
# Generate html_parser.rs (entry point)
# ---------------------------------------------------------------------------

def generate_html_parser_rs(ir):
    void_elements = ir["void_elements"]
    raw_text_elements = ir["raw_text_elements"]

    code = f"""{HEADER}
extern crate alloc;

use alloc::string::{{String, ToString}};
use alloc::vec::Vec;
use alloc::collections::BTreeMap;

pub use crate::tokenizer::{{Tokenizer, Token, VOID_ELEMENTS, RAW_TEXT_ELEMENTS}};
pub use crate::tree_builder::TreeBuilder;

// Re-export for downstream consumers (edgerun-demo, layout_builder, etc.)
pub use crate::entity_decoder::EntityDecoder;

/// Block-level elements — used by layout for block vs inline distinction.
pub const BLOCK_ELEMENTS: &[&str] = &[
    "address", "article", "aside", "blockquote", "caption", "col",
    "colgroup", "dd", "details", "dialog", "div", "dl", "dt",
    "figcaption", "figure", "fieldset", "footer", "form", "h1", "h2",
    "h3", "h4", "h5", "h6", "header", "hr", "legend", "li", "main",
    "nav", "ol", "p", "pre", "section", "summary", "table", "tbody",
    "td", "tfoot", "th", "thead", "tr", "ul",
];

/// Inline elements.
pub const INLINE_ELEMENTS: &[&str] = &[
    "a", "abbr", "audio", "b", "big", "br", "button", "canvas", "cite",
    "code", "data", "datalist", "del", "dfn", "em", "iframe", "img",
    "input", "ins", "kbd", "label", "link", "map", "mark", "meter",
    "object", "output", "picture", "progress", "q", "ruby", "samp",
    "script", "select", "slot", "small", "source", "span", "strong",
    "sub", "sup", "svg", "textarea", "time", "track", "u", "var",
    "video", "wbr",
];

/// DOM node types.
#[derive(Debug, Clone)]
pub enum Node {{
    Element(Element),
    Text(String),
    Comment(String),
}}

/// HTML element with tag, attributes, and children.
#[derive(Debug, Clone)]
pub struct Element {{
    pub tag: String,
    pub attrs: BTreeMap<String, String>,
    pub children: Vec<Node>,
}}

impl Element {{
    pub fn new(tag: &str) -> Self {{
        Self {{
            tag: tag.to_lowercase(),
            attrs: BTreeMap::new(),
            children: Vec::new(),
        }}
    }}

    pub fn is_void(&self) -> bool {{
        VOID_ELEMENTS.contains(&self.tag.as_str())
    }}

    pub fn attr(&self, name: &str) -> Option<&str> {{
        self.attrs.get(name).map(|s| s.as_str())
    }}

    pub fn class(&self) -> Option<&str> {{
        self.attr("class")
    }}

    pub fn id(&self) -> Option<&str> {{
        self.attr("id")
    }}
}}

/// Parse an HTML string into a DOM tree.
///
/// Pipeline: &str → Tokenizer → token stream → DOM tree
///
/// Generated from Parser IR — replaces the previous ad-hoc recursive descent parser.
pub fn parse_html(html: &str) -> Node {{
    let mut tokenizer = Tokenizer::new(html);
    let tokens = tokenizer.tokenize();

    // Simple stack-based DOM builder from token stream.
    #[derive(Debug)]
    struct Frame {{
        elem: Element,
        children: Vec<Node>,
    }}

    let mut stack: Vec<Frame> = Vec::new();
    let mut roots: Vec<Node> = Vec::new();

    for token in tokens {{
        match token {{
            Token::StartTag {{ name, attrs, self_closing: _ }} => {{
                let mut elem = Element::new(&name);
                for (k, v) in attrs {{
                    elem.attrs.insert(k, v);
                }}
                stack.push(Frame {{ elem, children: Vec::new() }});
            }}
            Token::EndTag {{ name }} => {{
                // Pop frames until we find the matching tag
                let mut found = None;
                while let Some(frame) = stack.pop() {{
                    if frame.elem.tag == name {{
                        let mut elem = frame.elem;
                        elem.children = frame.children;
                        found = Some(Node::Element(elem));
                        break;
                    }} else {{
                        // Implicit close
                        let mut elem = frame.elem;
                        elem.children = frame.children;
                        let node = Node::Element(elem);
                        if let Some(parent) = stack.last_mut() {{
                            parent.children.push(node);
                        }} else {{
                            roots.push(node);
                        }}
                    }}
                }}
                if let Some(node) = found {{
                    if let Some(parent) = stack.last_mut() {{
                        parent.children.push(node);
                    }} else {{
                        roots.push(node);
                    }}
                }}
            }}
            Token::Character(text) => {{
                if !text.trim().is_empty() {{
                    if let Some(parent) = stack.last_mut() {{
                        parent.children.push(Node::Text(text));
                    }} else {{
                        roots.push(Node::Text(text));
                    }}
                }}
            }}
            Token::Comment(text) => {{
                if let Some(parent) = stack.last_mut() {{
                    parent.children.push(Node::Comment(text));
                }} else {{
                    roots.push(Node::Comment(text));
                }}
            }}
            Token::Eof => {{
                // Close all open elements
                while let Some(frame) = stack.pop() {{
                    let mut elem = frame.elem;
                    elem.children = frame.children;
                    let node = Node::Element(elem);
                    if let Some(parent) = stack.last_mut() {{
                        parent.children.push(node);
                    }} else {{
                        roots.push(node);
                    }}
                }}
            }}
        }}
    }}

    if roots.len() == 1 {{
        roots.remove(0)
    }} else if roots.is_empty() {{
        let mut root = Element::new("div");
        root.attrs.insert("data-root".into(), "true".into());
        Node::Element(root)
    }} else {{
        let mut root = Element::new("div");
        root.attrs.insert("data-root".into(), "true".into());
        root.children = roots;
        Node::Element(root)
    }}
}}

/// Count nodes in the DOM tree (for rendering).
pub fn count_nodes(node: &Node) -> usize {{
    match node {{
        Node::Text(_) => 1,
        Node::Comment(_) => 1,
        Node::Element(elem) => {{
            1 + elem.children.iter().map(count_nodes).sum::<usize>()
        }}
    }}
}}
"""
    return code


# ---------------------------------------------------------------------------
# camelCase helper
# ---------------------------------------------------------------------------

def camel_case(name):
    """Convert SCREAMING_SNAKE_CASE or snake_case to PascalCase for Rust."""
    return ''.join(w.capitalize() for w in name.split('_') if w)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ir_path = os.path.join(ROOT, "ir", "tokenizer.json")
    if not os.path.exists(ir_path):
        print(f"Error: IR not found at {ir_path}")
        print("Run: python3 scripts/generate_parser_ir.py")
        sys.exit(1)

    with open(ir_path) as f:
        ir = json.load(f)

    print(f"Read IR: {len(ir['states'])} states, {len(ir['transitions'])} transitions, "
          f"{len(ir['tree_rules'])} tree rules, {len(ir['entities'])} entities")

    src_dir = os.path.join(ROOT, "crates", "edgerun-html-render", "src")

    # Generate tokenizer.rs
    code = generate_tokenizer_rs(ir)
    write_file(os.path.join(src_dir, "tokenizer.rs"), code)

    # Generate tree_builder.rs
    code = generate_tree_builder_rs(ir)
    write_file(os.path.join(src_dir, "tree_builder.rs"), code)

    # Generate entity_decoder.rs
    code = generate_entity_decoder_rs(ir)
    write_file(os.path.join(src_dir, "entity_decoder.rs"), code)

    # Generate html_parser.rs (replaces existing file)
    code = generate_html_parser_rs(ir)
    write_file(os.path.join(src_dir, "html_parser.rs"), code)

    # Update lib.rs to include new modules
    lib_path = os.path.join(src_dir, "lib.rs")
    lib_code = """\
//! HTML/CSS → RenderObject + pixel rendering pipeline.
//! DO NOT EDIT. Regenerate with: scripts/generate_html_parser.py
extern crate alloc;

pub mod html_parser;
pub mod tokenizer;
pub mod tree_builder;
pub mod entity_decoder;
pub mod css_parser;
pub mod computed_style;
pub mod layout_builder;
pub mod render;

pub use render::render;
pub use render::count_nodes;
"""
    write_file(lib_path, lib_code)

    print(f"\nGenerated {4} source files in edgerun-html-render/src/")
    print("Build with: cargo build --package edgerun-html-render")


if __name__ == "__main__":
    main()
