[package]
name = "edgerun-edit"
version = "0.1.1"
edition.workspace = true
license.workspace = true

[[bin]]
name = "edgerun-edit"
path = "src/main.rs"

[dependencies]
edgerun-http = { path = "../edgerun-http" }
edgerun-rt = { path = "../edgerun-rt" }
syn = { version = "2", features = ["full", "parsing", "extra-traits", "printing"] }
proc-macro2 = "1"
quote = "1"
prettyplease = "0.2"
edgerun-clap = { path = "../edgerun-clap" }
edgerun-json = { workspace = true }

[lints]
workspace = true
