[package]
name = "lifegraph-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hex.workspace = true
lifegraph-core = { path = "../lifegraph-core" }
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
prost-build.workspace = true
