[package]
name = "edgerun-hpack"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "HPACK header compression for HTTP/2 (RFC 7541)"

[lints]
workspace = true

[dependencies]
edgerun-log = { version = "0.1", path = "../edgerun-log" }

[features]
interop_tests = ["rustc-serialize"]

[target.'cfg(not(target_os = "none"))'.dependencies]
rustc-serialize = { version = "^0.3", optional = true }
