[package]
name = "edgerun-relay"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun relay node protocol and TCP relay runtime"

[[bin]]
name = "edgerun-relay"
path = "src/main.rs"
required-features = ["std"]

[[bin]]
name = "edgerun-relay-bench"
path = "src/bin/edgerun-relay-bench.rs"
required-features = ["std"]

[dependencies]
edgerun-crypto = { workspace = true, default-features = false }
edgerun-network-driver = { workspace = true, optional = true }
edgerun-protocols = { workspace = true, default-features = false }
edgerun-rusttls = { version = "0.1", path = "../../utility/edgerun-rusttls", default-features = false, optional = true }
edgerun-tungstenite = { version = "0.1", path = "../../utility/edgerun-tungstenite", default-features = false, features = ["deflate", "handshake"], optional = true }
edgerun-virtio = { workspace = true, optional = true }
edgerun-wire = { workspace = true, default-features = false }

[features]
default = []
ed25519 = ["edgerun-crypto/ed25519", "edgerun-protocols/ed25519"]
fast-public-relay = []
p256-message = ["edgerun-crypto/p256", "edgerun-protocols/sign-p256"]
std = ["ed25519", "p256-message", "edgerun-wire/std", "edgerun-protocols/keygen", "wss", "edgerun-rusttls/std", "dep:edgerun-tungstenite"]
virtio = ["dep:edgerun-network-driver", "dep:edgerun-virtio", "edgerun-network-driver/virtio", "edgerun-protocols/ethernet-ipv4"]
wss = ["dep:edgerun-rusttls"]

[dev-dependencies]
edgerun-protocols = { workspace = true, default-features = false, features = ["keygen"] }

[lints]
workspace = true
