[package]
name = "codex-shell-command"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
codex-protocol = { workspace = true }
edgerun-encoding = { workspace = true }
edgerun-json = { workspace = true, features = ["derive"] }
edgerun-url = { workspace = true }
