[package]
name = "edgerun-work"
version = "0.1.1"
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["edgerun-wire/std", "dep:edgerun-protocols", "edgerun-protocols/websocket"]
wasm-chat = []
wasm-example = []
virtual-disk = [
  "std",
  "dep:edgerun-protocols",
  "dep:edgerun-virtual-disk",
  "edgerun-protocols/block",
  "edgerun-virtual-disk/std",
]

[dependencies]
edgerun-crypto = { workspace = true, default-features = false, features = ["ed25519", "x25519", "aead", "hmac"] }
edgerun-protocols = { workspace = true, default-features = false, optional = true }
edgerun-virtual-disk = { workspace = true, default-features = false, features = ["std"], optional = true }
edgerun-wire = { workspace = true, default-features = false }
rkyv = { version = "0.8.16", default-features = false, features = ["alloc", "bytecheck"] }

[[example]]
name = "blake3_1024_wasm"
path = "examples/blake3_1024_wasm.rs"
crate-type = ["cdylib"]
required-features = ["wasm-example"]

[[example]]
name = "chat_wasm"
path = "examples/chat_wasm.rs"
crate-type = ["cdylib"]
required-features = ["wasm-chat"]
