[workspace]
resolver = "2"
members = [
  ".",
  "../edgerun-wire",
  "../../utility/edgerun-crypto",
  "../../utility/edgerun-encoding",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/edgerun-tech/edgerun"
homepage = "https://github.com/edgerun-tech/edgerun"
rust-version = "1.95"
version = "0.1.1"

[workspace.lints.rust]
dead_code = "allow"
missing_docs = "allow"
unused_variables = "allow"
unused_assignments = "allow"
unused_imports = "allow"
unused_mut = "allow"
non_upper_case_globals = "allow"
non_snake_case = "allow"
unused_must_use = "allow"
unused_comparisons = "allow"
unexpected_cfgs = "allow"
unused_parens = "allow"
deprecated = "allow"
function_casts_as_integer = "allow"

[package]
name = "edgerun-work"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["std"]
std = ["edgerun-wire/std"]

[dependencies]
edgerun-crypto = { path = "../../utility/edgerun-crypto", default-features = false, features = ["ed25519"] }
edgerun-wire = { path = "../edgerun-wire", default-features = false }
rkyv = { version = "0.8.16", default-features = false, features = ["alloc", "bytecheck"] }
blake3 = { version = "1", default-features = false }
