// This file is @generated by edgerun-work-wire-gen.
// Do not hand edit; update protocol structs and regenerate.

use alloc::string::String;
use alloc::vec::Vec;

use crate::admitted_route::*;
use crate::capability_packet::*;
use crate::channel::*;
use crate::chat_index::*;
use crate::codec::{EdgeWire, WireCursor, WireWriter};
use crate::message_seal::*;
use crate::node_control::*;
use crate::notary_role::*;
use crate::program_io::*;
use crate::protocol::WorkProtocolError;
use crate::protocol::*;

use crate::recipient_policy::*;
use crate::storage_payload::*;

pub type ArchivedWorkSignature = WorkSignature;
pub type ArchivedNodeIdentity = NodeIdentity;
pub type ArchivedNetworkMessage = NetworkMessage;
pub type ArchivedWorkRequest = WorkRequest;
pub type ArchivedWorkAdmission = WorkAdmission;
pub type ArchivedWorkReceipt = WorkReceipt;
pub type ArchivedWorkPacket = WorkPacket;
pub type ArchivedWorkAck = WorkAck;
pub type ArchivedRelayEndpoint = RelayEndpoint;
pub type ArchivedNodeAvailable = NodeAvailable;
pub type ArchivedNodeHeartbeat = NodeHeartbeat;
pub type ArchivedRelayAssignment = RelayAssignment;
pub type ArchivedChannelEndpoint = ChannelEndpoint;
pub type ArchivedRouteBinding = RouteBinding;
pub type ArchivedChannelEnvelope = ChannelEnvelope;
pub type ArchivedChannelProof = ChannelProof;
pub type ArchivedObjectStoreRequest = ObjectStoreRequest;
pub type ArchivedObjectRetrieveRequest = ObjectRetrieveRequest;
pub type ArchivedObjectRetrieveResponse = ObjectRetrieveResponse;
pub type ArchivedStoragePayload = StoragePayload;
pub type ArchivedRecipientMessagePolicy = RecipientMessagePolicy;
pub type ArchivedAdmittedCapabilityRoute = AdmittedCapabilityRoute;
pub type ArchivedNotarySealRequest = NotarySealRequest;
pub type ArchivedNotarySealResponse = NotarySealResponse;
pub type ArchivedNotaryUnsealRequest = NotaryUnsealRequest;
pub type ArchivedNotaryDeliveryReport = NotaryDeliveryReport;
pub type ArchivedNotaryUnsealResponse = NotaryUnsealResponse;
pub type ArchivedNotaryPayload = NotaryPayload;
pub type ArchivedSealedMessagePayload = SealedMessagePayload;
pub type ArchivedCapabilityEnvelope = CapabilityEnvelope;
pub type ArchivedProgramEnv = ProgramEnv;
pub type ArchivedProgramOpen = ProgramOpen;
pub type ArchivedProgramStdin = ProgramStdin;
pub type ArchivedProgramClose = ProgramClose;
pub type ArchivedProgramPoll = ProgramPoll;
pub type ArchivedProgramOutput = ProgramOutput;
pub type ArchivedProgramExit = ProgramExit;
pub type ArchivedProgramIoPayload = ProgramIoPayload;
pub type ArchivedProgramIoEvent = ProgramIoEvent;
pub type ArchivedProgramIoEvents = ProgramIoEvents;
pub type ArchivedContactPublicId = ContactPublicId;
pub type ArchivedExternalContactRef = ExternalContactRef;
pub type ArchivedContactObject = ContactObject;
pub type ArchivedMessageObject = MessageObject;
pub type ArchivedThreadMessageRef = ThreadMessageRef;
pub type ArchivedThreadObject = ThreadObject;
pub type ArchivedContactBookContactRef = ContactBookContactRef;
pub type ArchivedContactBookThreadRef = ContactBookThreadRef;
pub type ArchivedContactBook = ContactBook;

impl EdgeWire for WorkSignature {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.algorithm.encode_wire(out);
        self.public_key.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            algorithm: <u16 as EdgeWire>::decode_wire(input)?,
            public_key: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            signature: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NodeIdentity {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.node_id.encode_wire(out);
        self.role.encode_wire(out);
        self.public_key.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            role: <u16 as EdgeWire>::decode_wire(input)?,
            public_key: <PublicKey as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NetworkMessage {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.message_id.encode_wire(out);
        self.prev_hash.encode_wire(out);
        self.from.encode_wire(out);
        self.to.encode_wire(out);
        self.via_relay.encode_wire(out);
        self.department.encode_wire(out);
        self.work_type.encode_wire(out);
        self.sequence.encode_wire(out);
        self.payload_hash.encode_wire(out);
        self.payload.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            message_id: <Hash as EdgeWire>::decode_wire(input)?,
            prev_hash: <Hash as EdgeWire>::decode_wire(input)?,
            from: <NodeId as EdgeWire>::decode_wire(input)?,
            to: <NodeId as EdgeWire>::decode_wire(input)?,
            via_relay: <NodeId as EdgeWire>::decode_wire(input)?,
            department: <u16 as EdgeWire>::decode_wire(input)?,
            work_type: <u16 as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            payload: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for WorkRequest {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.request_id.encode_wire(out);
        self.user.encode_wire(out);
        self.user_sequence.encode_wire(out);
        self.recipient.encode_wire(out);
        self.work_type.encode_wire(out);
        self.department.encode_wire(out);
        self.payload_hash.encode_wire(out);
        self.input_root.encode_wire(out);
        self.max_total_cost.encode_wire(out);
        self.valid_until_unix_ms.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            request_id: <Hash as EdgeWire>::decode_wire(input)?,
            user: <PublicKey as EdgeWire>::decode_wire(input)?,
            user_sequence: <u64 as EdgeWire>::decode_wire(input)?,
            recipient: <NodeId as EdgeWire>::decode_wire(input)?,
            work_type: <u16 as EdgeWire>::decode_wire(input)?,
            department: <u16 as EdgeWire>::decode_wire(input)?,
            payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            input_root: <Hash as EdgeWire>::decode_wire(input)?,
            max_total_cost: <u64 as EdgeWire>::decode_wire(input)?,
            valid_until_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for WorkAdmission {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.admission_id.encode_wire(out);
        self.dao_id.encode_wire(out);
        self.user.encode_wire(out);
        self.admission_node.encode_wire(out);
        self.request_hash.encode_wire(out);
        self.assigned_route_commitment.encode_wire(out);
        self.assigned_channel.encode_wire(out);
        self.assigned_relay_path.encode_wire(out);
        self.admitted_budget.encode_wire(out);
        self.policy_hash.encode_wire(out);
        self.sequence.encode_wire(out);
        self.valid_until_unix_ms.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            admission_id: <Hash as EdgeWire>::decode_wire(input)?,
            dao_id: <PublicKey as EdgeWire>::decode_wire(input)?,
            user: <PublicKey as EdgeWire>::decode_wire(input)?,
            admission_node: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            request_hash: <Hash as EdgeWire>::decode_wire(input)?,
            assigned_route_commitment: <Hash as EdgeWire>::decode_wire(input)?,
            assigned_channel: <ChannelEndpoint as EdgeWire>::decode_wire(input)?,
            assigned_relay_path: <Vec<NodeId> as EdgeWire>::decode_wire(input)?,
            admitted_budget: <u64 as EdgeWire>::decode_wire(input)?,
            policy_hash: <Hash as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            valid_until_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for WorkReceipt {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.receipt_id.encode_wire(out);
        self.request_hash.encode_wire(out);
        self.admission_hash.encode_wire(out);
        self.worker.encode_wire(out);
        self.relay_node_id.encode_wire(out);
        self.input_hash.encode_wire(out);
        self.output_hash.encode_wire(out);
        self.units_used.encode_wire(out);
        self.total_claim.encode_wire(out);
        self.sequence.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            receipt_id: <Hash as EdgeWire>::decode_wire(input)?,
            request_hash: <Hash as EdgeWire>::decode_wire(input)?,
            admission_hash: <Hash as EdgeWire>::decode_wire(input)?,
            worker: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            relay_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            input_hash: <Hash as EdgeWire>::decode_wire(input)?,
            output_hash: <Hash as EdgeWire>::decode_wire(input)?,
            units_used: <u64 as EdgeWire>::decode_wire(input)?,
            total_claim: <u64 as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for WorkPacket {
    fn encode_wire(&self, out: &mut WireWriter) {
        match self {
            Self::NodeAvailable(value) => {
                (0u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::NodeHeartbeat(value) => {
                (1u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::RelayAssignment(value) => {
                (2u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::NetworkMessage(value) => {
                (3u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::WorkRequest(value) => {
                (4u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::WorkAdmission(value) => {
                (5u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::WorkReceipt(value) => {
                (6u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::Ack(value) => {
                (7u16).encode_wire(out);
                value.encode_wire(out);
            }
        }
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        match u16::decode_wire(input)? {
            0 => Ok(Self::NodeAvailable(
                <NodeAvailable as EdgeWire>::decode_wire(input)?,
            )),
            1 => Ok(Self::NodeHeartbeat(
                <NodeHeartbeat as EdgeWire>::decode_wire(input)?,
            )),
            2 => Ok(Self::RelayAssignment(
                <RelayAssignment as EdgeWire>::decode_wire(input)?,
            )),
            3 => Ok(Self::NetworkMessage(
                <NetworkMessage as EdgeWire>::decode_wire(input)?,
            )),
            4 => Ok(Self::WorkRequest(<WorkRequest as EdgeWire>::decode_wire(
                input,
            )?)),
            5 => Ok(Self::WorkAdmission(
                <WorkAdmission as EdgeWire>::decode_wire(input)?,
            )),
            6 => Ok(Self::WorkReceipt(<WorkReceipt as EdgeWire>::decode_wire(
                input,
            )?)),
            7 => Ok(Self::Ack(<WorkAck as EdgeWire>::decode_wire(input)?)),
            _ => Err(WorkProtocolError::InvalidShape),
        }
    }
}

impl EdgeWire for WorkAck {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.ok.encode_wire(out);
        self.code.encode_wire(out);
        self.text.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            ok: <bool as EdgeWire>::decode_wire(input)?,
            code: <u16 as EdgeWire>::decode_wire(input)?,
            text: <String as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for RelayEndpoint {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.relay_node_id.encode_wire(out);
        self.channel.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            relay_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            channel: <ChannelEndpoint as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NodeAvailable {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.node.encode_wire(out);
        self.relay_endpoint.encode_wire(out);
        self.sequence.encode_wire(out);
        self.unix_ms.encode_wire(out);
        self.heartbeat_secs.encode_wire(out);
        self.log_head.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            node: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            relay_endpoint: <Option<ChannelEndpoint> as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            heartbeat_secs: <u64 as EdgeWire>::decode_wire(input)?,
            log_head: <Hash as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NodeHeartbeat {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.node.encode_wire(out);
        self.sequence.encode_wire(out);
        self.unix_ms.encode_wire(out);
        self.connection_hash.encode_wire(out);
        self.log_head.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            node: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            connection_hash: <Hash as EdgeWire>::decode_wire(input)?,
            log_head: <Hash as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for RelayAssignment {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.node_id.encode_wire(out);
        self.relay.encode_wire(out);
        self.assigned_by.encode_wire(out);
        self.sequence.encode_wire(out);
        self.valid_until_unix_ms.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            relay: <RelayEndpoint as EdgeWire>::decode_wire(input)?,
            assigned_by: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            valid_until_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ChannelEndpoint {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.channel_id.encode_wire(out);
        self.kind.encode_wire(out);
        self.address.encode_wire(out);
        self.label.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            channel_id: <ChannelId as EdgeWire>::decode_wire(input)?,
            kind: <u16 as EdgeWire>::decode_wire(input)?,
            address: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            label: <String as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for RouteBinding {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.node.encode_wire(out);
        self.relay_node_id.encode_wire(out);
        self.endpoint.encode_wire(out);
        self.roles.encode_wire(out);
        self.departments.encode_wire(out);
        self.valid_until_unix_ms.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            node: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            relay_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            endpoint: <ChannelEndpoint as EdgeWire>::decode_wire(input)?,
            roles: <Vec<u16> as EdgeWire>::decode_wire(input)?,
            departments: <Vec<u16> as EdgeWire>::decode_wire(input)?,
            valid_until_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ChannelEnvelope {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.channel_id.encode_wire(out);
        self.from.encode_wire(out);
        self.to.encode_wire(out);
        self.route_hash.encode_wire(out);
        self.packet_hash.encode_wire(out);
        self.packet.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            channel_id: <ChannelId as EdgeWire>::decode_wire(input)?,
            from: <NodeId as EdgeWire>::decode_wire(input)?,
            to: <NodeId as EdgeWire>::decode_wire(input)?,
            route_hash: <Hash as EdgeWire>::decode_wire(input)?,
            packet_hash: <Hash as EdgeWire>::decode_wire(input)?,
            packet: <WorkPacket as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ChannelProof {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.channel_id.encode_wire(out);
        self.relay_node_id.encode_wire(out);
        self.from.encode_wire(out);
        self.to.encode_wire(out);
        self.message_hash.encode_wire(out);
        self.sequence.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            channel_id: <ChannelId as EdgeWire>::decode_wire(input)?,
            relay_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            from: <NodeId as EdgeWire>::decode_wire(input)?,
            to: <NodeId as EdgeWire>::decode_wire(input)?,
            message_hash: <Hash as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ObjectStoreRequest {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.manifest_hash.encode_wire(out);
        self.job_id.encode_wire(out);
        self.shard_index.encode_wire(out);
        self.shard_hash.encode_wire(out);
        self.original_len.encode_wire(out);
        self.bytes.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            manifest_hash: <Hash as EdgeWire>::decode_wire(input)?,
            job_id: <Hash as EdgeWire>::decode_wire(input)?,
            shard_index: <u16 as EdgeWire>::decode_wire(input)?,
            shard_hash: <Hash as EdgeWire>::decode_wire(input)?,
            original_len: <u64 as EdgeWire>::decode_wire(input)?,
            bytes: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ObjectRetrieveRequest {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.manifest_hash.encode_wire(out);
        self.job_id.encode_wire(out);
        self.shard_index.encode_wire(out);
        self.shard_hash.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            manifest_hash: <Hash as EdgeWire>::decode_wire(input)?,
            job_id: <Hash as EdgeWire>::decode_wire(input)?,
            shard_index: <u16 as EdgeWire>::decode_wire(input)?,
            shard_hash: <Hash as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ObjectRetrieveResponse {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.manifest_hash.encode_wire(out);
        self.job_id.encode_wire(out);
        self.shard_index.encode_wire(out);
        self.shard_hash.encode_wire(out);
        self.bytes.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            manifest_hash: <Hash as EdgeWire>::decode_wire(input)?,
            job_id: <Hash as EdgeWire>::decode_wire(input)?,
            shard_index: <u16 as EdgeWire>::decode_wire(input)?,
            shard_hash: <Hash as EdgeWire>::decode_wire(input)?,
            bytes: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for StoragePayload {
    fn encode_wire(&self, out: &mut WireWriter) {
        match self {
            Self::StoreRequest(value) => {
                (0u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::RetrieveRequest(value) => {
                (1u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::RetrieveResponse(value) => {
                (2u16).encode_wire(out);
                value.encode_wire(out);
            }
        }
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        match u16::decode_wire(input)? {
            0 => Ok(Self::StoreRequest(
                <ObjectStoreRequest as EdgeWire>::decode_wire(input)?,
            )),
            1 => Ok(Self::RetrieveRequest(
                <ObjectRetrieveRequest as EdgeWire>::decode_wire(input)?,
            )),
            2 => Ok(Self::RetrieveResponse(
                <ObjectRetrieveResponse as EdgeWire>::decode_wire(input)?,
            )),
            _ => Err(WorkProtocolError::InvalidShape),
        }
    }
}

impl EdgeWire for RecipientMessagePolicy {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.recipient.encode_wire(out);
        self.sequence.encode_wire(out);
        self.valid_until_unix_ms.encode_wire(out);
        self.allow_unknown_senders.encode_wire(out);
        self.allowed_senders.encode_wire(out);
        self.blocked_senders.encode_wire(out);
        self.allowed_relays.encode_wire(out);
        self.allowed_departments.encode_wire(out);
        self.allowed_work_types.encode_wire(out);
        self.max_payload_bytes.encode_wire(out);
        self.policy_hash.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            recipient: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            valid_until_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            allow_unknown_senders: <bool as EdgeWire>::decode_wire(input)?,
            allowed_senders: <Vec<NodeId> as EdgeWire>::decode_wire(input)?,
            blocked_senders: <Vec<NodeId> as EdgeWire>::decode_wire(input)?,
            allowed_relays: <Vec<NodeId> as EdgeWire>::decode_wire(input)?,
            allowed_departments: <Vec<u16> as EdgeWire>::decode_wire(input)?,
            allowed_work_types: <Vec<u16> as EdgeWire>::decode_wire(input)?,
            max_payload_bytes: <u64 as EdgeWire>::decode_wire(input)?,
            policy_hash: <Hash as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for AdmittedCapabilityRoute {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.route_id.encode_wire(out);
        self.request_hash.encode_wire(out);
        self.admission_hash.encode_wire(out);
        self.user.encode_wire(out);
        self.source_node_id.encode_wire(out);
        self.target_node_id.encode_wire(out);
        self.relay_node_id.encode_wire(out);
        self.relay_path.encode_wire(out);
        self.role.encode_wire(out);
        self.department.encode_wire(out);
        self.work_type.encode_wire(out);
        self.admission_route_commitment.encode_wire(out);
        self.target_route_commitment.encode_wire(out);
        self.policy_hash.encode_wire(out);
        self.admitted_budget.encode_wire(out);
        self.valid_until_unix_ms.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            route_id: <Hash as EdgeWire>::decode_wire(input)?,
            request_hash: <Hash as EdgeWire>::decode_wire(input)?,
            admission_hash: <Hash as EdgeWire>::decode_wire(input)?,
            user: <PublicKey as EdgeWire>::decode_wire(input)?,
            source_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            target_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            relay_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            relay_path: <Vec<NodeId> as EdgeWire>::decode_wire(input)?,
            role: <u16 as EdgeWire>::decode_wire(input)?,
            department: <u16 as EdgeWire>::decode_wire(input)?,
            work_type: <u16 as EdgeWire>::decode_wire(input)?,
            admission_route_commitment: <Hash as EdgeWire>::decode_wire(input)?,
            target_route_commitment: <Hash as EdgeWire>::decode_wire(input)?,
            policy_hash: <Hash as EdgeWire>::decode_wire(input)?,
            admitted_budget: <u64 as EdgeWire>::decode_wire(input)?,
            valid_until_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NotarySealRequest {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.aad.encode_wire(out);
        self.plaintext_hash.encode_wire(out);
        self.plaintext.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            aad: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            plaintext_hash: <Hash as EdgeWire>::decode_wire(input)?,
            plaintext: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NotarySealResponse {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.notary.encode_wire(out);
        self.requester.encode_wire(out);
        self.aad_hash.encode_wire(out);
        self.plaintext_hash.encode_wire(out);
        self.sealed_hash.encode_wire(out);
        self.sealed_envelope.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            notary: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            requester: <NodeId as EdgeWire>::decode_wire(input)?,
            aad_hash: <Hash as EdgeWire>::decode_wire(input)?,
            plaintext_hash: <Hash as EdgeWire>::decode_wire(input)?,
            sealed_hash: <Hash as EdgeWire>::decode_wire(input)?,
            sealed_envelope: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NotaryUnsealRequest {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.aad.encode_wire(out);
        self.sealed_hash.encode_wire(out);
        self.sealed_envelope.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            aad: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            sealed_hash: <Hash as EdgeWire>::decode_wire(input)?,
            sealed_envelope: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NotaryDeliveryReport {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.notary.encode_wire(out);
        self.requester.encode_wire(out);
        self.request_message_id.encode_wire(out);
        self.request_payload_hash.encode_wire(out);
        self.via_relay.encode_wire(out);
        self.sequence.encode_wire(out);
        self.aad_hash.encode_wire(out);
        self.sealed_hash.encode_wire(out);
        self.plaintext_hash.encode_wire(out);
        self.opened_unix_ms.encode_wire(out);
        self.signature.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            notary: <NodeIdentity as EdgeWire>::decode_wire(input)?,
            requester: <NodeId as EdgeWire>::decode_wire(input)?,
            request_message_id: <Hash as EdgeWire>::decode_wire(input)?,
            request_payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            via_relay: <NodeId as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            aad_hash: <Hash as EdgeWire>::decode_wire(input)?,
            sealed_hash: <Hash as EdgeWire>::decode_wire(input)?,
            plaintext_hash: <Hash as EdgeWire>::decode_wire(input)?,
            opened_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            signature: <WorkSignature as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NotaryUnsealResponse {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.plaintext_hash.encode_wire(out);
        self.plaintext.encode_wire(out);
        self.delivery_report.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            plaintext_hash: <Hash as EdgeWire>::decode_wire(input)?,
            plaintext: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            delivery_report: <NotaryDeliveryReport as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for NotaryPayload {
    fn encode_wire(&self, out: &mut WireWriter) {
        match self {
            Self::SealRequest(value) => {
                (0u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::SealResponse(value) => {
                (1u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::UnsealRequest(value) => {
                (2u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::UnsealResponse(value) => {
                (3u16).encode_wire(out);
                value.encode_wire(out);
            }
        }
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        match u16::decode_wire(input)? {
            0 => Ok(Self::SealRequest(
                <NotarySealRequest as EdgeWire>::decode_wire(input)?,
            )),
            1 => Ok(Self::SealResponse(
                <NotarySealResponse as EdgeWire>::decode_wire(input)?,
            )),
            2 => Ok(Self::UnsealRequest(
                <NotaryUnsealRequest as EdgeWire>::decode_wire(input)?,
            )),
            3 => Ok(Self::UnsealResponse(
                <NotaryUnsealResponse as EdgeWire>::decode_wire(input)?,
            )),
            _ => Err(WorkProtocolError::InvalidShape),
        }
    }
}

impl EdgeWire for SealedMessagePayload {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.from.encode_wire(out);
        self.to.encode_wire(out);
        self.recipient_encryption_key.encode_wire(out);
        self.ephemeral_public_key.encode_wire(out);
        self.nonce.encode_wire(out);
        self.ciphertext.encode_wire(out);
        self.tag.encode_wire(out);
        self.plaintext_hash.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            from: <NodeId as EdgeWire>::decode_wire(input)?,
            to: <NodeId as EdgeWire>::decode_wire(input)?,
            recipient_encryption_key: <EncryptionPublicKey as EdgeWire>::decode_wire(input)?,
            ephemeral_public_key: <EncryptionPublicKey as EdgeWire>::decode_wire(input)?,
            nonce: <[u8; NONCE_LEN] as EdgeWire>::decode_wire(input)?,
            ciphertext: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            tag: <[u8; TAG_LEN] as EdgeWire>::decode_wire(input)?,
            plaintext_hash: <Hash as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for CapabilityEnvelope {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.session_id.encode_wire(out);
        self.invocation_id.encode_wire(out);
        self.capability_id.encode_wire(out);
        self.source_node_id.encode_wire(out);
        self.target_node_id.encode_wire(out);
        self.kind.encode_wire(out);
        self.operation.encode_wire(out);
        self.content_type.encode_wire(out);
        self.sequence.encode_wire(out);
        self.timestamp_unix_ms.encode_wire(out);
        self.payload_hash.encode_wire(out);
        self.payload.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            session_id: <Hash as EdgeWire>::decode_wire(input)?,
            invocation_id: <Hash as EdgeWire>::decode_wire(input)?,
            capability_id: <Hash as EdgeWire>::decode_wire(input)?,
            source_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            target_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            kind: <u16 as EdgeWire>::decode_wire(input)?,
            operation: <u16 as EdgeWire>::decode_wire(input)?,
            content_type: <u16 as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            timestamp_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            payload: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramEnv {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.key.encode_wire(out);
        self.value.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            key: <String as EdgeWire>::decode_wire(input)?,
            value: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramOpen {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.session_id.encode_wire(out);
        self.program.encode_wire(out);
        self.args.encode_wire(out);
        self.env.encode_wire(out);
        self.cwd.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            session_id: <Hash as EdgeWire>::decode_wire(input)?,
            program: <String as EdgeWire>::decode_wire(input)?,
            args: <Vec<String> as EdgeWire>::decode_wire(input)?,
            env: <Vec<ProgramEnv> as EdgeWire>::decode_wire(input)?,
            cwd: <String as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramStdin {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.session_id.encode_wire(out);
        self.bytes.encode_wire(out);
        self.eof.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            session_id: <Hash as EdgeWire>::decode_wire(input)?,
            bytes: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            eof: <bool as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramClose {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.session_id.encode_wire(out);
        self.signal.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            session_id: <Hash as EdgeWire>::decode_wire(input)?,
            signal: <u16 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramPoll {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.session_id.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            session_id: <Hash as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramOutput {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.session_id.encode_wire(out);
        self.stream.encode_wire(out);
        self.bytes.encode_wire(out);
        self.eof.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            session_id: <Hash as EdgeWire>::decode_wire(input)?,
            stream: <u16 as EdgeWire>::decode_wire(input)?,
            bytes: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            eof: <bool as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramExit {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.session_id.encode_wire(out);
        self.code.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            session_id: <Hash as EdgeWire>::decode_wire(input)?,
            code: <i32 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ProgramIoPayload {
    fn encode_wire(&self, out: &mut WireWriter) {
        match self {
            Self::Open(value) => {
                (0u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::Stdin(value) => {
                (1u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::Close(value) => {
                (2u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::Poll(value) => {
                (3u16).encode_wire(out);
                value.encode_wire(out);
            }
        }
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        match u16::decode_wire(input)? {
            0 => Ok(Self::Open(<ProgramOpen as EdgeWire>::decode_wire(input)?)),
            1 => Ok(Self::Stdin(<ProgramStdin as EdgeWire>::decode_wire(input)?)),
            2 => Ok(Self::Close(<ProgramClose as EdgeWire>::decode_wire(input)?)),
            3 => Ok(Self::Poll(<ProgramPoll as EdgeWire>::decode_wire(input)?)),
            _ => Err(WorkProtocolError::InvalidShape),
        }
    }
}

impl EdgeWire for ProgramIoEvent {
    fn encode_wire(&self, out: &mut WireWriter) {
        match self {
            Self::Output(value) => {
                (0u16).encode_wire(out);
                value.encode_wire(out);
            }
            Self::Exit(value) => {
                (1u16).encode_wire(out);
                value.encode_wire(out);
            }
        }
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        match u16::decode_wire(input)? {
            0 => Ok(Self::Output(<ProgramOutput as EdgeWire>::decode_wire(
                input,
            )?)),
            1 => Ok(Self::Exit(<ProgramExit as EdgeWire>::decode_wire(input)?)),
            _ => Err(WorkProtocolError::InvalidShape),
        }
    }
}

impl EdgeWire for ProgramIoEvents {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.events.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            events: <Vec<ProgramIoEvent> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ContactPublicId {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.kind.encode_wire(out);
        self.value.encode_wire(out);
        self.label.encode_wire(out);
        self.verified_at_unix_ms.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            kind: <u16 as EdgeWire>::decode_wire(input)?,
            value: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            label: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            verified_at_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ExternalContactRef {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.kind.encode_wire(out);
        self.value.encode_wire(out);
        self.label.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            kind: <u16 as EdgeWire>::decode_wire(input)?,
            value: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            label: <Vec<u8> as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ContactObject {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.contact_id.encode_wire(out);
        self.primary_node_id.encode_wire(out);
        self.display_name.encode_wire(out);
        self.avatar_payload_hash.encode_wire(out);
        self.public_ids.encode_wire(out);
        self.external_contacts.encode_wire(out);
        self.updated_unix_ms.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            contact_id: <Hash as EdgeWire>::decode_wire(input)?,
            primary_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            display_name: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            avatar_payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            public_ids: <Vec<ContactPublicId> as EdgeWire>::decode_wire(input)?,
            external_contacts: <Vec<ExternalContactRef> as EdgeWire>::decode_wire(input)?,
            updated_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for MessageObject {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.message_id.encode_wire(out);
        self.thread_id.encode_wire(out);
        self.from.encode_wire(out);
        self.to.encode_wire(out);
        self.sequence.encode_wire(out);
        self.created_unix_ms.encode_wire(out);
        self.message_kind.encode_wire(out);
        self.payload_hash.encode_wire(out);
        self.payload_len.encode_wire(out);
        self.sealed_payload_hash.encode_wire(out);
        self.storage_ref.encode_wire(out);
        self.previous_message_hash.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            message_id: <Hash as EdgeWire>::decode_wire(input)?,
            thread_id: <Hash as EdgeWire>::decode_wire(input)?,
            from: <NodeId as EdgeWire>::decode_wire(input)?,
            to: <NodeId as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            created_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            message_kind: <u16 as EdgeWire>::decode_wire(input)?,
            payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            payload_len: <u64 as EdgeWire>::decode_wire(input)?,
            sealed_payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            storage_ref: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            previous_message_hash: <Hash as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ThreadMessageRef {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.message_id.encode_wire(out);
        self.payload_hash.encode_wire(out);
        self.sequence.encode_wire(out);
        self.created_unix_ms.encode_wire(out);
        self.from.encode_wire(out);
        self.message_kind.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            message_id: <Hash as EdgeWire>::decode_wire(input)?,
            payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
            sequence: <u64 as EdgeWire>::decode_wire(input)?,
            created_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            from: <NodeId as EdgeWire>::decode_wire(input)?,
            message_kind: <u16 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ThreadObject {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.thread_id.encode_wire(out);
        self.participant_a.encode_wire(out);
        self.participant_b.encode_wire(out);
        self.created_unix_ms.encode_wire(out);
        self.updated_unix_ms.encode_wire(out);
        self.message_count.encode_wire(out);
        self.head_message_hash.encode_wire(out);
        self.tail_message_hash.encode_wire(out);
        self.entries.encode_wire(out);
        self.thread_hash.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            thread_id: <Hash as EdgeWire>::decode_wire(input)?,
            participant_a: <NodeId as EdgeWire>::decode_wire(input)?,
            participant_b: <NodeId as EdgeWire>::decode_wire(input)?,
            created_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            updated_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            message_count: <u64 as EdgeWire>::decode_wire(input)?,
            head_message_hash: <Hash as EdgeWire>::decode_wire(input)?,
            tail_message_hash: <Hash as EdgeWire>::decode_wire(input)?,
            entries: <Vec<ThreadMessageRef> as EdgeWire>::decode_wire(input)?,
            thread_hash: <Hash as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ContactBookContactRef {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.contact_id.encode_wire(out);
        self.primary_node_id.encode_wire(out);
        self.display_name.encode_wire(out);
        self.avatar_payload_hash.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            contact_id: <Hash as EdgeWire>::decode_wire(input)?,
            primary_node_id: <NodeId as EdgeWire>::decode_wire(input)?,
            display_name: <Vec<u8> as EdgeWire>::decode_wire(input)?,
            avatar_payload_hash: <Hash as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ContactBookThreadRef {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.thread_id.encode_wire(out);
        self.participant_a.encode_wire(out);
        self.participant_b.encode_wire(out);
        self.message_count.encode_wire(out);
        self.head_message_hash.encode_wire(out);
        self.updated_unix_ms.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            thread_id: <Hash as EdgeWire>::decode_wire(input)?,
            participant_a: <NodeId as EdgeWire>::decode_wire(input)?,
            participant_b: <NodeId as EdgeWire>::decode_wire(input)?,
            message_count: <u64 as EdgeWire>::decode_wire(input)?,
            head_message_hash: <Hash as EdgeWire>::decode_wire(input)?,
            updated_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
        })
    }
}

impl EdgeWire for ContactBook {
    fn encode_wire(&self, out: &mut WireWriter) {
        self.abi_version.encode_wire(out);
        self.owner.encode_wire(out);
        self.contacts.encode_wire(out);
        self.threads.encode_wire(out);
        self.updated_unix_ms.encode_wire(out);
        self.contact_book_hash.encode_wire(out);
    }

    fn decode_wire(input: &mut WireCursor<'_>) -> Result<Self, WorkProtocolError> {
        Ok(Self {
            abi_version: <u16 as EdgeWire>::decode_wire(input)?,
            owner: <NodeId as EdgeWire>::decode_wire(input)?,
            contacts: <Vec<ContactBookContactRef> as EdgeWire>::decode_wire(input)?,
            threads: <Vec<ContactBookThreadRef> as EdgeWire>::decode_wire(input)?,
            updated_unix_ms: <u64 as EdgeWire>::decode_wire(input)?,
            contact_book_hash: <Hash as EdgeWire>::decode_wire(input)?,
        })
    }
}
