[package]
name = "edgerun-tftp"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "TFTP client for kernel loading"

[features]
default = []
# Compatibility only: server support is always no_std now.
server = []

[dependencies]
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding", default-features = false }
edgerun-rt = { version = "0.1", path = "../edgerun-rt" }
edgerun-log = { version = "0.1", path = "../edgerun-log" }

[lints]
workspace = true
