[package]
name = "edgerun-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Generated Edgerun protocol v0 protobuf types"

[dependencies]
edgerun-json = { version = "0.1", path = "../edgerun-json" }
prost = { workspace = true, features = ["std"] }
prost-types = { workspace = true, features = ["std"] }

[build-dependencies]
prost-build.workspace = true

[lints]
workspace = true
