[package]
name = "edgerun-sdk-unit-ethernet-ipv4-v1"
version = "0.1.1"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[package.metadata.edgerun.unit]
id = "ethernet-ipv4-v1"
standard = "ETHERNET-IPV4"

[dependencies]
edgerun-protocols = { version = "0.1.1", path = "../../../../protocol/edgerun-protocols", default-features = false, features = ["ethernet-ipv4"] }
edgerun-unit = { version = "0.1.1", path = "../../../../edgerun-unit" }

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true
