[features]
resolution = true
skip-lint = false

[programs.localnet]
edgerun_program = "Fg6PaFpoGXkYsidMpWxTWqkZK8mJzqzH9uM6YqkB6x6a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
