[package]
name = "edgerun-rustls-native-certs"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun shim for rustls-native-certs"

[dependencies]
pki_types = { package = "edgerun-rustls-pki-types", path = "../edgerun-rustls-pki-types", default-features = false, features = ["alloc"] }

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
openssl-probe = { package = "openssl-probe", path = "../../../vendor/cargo/openssl-probe" }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = { package = "security-framework", path = "../../../vendor/cargo/security-framework" }

[target.'cfg(windows)'.dependencies]
schannel = { package = "schannel", path = "../../../vendor/cargo/schannel" }

[lints]
workspace = true
