[package]
name = "edgerun-sdk-unit-blake3-1024"
version = "0.1.1"
edition = "2021"
publish = false

[package.metadata.edgerun.unit]
id = "blake3-1024"
standard = "BLAKE3"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = { version = "1", default-features = false }
edgerun-unit = { version = "0.1.1", path = "../../../../edgerun-unit" }

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true
