[package]
name = "edgerun-sdk-unit-capability-provider-v1"
version = "0.1.1"
edition = "2021"
publish = false

[package.metadata.edgerun.unit]
id = "capability-provider-v1"
standard = "edgerun.v0.capability_runtime"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
edgerun-unit = { version = "0.1.1", path = "../../../../edgerun-unit" }

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = true
strip = true
