// EdgeRun Build Script — manifest-based module builder
import { readFileSync, writeFileSync, statSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { execSync } from 'child_process';
import {
  resolveRoot, rootPath, readFile, writeFile, fileExists,
  concatFragments, compileWat, wrapModule,
  buildSourcePayload, bytesToWatString
} from './build-lib.mjs';

function ensureDir(path) {
  if (!existsSync(path)) mkdirSync(path, { recursive: true });
}

const ROOT = resolveRoot();

// Load manifest.json and filter for the standard build
const manifestJson = JSON.parse(readFileSync(rootPath('manifest.json'), 'utf-8'));
const MANIFEST = manifestJson
  .filter(e => !e.builds || e.builds.includes('standard'))
  .map(e => e.path);

// ── Generate data/embedded-source.wat ───────────────────────
function generateSourceData(sourceFiles) {
  const payload = buildSourcePayload(sourceFiles);
  const addr = 0x3400000;
  const lines = [];
  lines.push(';; Auto-generated by build.mjs — do not edit');
  lines.push('');
  lines.push(`(global $ER_TOOLS_SOURCE_ADDR (export "ER_TOOLS_SOURCE_ADDR") i32 (i32.const ${addr}))`);
  lines.push(`(global $ER_TOOLS_SOURCE_LEN (export "ER_TOOLS_SOURCE_LEN") i32 (i32.const ${payload.length}))`);
  lines.push('');

  const chunkSize = 2000;
  let offset = 0;
  while (offset < payload.length) {
    const end = Math.min(offset + chunkSize, payload.length);
    const chunk = payload.slice(offset, end);
    const escaped = bytesToWatString(chunk);
    lines.push(`(data (i32.const ${addr + offset}) "${escaped}")`);
    offset = end;
  }

  lines.push('');
  lines.push('(start $er_tools_auto_init)');
  lines.push('(func $er_tools_auto_init');
  lines.push(`  (drop (call \$init_source`);
  lines.push(`    (global.get \$ER_TOOLS_SOURCE_ADDR)`);
  lines.push(`    (global.get \$ER_TOOLS_SOURCE_LEN)))`);
  lines.push(')');

  const outPath = rootPath('out/data/embedded-source.wat');
  ensureDir(dirname(outPath));
  writeFile(outPath, lines.join('\n') + '\n');
  const fileCount = Object.keys(sourceFiles).length;
  const chunkCount = Math.ceil(payload.length / 2000);
  console.log(`✓ data/embedded-source.wat generated (${(payload.length / 1024).toFixed(0)} KB, ${fileCount} files, ${chunkCount} data chunks)`);
}

function collectManifestSources(root, manifest) {
  const files = {};
  for (const filePath of manifest) {
    const fullPath = resolve(root, filePath);
    try { files[filePath] = readFileSync(fullPath, 'utf8'); } catch {}
  }
  return files;
}

function build() {
  // ── Collect source files ────────────────────────────────
  const sourceFiles = collectManifestSources(ROOT, MANIFEST);
  delete sourceFiles['out/data/embedded-source.wat'];

  // ── Generate embedded-source.wat ────────────────────────
  generateSourceData(sourceFiles);

  // ── Concatenate manifest + wrap in module ───────────────
  const outPath = rootPath('out/edgerun.wat');
  ensureDir(dirname(outPath));
  const { body, count } = concatFragments(MANIFEST, ROOT);
  const moduleWat = wrapModule(body);
  writeFile(outPath, moduleWat);
  console.log(`✓ ${count} fragments → ${outPath} (${(moduleWat.length / 1024).toFixed(0)} KB)`);

  // ── Parse with wasm-tools ──────────────────────────────
  const wasmPath = rootPath('out/edgerun.wasm');
  try {
    execSync(`wasm-tools parse "${outPath}" -o "${wasmPath}"`, { stdio: 'pipe' });
    const wSize = statSync(wasmPath).size;
    console.log(`✓ ${wasmPath} (${(wSize / 1024).toFixed(0)} KB)`);
  } catch (e) {
    console.error(`  ✗ wasm-tools parse failed: ${e.stderr?.slice(0, 2000) || e.message}`);
    process.exit(1);
  }
}

build();
