[package]
name = "edgerun-tokio"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Edgerun-owned Tokio-compatible async runtime facade"

[features]
default = ["edgerun-runtime"]
compat = []
edgerun-runtime = ["dep:edgerun-runtime"]
fs = []
io-util = []
macros = []
net = []
process = []
rt = []
rt-multi-thread = []
signal = []
sync = []
time = []

[dependencies]
edgerun-futures = { version = "0.1", path = "../edgerun-futures" }
edgerun-runtime = { version = "0.1", path = "../edgerun-runtime", default-features = false, features = ["std"], optional = true }

[lints]
workspace = true
