[package]
edition.workspace = true
license.workspace = true
name = "codex-client"
version.workspace = true

[features]
default = ["native-transport"]
native-transport = [
    "dep:edgerun-reqwest",
    "dep:edgerun-rustls-native-certs",
    "dep:edgerun-rustls-pki-types",
    "dep:edgerun-rusttls",
    "dep:opentelemetry",
    "dep:tracing-opentelemetry",
    "edgerun-reqwest/cookies",
    "edgerun-reqwest/http1",
    "edgerun-reqwest/http2",
    "edgerun-reqwest/http3",
    "edgerun-reqwest/native-root",
    "edgerun-reqwest/rustls-tls-native-roots",
    "edgerun-reqwest/stream",
]

[dependencies]
edgerun-async-trait = { workspace = true }
edgerun-bytes = { workspace = true }
edgerun-error = { workspace = true }
edgerun-eventsource-stream = { workspace = true }
edgerun-http = { workspace = true }
edgerun-json = { workspace = true }
edgerun-random = { workspace = true }
edgerun-futures = { workspace = true }
opentelemetry = { workspace = true, optional = true }
edgerun-reqwest = { workspace = true, default-features = false, optional = true }
edgerun-rustls-native-certs = { workspace = true, optional = true }
edgerun-rustls-pki-types = { workspace = true, optional = true }
edgerun-rusttls = { workspace = true, optional = true }
edgerun-tokio = { workspace = true, features = ["macros", "rt", "time", "sync"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true, optional = true }
edgerun-zstd = { workspace = true }

[lints]
workspace = true
