---
apiVersion: edgerun.io/v1alpha1
kind: SmtpServer
metadata:
  name: mail
  namespace: edgerun-mail
spec:
  hostname: mail.edgerun.tech
  bind_address: "0.0.0.0:25"
  smtps: true
  starttls: true
  max_message_size: 35882577
  local_domains:
    - edgerun.tech
  maildir_root: /var/lib/edgerun/mail/maildirs
  relay_enabled: true
  queue_dir: /var/lib/edgerun/mail/queue
  dns_server: "1.1.1.1:53"
  dkim_domain: edgerun.tech
  dkim_selector: mail
  dkim_key_path: /etc/edgerun/mail/dkim-mail.private.pem
  tls_cert: /etc/edgerun/mail/tls/fullchain.pem
  tls_key: /etc/edgerun/mail/tls/privkey.pem
  acme_enabled: true
  acme_directory: letsencrypt
  acme_contact_email: ken@edgerun.tech
  acme_domains:
    - mail.edgerun.tech
    - mta-sts.edgerun.tech
  acme_account_key_path: /etc/edgerun/mail/acme-account.pem
  acme_cert_dir: /etc/edgerun/mail/tls
  catch_all_user: ken
  users:
    - username: ken
      domains:
        - edgerun.tech
