[package]
name = "edgerun-fingerprint"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Fingerprint biometric abstractions for Edgerun"

[dependencies]
edgerun-biometrics = { version = "0.1", path = "../edgerun-biometrics" }

[lints]
workspace = true
