[package]
name = "edgerun-oci"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "OCI container runtime and registry client — pull, push, login, create, start, exec containers"

[dependencies]
edgerun-json = { path = "../edgerun-json", features = ["serde"] }
edgerun-crypto.workspace = true
edgerun-http = { path = "../edgerun-http", features = ["tls"] }
edgerun-rt = { path = "../edgerun-rt" }
edgerun-tls = { path = "../edgerun-tls" }
edgerun-secret-service = { path = "../edgerun-secret-service" }
edgerun-core = { path = "../edgerun-core" }
serde = { version = "1", features = ["derive"] }
libc = "0.2"
flate2 = "1"
tar = "0.4"
zstd = "0.13"

[[bin]]
name = "ert"
path = "src/bin/ert.rs"

[lints]
workspace = true
