[package]
name = "edgerun-json-derive"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/edgerun-tech/edgerun"
homepage = "https://github.com/edgerun-tech/edgerun"
description = "Derive macros for edgerun-json"

[lib]
proc-macro = true
