[package]
name = "edgerun-json-derive"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/Sylchi/edgerun_reference_core"
homepage = "https://github.com/Sylchi/edgerun_reference_core"
description = "Derive macros for edgerun-json"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing", "extra-traits", "printing"] }
