[package]
name = "edgerun-quic"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "QUIC transport protocol (RFC 9000)"

[features]
default = []
std = []

[lints]
workspace = true

[dependencies]
edgerun-tls = { version = "0.1", path = "../edgerun-tls", default-features = false }
edgerun-crypto = { version = "0.1", path = "../edgerun-crypto", default-features = false, features = ["aead", "ed25519", "hmac", "p256", "rsa"] }
edgerun-rt = { version = "0.1", path = "../edgerun-rt" }
edgerun-encoding = { version = "0.1", path = "../edgerun-encoding", default-features = false }
