//! Parse `/etc/resolv.conf` to extract nameserver addresses.
//!
//! Supports the standard directives:
//! - `nameserver <ip>` — one per line, up to 3 (MAXNS)
//! - `port <number>` — default port for all nameservers
//! - Ignores comments (`#`), blank lines, and unknown directives

use crate::std::net::{IpAddr, SocketAddr};
use alloc::{
    boxed::Box,
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};

const RESOLV_CONF: &str = "/etc/resolv.conf";
const MAXNS: usize = 3;
const DEFAULT_DNS_PORT: u16 = 53;

/// A nameserver entry from resolv.conf.
#[derive(Debug, Clone)]
pub struct Nameserver {
    pub addr: IpAddr,
    pub port: u16,
}

/// Parsed resolv.conf configuration.
#[derive(Debug, Clone)]
pub struct ResolvConf {
    pub nameservers: Vec<Nameserver>,
    pub search: Vec<String>,
    pub domain: Option<String>,
    pub options: Vec<String>,
}

impl ResolvConf {
    /// Parse the system resolv.conf at `/etc/resolv.conf`.
    ///
    /// Returns a default configuration with `8.8.8.8:53` if the file
    /// doesn't exist or contains no nameservers.
    pub fn load() -> Self {
        Self::load_path(RESOLV_CONF)
    }

    /// Parse a resolv.conf from the given path.
    pub fn load_path(path: &str) -> Self {
        match crate::std::fs::read_to_string(path) {
            Ok(content) => Self::parse(&content),
            Err(_) => Self::default_with_fallback(),
        }
    }

    /// Parse resolv.conf content from a string.
    pub fn parse(content: &str) -> Self {
        let mut nameservers = Vec::new();
        let mut search = Vec::new();
        let mut domain = None;
        let mut options = Vec::new();
        let mut global_port = DEFAULT_DNS_PORT;

        for line in content.lines() {
            let line = line.split('#').next().unwrap_or("").trim();
            if line.is_empty() {
                continue;
            }

            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.is_empty() {
                continue;
            }

            match parts[0] {
                "nameserver" => {
                    if nameservers.len() >= MAXNS {
                        continue;
                    }
                    if let Some(addr) = parts.get(1).and_then(|s| s.parse::<IpAddr>().ok()) {
                        nameservers.push(Nameserver {
                            addr,
                            port: global_port,
                        });
                    }
                }
                "port" => {
                    if let Some(p) = parts.get(1).and_then(|s| s.parse::<u16>().ok()) {
                        global_port = p;
                        // Update existing nameservers
                        for ns in &mut nameservers {
                            ns.port = p;
                        }
                    }
                }
                "domain" => {
                    if let Some(d) = parts.get(1) {
                        domain = Some(d.to_string());
                    }
                }
                "search" => {
                    search = parts[1..].iter().map(|s| s.to_string()).collect();
                }
                "options" => {
                    options = parts[1..].iter().map(|s| s.to_string()).collect();
                }
                _ => {}
            }
        }

        let mut conf = Self {
            nameservers,
            search,
            domain,
            options,
        };

        if conf.nameservers.is_empty() {
            conf = Self::default_with_fallback();
        }

        conf
    }

    /// Return nameservers as `host:port` strings suitable for `DnsClient::new()`.
    pub fn server_addrs(&self) -> Vec<String> {
        self.nameservers
            .iter()
            .map(|ns| format!("{}:{}", ns.addr, ns.port))
            .collect()
    }

    /// Default fallback when resolv.conf is empty/missing.
    fn default_with_fallback() -> Self {
        Self {
            nameservers: vec![
                Nameserver {
                    addr: "8.8.8.8".parse().unwrap(),
                    port: DEFAULT_DNS_PORT,
                },
                Nameserver {
                    addr: "1.1.1.1".parse().unwrap(),
                    port: DEFAULT_DNS_PORT,
                },
            ],
            search: Vec::new(),
            domain: None,
            options: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_typical_resolv_conf() {
        let content = r#"# Generated by NetworkManager
search example.com local
nameserver 192.168.1.1
nameserver 10.0.0.1
nameserver 8.8.4.4
"#;
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.nameservers.len(), 3);
        assert_eq!(conf.nameservers[0].addr.to_string(), "192.168.1.1");
        assert_eq!(conf.nameservers[0].port, 53);
        assert_eq!(conf.search, vec!["example.com", "local"]);
        assert!(conf.domain.is_none());
    }

    #[test]
    fn parse_with_port_directive() {
        let content = r#"port 5353
nameserver 127.0.0.53
"#;
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.nameservers.len(), 1);
        assert_eq!(conf.nameservers[0].addr.to_string(), "127.0.0.53");
        assert_eq!(conf.nameservers[0].port, 5353);
    }

    #[test]
    fn parse_ipv6_nameserver() {
        let content = "nameserver ::1\n";
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.nameservers.len(), 1);
        assert_eq!(conf.nameservers[0].addr.to_string(), "::1");
    }

    #[test]
    fn parse_ignores_extra_nameservers() {
        let content =
            "nameserver 1.1.1.1\nnameserver 2.2.2.2\nnameserver 3.3.3.3\nnameserver 4.4.4.4\n";
        let conf = ResolvConf::parse(content);
        assert_eq!(conf.nameservers.len(), 3); // MAXNS
    }

    #[test]
    fn fallback_on_empty() {
        let conf = ResolvConf::parse("");
        assert!(!conf.nameservers.is_empty());
        assert_eq!(conf.nameservers[0].addr.to_string(), "8.8.8.8");
    }

    #[test]
    fn server_addrs_format() {
        let content = "nameserver 192.168.1.1\nnameserver 10.0.0.1\n";
        let conf = ResolvConf::parse(content);
        let addrs = conf.server_addrs();
        assert_eq!(addrs, vec!["192.168.1.1:53", "10.0.0.1:53"]);
    }
}
