  (memory 1)
  (data (i32.const 0x2000) "0123456789abcdef")
  (func (export "_start") (result i32)
    (local $buf i32) (local $out i32) (local $nread i32)
    (local $i i32) (local $byte i32) (local $hi i32) (local $lo i32)
    (local.set $buf (i32.const 0x1000))
    (local.set $out (i32.const 0x3000))
    (block $eof
      (loop $loop
        (local.get $buf) (local.get $buf) (i32.const 4096) (call $sys_read)
        (local.tee $nread)
        (i32.le_s (i32.const 0))
        (br_if $eof)
        (local.set $i (i32.const 0))
        (block $next
          (loop $enc
            (local.get $i)
            (local.get $nread)
            (i32.ge_u)
            (br_if $next)
            (local.set $byte (i32.load8_u (i32.add (local.get $buf) (local.get $i))))
            (local.set $hi (i32.shr_u (local.get $byte) (i32.const 4)))
            (local.set $lo (i32.and (local.get $byte) (i32.const 15)))
            (i32.load8_u (i32.add (i32.const 0x2000) (local.get $hi)))
            (i32.store8 (i32.add (local.get $out) (i32.shl (local.get $i) (i32.const 1))))
            (i32.load8_u (i32.add (i32.const 0x2000) (local.get $lo)))
            (i32.store8 (i32.add (i32.add (local.get $out) (i32.shl (local.get $i) (i32.const 1))) (i32.const 1)))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $enc)
          )
        )
        (local.get $out) (local.get $out) (i32.shl (local.get $nread) (i32.const 1)) (call $sys_write)
        (drop)
        (br $loop)
      )
    )
    (i32.const 0)
  )
