[package]
name = "tinyvec"
version = "1.11.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "EdgeRun-owned safe vec-like data structures"

[features]
default = []
alloc = ["tinyvec_macros"]
debugger_visualizer = []
experimental_write_impl = []
grab_spare_slice = []
latest_stable_rust = ["rustc_1_61"]
nightly_slice_partition_dedup = []
real_blackbox = []
rustc_1_40 = []
rustc_1_55 = []
rustc_1_57 = []
rustc_1_61 = ["rustc_1_57"]
std = ["alloc"]

[dependencies]
tinyvec_macros = { path = "../edgerun-tinyvec-macros", optional = true }

[lints]
workspace = true
