[package]
name = "edgerun-drm-display"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Linux DRM display adapter for Edgerun"

[dependencies]
edgerun-capabilities = { version = "0.1", path = "../capability/edgerun-capabilities" }
edgerun-display = { version = "0.1", path = "../device-types/edgerun-display" }

edgerun-linux-sysfs = { version = "0.1", path = "../edgerun-linux-sysfs" }

[lints]
workspace = true
