[package]
name = "edgerun-amd-xdna"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
edgerun-linux-npu = { path = "../edgerun-linux-npu" }
edgerun-linux-sysfs = { path = "../edgerun-linux-sysfs" }
edgerun-npu = { path = "../edgerun-npu" }
libc.workspace = true
edgerun-log = { path = "../edgerun-log" }

[lints]
workspace = true
