tunnel: 046ed5c7-0d48-4eee-ac5e-35d829135536
credentials-file: /etc/cloudflared/creds/node-manager-tunnel-credentials.json

ingress:
  - hostname: node.edgerun.tech
    service: http://127.0.0.1:7777
  - hostname: osdeve2e.edgerun.tech
    service: http://127.0.0.1:4175
  - service: http_status:404
